### ISSUE TITLE
Suggestion: make vehicles obey "start turn", "end turn" waypoints in all modes.

### ISSUE THREAD

**Issue by OldFisher** [Courseplay/courseplay#1026]
Currently the vehicle running refill/unload, combine unload, transfer or sell course ignores "start turn" and "end turn" waypoints. Would be nice if they dropped to turn speed after "start turn" and resumed to street speed after "end turn".

**Comment by JakobTischler** [comment]
Why don't you just slow down at that point? The `turnStart` and `turnEnd` values are only for turn maneuvers.

**Comment by OldFisher** [comment]
I wonder if anyone even reads comments on closed issues...
But anyway, I just want vehicles to run the course in "maximum speed" mode, dropping to "turn speed" in the points that I set explicitly. Can't have them use "recorded speed" because I record courses at slow speeds for precision.
Currently I have to use some tricky manipulations with pause button. Not very reliable, not very predictable, very vehicle-dependent.

**Comment by Satissis** [comment]
Yes we get notification and do read closed issues. ;)

I do see your point, on wanting something that slows it down before a turn when using max speed, but in my opinion, it's not worth it, since that's what the recorded speed was original intended for.

I do have an G27 steering wheel, but I have not used it on FS15 yet, so I'm still using the keyboard when recording. Some pointers from me is, to set the Cruise Control to slow speed when turning in turns (While recording) and then hold down the forward button while driving strait and long curves while tapping the direction buttons.

Another way to record with an higher speed would be to use a car that drives faster than any tractor and then record it with that, since then you will have higher speeds on the strait and long curve parts.

You might already know the above, but I just wrote it in case you didn't.

**Comment by OldFisher** [comment]
In my practice I found recorded speed to be too crude an instrument. I record courses at slow speed, with extra precision and control, but I don't want my vehicles to drive it just as slowly.
Also, even in recorded speed mode, what worked for one vehicle won't necessarily work for another, so it isn't reliable enough. 
I have to *emulate* turning points through some obscure pause-magic, so wouldn't it be nice to have means of saying "turn from here to here" explicitly? Especially when we already have turn-placing button?

**Comment by JakobTischler** [comment]
There won't be such thing. `turnStart` and `turnEnd` are for turn maneuvers only, and for nothing else. And turn maneuvers are only part of modes 4 and 6. Anywhere else, trying to execute turn maneuvers will wreak havoc.

Over and out.

**Comment by AndyK70** [comment]
@OldFisher maybe you like to use [Coursedrawer](https://github.com/PromGames/Coursedrawer) to edit your saved courses and to change "recorded" speeds.
I'm used to drive too fast while recording and l edit courses and set the speeds in turn lower. You could do the opposite.

**Comment by OldFisher** [comment]
@AndyK70
It seems we have left only that and the magic of pause.
