### ISSUE TITLE
Doubts about the corrections system.

### ISSUE THREAD

**Issue by erksartori** [Courseplay/courseplay#1046]
After sending and detected that there is a problem, and you guys respond to test and after many coming and going, what the deadline for these corrections is available for download?

Because it was released a mistake on January 3, 2015, do not know yet if already was given as closed but the last answer was the January 28, 2015, and when I posted about the error, was reported double - # 1042.

I wonder that, after finding the error and seen an error solution, which term to be available a new release of the fix.

Thank attention.

**Comment by Maxcdr** [comment]
The issue #1042 is due to Giants physics system, not Courseplay. See #1036.

**Comment by gui7545** [comment]
There is no correction system, it is not a hotline. Developers are volunteer and spend a lot of time to make a mod reliable and bugless. There is therefore no deadline. 
Your issue is not relative to Courseplay. It is because of Giant's physic systems. So, you can send a email to Giant to report your issue if you want.
Now that you have publish your issue, you just have to wait for a solution.
If you don't want to wait, just delete thee mod and you will never have this problem again.

**Comment by ThomasGaertner** [comment]
there is noting to add to @gui7545 s comments.....

**Comment by erksartori** [comment]
Excuse me, but if it was physical game, why so occurs with activated courseplay, and when we have not enabled courseplay works correctly. Before answering something, there it happened.

**Comment by benjoglove** [comment]
Now fixed with latest courseplay.
