### ISSUE TITLE
MigMap Soil Mod

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1073]
Is it possible that you programmatically in courseplay menu can adjust each fertilizer or Herbezide! He invites the trigger right?

**Comment by sootysax** [comment]
so far, in its current Beta 2.0.7, all the different fertilizers and lime are filled with the same standard fertilizer trigger.   you have to select the standard fertilizer to fill and after full then switch to which one you need.  so far, i dont know of any specialized trigger mods for soil mod in fs15 yet.

**Comment by Paul2510** [comment]
My problem is the time when I will sprinkle lime, herbicide spraying or manure Offer, He surrounded the trigger on fertilizer! This means that I must always kontollieren is set right! And I think that there will be several fertilizer and Herbezide again!

**Comment by sootysax** [comment]
i'm not sure I follow what you are saying, but the issue with SoilMod is the same as when it first came out on FS13.   That you can only fill the fertilizer with Type A (NPK) Fertilizer..   You must then switch to the type of fertilzer that you want to spray with (while next to the fertilizer tank).    You will not be able to use courseplay to spray a field, and then run a refill course and back to spray the field (because it will refill with NPK and you want to spray Herbicide A for instance).

This is not a courseplay problem..   we will have to wait until someone mods custom fill triggers like they did with the FS13 version.

**Comment by Paul2510** [comment]
If he is, for example, lime load and I set it loads the next time the NFC again! Therefore, the idea of having a choice in the retract mode!

**Comment by sootysax** [comment]
yes, this is a limitation of the Soil Mod.   Either Decker will address it, or we will have to wait for placeable fertilizer tank mods to be developed.

**Comment by Paul2510** [comment]
Many Thanks!

**Comment by sootysax** [comment]
i've created modded fertilizer tanks for each soilmod fertilizer..  testing now, will upload to modhoster soon.

**Comment by Paul2510** [comment]
Thanks Alot!

**Comment by ThomasGaertner** [comment]
#1080

**Comment by Paul2510** [comment]
Is it possible that, for example, the syringe is not completely emptied but the 1-2% stay inside so that he remembers what's inside! Thus then it loads the right one!
