### ISSUE TITLE
Courseplay crashing game when trying to delete course. 

### ISSUE THREAD

**Issue by greenscag** [Courseplay/courseplay#1095]
Hello guys, I have had a couple situations where courseplay crashes and it screws up all the courses for that saved game. So I copy courseplay files from the backup folder, and the courses then show up no problem, but the problem is if I try to then delete a course, it crashes the game and the courseplay file will be corrupted again. Any suggestions? I apologize if this is a known issue already. 

Thanks for the really wonderful mod. It makes Farming Sim a whole different game. Your hard work is appreciated.

**Comment by benjoglove** [comment]
I had this only happen last night!!!

 I can only put it down to too many saved courses. Once it gets really large it crashes. Try reducing your saved courses and see how you go. Dont click when deleting courses either, allow it to do its thing and see how you go.

**Comment by maddavo** [comment]
I have experienced this.  My courseplay file is 8.5Mb.  Occasionally when I delete a course after playing for a while then it will crash and when restarting the game then the courses are all gone.  Thankfully I use autosave mod and restore the courses.  I CAN delete the course OK in the restarted game.  So the problem seems to be intermittant and also only after playing for some time.

**Comment by AlterSack1966** [comment]
I had the same problem when deleting a course, the game crashed, the CoursePlay.xml was destroyed. The Courseplay.xml is about 17MB large, but this was not a problem in the past.

**Comment by horoman** [comment]
https://github.com/Courseplay/courseplay/issues/1143

**Comment by Satissis** [comment]
#1346
