### ISSUE TITLE
Liquid Manure transporter NOT loading at the farm.

### ISSUE THREAD

**Issue by Sejer74** [Courseplay/courseplay#1140]
Is there anybody else having problems with liquid manure transporting? I have this problem that it DONT stop at the filling point. And if I put in another waiting point at the filling point, so that I have two waitingoints, one at the overloadibng point and one at the filing point it says "too many waitingpoints". And yes I have put it at the "manuretransporter" course :-)

**Comment by Sejer74** [comment]
Jeg er dansker så evt danskere må gerne svare på dansk :-)

**Comment by Satissis** [comment]
English:
Well you should only have one waiting point, since it will find the fill trigger automaticly at the farm, so just make an waiting point at the overloading point and you should be fine.

Danish:
Du behøver kun 1 waiting point, da den vil automatisk finde fill triggeren på farmen og fylde op der fra, så du behøver kun at sætte 1 waiting point hvor du vil tømme den fra.

**Comment by Sejer74** [comment]
I know. AndI have done that. But it still wont load at the filling trigger. :-)

**Comment by gui7545** [comment]
What is your map/ mod/ trailer / filling trigger ?

**Comment by Sejer74** [comment]
It is Volksholm_SE_V1.4.5_Unkraut. And the problem is so far from the liquid manure STORAGE. And trailer is the STANDARD ORIGINAL trailer for liquid manure transport. Trigger??? eeeh don't know.

**Comment by Satissis** [comment]
#1346
