### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by SirSeriously** [Courseplay/courseplay#1143]
Scenario is the following:
- Playing on Region Of Texas (latest version)
- Have a very large number of courses setup with many folders
- Try to delete a course
- Game crashes
- courseplay.xml is half written too

Has happened multiple times on different maps.
Any ideas?

BTW, I love course play and keep up the great work!!

**Comment by AndyK70** [comment]
my idea: your courseplay.xml became too big over the time.
Are you saving all fieldwork courses?

**Comment by maddavo** [comment]
I have this problem also and I can replicate it.   Playing on Pleasant Valley Map (which is HUGE) - my courseplay.xml file is 14,441 kB.  Trying to delete a course will consistently crash the game.  The courseplay.xml that remains in the savegame folder is then only partially saved - only 4,293 kB.  On restarting the savegame then it won't read the partial courseplay.xml and all the courses are gone.  (Have to restore from backup).

Is this something to do with having to re-write the file and reaching some byte limit / memory limit?  New courses can be added OK.  New folders can be added OK.  Courses can even be moved between folders OK.  It's only the deleting courses that crashes.

There is nothing special in the 14Mb file at the point where the 4Mb file ends - just mid-course and not the course I was deleting.

Yes, I do save fieldwork courses (which obviously makes the xml large) because most courses are driven by multiple machines.

**Comment by Satissis** [comment]
Yeah I have seen this happens for others when the file size is getting to big.
There might be an solution.
First of, goto your savegame backup and copy the courseplay.xml back to your savegame folder, so you won't lose all your saved courses.
Then open up courseplay.xml in an text editor and find: ``<courseManagement batchWriteSize="4096" />``
Try change the 4096 to 2048.
It changes how big a chunk it saves each time to the file. That might help, but I haven't tested it, so an failure might still occur.

**Comment by maddavo** [comment]
Thanx Satissis for the suggestion.  Unfortunately that did not work - still crashes.  It did get further writing the courseplay.xml though - 8Mb instead of 4Mb.

**Comment by horoman** [comment]
Does that mean, that if you change to 8MB it works again?

**Comment by horoman** [comment]
https://github.com/Courseplay/courseplay/issues/1095

**Comment by horoman** [comment]
https://github.com/Courseplay/courseplay/issues/1095

**Comment by maddavo** [comment]
No, it just gets further when saving the courseplay.xml before crashing.  The file is still bad on restart and I have to restore from backup.

**Comment by Satissis** [comment]
Then try lowering it again, like to 1024 or 512. If that don't help, then we can't do anything, since Giants have limited how much data we can use now when saving big files.
That is also why one of our todo is to save each course into there own separate file. which should make the game load faster and don't make the game crash when deleting courses, since the files are smaller.

The only advise if anything fails would be, not to save generated courses, but regenerate them each time you need it, since that will save allots of file space.

**Comment by maddavo** [comment]
Hi @Satissis , thanx for that.  I will try even smaller value.

**Comment by maddavo** [comment]
I have tested this with a value of batchWriteSize="512".  It WORKS!  Deleted courses OK, saved and reopened OK.  THANK YOU very very much!

**Comment by Satissis** [comment]
Okay, good to know that it worked with lowering the batch write size to 512. Just keep in mind that if it happens again, there might not be much more to do, since I don't know how low we can lowering that value further.
So try keep it more clean and generate field courses each time, instead of saving then in the future, at least that will prevent it for doing the same thing for a much more longer time ;)

@SirSeriously Did this also help you ?

**Comment by Satissis** [comment]
#1346
