### ISSUE TITLE
A course play route

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#1167]
I have made a 1200 point route 600 there 600 back, now I have a few errors in my route and I would like to edit the course , rather than doing a new course. So can I edit out the incorrect "way points" and keep the course intact. I have tried removing the incorrect waypoints by cutting or deleting the line,But this does not give me the correct sequence of needed waypoint numbers.   Thanks  Bob

**Comment by ThomasGaertner** [comment]
#1135

**Comment by hackselgut** [comment]
Ok...I looked at the  issue mentioned above, I have downloaded a file called "coursedrawer-master.zip"
Now what do I do with it, then where does it go to do any editing of a course.  Bob.

**Comment by sootysax** [comment]
its a stand alone program to edit courses

**Comment by hackselgut** [comment]
Ok....It is a stand alone program, do we do an install of it to the root drive or what, as there are no instructions in the download file.  Some instructions would be of some Help.   Thanks  Bob

**Comment by sootysax** [comment]
find the coursedrawer github for support

**Comment by hackselgut** [comment]
Thanks..... Big help that is......

**Comment by sootysax** [comment]
promgames / coursedrawer

**Comment by PromGames** [comment]
Hi hackselgut and all courseplay users,

The new version of courseplay editor is almost ready.

 I will not publish now, because we are creating a toolbox that includes some other programs with the editor and we are testing the usability of the application at the moment. Mod server manager, and other folder and settings edition capability programs in .net will be included in this bundle of applications, that we called FS15 ToolBox.

We expect to release it for a limited betatesters group in a week or two. 

Thanks for you patience.

PromGames

**Comment by Satissis** [comment]
#1346
