### ISSUE TITLE
CoursePlay Ignoring me while unloading from harvester.

### ISSUE THREAD

**Issue by Ormsher** [Courseplay/courseplay#1189]
Hello. So i have a problem there courseplay completly ignores me while i am unloading from harvester.
I uploaded short video showing what issue i am experiancing. Combine using courseplay fieldwork mode too.

https://www.youtube.com/watch?v=croB3yxBmyY

**Comment by gui7545** [comment]
I don't think that it is an issue. Courseplay does this task automatically without taking care if you are here or not. You need to stop the other tractor in order to do the harvest full manually, or you need to set up courseplay in your tractor to do the harvest full automatically. there is no half manually mode

**Comment by Satissis** [comment]
That's an giant thing, it will take the latest bought trailer before the older one if they get too close to it. nothing we really can do about it

**Comment by gui7545** [comment]
Sorry, i thought that you were driving the first tractor by yourself, I didn't realise that it was drive by courseplay

**Comment by Satissis** [comment]
#1346
