### ISSUE TITLE
Abfahrer für Gülle Verkauf-Transport

### ISSUE THREAD

**Issue by sekator1963** [Courseplay/courseplay#1208]
Hallo, ich hatte schon mal versucht auf ein Problem in english zu posten. Aber mein englisch ist nicht besonders. Deshalb versuche ich es mal in deutsch.
Ich habe das Problem, wenn ich versuche einen Abfahrer zu sagen er soll am Startpunkt Gülle aufnehmen (z.B Verkauf), das dieser zwar dann am Trigger anhält, es aber nichts passiert. Es steht dann nur wird gelagen z,B  0 von 30000. Es passiert nichts. 

MfG
Sekator

**Comment by Phantom742** [comment]
I will translate in english since I experience the same issue:

Since a lot of the maps use the 'Rindermast' and 'Schweinemast' from Marhu.net a lot of players would appreciate if courseplay would work with: http://www.modhoster.de/mods/kotte-universal-trailer-pack or the http://www.modhoster.de/mods/gulle-lager-gulle-transporter !! Both versions of the liquid manure transporter work only in the overloading mode. None will work in the transport mode to transport the manure to the storage. It would be really helpful to get this issue fixed. I tested it in version 4.01.109 and earlier versions, none of them work.

I hope for a reply,

Phantom742

**Comment by Phantom742** [comment]
It is the same issue as:
liquidManureTipTrigger #1204  and 
Liquid Manure transporter NOT loading at the farm. #1140
Might be a good idea to combine those issues!

If you need more info fee free to ask!

Phantom742

**Comment by Satissis** [comment]
#1346
