### ISSUE TITLE
serveur courses play

### ISSUE THREAD

**Issue by Kiralos62** [Courseplay/courseplay#1234]
bonjour est-il possible de metre le couses play sur serveur car jessaye mes j'y arrive pas

**Comment by gui7545** [comment]
Bonjour,
Courseplay n'est actuellement pas compatible avec le mode multi.
ll ne fonctionnera pas sur serveur.
Tu peux clore le ticket si la reponse te convient

English:
#######################################
Hello, is it possible to put coursplay on serveur, because i try but i don't manage to.
#######################################
Hello,
Courseplay is not compatible with multi.
It will not work on server.
You can close the issue if the answer is ok.

**Comment by Satissis** [comment]
#1346
