### ISSUE TITLE
Freezing during automatic field scan

### ISSUE THREAD

**Issue by rubberburner89** [Courseplay/courseplay#1281]
First off I just want to say thank you to the writers of courseplay! This adds a whole new element to the game and makes it that much more exciting. This is the first issue I've had, so I am hopefull someone has a solution.

With mod installed in game, when I load my current game (Norgeholm 7.1), it will ask me whether or not to automatically scan fields. If I click yes, the game will freeze on field 23 every time! Only way around this is to 1. Disable courseplay or 2. not scan fields (which lets be honest would be a big pain)

Note: If I load another new game, same map, scan works flawlessly.

If you guys need anymore information from me please let me know. Thanks in advance, Steve.

**Comment by Satissis** [comment]
The reason it properly is freezing, is due to the map it self, around field 23. Mostly because the buy icon for the field is outside the field it self, which was one of the reason we added the question if you waned to scan the field automatic.

But here is an hint.
If you select not to scan fields automatic, you can still scan them without any problem. What you need to do is drive into the field it self with an vehicle, open up CP hud, on the first page (Where you select start and stop when a route is loaded), there is an button where you can scan current field that you are on, and when it's scanned, you can select what field number you want to save it on. When that's done, you can select the field from the generation tab as you normally would do.

Hope that helps :)

Ps. Close this issue if no more attention is required ;)
