### ISSUE TITLE
Game crashes if a course will delete

### ISSUE THREAD

**Issue by Stolli1996** [Courseplay/courseplay#1291]
Hi

I have the poblem that when i will delete a course the game crashes and i dont know why 
Log:
Warning (physics): Add trigger callback failed, object colJoint is not a physics trigger.
Error: Running LUA method 'mouseEvent'.
D:/code/lsim2015/build/finalbin/dataS/scripts/vehicles/VehicleEnterRequestEvent.lua(34) : attempt to index field 'object' (a number value)
Warning (physics): Add trigger callback failed, object colJoint is not a physics trigger.

mfg
Stolli

Ps I have very much courses but this cant be the reaseon or?

**Comment by zippgunn** [comment]
I think something similar happened to me once when I deleted a course while it was still assigned and active on a vehicle, but not sure if this is what you saw? Should be easy to test if that happens.

**Comment by Stolli1996** [comment]
i think the problem is when a other vehical has load the course at the moment on them i will delete the course.

**Comment by greenscag** [comment]
I ran into this issue, and what I was told last is this is most likely due to the file size limitations and the file becoming to large. Go to the CoursePlay XML in your save game folder and go to this line <courseManagement batchWriteSize=" and change the number to "512". Also try not to save courses that are field work, like seeding, harvesting, plowing, spraying.  Create a temp course for them each time, as if you save them, it rapidly increases file size due to how large they are in nature.

**Comment by ThomasGaertner** [comment]
#1346
