### ISSUE TITLE
FS15 Long Load Time or Not at all 

### ISSUE THREAD

**Issue by dsn005** [Courseplay/courseplay#1296]
As I save more courses for Courseplay it takes longer and longer to load the game until it will not load at all. If I take Courseplay out of the Mods folder FS15 loads or loads faster. This happens especially with the Baxley Map. Am  I doing something wrong?

**Comment by sootysax** [comment]
you shouldn't save fieldwork courses that you can easily regenerate.   it is too many waypoints to load every time you start the game.   You can also try using combined courses instead of saving a new route for every job you're trying to do.   I will record one course each way on each road, and then use Coursedrawer to place crossing points so I can just link them together and transverse the whole map with just those courses.

**Comment by Siniy-lom** [comment]
This problem continues for several years ... courses.xml - >20mb = 20 min+ load time... wait for an answer ... wait for an answer ... wait for an answer ... )))
