### ISSUE TITLE
overloader mode

### ISSUE THREAD

**Issue by 3lronMcBong** [Courseplay/courseplay#1302]
hello friends :-)

is it possible that two combines for one overloader define?
some fields detects the overloader automatic modus not the harvesters.

thanks for your work on cp ;-)

**Comment by JDTiger** [comment]
it works only on the same field
i.e. inside the outline the modder made for that field...
On Bjornholm or westbridgeHills, it should work on all fields, IF the overloader stops inside the field the combines are on.
On the MIG map on the otherhand, it works hardly anywhere, because the field outlines aren't that precise...

**Comment by PatrickWende** [comment]
You can assign a combine to an overloader. If you open the Courseplay-menu while the overloader is running its path you will see a button with a combine on it, this is where you can assign the combine. Just change to manual selection. You can do this for both overloaders. This function is especially designed to solve the problem of combines on uneven (no line of sight) or difficult fields like on the MIG-map.

**Comment by ThomasGaertner** [comment]
#1346
