### ISSUE TITLE
Fields with obstacles

### ISSUE THREAD

**Issue by Jameshook** [Courseplay/courseplay#1307]
How I get Courseplay to automatically recognize the interior obstacles in fields?  The example is below is from the Two Rivers Map.  In the following image, the red line is the field border which CP detects but the interior island (yellow line) is ignored.

[img] http://i65.tinypic.com/15545xx.png [/img]

**Comment by BufordMapping** [comment]
What exactlly are you doing for it to hit this obstic.?

**Comment by Jameshook** [comment]
IMO, CP should calculate a path that will avoid the area where crops are not planted.  I have seeded the interior outline with grass thinking that was the issue, but still get the same result.  I have CP calculate the field edge and generate the course automatically for the given inmplement width.  this picture [IMG]http://i65.tinypic.com/2cmvm6x.jpg[/IMG] is the result when CP automatically calculates the route automatically for the criteria given (width, starting corner, headland, direction, etc.).  As noted, CP appears not to recognize the inner "island" in field 4.  BTW, I am using the current developer version of CP.

**Comment by BufordMapping** [comment]
Have you considered building your own course? That way you can drive around it... I know it sounds like a time consuming idea but in the end atleast your not going into the island.. Ive had to do this tons of time in the MIG map in 13.... 

Now this isa question for the devs.. have you guys tried a if true statement in the lua so that when a course is generated it goes along the field it self and looks for gaps as such mentioned in this post and determines a way around it((I know this will cause a bit of lag in the game searching large fields))? And for normal fields it does a false statement and builds the course as it normally would?

**Comment by PromGames** [comment]
I use my courseplay editor to solve this problem. After defining the course, I edit it and change the courses to avoid the island. That is the only way I think we can do it.
