### ISSUE TITLE
Pathfinding not working

### ISSUE THREAD

**Issue by Scottvdken** [Courseplay/courseplay#1333]
With the latest version pulled off of the hub, it seems that pathfinding no longer works for me. Tractors behave the same while unloading combines as if pathfinding was deactivated.

**Comment by ThomasGaertner** [comment]
try again with the lates version and reprt, wheter its still valid . 
if it still occurs, try with debug channel 4 active and post the log here...

**Comment by ThomasGaertner** [comment]
closed to keep issues clean

**Comment by dkfiremann** [comment]
Hey Thomas 

This is still a.n issue. 
Just tested this today with version .52. 
Two tests, one where courseplay is controlling the combine, and one with a hired worker. 
With courseplay controlling the combine everything is working okay. 
With the hired worker, the tractor that courseplay is controlling, is ignoring the pathfinding. 

![20170128125114_1](https://cloud.githubusercontent.com/assets/25283454/22396451/0a5fd2fa-e55a-11e6-875a-84d2cccca468.jpg)

So the problem is with a hired worker in the combine. 
Tested on sosnovka in a comlete new game.

**Comment by ThomasGaertner** [comment]
then give me your log please ...

**Comment by dkfiremann** [comment]
Sure
[log.txt](https://github.com/Courseplay/courseplay/files/736894/log.txt)

I can maybe make a more simple log, but then it might be monday before I can do that. 
Let me know if there is anything else I can do.

**Comment by ThomasGaertner** [comment]
please try again with v.0055 or higher and report

**Comment by dkfiremann** [comment]
That fixed the issue. 
Tested with the base combine and tractor on a new game. 

Thanks
