### ISSUE TITLE
where are we?

### ISSUE THREAD

**Issue by ThomasGaertner** [Courseplay/courseplay#1346]
Dear all,
since we are all trapped in reality, we where not able to force this project further for a long time.
We are aware of the importance of it for many FS users. We will try to get it running on FS17 as well.
If we spend our rare time for converting it, we are not able to answer the backlog of 184 open issues.
For this reason we decided to close all open issues to get a chance to get feedback for the FS17 version.
We hope, you will understand it and give feedback when we pushed the FS17 version. 
And NO, we don't get the FS17 earlier so you don't need to ask for a fix before mid of november :-)

**Comment by tsikows** [comment]
Woohoooo can't wait for 17

**Comment by kwguk** [comment]
I was really worried that you weren't going to make a version for FS17

I'm absolutely delighted you will be!

CP is the best mod for FS

**Comment by Mopar** [comment]
I agree, I consider CP to be a mandatory mod in FS 15, and greatly look forward to its FS 17 release.

On another note, I don't consider myself to be trapped by reality, but it does fight me on a daily basis ;)

**Comment by mB-PiBox** [comment]
So does this mean no bug/issue fixes for people that just bought FS15 and have no intention of buying FS17? From quick look mods work different in FS17 so they won't be backward compatible...

**Comment by ThomasGaertner** [comment]
yes

**Comment by mB-PiBox** [comment]
Can you separate the option for "Stop at last point or at next trigger" -- make 1 option for each -- So on Grain transport it doesn't stop at trigger/unload but stops at silo/end of course.

**Comment by kwguk** [comment]
I think the answer to that will be no.

Read Thomas first post.

**Comment by mB-PiBox** [comment]
@kwguk meant in the FS17 version.

**Comment by MoslessNeo** [comment]
This is great news for everyone.

**Comment by omegaMV6** [comment]
Great news! Because no courseplay, no FS17.
Sorry for my bad english!

**Comment by gary-albano** [comment]
I may purchase FS17 when CP has something for it. 
Smart move! +1

**Comment by ChrisZaal** [comment]
It would be good for people to remember that the devs are donating their time to this project. Considering the number of people who want this updated for FS17, now might be a good time to visit the Courseplay information page (Here for ease of access: http://courseplay.github.io/courseplay/en/index.html), click on the donate button and slide them a few bucks. 

It doesn't take too much to motivate programmers but showing your appreciation by putting your money where your mouth is can be a real game changer in how quickly they'll come back to this project. Thanks to the developers and expect another "coffee" donation from me in the near future. :-)

**Comment by Umiyaki** [comment]
After three years without a reaction close all comments without solving. Donate, really? I like donate if I see some progress.

**Comment by ThomasGaertner** [comment]
You don't have to donate at all ...

**Comment by CaptACE** [comment]
After reading this great news and using courseplay for years for free, i decided to donate.

**Comment by TommyC81** [comment]
10 Euro donated, thanks for the hard work guys!

**Comment by AgroWillem** [comment]
Ahh Great news. CP is the best mod for FS ever. Gives me more then 50% gaming pleasure of FS.

**Comment by SGFITZY** [comment]
I am loving FS17 and Cannot wait for Courseplay to come out on it.  To me its the only way to play the game.  I donated $20.00 to the cause Good luck Guys cant wait to see what you come up with.

**Comment by farmernick** [comment]
Gaming sim is nothing the without CP, it really needs a 2017 mod to enjoy it. Please guy carry on the epic work

**Comment by farmernick** [comment]
Faming Sim

**Comment by farmernick** [comment]
is there any thing we can do to help

**Comment by farmernick** [comment]
Think we should all think about doing sone donations to these guys via there website to help motivate and show how badly farming sim 2017 needs cp

**Comment by Simba76** [comment]
我期待着为CP LS17

**Comment by berntseb** [comment]
Hey guys. That's really good news. Do you need any assistance? I'm programming for 23 years now and playing LS/FS since 2011. I'm new to Lua, but to be honest it's not that far away from Ruby, Python and Groovy - programmed these among others during the last years. As you mentioned too be stuck in real life (which I totally understand) it maybe could help to get things done quicker by enhancing the team. I've even fixed some smaller bugs in 2015 version on my own behalf in the git clone (mainly problems with finding unloading places, attacher joints and stuff). So if you like to get some help, don't hesitate to contact me.

**Comment by hsiverts** [comment]
Hope you will find time to make courseplay for FS 17! €15 donated.

**Comment by Satissis** [comment]
Update:
We are working on converting CP to FS17.
Allot have changes since FS15 so there is allot to do before we will release the first beta here on GitHub.

@berntseb we can talk about it when we have the first beta out. We have direct contact with Giants now, so they are helping on infoes that have changed since FS15, which means we would have to explain allot of the new things, which would be easier for us to just do it our self at the moment ;)

**Comment by jordyboytjuh** [comment]
Keep up the good work! You guys are awesome :)

**Comment by Simba76** [comment]
Mentally support CP team！

**Comment by SnoopBok** [comment]
Great news to hear, also very promising that you were invited by Giants. I will make a donation too,  I'm now realizing again how much I miss courseplay 😆

**Comment by Homskiy** [comment]
Mid of november is comming! ;)

**Comment by SnoopBok** [comment]
Why are some people talking about mid of november? 

I love the new farming simulator but I really do miss courseplay 😆

**Comment by Satissis** [comment]
If some one have told you that CP would be ready around mid November, then they are wrong.
I know that allot of you guys are waiting for it, but as I have mentioned a couple of times before, then it's just not as easy as it was to convert from FS13 to FS15, since allot have changed.

**Comment by olavinto** [comment]
The "mid November" time most likely came from the report that "all open issues have been closed because we are focusing on 2017 version. Don't expect updates before mid November". Or at least it was something along those lines. People often take public posts too seriously and after they get a time in their heads anything after that is considered delayed and will often be met with negative feedback. Patience is a virtue many people do not have, I've noticed over the years. Like for another post in this thread already: "After three years without a reaction close all comments without solving. Donate, really? I like donate if I see some progress.". Very negative (hostile even) and could have been said with a different tone.

**Comment by AgroWillem** [comment]
We have time.
Things has changed in FS17. BGA/chaff handling is more difficult than in FS15. That could be a problem.
I volunteer for beta-testing. ;)

And i agree that CP is missing in FS17. I went back to the FS15 game so i can use CP again. :P

**Comment by Satissis** [comment]
> Things has changed in FS17. BGA/chaff handling is more difficult than in FS15. That could be a problem.

That is very true. We have been talking on how to handle this and found an solution, but we are not sure if it will be available in the first beta yet. If it's implemented, you will see a whole new behavior of the CP drivers ;)

**Comment by santaranger** [comment]
OK so I kinda created a GitHub account only to post here, to tell you to keep up the good work.

Any chance for an early beta release, with some of the safer driving modes only and the rest deactivated? (need combi mode so much :P)
I'd offer my programming skills as well, but I'm not into this type of code.
I could help with end-to-end testing though :D

**Comment by Phantum** [comment]
> That is very true. We have been talking on how to handle this and found an solution, but we are not sure if it will be available in the first beta yet. If it's implemented, you will see a whole new behavior of the CP drivers ;) 

Awesome! ;P

**Comment by Outcastus** [comment]
Is there a chance for like a trello or something to keep us updated on the current state/progress of the mod?  I think it would go a long way to keeping some of the rumbling down about when this will be completed.   AND it might help get some donations since some ppl worry about donating to something unfinished, but they dont seem to mind if they see some progress.   This mod on FS15 was just about essential to singleplayer,  the automation gave the game almost ALL of its fun transforming this game completely.  Without it the game was pretty much having to drive beside a harvester 100 percent of the time if you had more than 2 fields or so to manage.  And without courseplay all hay and straw and bale management had to be done by hand which was tedious as hell.  With courseplay it was still tedious a lil bit, but it was transformed to more real life management of "Did my farm hands do their jobs right or did they do a half assed job and need retrained."   Amazing mod, Please let us know where you're at cause we all REALLY want this one.

**Comment by Phantum** [comment]
to be honest I'd rather they spent their time working on it, than on trying to manage our impatience.

**Comment by Fogest** [comment]
Hey @Outcastus I'm not sure if any tracking will be posted publicly regarding the progress however I guess the best I can do is to let you know that progress is being made and it is actively being worked on by multiple people daily. Some things changed when going to FS17, and some projects like AutoCombine are not even going to exist in FS17 due to the changes made in the game. 

Rest assured though, Courseplay will be updated for FS17! I guess for now your best bet is to progress your farm to get enough money for the bigger fields so that you're ready when Courseplay does get released for FS17.

**Comment by Outcastus** [comment]
I get what you're saying, phantum, but honestly, someone had posted something about donations in some kind of attitude in previous comments, seeming like they were annoyed at being asked a lot of questions, I just figured if they had something that provided the information that people wouldnt be bothering them with as many questions, and it might show progress and show potential investors they wouldnt be investing in a pipe dream.   Autocombine isnt even gunna be in this version tho? you mean like having the truck go unload the combine for you isnt gunna work?  So is it pretty much just programming paths then with this version and no automated interaction of the vehicles and/or tools?

**Comment by Fogest** [comment]
Are you referring to the AutoCombine mod made by other people? That is not being updated. However if you're referring to the field work with the combine, then that is already there. You shouldn't really be losing any features from the current FS15 CP.

**Comment by Outcastus** [comment]
No I was referring to only courseplay's autocombine feature.  I believe with your answer that you were saying that a separate mod called Autocombine wont be made due to some fundamental changes to the game that "Autocombine mod" depended on.     Will the new version of courseplay for FS17 have all the features of the fs15 version or is there some things that arent possible with the new Game Build as well?

**Comment by Fogest** [comment]
The truck emptying the combine works fine for me in tests. Some people in FS15 used an AutoCombine mod in combination with Courseplay and Courseplay provided support for that compatibility with the other mod. That mod is not being updated however. That is separate from the normal field work that can be done in Courseplay with the combine. The combine still works as before :)

**Comment by Satissis** [comment]
I have an update for you all.
First off, Welcome to @Fogest. He have agreed to help on updating the user manual page we have on cp so Thomas and I can mainly focus on getting CP done. This is also why he have access to the latest build we have + insight in what's going on :)
@skydanc3r is an former CP Developer from before my time, but he is helping out as well when he have the time and get around to know all the new changes since he was an developer.

CP Is getting there. Most of the features are converted over but there is still stuff we need to sort out, like:
A new save system (which I'm currently working on)
Yes new save system, this means that we hopefully should not have any problems anymore with corrupt saves.
What is planed to do is:
Save each course in it's own xml file, so the file size wont exceed the max file size that you can create in one go.
Since we cant delete any folders or files anymore, due to Giants disabling the delete function for mods, we have to make an reusable file system, so if you delete an course, that will, will be wiped, and pot into an holding position for the next course to save into. If there is no files left to use for saving an course, then we create an new one and keep track on that one as well.

An beta date...... Well we might have some internal date we want to try keep, but will not tell here in the public, since it's easier for us to not set an date to the public and then have to move the date again if we just cant hit the target. Hope you understand.

@Outcastus we do have an Pivotal Tracker going on our end, but only members invited into it, can view the current progress, like what we are working on right here and now.
You can see it without being an member, but you can only see the done tasks we have done so far.
If that's enough for you, I would happily share the link for it, but as mentioned before, it will only show the done tasks and not what we are working on or what we have in plans.

Just an weekend update from me :P
Now back to work ;)

**Comment by Tohva** [comment]
I'm just leaving this here: You guys did an awesome job throughout FS15 when I first started playing FS and I am pretty sure you will amaze us again with a great and indispensable FS17 courseplay mod. Thank you for your work, devotion and the time you invest to make our gaming experience so good. And the fact that you still find the time to keep us up-to-date is remarkable. 
So keep up the good work. Donation is coming. Cheers and greetings from Germany.

**Comment by Satissis** [comment]
An update again from me.
Yesterday I just finished the new save system. Here is what have changed:

> courses and folders are saved in CoursePlay_Courses/(mapID)/
> Each course is now saved in there own files
> courseManager.xml holds information on what course each file belongs to.
> courseManager.xml holds all the folder setup as well.
> All settings are stored in savegame(x)/courseplaySettings.xml file and only saved on save game save.
> All custom fields are stored in savegame(x)/courseplayCustomFields.xml file and only saved on save game save.
> If an old courseplay.xml is found and no folders and courses are saved, it will import all settings, courses and folders from the old file into the new system.
> If an old courseplayFields.xml is found and courseplayCustomFields.xml is not found, it will import all the old custom fields into the new section.

All of these changes makes the saving an course allot faster and deleting an course is also really fast now, since it don't need to rewrite one big file with all the remaining courses in it.
This should also remove all those corrupt file problems we are having, again, because it don't work with one big file anymore :)

**Comment by ThomasGaertner** [comment]
we also made Improvements for the combine unload mode: the sugarbeet harvester is able to create heaps. 
Of course the sugarbeet loader will be supported: you will need to drive it, but the tractors will work and take it  as a usual combine ... 
![fsscreen_2016_11_14_20_01_09](https://cloud.githubusercontent.com/assets/3279913/20538737/b7d720ba-b0f2-11e6-8c47-6429407203f2.png)

the BunkerSilo unloading mode has been adapted to the new tipAny structure of the game, it will autonomous search the Silo and unload it with a certain logic
![fsscreen_2016_11_20_00_25_58](https://cloud.githubusercontent.com/assets/3279913/20538834/220ab8ac-b0f3-11e6-9b80-2d6e35a242ce.png)

and one thing on our list is :
![fsscreen_2016_11_20_12_39_42](https://cloud.githubusercontent.com/assets/3279913/20538921/872a1426-b0f3-11e6-99da-3f38ec492e6c.png)

**Comment by SnoopBok** [comment]
Great looking job guys, I'm getting so excited about this. Playing farming simulator 2017 isn't the same experience without courseplay!

**Comment by AgroWillem** [comment]
Wow, you guys are serious making progress!
The "BGA-compressing thingy" looks an major issue to me indeed. But i am hopeful. ;)

**Comment by Castaway-Dave** [comment]
Great work, fella's!

**Comment by Galwaygrass** [comment]
Will the loader mode be able to fill a silo
As well empty it?

**Comment by dragonskil** [comment]
I find it fabulous that persone like you all creates mod such as coursplay thank you infinitely time you spent elaborating the one for Farming 2017 ...... I am so excited to have this mod to play ... .... felicitation to you the creator. (Translated from French to English via google translated.)

**Comment by Neomerlin17** [comment]
Please is there a way we can try wip versions?

**Comment by ThomasGaertner** [comment]
yep, if we ask you to test :-)

**Comment by Neomerlin17** [comment]
I would love to test it.

**Comment by AlphaXray** [comment]
Looks great, cant wait until release

**Comment by Simba76** [comment]
I would love to test it.

**Comment by Christian9600** [comment]
I would love to test it

**Comment by Maon** [comment]
I would love to test it too :) I am using this mode since beginning and I am more than happy to help!

**Comment by Castaway-Dave** [comment]
Would be happy to help also..

**Comment by Andreas115** [comment]
I would love to test it!!!!!
Andreas from Germany

**Comment by lxfTTjek** [comment]
I would love to test it!!!!!
Andreas from Germany

**Comment by Andii1980** [comment]
I would love to test it ! 
another Andreas from Germany ;-)

**Comment by BenB78** [comment]
Well I'm not an Andreas, nor from Germany, but I'd be glad to help with testing too. I loved CP with FS15 and it would be great to help it come to FS17. Vielen Dank to the developers for your hard work. It's appreciated!

**Comment by Hutchiewoo** [comment]
Writing to offer my testing services as well.

I used courseplay so much on FS15 that FS17 is pretty much unplayable for me until this mod is available!
No pressure guys, keep up the good work. :)

**Comment by Satissis** [comment]
#1375

**Comment by mB-PiBox** [comment]
Are there any plans for a multiplayer/server beta release? Would like to test this out on my private dedicated server.

**Comment by cookins** [comment]
hey there
some time pass -
isnt that mod already out?

**Comment by pops64** [comment]
? Yes there is a released version available on modhub
