### ISSUE TITLE
No Load Liquid with Kotte Universal Pack

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/courseplay#1350]
Hi, I can't load liquids with this mod, I create simply route in mode "Grain Transport", select "liquidManure" (f.e. in BGA), but this no load the trailer. However, this unload without problem when arrive at correct trigger.

**Comment by Satissis** [comment]
I cant remember if this was implemented fully, but I think it was.
Anyway I think you need to use mode 8 ( Manure transporter ) for it to work

**Comment by Vanquish081** [comment]
With mode 8 no work, the problem is the trigger, with trigger UPK work fine.

This route is for make fertilizer from liquidmanure or manure.

**Comment by Satissis** [comment]
hmm okay, well I don't know if I'll get around to this before FS17, since I'm working on something new for CP that I hope will be done for the fs17 release.

**Comment by ThomasGaertner** [comment]
quick and dirty solution would be to add 
"or   workTool.typeName == 'Kotte_Universal.kotteUniversal' then"
to specialTools.lua line 80....

**Comment by Vanquish081** [comment]
This?
"	-- [1] AUGER WAGONS
	if workTool.typeName == 'augerWagon' or workTool.typeName == 'Kotte_Universal.kotteUniversal' then
		if workTool.fillTypes and workTool.fillTypes[Fillable.FILLTYPE_LIQUIDMANURE] ~= nil then 
"

**Comment by ThomasGaertner** [comment]
Yep

**Comment by Vanquish081** [comment]
No work, the kotter require manual fill with key "R", the problem continue..... f*** trigger BGA...

**Comment by pops64** [comment]
I am using the KOTTE UNIVERSAL PACK V 3.2 FS15 by farm andy. When I tried running a known to be working course in mode 8 from BGA to a FRC tank(the one that comes default with game). It would not even run the course because it was expecting a water trigger. By adding

elseif workTool.cp.xmlFileName == 'Kotte_Universal_MAN.xml' then
		workTool.cp.isLiquidManureOverloader = true;


to line 176 in specialtools.lua I was able to get the the Kotte Universal Man slurry truck to work. My guess is crouseplay is not decteing this mod pack a liquid manure overloader. So you would have to do the above fix for each trailer in that mod pack. Simply by replacing Kotte_Universal_MAN.xml with the file name of each trailer.

**Comment by Satissis** [comment]
sorry, but I'm pretty sure we wont work on fs15 version anymore, since we are converting it over to FS17 at the moment

**Comment by pops64** [comment]
I figured, which is why I gave the guy a way to fix it if he continues using FS15.

**Comment by Satissis** [comment]
Closing Since we moved over to FS17 converting. This should hopefully not be an issue in FS17
#1346

@pops64 if you want to fix it for FS15, then make an pull request with these fixes into the FS15_Legacy branch and we will merge it in to the FS15_Legacy branch. That way people that still uses FS15 could have that fix in it :)
If you make an pull request to the master branch, it will not be accepted anymore, since I have just created the FS15_Legacy branch for FS15
