### ISSUE TITLE
new mode for fs17

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#1353]
Hey gang. been a while that me and many other players use your great mod, i bet.
dont know if this the right place to ask for a request, but here it goes......

would it be possible to create a new mode for fs17 that acts simmilar to combine self unload mode, for seeders, fertilizers and maybe other tools, but instead of going to unload, they will head to a (mobile) trigger to refill seeds or fertilizer?
maybe such mode could make the current field seeding/fert mode obsolete, but considering the auto-tractor mod around, it would be nice to have something like it instead of using the field generation and fieldwork mode to actually seed/fert the field, would be also just one course recording instead of 2 (self loading mode instead of seed/fert workfiled+ refill path).

or maybe do it on other way (and maybe simplier)......
use a refill mode, where a trailer with seeds/fert/diesel/other would drive towards the tool to refill it, just like a empty trailer heads to a combine to unload it.
to be honest, this option seems more usefull while using auto-tractor mod i believe.

what do you guys think about it?
thanks in advance for reading and hope to see courseplay in action soon in fs17...... with added features for trains :P

**Comment by Satissis** [comment]
>would it be possible to create a new mode for fs17 that acts simmilar to combine self unload mode, >for seeders, fertilizers and maybe other tools, but instead of going to unload, they will head to a >(mobile) trigger to refill seeds or fertilizer?
That's already possible and have been for the last couple of games (Back from fs11) thou it's not possible while using the auto-tractor mod.
Look at the CP guide: http://courseplay.github.io/courseplay/en/manual/index.html#driveMode4
on how to add an refill route, which is explained there as well.

Making an new mode, just because some people uses auto-tractors seams a bit pointless to us, so don't expect it ;)

**Comment by fudoido** [comment]
i know that mode, hence i suggested something simmilar to the combine self unload mode, but instead of unloading, would refill.
its not about using the auto-tractor, even the regular helper could use that mode. i believe it would just prevent an overload of recorded courses due the field course generation, and isnead of 2 combined courses, it would only use 1.
anyway, it was just a sugestion, hope you guys can work out the kinks of courseplay for fs17 as soon as possible. :)

**Comment by Simba76** [comment]
anyway, it was just a sugestion, hope you guys can work out the kinks of courseplay for fs17 as soon as possible. :)

**Comment by sootysax** [comment]
I'm there for you guys when you need beta testers :)

**Comment by Simba76** [comment]
谢谢

**Comment by jiggin** [comment]
Lets get it converted to 17 first, then offer new additional upgrades!

**Comment by Simba76** [comment]
不错啊

**Comment by Satissis** [comment]
@Simba76 sorry but we don't understand what you are saying ;)

**Comment by Simba76** [comment]
Look forward to CP support FS15!

**Comment by sootysax** [comment]
well it seems that AutoTractor is not going to be developed for FS17 anyway

**Comment by Robyvit2000** [comment]
I can have the new CP for Farming Simulator 17? Also the beta. I could also join me to you to improve your work at least the translation of Italian. Sorry for my English.. ;)

**Comment by Satissis** [comment]
@Robyvit2000 you are welcome to help translating the new things when the first beta is released here on Github.
Regarding getting the beta before time, then no. You will have to wait just like everyone else. ;)

Anyway. An update again from me.
Yesterday I just finished the new save system. Here is what have changed:

> courses and folders are saved in CoursePlay_Courses/(mapID)/
> Each course is now saved in there own files
> courseManager.xml holds information on what course each file belongs to.
> courseManager.xml holds all the folder setup as well.
> All settings are stored in savegame(x)/courseplaySettings.xml file and only saved on save game save.
> All custom fields are stored in savegame(x)/courseplayCustomFields.xml file and only saved on save game save.
> If an old courseplay.xml is found and no folders and courses are saved, it will import all settings, courses and folders from the old file into the new system.
> If an old courseplayFields.xml is found and courseplayCustomFields.xml is not found, it will import all the old custom fields into the new section.

All of these changes makes the saving an course allot faster and deleting an course is also really fast now, since it don't need to rewrite one big file with all the remaining courses in it.
This should also remove all those corrupt file problems we are having, again, because it don't work with one big file anymore :)

**Comment by Robyvit2000** [comment]
@Satissis I wait anxiously for the first beta. but I remember that the first beta was not released before the middle of November, but still do not know when it comes out? at least here among the producers of the CP and beta-testers that they can try and testare..o I'm wrong?

**Comment by Satissis** [comment]
#1375
