### ISSUE TITLE
Courseplay for 2017 

### ISSUE THREAD

**Issue by farmernick** [Courseplay/courseplay#1355]
So farming sim 2017 is out but it's not the same without Courseplay so is there going to be a version for 2017, done anyone have any ideas on what can be done to try and get it working on 2017 if that's even posable?

**Comment by farmernick** [comment]
Here's a link to the Courseplay user forums discussing the future of CP for FS17. While I can sympathize with FS15 users who won't get their bugs fixed, I feel this is the smart move for the CP guys to focus on the new 2017 version. 

I hope the gap between the release of FS17 and CP is a short one.

https://github.com/Courseplay/courseplay/issues/1346

**Comment by farmernick** [comment]
I was really worried that you weren't going to make a version for FS17

I'm absolutely delighted you will be!

**Comment by farmernick** [comment]
I consider CP to be a mandatory mod in FS 15, and greatly look forward to its FS 17 release.

**Comment by farmernick** [comment]
I decided to donate to CP you can to at to help them get the 2017 version done https://courseplay.github.io/courseplay/

**Comment by Beebtrek** [comment]
Chucked 20 Euro at the team good to see contiuned support

**Comment by ymisafir** [comment]
waiting for fs 17 great addon

**Comment by Simba76** [comment]
Me too

**Comment by sootysax** [comment]
http://www.farming2015mods.com/farming-simulator-2017-mods/fs17-other/fs17-courseplay/

obviously a shitty unauthorized conversion - don't get your hopes up when you see this

**Comment by Satissis** [comment]
Exactly as @sootysax said. This happened last time as well, when we were converting it over to FS15

**Comment by INDEFITY** [comment]
Satissis, then it is not a real courseplay?

**Comment by Satissis** [comment]
Of cause it's not :) the first place CP will ever released is here on GitHub as an beta and once the beta stage is over, it will only be uploaded to certain websites and not those fraud sites, which always steals other peoples work and put it on them, so they can earn money of some one else work.

**Comment by sootysax** [comment]
not sure if you are taking suggestions or not, but a big one i always wanted to be implemented would be taking jnto account the working width when generating courses with headlands.

meaning when you have a 24m spray and make a headland, the internal lines would start not based on the center of the headland line, but the inside edge of the headland.   this would eliminate much overlap and overspray. 

not sure if im making myself clear, but hope you get my thought..

Scott

**Comment by fudoido** [comment]
considering that you guys had advice from giants staff, will cp17 have new functions, or just bugs fixed? any prevision for release? how can one become a tester? (i have made alpha and beta testing for games before, would like to help if possible).

**Comment by Satissis** [comment]
@fudoido First of all, we want to make CP stable before release, so adding new features is not our priority, but maybe and only an maybe there will be an surprise in the first beta version ;)
Regarding how to become an tester, well everyone that get the developing version is basically an tester, but no one can start test it until we actually make the first beta release here on Github, so as everyone else, you will have to wait for that as well :)

@sootysax I know exactly what you mean. Maybe in some time, but I don't think it will be done in the first Beta release.
About asking for improvement, we don't mind people asking them, but I don't think we will take them into account until the first beta is out or even possible first at the first Stable release, since there will definitely be some bugs, as always, that needs to be fixed.

**Comment by Beebtrek** [comment]
Yes I agree we all must be patient. As for adding new features, yes lets us get a beta out to test and when things become stable ok new functions and additions maybe. I miss my auto tractors unloading to overloaders <grin>.
Thanks in advance. Regards Beebtrek.

**Comment by jorn-fa** [comment]
not sure if this is the correct spot to post this, but i download the conversion of whomever did it , and ran into an issue with it, regarding seeders without Ridgemarkers.     I know its not an offical version ofc, but your gonna run into the same problem as theres seeders without Ridgemarkers.

basicly lau start spitting out errors when using seeders without ridgemarkers so i did a dirty fix to the code to get it working without lua error.

In mode 4 i changed ridgmarker to have a value , im suspecting the code gets a value it cant handle when there is no ridgemarkers


	local ridgeMarker = prevPoint.ridgeMarker;
	ridgeMarker = 1;

i know its a diry fix,    i tried  if ( ridgeMarker == nill ) then ridgeMarker = 0; but that wouldnt let me start the mode at all

hope it helps a bit

Jorn

**Comment by sootysax** [comment]
the sloppy conversion is full of errors

**Comment by erksartori** [comment]
Well guys, I know that your work is the best. No doubt I'm playing the farming simulator 2013 and 15 good, with the program for you. Well I am Brazilian, and I am waiting for the new courseplay for FS17. For game alone, and the program you help me a lot to make my videos. Please, once you have a version where we can use and of course test with you, let me know please. Once you have something, I'll post on my channel, and of course the credits will all of you. I can not forget it.
Strong hugs everyone.
Congratulations.

**Comment by fudoido** [comment]
@Satissis  regarding the developer version, latest builds for fs15 i got them from an developer version updater downloaded from fs-uk site, but in its support topic someone says it no longer works (posted in december 2014).
is there any kind of dev version updater also, or will this same verion work?

**Comment by farmernick** [comment]
November was the guide date that we would be an update regarding CP for FS2017

**Comment by farmernick** [comment]
Almost here

**Comment by Satissis** [comment]
@fudoido I don't know if it will work for the FS17, but I believe that program is using an git plugin to get the latest files. If this is the case, then once we push our first beta into github it will take download the new fs17 stuff.
The FS15 will be put into it's own branch, in case someone needs the old FS15 version. We did the same for FS13

**Comment by gibson89** [comment]
Am I the only person who has realised we can download the latest version of CP as the guys work at getting it to beta stage?

**Comment by sootysax** [comment]
@gibson89 the latest version of CP for FS15...  not for FS17

**Comment by Satissis** [comment]
@gibson89 that is true, but I wont tell how to get it. Also, even that if you find it here, then it wont work either, since we have deactivated it for anyone else that Thomas and me + some other stuff.
We are doing this since while converting it, we really don't want any bug reports on it until it comes into beta, else we would have to use allot of time looking here for your reports, which we rather wound not do, but use our time converting it instead ;)
So if you know how to find it, fine, but please dont show others how to get it, even that they cant use it anyway

**Comment by RealZwox** [comment]
I downloaded the unauthorized conversion yesterday (shame too me) but farm 2 hours potatoes for a mission? No way :D

**Comment by gibson89** [comment]
Cool - sorry I should've kept to myself

**Comment by Vanquish081** [comment]
Where is the beta version for FS17?

**Comment by JanZacher** [comment]
http://www.farming2015mods.com/farming-simulator-2017-mods/fs17-other/fs17-courseplay/

**Comment by sootysax** [comment]
JanZacher: are you serious?

**Comment by Vanquish081** [comment]
He hasn't read anything from the thread hahaha

**Comment by Beebtrek** [comment]
Putting my BIG SIZE 10'S in here <grin>
The reason the Alpha is not available is because someone will put it out to a release site, with good intentions no doupt. But that will then cause a very large volume of BUG reports. As people will not abide by the rules of using such releases. This does not help the dev's.

SO WE ARE JUST GONNA HAVE TO BE PATIENT. 

I Want it now too.

**Comment by JanZacher** [comment]
I have found this on the page that is a version which is good times runs well up to a mistakes have it only by chance seen on the side but for the people who do not want to wait under nerves until the right there is they can play with there And the programmers are calmly doing their work so that they can work quietly on the project

**Comment by olavinto** [comment]
A release will cause bug reports etc. and that will not let "developers work quietly". The amount of feedback will be much larger than it is now, without an official release (alpha/beta/final). This is also why an unofficial build is bad - it will cause unwanted feedback towards the official developers who do not have anything to do with it (this can already be seen even in this thread).

**Comment by knoxville73** [comment]
Be patient, and leave the team alone ...

**Comment by Satissis** [comment]
@Vanquish081 nop that will not be possible :) you all just have to be patient and wait

**Comment by Vanquish081** [comment]
@Satissis ok, I wait... but if you need for test or translation to spanish, only said me.

**Comment by Simba76** [comment]
@Satissis ok, I wait... but if you need help for test or translation to Chinese language, only said me.

**Comment by Vanquish081** [comment]
@Simba76 >_>

**Comment by Fogest** [comment]
Out of curiosity when there are beta and/or public releases coming out for 2017 where should I be looking to hear about them? I have an RSS feed setup on the Github releases page, and a script checking for page changes on the Github.io changelog page, but is there anywhere better to be looking?

**Comment by Homskiy** [comment]
Beta release will not. Will be paid DLC ;)

**Comment by Fogest** [comment]
I am confused what you're saying? Are you saying this mod will instead be
included in a paid dlc?

**Comment by Homskiy** [comment]
I see no reason why not to create beta branch in git. Therefor, I think that in the future this modification will be separate DLC. In addition, one of the developers invited to GIANTS.

Sorry for my English, I hope you understand.

**Comment by Fogest** [comment]
Ah okay, so you're saying the beta will be on git, but the full version will be released as a DLC? Would this be a paid DLC do you think, or a mod available through the official farming simulator mod hub?

**Comment by Homskiy** [comment]
Beta is still not in git, and I think it does not appear there ever, if developers planning monetization. This is my personal view (i am not developer).

**Comment by Vanquish081** [comment]
Sorry, I don't believe that Courseplay will be DLC

**Comment by Fogest** [comment]
I do not really mind if it is a mod, dlc, or paid dlc, I am more interested in where I can keep up to date with the development progress so that I can get the mod as soon as it is out :)

**Comment by ThomasGaertner** [comment]
@Homskiy : if you have no idea from any facts, please shut up instead of spreading wrong rumors !!!
there is a reason why we dont have a public beta at the moment: some guys would draw it and publish it as their mod ,which we can't accept...

**Comment by Fogest** [comment]
Ah thanks for some actual facts! That makes absolute sense to not have a
public beta. Is there anything I can get involved with to help? I am a
developer as well.

**Comment by JDTiger** [comment]
it will NOT be a paid DLC, but it is a very complex script, wich must be nearly completely rewritten, because of the changes from FS15 to 17... therefore they work together with GIANTS...
This also is the reason, we don't have a beta, it is a lot of work and they do it in their freetime...

If you know where to look, and i won't tell you where, you can actually watch what they do at the moment...

Also, as stated before, a rewlease of the actual build would result in a lot of bugreports and most of them bad ones... to avoid that, they first need convert the mod to a point at wich most of the quirks have been eleminated and they can't find too many new bugs...

Just be patient and stop imagining conspiracies and spreading them, the team has already enough to worry about with the Conversion of CP itself...

Greets JD_tiger (not involved in programming and Courseplay in any way)

**Comment by Fogest** [comment]
@JDTiger You seem to know a thing or two about the project. Do you know anyway I could get involved with the development or at least a more QA side of the project? Feel free to email me from my Github profile if you do know something and don't want to share it publicly.

**Comment by JDTiger** [comment]
I am sorry but no...
I am as stated not involved with the Project in any way...

Where do i have my infos from?
I just read this Thread :P

**Comment by Homskiy** [comment]
2 ThomasGaertner

You refute the rumors about the DLC? Or not? :)

**Comment by knoxville73** [comment]
Homskiy,
This rumor is your rumor !
Let work the team and be patient

**Comment by Homskiy** [comment]
It does not matter whose it is a rumor. The main thing that it has not denied officially.

**Comment by Satissis** [comment]
@Homskiy I can answer that as well.

No CP will never be an DLC. The reason is that it's too heavy script based, that even if Giants agreed to let us make an free DLC, it would never happen because of that.

**Comment by Homskiy** [comment]
> No CP will never be an DLC.

If you are developers team member - thanks for answer.

**Comment by Satissis** [comment]
I am. together with @ThomasGaertner

**Comment by sootysax** [comment]
I have been active on this Github for many years, and never have I seen such speculation and posting by people who are not involved with the project...   When did this become a forum?

**Comment by Homskiy** [comment]
Comment button exists - this is forum. Disable it or kick me and no problem.
