### ISSUE TITLE
这里很安静

### ISSUE THREAD

**Issue by Simba76** [Courseplay/courseplay#1357]
It's very quiet here.

**Comment by Satissis** [comment]
yeah it will be as long we are working on converting CP :)
We might only look here some times, while doing it, so there will not be many updates until we have an beta ready ;)

**Comment by MartinGrisotto** [comment]
AFAIK cp is working OK in FS17, isn't it? To some extent at least... :P

![image](https://cloud.githubusercontent.com/assets/10392883/20028442/f5df5806-a331-11e6-91a7-d7e030aa204c.png)
![image](https://cloud.githubusercontent.com/assets/10392883/20028474/f3eb35e6-a332-11e6-87ee-70d825c7d39c.png)

**Comment by Simba76** [comment]
I don't agree

**Comment by MartinGrisotto** [comment]
Cool. In the meantime, lemme play FS17 with CP.

**Comment by Gargy** [comment]
Port from FS15 is somehow "usable..." There are some bugs, some of them can crash your game. In the port are some key bindings missing, some units (like km/h or mph in speed settings), there is nasty bug in graphic - driver is one on another after selecting vehicles (can crash your game), because of modification for helper, empty combine mode is half usable (crashing into harvester at the end of the field), on streets its ignoring the traffic (crashing into them when driving behind), sometime loader doesn't remember which crop should fill etc... There are probably quite some more which I didn't noticed...
But - it is usable to extent that this game is "playable" - at least for us playing exclusively with CP  :)

**Comment by silvaport** [comment]
Please keep working...
The game doesn't make any sense to me without CP
Your work is appreciated thanks

**Comment by Satissis** [comment]
Closing this to clean up issues
Continue in #1346 if needed
