### ISSUE TITLE
[FS17 - 4.0.1.00124.dev] - Shovel not found

### ISSUE THREAD

**Issue by lsv** [Courseplay/courseplay#1359]
Shovel not found in shovel mode.

Im using the "Universal Shovel" on a tractor with frontloader.

![](http://i.imgur.com/Gx4ZBCE.jpg)

**Comment by Phantum** [comment]
Thats not the official fs17 cp mod, it's one that someone randomly changed some version numbers on and uploaded.  

Going to have to wait for the actual FS17 version of courseplay for fixes to things like this, (not going to be anytime soon yet)

**Comment by Phantum** [comment]
If you do use that version, dont do anything chaff related, dont use seeders etc without ridge markers, and be careful sending workers out on the roads as they can run into traffic/ have traffic run into them.

other than that, it should work for the most part.

**Comment by Wacko71** [comment]
Possibly because CP is not released yet for FS17. You are using a modified version that is not endorsed by the team running CP. I know this because I use the same version you use and use it at my own risk. I have managed to get the harvester and empty harvester working and even this is with bugs.

If you read a few of the posts you will see the guys are working hard to get us a stable version of CP but posting issues for non verified versions delays their time getting an actual version out for us.

**Comment by Phantum** [comment]
Wish there was something I could do to help, but my coding skills haven't been used in 10 years, and thus I forget almost everything :/

**Comment by Fogest** [comment]
They are actively working on the new version. I'd suggest for now just
using the unofficial version if you really want one to use however it's
unofficial so you're not really going to get support for it here.
