### ISSUE TITLE
Problem to create route

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/courseplay#1377]
This route have issue in curve of field...

![Example](http://i.imgur.com/MvxVWoV.jpg)

**Comment by Satissis** [comment]
Yeah that's an know old issue, that we can't really do anything about right now, since that would require an new avoidance system to go from one endpoint to the start point on the opposite side of the obstacle.

I might have an idea to how to work around this, but that will not be an easy task right here and now and is something that would have to wait for an later date.

**Comment by sootysax** [comment]
this is classic CP behavior, if you would have run the course North/South, it would have worked fine.

**Comment by fudoido** [comment]
while in "fieldwork" mode, it wont do any obstacle avoidance while operating, best solution is to find the best direction to avoid those field "gaps" and avoid obstacles.
as @sootysax mentioned, doing it on a north/south direction instead of east/west would be a better choice in that field, since doing N/S will find less gaps and obstacles in the paths created, loosing the benefit of having less turns to harvest the full field.

(thats the kind of field where auto-combine/tractor would be needed, shame creators wont be updating it to fs17 *sniffs* )

**Comment by Vanquish081** [comment]
@sootysax Yes, I did it.

**Comment by Satissis** [comment]
I have added it to our pivotal Tracker, so once we start getting some free time, I will have an look into this :)

**Comment by Satissis** [comment]
@Vanquish081 do you remember what map you were using here ?

**Comment by Vanquish081** [comment]
@Satissis Yes, Hof Bergmann Map in #FS15

**Comment by Satissis** [comment]
Hmm if we don't have an FS17 map with that kind of shaped field, I won't be able to have something to test on.

Regarding your second problem, then that's not something I want to do anything about, since that's a question about making 1 single headland around the field to clean that up.

**Comment by Vanquish081** [comment]
Ok, I modified the next map where you can see this error:

[Map](https://drive.google.com/file/d/0Bz4sImAjNZ9BM0U3SUczYV91TzQ/view?usp=sharing)

![Example](http://imgur.com/kfgIVOv.jpg)

![Example](http://imgur.com/I8wzXbd.jpg)

**Comment by Sythos** [comment]
Actually i've "workarounded" setting by hand 2 or more edges (fieldXX-part1, fieldXX-part2, fieldXX-part3, etc.etc.) picking the slices to avoid critical lanes, so loaded to append one to other. This seem work, but is very nasty and time consuming, can be done something alike via CP? Should be like a check if a lane go outside outer lane or field edge, if yes so "split" the field area perpendicular where the lane go out (i know, is simple to say, maybe not so much code in LUA :D )

**Comment by Blackmankot** [comment]
@Satissis Can this issue be closed? To cleanse the topic.

**Comment by pops64** [comment]
This will stay open until it is resolved. Which won't be until after the release.

**Comment by Blackmankot** [comment]
@pops64 I understand you. Thank you. I'll know.

**Comment by LGRDDOG** [comment]
For the U-shaped fields, I found that adding headland rows quite often fixed it so that it no longer left the field (however it *Would* cross over the inside of the U's headland area when doing the straight portion.

As for the field being cut off (as in image #2) I've only had that happen on really large fields when I have the distance between points for the field border edging set too low.  Apparently, there is a maximum # of reference points that it can use for border detection, and once it hits that max, it simply makes a straight line from the last point it could make, to the first.  Increasing the distance setting (in the courseplaysettings.xml decreased the field edge accuracy, however, reduced the number of points so that it could actually make an edge path for the field.

Not sure if the second thing is the same as what I've experienced, however I figure it never hurts to try.  I only discovered that *fix* since as soon as I started a new map, I always exited and set the point distance down from the default of 5, to 1 for better edge accuracy.  :)

**Comment by pvajko** [comment]
You probably want to take a look at https://github.com/pvajko/course-generator, also https://github.com/pvajko/course-generator/issues/12, the discussion at https://github.com/Courseplay/courseplay/issues/1793 and maybe https://github.com/pvajko/courseplay

**Comment by pvajko** [comment]
Closing this as the new course generation can handle this situation.
