### ISSUE TITLE
New folder structure

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#1398]
Thanks a lot for your increíble word, you really made huge improvements in data management, and safety, I like so much the slot system. This will allow to avoid problems with savegame saving process. Also sync courses seems now much more easier. And deletion of courses, folders, ... Is much more clear. 

 I have just aquestion, the system now is indexed on maps,  as folder creation courseplay_courses, What if I have two save games with the same map, let's say Map01 Glodcrest valley, I will only have one set of courses for this map ? And if I run any of the save games with the same map, I will get in any of them the defined unique set of courseplay courses? 

That's avoid to have to copy files as in FS15, and provide a good source to sync in multiplayer.
I suppose this is the way you thought will work better and for me make totally sense.

**Comment by Satissis** [comment]
yeah, since we uses the map id as the folder each savegame with that map will have all the courses that you did in an older one.
If you merge 2 fields together and save it as an new field definition, that will only be for the savegame and not the map it self, since if that was done so, all the defined fields would not fit together since you might do differently in another savegame.
That's totally up to the user to make folders for special defined fields as well :) just an side node ;)

I am thinking on changing so that courses that is not used on game start, will not be loaded in, but will first be loaded when they are loaded from the course list it self. That way the game would load faster and also save memory for courses that is not loaded :)

**Comment by PromGames** [comment]
This reload  could be Having a button to reload courses from the xmi? that would be very nice, then we can update the courses after edited with the editor and see ingame the results without the need to start the game again.

**Comment by Satissis** [comment]
yeah I'll think about that :)

**Comment by omegaMV6** [comment]
I`ll think, the first we need is an offline-Editor (Course-Drawer) and then if it´s possible an reload button for this in CP ;)

By the way, many thanks for courseplay and all the work you´ve done for us! 

greetings
omegaMV6

Sorry for my bad english, i´m from Germany
