### ISSUE TITLE
Arcussin auto stacker

### ISSUE THREAD

**Issue by Karlshoj** [Courseplay/courseplay#1416]
Thanks a lot for the CP 17

I have got a problem with the Arcussin auto stacker.
When coming to the end of the lane it starts running in circles instead of running the next lane.

**Comment by xiTango** [comment]
I have also had this with the Ursus Z-586 bale wrapper.

**Comment by iceman4** [comment]
hi ich denke,
es kommt von der Geräteversatz ,ich habe die selben probleme immer wenn ich mit geräteversatz arbeite

**Comment by Satissis** [comment]
Please try again with v.019 and report back

**Comment by iceman4** [comment]
Hi now the Pottinger Novacat 302 ED works fine with device offset 
thanks for the fix and great work and support !!!

**Comment by Karlshoj** [comment]
Thank you. Its working now.
I'm running a 10,5 m line distance, which doesn't leave enough space for the turning (circle 22 m), coursing the  tractor to collide with the bales waiting in the following line.
Could it be an idea if you are facing a right hand turn then when you have finished  line 1 let the tractor reverse and pull to the left sufficient distance to allow the right turn without overriding line 2.

**Comment by Satissis** [comment]
Yes that might be possible in the future. For now there is an setting in the "Settings Combi Mode" tap, called "Turn on Field" if you deactivate that one, it will never reverse with an trailed tool, so in your case, it will make an Ohm turn, like Giants do, at the end of the line into the next one.

Could you post you last suggestion in a new issue, since then I can close this one (Or you could close it)

**Comment by Karlshoj** [comment]
I will fiddle around a bit more with we already have got, and re-think what would be the best solution.
