### ISSUE TITLE
Shovel Mode / Transport Mode and Heaps

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1471]
I'm trying to figure out the best way to use CP to move silage from a cow bunker on the farm to the BGA and sell it..

In FS15 CP would recognize placeable heaps as tip triggers..  CP doesn't seem to do so in FS17.  Can I set a waiting point to tell CP when to unload?  Not to mention tractors seem to get hung up on heaps pretty badly if you tip from the side, the only way it would work is to back up and dump in from the back.

Also shovel mode doesn't seem to deal with heaps very well either (at least wide, side tipped heaps)..  have you guys done any testing with shovel mode and heaps (silage, potatoes, beets)?   How do you go about setting up a course if you can't drive over the top of the heap without getting stuck?

**Comment by ThomasGaertner** [comment]
nope , heaps tipping is not implemented at the time , but on our list, same for loading heaps in shovel mode. Since you can use recorded courses of all savegames with the same MapId, you can open a new savegame with the empty bunker, record and save the course  and you have it in your other savegame also.

**Comment by SquareCloud506** [comment]
The way I would setup a course for a shovel with a heap I couldn't drive over (mostly because of Pleasant Valley 2.2 quarry) is I would start recording the course driving up to the heap with the first waypoint, then pause the recording and drive around the heap to the other side facing away, then unpause the recording to get a couple more waypoints, hit the second waypoint and a reverse, back up to the back side of the heap, pause, drive around to the front of the heap, unpause, continue backing and finish the rest of the shovel route.

Maybe using this method using CP for FS17 would work with a heap you cant drive over without creating a new savegame.

**Comment by pseudex** [comment]
> How do you go about setting up a course if you can't drive over the top of the heap without getting stuck?
You can record the course around it and correct it with coursedrawer: https://github.com/pseudex/Coursedrawer

**Comment by pops64** [comment]
Closed to keep the issues are clean this is in the tracker for us to do
