### ISSUE TITLE
just had this error

### ISSUE THREAD

**Issue by bigdigger** [Courseplay/courseplay#1515]
Load mod: vehicleSort
Load mod: ZZZ_CommodityPrices
Load mod: zzz_courseplay
Error: Unsupported mod description version in mod zzz_courseplay
Load mod: ZZZ_GPS
Load mod: ZZZ_GrowthControl
Error: Can't load resource ''.

im using stream accout of the game which just updated its self

**Comment by bigdigger** [comment]
Leave a comment

**Comment by Satissis** [comment]
well if you have v.035, then yeah that will happen. I made an mistake while making an push and changed the wrong number, but I fixed it shortly after in v.036
Basically it just notifying that you are running the wrong game version, but since you are using steam, that's not the case, so the only reason for you getting this is the you are using the v.035 here for github :)

I'm also guessing that you figured it out since you closed this issue ;)

**Comment by bigdigger** [comment]
no, closed by accedent,  just closed waiting for next update form your great work, keep good work up I don't play the game without your mod.


________________________________
