### ISSUE TITLE
Courseplay rutes

### ISSUE THREAD

**Issue by ZZenon** [Courseplay/courseplay#1522]
Is it possible to make a networks of points (recording all roads) and then for example if u want to send a tractor to "cows" just use transport and the tractor goes to nearest point and then folow the road. This from any point on the map. If im not mistaken autodrive has that feature but i could never make it work because of constant crashing

**Comment by tjb8907** [comment]
I wasn't going to add this suggestion yet since beta isn't the right time for huge upgrades, but I will chime in since someone else added it too. 

I have started using AutoDrive in conjuction with Courseplay, and I really like them both, I think they are a good compliment to each other. I like the ability in AutoDrive to select a destination and it goes there without having to record separate courses for each destination. I realize that you can do that with course play routes and crossing points, but it is somewhat tedious I think. (creating routes for AutoDrive on maps other than GoldCrest is too). 

They both have their strengths and weakness is, and I know its a HUGE project, but it would be cool to see something similar integrated with courseplay. I play single player only and like big maps, so I usually have all field work and grain handling on courseplay and then take care of the animals manually in the meantime. 

One example that I use AutoDrive for is parking equipment. For example, I have a refill route that goes past all 4 refill triggers (seed, liquid fert, solid fert, and fuel) I record a route from field to the farm, and vice versa, then combine the Fieldwork Route with those 2 routes, plus my refill route (in the correct order), and when the Seeder finishes it's route, I send it on the refill route, and have it stop at the next trigger. From there I engage autodrive to go to the seeder parking spot, so it is not in the way for when the sprayer or another seeder comes through. 

Anyway, I'm rambling now...haha. Just wanted to throw out there how I use the two together. Like I said, its a huge upgrade to have for courseplay, so I understand if its not a high priority, or even feasible.

**Comment by sootysax** [comment]
yes - i do this on every map, but it requires the courseplay editor (what i use)

you drive the lenght of each road, both ways and use crossing points at intersections.   when you combine routes, it will make the turn at the crossing points.   i record each road, each field, farm and sell entrance and exit.

it takes alot of tweaking in courseplay editor; but works great once its done.   you'll have to come up with a street name in convention that you remember because you need to load each segment of the trip each time.

**Comment by tjb8907** [comment]
I used to use the editor for FS13 and 15 too. However you have to create a route everytime, I like that autodrive you can select a destination no matter where you are at on the map. Courseplay however wins for about everything else. :)

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
