### ISSUE TITLE
CoursePlay Script Functions

### ISSUE THREAD

**Issue by tjb8907** [Courseplay/courseplay#1542]
Hey Guys, 

If you have a minute to help me out...I have a mod that I'm working on to add a few functions of my own to your great mod :). 

I had it working in FS15, but I'm having troubles with it in 17. 
 It has a couple functions, 1. I can load courses with a hotkey. I have a small HUD for my mod that shows the current vehicle type and field number, and when I push Ctrl + KP_0 It will load that course (I save all my courses in the right format, such as 3.Combine), so If the combine is in field 3, it will load 3.Combine).  The second feature is it assigns a hotkey to toggle the stopAtEnd option in CP. 

My problem is I can't get my mod to run any CP functions. I don't know if its Giants that changed how things work or not, but I have figured out how to access some of the Giants functions from a mod. I just can't get the CP functions to work. Here is a little snippet of my code that I used before.

`courseplay:clearCurrentLoadedCourse(self)`

but when it runs I get this because it can't reference "courseplay"

`C:/Users/Tom/Documents/My Games/FarmingSimulator2017/mods/ZZZ_zcpAutoLoad/cpAutoLoad.lua:69: attempt to index global 'courseplay' (a nil value)`

so after playing around, I tried this instead:

`self:clearCurrentLoadedCourse(self)`

and get:

`attempt to call method 'clearCurrentLoadedCourse' (a nil value)`

I'm studying other mods to try to figure this out on my own, but if you guys are willing to give me a pointer it would be appreciated! I am hoping to develop this into a Add-on for CP. I found it really helpful in managing many vehicles when I used it in FS15.

Thanks for any help you may provide! I can share more of my script if necessary!

**Comment by davidhunt135** [comment]
This would depend on where you are trying to call the function. Courseplay is always the last mod to be loaded so if your mod tries to call functions from courseplay any time before courseplay is loaded then these functions are not registered yet. You could try naming your mod with ZZZZ_ so that its loaded after to see if that is the issue. If your mod is a vehicle that needs courseplay to be registered on it then you will need to find another solution.

I'm not hugely experiences in LUA so please correct me if I'm wrong.

**Comment by tjb8907** [comment]
Already have it loading after courseplay, but that wouldn't matter anyway I don't think, and the only time I try to call courseplay functions is in the keyEvent function of my mod.

**Comment by Satissis** [comment]
I have been thinking on this since yesterday, but I cant see any reason it should not work, since the functions have not changed and courseplay should be an global value as well, unless Giants made so any mod specializations are now local to it's own mod folder now, which I would think was stupid.

Regards using `self:clearCurrentLoadedCourse(self)` then that might be because you are using an mod vehicle that is loaded after courseplay and is not getting courseplay specialization in it, but that's only guessing.

Sorry I can't be of more help.

**Comment by tjb8907** [comment]
The vehicle I'm testing with is a vanilla vehicle, and it definitely has courseplay loaded, so that part works. 

I appreciate the time thinking about it though! I have a suspicion there is some minor change to how the scripts work in 17 that I haven't found yet. I will keep playing around with it. Thanks anyway!

**Comment by Satissis** [comment]
Can we close this then ?

**Comment by tjb8907** [comment]
For what its worth. I believe I have this figured out. After extensive trial and error (heavy on the error), I have found that Giants must have changed something, like you suggested. It appears like you have to reference the mod folder name in order to access the functions, so instead of 

`courseplay:clearCurrentLoadedCourse(self)

I am using

`ZZZ_courseplay.courseplay:clearCurrentLoadedCourse(self)`

I have my courseplay folder named "ZZZ_courseplay" (even though it doesn't have to load last anymore).

I'm pretty sure I can have a way for it to find the name of the courseplay folder so it can be named anything, I just haven't got that far. 

Anyway, thought I would share my findings. Maybe it will help someone else down the road!

**Comment by Satissis** [comment]
or you could use something like this also:
`local courseplay = SpecializationUtil.getSpecialization('courseplay');`
That should give you an local instance of the courseplay specialization ;)
Also an good practice is to always check if the variable is avalible, like if you used that function above, but courseplay have not not been initialized yet, it should give you an nil value, so just do an:
`if courseplay then`
statement and do anything inside that :)
