### ISSUE TITLE
Lemkin Gigant 10

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#1552]
I have tried with multiple tractors to create a cultivate course using the Lemkin, but it leaves the beginning of each lane cultivated untouched for several meters.

**Comment by rmn18** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by lcc1211** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/672346/log.txt). I am using Courseplay version 5.00.00037 on FS17.

**Comment by rkaerner** [comment]
Errors are Errors. You, me and the rest of the world including Giants' staff are unable to know what kind of error in one mod will provoke other mods not to function well. So please: clean your mod directory. Throw the mods out that throw errors out. After that, try it again. If your discovered behavior of the Lemken is  still there, try it without any other mod in the mods directory. Why do I tell all this? I do missions with course play and also with the Lemken Gigant 10. And I do not have any problems in any situation. The only difference between our logfiles is: there is neither an error nor a warning in my logfile because I throw everything out that causes an error or a warning.

**Comment by ThomasGaertner** [comment]
what's the status ?

**Comment by lcc1211** [comment]
I have tried it again on GCV without any mods loaded and it worked fine.  I think this issue can be closed out.
