### ISSUE TITLE
Courseplay5 crash

### ISSUE THREAD

**Issue by tbonedaddyo** [Courseplay/courseplay#1557]
edited.  question withdrawn.

**Comment by tbonedaddyo** [comment]
I've just noticed that Courseplay5 is still in the "no mods" stage of development.  Would a particular mod cause this problem?  My apologies if I've jumped the gun posting this issue to you.

**Comment by SquareCloud506** [comment]
Are you able to start a new vanilla map with CP as the only mod and not get these errors? If so, it would be a mod conflict. 

And yes, CP beta is still in a 'no mods' stage, so if you can find the specific conflict, it can be added to the todo list of the fine CP programmers.

Cheers :)

**Comment by Satissis** [comment]
we cant say yet, since we are still in the no mod face

Also for further references, please post your log on gist or pastbin and put the link for it here instead, since a full log here takes too long to look through and a long way to scroll down to the bottom to the next post, so could you edit you first post and put the log in there instead. If unsure on how to do it, look at the wiki in the top tab here on github.

**Comment by tbonedaddyo** [comment]
Thank You.  Per your advice, I'm checking the mods one by one.

**Comment by thiemok** [comment]
I have the same problem and was able to narrow it down. First of all, it still happens with all other mods disabled. It happens to me while a wheelloader is unloading the silages bunkers at the BGA. For my specific case I could observe a few things going wrong here:

-  The shovel kinematics try to reach all target states at the same time, thus dumping some of the load if the angle between tool and arm is more acute in the loading position than in the transport position.
- If the previous problem dumps all the shovels (or in my case silage forks) content while moving into the transport position coursplay locks up on that vehicle after reversing out of the bunker.
- If coursplay locks up on a vehicle all input not directed at courseplay (eg movement, escape etc.) is blocked. So if you are in the locked up vehicle you can simply dismiss the current worker and restart the course, but otherwise only force quiting the game works

[http://pastebin.com/iCa4RVx6](url) (I don't know why its logging loaded mods the the logfile, I disabled an deleted them for the test)
I will add a video later, after i have set that up

**Comment by bigjoker76** [comment]
Hello all,
I saw the problem also. I´ve seen it, when the loader is not able to fill the shovel completely in the silo. This happens when he gets stuck in the silo wall, for example. There seems to be a timeout for filling the shovel...
Regards Jochen

**Comment by pops64** [comment]
I know this mode always starts at first waitpoint and I have no clue what the drive now button does in this mode. I would suggest if it gets stuck reverse it out of the silo and restarting it when it is facing the first waitpoint.

**Comment by nyfarmboy07** [comment]
I have had the same issue with the unloading bunker silo course.  I have had to force quit every time.  The loader will randomly stop between unloading and restarting the course, but that is a minor issue that may be related to my particular course.  I get the red message in the left hand corner of the screen that says "JCB slipping" and then my controls fail to function (i.e. ESC. F1. or any mouse function).  Like the above, it appears to happen when the loader enters the pile and contacts the wall of the bunker silo.

**Comment by ThomasGaertner** [comment]
since the question is withdrawn , I will close here to keep the issues section clean....
