### ISSUE TITLE
Problem after unloading chaff in reverse mode to silo

### ISSUE THREAD

**Issue by svent75** [Courseplay/courseplay#1618]
Hi,

I recorded the unloading route for grass trailer without trailer as I had to add a reverse part of the route due to unloading into a silo.
Everything works fine until the trailer is empty.
The tractor is then selection not the next possible waypoint in the forward route but an approx. 15 figures higher waypoint. This waypoint unfortunately is after a corner which leads the tractor shortening the route and running into a fence.
I use version 5.020 and JCB Fast Trac 3000 with Bergmann Repex 34S. I experienced the same issue also with other combinations and on different maps.

Greatings 
Sven

**Comment by tjb8907** [comment]
try recording the course with driving farther straight ahead out of the silo. It doesn't select the exact next waypoint, but instead goes to the next closest waypoint that is going forward, if the tractor is already ahead of the "silo exit" route, it can get messed up.

**Comment by svent75** [comment]
How many "straight ahead" waypoints are recommented?

**Comment by tjb8907** [comment]
This is the course that I am using right now, it works, but it is cutting it close. You can see how the tractor doesn't go all the way to the last reverse waypoint, so you need to have at least 1 waypoint in front of the tractor. In this case it will go to one of the circled waypoints, because they are the next "forward" waypoints that are infront of the tractor. 

![image](https://cloud.githubusercontent.com/assets/5883859/21748545/35a9692a-d54d-11e6-8a82-f705a726c754.png)

**Comment by tjb8907** [comment]
its possible that you are doing it right as well, and its a bug, but I haven't had much trouble with reversing into a silo if the course it recorded right.  :)

**Comment by ThomasGaertner** [comment]
yes , as tjb8907 said.....

**Comment by svent75** [comment]
It works fine now with adjusted "out-Course" of Silo.

Thanks for help
Sven
