### ISSUE TITLE
Edge of field resume work bug

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1626]
I know there is a closed issue about this somewhere. Sorry for the double post.  See video for the bug. My best description is when the Wait point is to close to the edge CP cant resume work CP doesn't give it the next waypoint to drive to.  [Video](https://www.dropbox.com/s/ym8ma6wtakrh0i8/Farming%20Simulator%2017%201_11_2017%207_45_03%20PM.mp4?dl=0) [Log](http://pastebin.com/wSF0CN20) [Savegame](https://drive.google.com/open?id=0B5ZZXJetOeMRQjhjTXUyU0RVSXM) [CP Courses](https://drive.google.com/open?id=0B5ZZXJetOeMRTldjSEpqSEFXSkU)

**Comment by ThomasGaertner** [comment]
#1500

**Comment by pops64** [comment]
Different. This is post abort work. Like #1423 but instead of doing doughnuts it just drives straight like in the video or drives a really big circle

**Comment by Satissis** [comment]
Should be fixed in v01.0031.
Try it out.
also I did an change that might affect #1500 but I did take it into consideration (I think) so could you test it again as well?

**Comment by pops64** [comment]
Sorry for the bad news but. Your fix did fix this issue but I was able to produce the 1500 issue in mode 4. I'll edit this as soon as I test to see if the 1500 issue has been fixed in mode 6 and Ill upload a save of mode 4. Maybe we can figure out why mode 6 behaves differently than mode 4 when resuming work and replicate it(Though this is not good when the resume waypoint is only 2 points or so from the edge) I'll upload videos to of the resume work

**Comment by Satissis** [comment]
Try again with v01.0033 or newer.
I did it a bit different, since I now check if in mode 6 and we are full, then abort the turn and if in mode 4 and either the seed or the fertilizer is empty, and the abort if that is true as well.

**Comment by pops64** [comment]
Ok. So the 4 savegames you have worked. I have another that I tested. The waypoint it aborted on was 66. The turn was 60 and the abortwork waypoint was 54. When it reached 54 it moved very quickly to 60(I think this was from the way my course is set up and CP think it has already made it these waypoints already) and successfully calculated and maneuvered a turn in the middle of a field.  [Video](https://www.youtube.com/watch?v=r53iPyPE0ik) sorry for the crap quality should invest in a better recoreder. I fixed this by bumping up the `local minNumWPBeforeTurn = 6;` to 8. 

Second question in `((tool.sowingMachine ~= nil and self.cp.totalSeederFillLevelPercent == 0) or (tool.sprayer ~= nil and self.cp.totalSprayerFillLevelPercent == 0))` My question is in this code if I run a sowing machines fertilizer level down to 0 will this return true? I ask this cause I believe mode 4 resumes work just as long as the levels are not 0. So it could be possible that you forget to fill the fertilizer and it will make this same bug occur? Or does mode 4 only go to refill course if the seed level is 0 in a sowing machine and not the fertilizer level?

Thanks for reading this book. Thanks for the update :D

**Comment by Satissis** [comment]
arh yeah, the reason it does that in the video, is that the angle you are approaching the abort wp is so steep that when it changes to the next wp, it checks the distance from the tractor to the next wp and if that is inside the change distance, it will continue skipping wp until it's far enough away, so since the tractor is so close to all the wp in the lane, it will skip further ahead that it should and it's hitting the turn point and starts turning.
I'll change the 6 to an 8, which just makes it resuming further back, but that's better than in the video.

Regarding the seeder with fertilizer as well, then the tool.sowingMachine is referring to the seeder part of it and the tool.sprayer is referring to the fertilize part of it, but that value is also used for other stuff, which is why it's called sprayer ;)
So that means that it both checks for the seeds and fertilizer as an separate value. = if one of them is empty, it will abort the turn ;)

Hope that explains it :)

I'll close this one once I have pushed the 6-8 change :)
