### ISSUE TITLE
Harvester Leaving Sections of Fruit in Field

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#1639]
I've noticed that if my harvesters reach 100% full just short of the end of the field, they will completely ignore the last 2 or 3 meters of the fruit.  I've been trying to reproduce it today, but all my tractors are getting to them before they get to that part of the field. Anyone else had this issue?

**Comment by lcc1211** [comment]
I managed to catch it doing the skipping.  Please see the video here:  https://youtu.be/zO_-lmyEVOk

**Comment by SquareCloud506** [comment]
I recall this happening in FS15 as well. if the harvester hit 100% and had to stop to wait for a tipper within a few points of the end of a row, when it resumed, it would start the turn maneuver and head to the next row, leaving a small patch untouched. Because of the rare time a harvester would stop at 100% near the end of a row, this probably was never addressed, or even mentioned, in earlier versions of CP.

**Comment by lcc1211** [comment]
If you hit the right combination of header size, grain tank capacity and tipper capacity, you can end up with this.  I can't remember the specific equipment, but on Westbridge field 17 it was happening to me every other lane.  However, I only saw it infrequently on other maps/fields.  The current custom field I am playing has it showing up a bit more frequently, though.

**Comment by pops64** [comment]
This is because if you look at the current waypoint indicator when harvesters resume work after unloading when full it will jump by 2 points. So if your within 2 waypoints of the edge of the field or stop work marker it will skip the fruit because the harvester is told that it is at a turn waypoint or stop work waypoint and will behave accordingly

**Comment by Satissis** [comment]
try with v01.0043 or newer and report back.
I was not able to tested it ingame, since I don't have an setup for it, but I believe I know what was the problem, so I made an change to lower the implement as soon as the it hits the turn marker, which should fix your problem.

**Comment by lcc1211** [comment]
I tried again with version .43 and it still left the last few meters of fruit, and it doesn't seem to matter if the end of the lane has fruit. I started harvesting with 2 headlands, so the harvester was further back (roughly double from the previous video.  So it is as if CP ignores the last few meters of fruit regardless.  Please see this video:  https://youtu.be/IiT6I9eFQ28

**Comment by Satissis** [comment]
Try out v01.0046 and report back.

**Comment by lcc1211** [comment]
Ran the course on the same field 3 times using the same equipment, same crop and plowed with 3 fertilizer courses (just like last time), but I could not repeat the  problem.  I think it is fixed.  Thank you again.
