### ISSUE TITLE
Target Point Layout 

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#1643]
Can you Fellows build in some kind of "Offset" for our Vehicles. As it is now the target markers that are placed by Building a Course, are on the Center Point of a Vehicle. Example... A truck that is 20 feet long and 8 feet wide, the Marker will show up at a point 10 feet from the nose of that vehicle and 4 feet from the side of the vehicle. Keep in mind we Steer from the front  ( Nose not 10 feet back, as the Marker shows ) This problem really shows when you Set a Pause Point, you will notice the vehicle stops 10 feet or so Ahead of the Target marker. ( I want the stop to be as I hit the Pause Point, not 10 feet further on. ) So if we could get a Vertical offset, that would help a lot.. Bob.

**Comment by Akoasma** [comment]
I would say, the Point is near the rear axle.
![fsscreen_2017_01_20_16_19_41](https://cloud.githubusercontent.com/assets/25203292/22155305/3a1959ac-df2f-11e6-8e09-4c13f57a8e78.png)
![fsscreen_2017_01_20_16_23_05](https://cloud.githubusercontent.com/assets/25203292/22155314/400c3168-df2f-11e6-8f05-416d309217a1.png)
Or whatever
![fsscreen_2017_01_20_16_27_18](https://cloud.githubusercontent.com/assets/25203292/22155366/7899d242-df2f-11e6-9664-15a018568e70.png)

**Comment by hackselgut** [comment]
Pictures here do skow exactly the problem, The longer the vehicle the worse the problem becomes, So now are you Fellows able to assist us with a remedy.  Bob.

**Comment by Satissis** [comment]
Well I know what your problem is, since the way I changed this in fs15 was that you start recording when the first trailer is underneath the silo. Once the route is recorded, it will stop at the first wp to start filling up in the first trailer. then if you have more trailers attached, it will take the middle of the next trailers top fill reference point and try to place it right under the middle of the silo and then unload. (Note that this is only working for the second trailer afterwards)

This result in this behavior in fs17, since the real turning midpoint of an tractor is in the middle of wheels that cant turn, so that's why most of them stops at the real wheels. (and trucks as you can see in your picture)

Now I have thought on a way to fix this. We would have to start recording the route right underneath the silo, so the first wp is underneath the silo. Then it will find the center fill point of the first trailer (or hooklift container) and continue driving forward until it's centered underneath the silo and then start unloading, which should fix your problem. then if you have more trailers attached, just continue doing it the way it's already implements as, since that part is working fine.

I'll put this onto our todo/suggestion list, since I have some stuff I want to finish before doing this.

**Comment by hackselgut** [comment]
Thank you very much  Bob.

**Comment by Satissis** [comment]
Bob ?!?

**Comment by Satissis** [comment]
Implemented in v01.0047.
Try it out and report back.

**Comment by UncleBuck62** [comment]
I think this change may have changed something else in the way overloading works.
I have a Harvester, Overloaded and a Semi-Trailer harvesting F20 on Gold Crest Valley. In the previous versions of CP this worked fine, but as of this version the Semi no longer stops and waits to be filled. It just keeps running the course that takes the grain to the silo.
Is there a setting that has been implemented which I have neglected to set up in this version?

**Comment by Satissis** [comment]
Nop, It's an thing I never had thought of and was pointed out to me when I got home from work today, so I have to look into this to see what I can do about it.

**Comment by Satissis** [comment]
Should be fixed in v01.0048.
If you experience that the tractor and trailer in an silo unloading course stops before the trailer go underneath the silo fill trigger, then you need to start your recording further ahead of the silo trigger.

Now to explain how this is done, so you understand the system of it, then if an trailer have not found an silo trigger and the tractor changes to waypoint 2, it will stop and wait for the trailer to be filled like with an overloader.

If it finds an silo trigger before the tractor changes to waypoint 2, it will center the trailer underneath the silo trigger and start loading, otherwise it will do as described above.

Try it out and report back.

**Comment by Akoasma** [comment]
![fsscreen_2017_01_23_20_25_54](https://cloud.githubusercontent.com/assets/25203292/22219437/05d4192e-e1ab-11e6-95a8-f8f9c4a1349a.png)

Thanks 👍

**Comment by UncleBuck62** [comment]
Looks like it is all fixed as previous courses I have recorded are working again. Thanks for your quick action on this one. Your hard work and dedication is much appreciated.

**Comment by pops64** [comment]
Looks like if the trailer isn't full because the silo ran out and you hit drive now. It doesn't switch to street speed it stays at crawl speed

**Comment by Satissis** [comment]
@pops64 it should be fixed in v01.0051.
Try it out and report back.

**Comment by pops64** [comment]
Works great thanks for the quick reply and update :D
