### ISSUE TITLE
Can't open CP HUD for certain vehicle

### ISSUE THREAD

**Issue by MartinGrisotto** [Courseplay/courseplay#1666]
Hi,

is there a possibility to hunt down a reason why CP HUD is not showing for certain vehicle? I downloaded some trucks and none of them is showing HUD, where as other mods work just fine.

**Comment by pops64** [comment]
Rename you courseplay folder to ZZZ_Courseplay

**Comment by rkaerner** [comment]
various mod vehicles here. No problems at all. Follow pop64's advice and everything will be good.

**Comment by MartinGrisotto** [comment]
This is gold, why i didn't think of it.... thank you :)

**Comment by Satissis** [comment]
Once I get an look into this, I really hope we don't need to add the ZZZ_ in front of it anymore :)

I'll close it for now to clean up the issues :)

**Comment by UnderminedArcus** [comment]
Hello, I have courseplay prefixed by ZZZ_ and it still doesn't show up in one of my **stock** tractors. I have 2 vehicles of this particular tractor, and the one where it doesn't show up is the last one I bought. I know this because I outfitted the first one with a front loader base. Other than that I can't think of a reason why it wouldn't show up. Is it possible that courseplay is only available for one (the first) vehicle of a given model

**Comment by pops64** [comment]
Try right click or Ctrl delete. CP sets default back to right click on vehicle purchase

**Comment by UnderminedArcus** [comment]
Neither input worked at the time (in the tractor I mentioned above, and then too in another tractor with a log trailer attached). I switched off a few other non-vehicle mods and I don't experience the problem now.

**Comment by pops64** [comment]
That sounds like one of those other non vehcile mods was creating conflict with CP or with the key bindings
