### ISSUE TITLE
Editable working width

### ISSUE THREAD

**Issue by DynamicXYZ** [Courseplay/courseplay#1699]
I'm wondering if it was possible to add a customizable working width. For example, you'd type in the value in a text box that only accepts numeric characters instead of clicking the arrows or using the scroll wheel.

The reason I ask of this is because some of the equipment's width's go over 10 meters and it's always like 10.3, 11.4, 12.7, etc. and don't match up with other equipment, a good example would be the Lely Hibiscus 1515 CD Profi (windrower) and the Strautmann tera-vitesse 5201 (forage wagon).

I read somewhere that the values were predefined though.

**Comment by Satissis** [comment]
holding down Alt above 10m will increase/decrease the value with 0.1m
holding down Ctrl above 10m will increase/decrease the value with 5m
and then the normal click/scroll is 1 above 10m

With these, you should happily be able to set the work width with ease.

Also, if the with calculator is too small, you would have to unfold the implement first, since not all width can be calculated when they are folded (Depends on how they are build)

**Comment by DynamicXYZ** [comment]
I just tested it.

Holding down Ctrl below 10m incr/decr by 0.5
Holding down Ctrl above 10m incr/decr by 2
Holding down Alt above 10m incr/decr by 0.1
Scrolling (and plus and minus buttons) below 10m incr/decr by 0.1
Scrolling (and plus and minus buttons) above 10m incr/decr by 0.5

Can the manual by any chance be updated on this? 
https://courseplay.github.io/courseplay/en/manual/index.html#hud_courseGeneration

**Comment by Satissis** [comment]
The manual is on our todo list, but it will first be taken care of when we are about to make an release

I'll close here to keep the issues clean :)
