### ISSUE TITLE
Nicht ganz Leere Ladewagen

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1707]
Hi! Hab ein kleines Problem das der Orginal Strautmann und Bergmann beim rückwertsentladen nicht ganz entleert! Vieleicht hat jemand einen tipp oder es gib vieleicht die möglicht eine einstellung zu machen das er trotz dem rest wieder fährt

LG

Hi! Have a small problem that the original Strautmann and Bergmann at the discharge unloaded not completely emptied! Maybe someone has a council or it gives many times the possible to make a setting that he drives despite the rest again

**Comment by rkaerner** [comment]
Which Map, what charge, where do you unload after reverse driving? Did you record the course without a trailer? Don't repeat my mistake and give us a sexy bug report instead as mentioned in the wiki, please.

**Comment by Paul2510** [comment]
Sorry! Map ist FS17_SuedThueringen entleeren Grass im CowSilo! Kurs wurde mit dem Ladewagen aufgenommen! 

Sorry! Map is FS17 South Thuringia emptying grass in Cow Silo! Course was recorded with the trailer!

**Comment by rkaerner** [comment]
Okay, The first and important thing: Never ever in the history of cp record a course with an attached trailer! Re-record the course without any trailer, just with the tractor. That hadn't happened in all the time cp exist. You record courses ALWAYS WITHOUT an attached trailer! Drive with that tractor ALONE straight to the point you normally find your trailer unloading. Finish your course. Let the cp helper drive it with attached trailer and charge. Tell your experience here and if your problem is solved, close this issue.

Okay, die erste wichtige Sache: Fahre niemals - never ever in the Geschichte of cp (*g*) - einen Kurs mit einem Anhänger ein. Das wurde noch nie in keinem Tutorial so behandelt. Man fährt Kurse immer ohne Hänger ein! Fahre den Kurs OHNE Hänger ein und fahfre bis zu dem Punkt, an dem normalerweise Dein Hänger entladen würde. Beende Deinen Kurs. Und nun lass den Abfahrer den Kurs mit Hänger abfahren. Berichte hier. Und wenn Dein Problem erledigt sein sollte, dann schließe diesen Vorfall.

**Comment by Paul2510** [comment]
Hi! Thanks very much! Its works! :-)!
