### ISSUE TITLE
Tractor not matching speed of combine

### ISSUE THREAD

**Issue by Zoochase** [Courseplay/courseplay#1723]
In Combi mode, the tractor does not match the speed of the combine.  Speeds up and slows down rapidly.

**Comment by pops64** [comment]
Yep been a problem since the beta release of FS17 Courseplay

**Comment by ThomasGaertner** [comment]
which tractor on which combine on which map ?

**Comment by Zoochase** [comment]
Since I have been using beta, all tractors and combines on all maps.  Specifically, Valtra S-Series, Krampe Bandit 750 and Case 9230 on Goldcrest Valley.

**Comment by pops64** [comment]
Can confirm. I have not seen a combination that this does not occur on. I have only used the MF 7347 and the Case 1660. The cruise speed limit goes from 4 to 8 mph

**Comment by rkaerner** [comment]
Thomas: not neccessary. Have the same Problem with MAN TGS. Speeds up and brakes, speed uo and brakes. So I think every vehicle is not able to get the speed from the combine. But: I haven't claimed about that until now because it is not really a problem. Looks a liitle bit ugly, but maybe the driver is drunken ;-)

**Comment by ThomasGaertner** [comment]
test v .0063 or higher and report....

**Comment by pops64** [comment]
Works for me. Thanks

**Comment by Zoochase** [comment]
Works like it should.  Thanks for the quick fix.
