### ISSUE TITLE
Suggestion:  Drive from Set Spot to Field and Begin Action

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#1772]
Since it is possible to have 2 courses loaded (i.e. fertilize the field and refill the fertilizer when empty), could it be possible to combine 2 modes such as maybe transfer and field work?  Ultimately, I think it would be fantastic to move the harvester from its parking place in the shelter to the start position of a field and start harvesting.

**Comment by pops64** [comment]
Yes it is already possible. To move from a parking spot to the field. Auto Geranate your field work course. Save it. Clear out that course. Load you transfer course. Merege(Same button has load) you saved fieldwork course. And your set. 

Basically the transfer course must come first before the field work course.

**Comment by lcc1211** [comment]
This is different from creating 2 courses and then loading one after the other?  So in effect, I have only one course loaded?

**Comment by pops64** [comment]
Your welcome the transfer course functions is only a few bits of code I didn't even know about. Just be carfull of the difference between append and merge. Merge will combine courses at the first crossing point(Not always the last point) This pic is my transfer corse to Field 7
![farming simulator 17 2_13_2017 9_41_19 pm](https://cloud.githubusercontent.com/assets/10678220/22912831/7fbf0f38-f235-11e6-8edf-5acb490e35fd.png)
Has you can see it is a loop. But I stuck a crossing point where it touches field 7. If I were to **append** this course it would look like this.
![farming simulator 17 2_13_2017 9_44_48 pm](https://cloud.githubusercontent.com/assets/10678220/22912875/b3c5a60c-f235-11e6-860f-09c7bb48d903.png)
Because append is dumb and just adds the course onto the end of current course. If I were to **merge**(same button has load) it would look like this.
![farming simulator 17 2_13_2017 9_41_53 pm](https://cloud.githubusercontent.com/assets/10678220/22912896/d69bb3d8-f235-11e6-92b0-0cca87d29a8f.png)
If you want to get really fancy you could add a refill course which is always the append button because Mode 4 and 6 are always expecting the refill course at the end of field work course. Which is why you can't add a transfer course onto the end of a field work course because then CP would think it is a refill course. But you can has you saw  in my transfer course create a loop and just clear out your field work course when your done and use transfer mode to go back to the parking spot.
![farming simulator 17 2_13_2017 9_42_30 pm](https://cloud.githubusercontent.com/assets/10678220/22912977/3d536166-f236-11e6-94ef-1e4c1e6279d8.png)

Sorry this went on long. Just want to advise in the difference between append and merge/load. For a fancy diagram http://courseplay.github.io/courseplay/en/manual/index.html#hud_manageCourses

Thanks for reading
