### ISSUE TITLE
A Request to re look at "way Points"

### ISSUE THREAD

**Issue by hackselgut** [Courseplay/courseplay#1782]
In issue #1643, I got an answer that it would be looked at, and then an answer was that it would be Implemented in Version 5.0100047, but as of version 5.01.00076, there looks to be no change made. Bob

**Comment by hackselgut** [comment]
![fsscreen_2017_02_16_11_27_33](https://cloud.githubusercontent.com/assets/10256656/23031912/b4a74e10-f440-11e6-9954-392e1c73cd4d.png)

**Comment by pops64** [comment]
This was only implemented for silo triggers. Wait Points are something different.

**Comment by Satissis** [comment]
the way point as you call it, is an Wait point and is not handles as you want it to in grain transfer mode (mode 1).
You need to start the course at the spot you want it to wait in the field.
Secondly the way it places the waypoints while recording is based on a vehicles center turn point, which in your case is at the rear axel on that truck. it's the same for tractors and it can't be changed how that's done, since it wont follow the path correctly then.

The change I made was also only regarding the silos and an offset value is not needed, since that is dynamic hard-coded based on the vehicle center turn point and the center fill node of the trailer/module and where the fill trigger for an silo is.

**Comment by hackselgut** [comment]
Mode 1 is Labeled ""load at Start" you nave to be at a location where you can fill the Vehicle, that is the Start Point. Now you enter the Record mode, and plot the Route, In the Route you can Set a "Pause Point " a place the vehicle waits at for a set period. Now we did not have this problem in the FS15 Version, at lest it did not show any problem. Can you not give us some kind of " Vertical Off-Set " to get the Target points over the Front Wheels. Note, The longer the Vehicle is the worse the problem becomes. Bob.

**Comment by hackselgut** [comment]
The Vehicle's center turn point, is that an item we got from changes made by Giants this year?  Bob.

**Comment by SavageMkII** [comment]
I would like to second that this is a problem. I recall that the old CP(4.01) would record waypoints from a point usually over the cab of a truck, and then when reading a course, try to steer towards the next waypoint as soon as it passed the current one. Now, CP drivers seem to "aim" at the next waypoint with that central turn point instead of the front of the vehicle. They overshoot the course, particularly on corners or curves, taking the corner or curve way too wide. The problem is really exaggerated when using a long wheelbase vehicle, like the truck bob was using above. It makes it so that CP drivers have real trouble in tight areas, or at least on courses with tight corners recorded

**Comment by hackselgut** [comment]
To Satissis.....You see there are two of us ( SavageMKll & hackselgut ) that are asking if there can be anything done to reset the points over the Front of the Vehicles, I will bet there are more people with this concern. or is this a fix for Giants to do.. Bob.   Your answer  Thanks.

**Comment by Satissis** [comment]
> The Vehicle's center turn point, is that an item we got from changes made by Giants this year?

Yes that's an Giants update in FS17

From my experiences, the way it's done now is actually better driving wise, but I also know the the standard trucks don't drive that well, without me having to change the point to around the middle of the truck, which is why the vanilla trucks are actually working fine and mod trucks might now work that well.

I might consider thinking on a way to check if it's an truck and if it is, then move the center point further forward, to improve the mod support without having to manually add them to the special tools section.

**Comment by Satissis** [comment]
Could you by a change give me a link to that truck, just so I have something to test with as an mod ?

**Comment by Satissis** [comment]
I did some changes in v01.00090 that should automatic center the steering point both for vanilla and mods.
It should help a bit on your problem.
I have more planed for it, but for now this push should help a bit

**Comment by hackselgut** [comment]
Hi Satissis....The Mod you asked about is a "Man Tgs with Fliegl Extension Ver 2" it was obtained from "Modhub-us" web site.    http://www.modhub.us/category/farming-simulator-2017-mods/maps/     You can do a Search for the mod here.

**Comment by Satissis** [comment]
@hackselgut yeah that means that I wont get it :)
I simply refuse to get mods from there, since they rip off other modders mods and upload them to earn money on stuff they have not created them self, which I don't support ;)

I'll find something else to test with instead ;)

**Comment by hackselgut** [comment]
Hi Satissis...Sorry you do not like that site...Yes I have D/L the version 90, There is an improvement with the Markers, They are further ahead than before, Could go further forward if possible Thanks ( see Pictures )  Bob.
![fsscreen_2017_03_02_13_43_04](https://cloud.githubusercontent.com/assets/10256656/23522611/a72c016a-ff51-11e6-891c-c6bc24210c3d.png)
![fsscreen_2017_03_02_13_43_16](https://cloud.githubusercontent.com/assets/10256656/23522612/a73151f6-ff51-11e6-83ce-418965f27cce.png)

**Comment by Satissis** [comment]
If I move them further ahead, then it will mess up there drivability a bit, but I did mention as well that I have more things planed, which includes an offset system for it.

**Comment by hackselgut** [comment]
When I do a "Load at Start" ( mode 1 ) I put in a pause point before the " end Point " So that I can ( refuel and also delay the second or third Vehicle in the Group. as there are some Moded Vehicles that do not stop before they Hit each other, so this allows me to Stagger them. Bob  Note.. look forward to changes, Thanks..

**Comment by Raints** [comment]
@hackselgut  I think you using it wrong. There is really no need for waitpoint, specially for refuel since CP will refuel automatically. And if vehicles wont stop then it is a crap mod.

**Comment by Satissis** [comment]
@hackselgut if the vehicles do not stop after eachother, then it might be because they are missing the trafficCollicion trigger in front of it. It's not uncommon to see modders forgetting to add that in, which is an simple 2 min job to do.
If you have development mode turned on from the game.xml file, you can hit F5 to see all collitions.

**Comment by hackselgut** [comment]
Using the F5 can I then add The option to a Vehicle or does it just tell me there is No collision rhere?  Bob.

**Comment by pops64** [comment]
It just shows collision. You have to go and edit the i3d file and such to add traffic collisions

**Comment by hackselgut** [comment]
Okay thanks  Bob.

**Comment by Satissis** [comment]
To see if it's missing the traffic Collision trigger, then the easiest way is to look inside the log.
In the load section of the log, check each vehicle it loads and if there is one of them missing the collision, then cp actually prints it in the log, right after the text showing that it's loading that vehicle.

to add it to those that are missing it, search the web about it or ask on some modding sites, like: [Modding Central](modcentral.co.uk)

**Comment by Satissis** [comment]
@hackselgut v01.00101 contains an update to offsets, so you should be able to set the offset of the wait point now. there is 2 new offset you can set, for load/unload/wait points.
This is the last thing I really can do about it, so try it out and report back.

**Comment by Satissis** [comment]
@hackselgut did you have an look at the new settings for this ?

**Comment by pops64** [comment]
Assumed that this is working for OP closed
