### ISSUE TITLE
Autodrive

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1789]
Have you guys been playing around with Autodrive at all?   it seems that development has halted on it, and it is pretty unstable and very crashy.  However, i really do like the road networking and way waypoints are layed out and how it finds the shortest path.

I would be interested to see courseplay adopt this kind of road networking, pathfinding or route combining somedayx

**Comment by jmj486** [comment]
If CP could make the same road network, that would be epic

**Comment by Satissis** [comment]
The idea ti good, but practically not ideal, since we would have to have 2 systems for driving then and they should also have to be able to work together, which is allot of work and could cause allot of issues.

Atm I don't see it happen, but who knows what the future holds.

Going to close here for now to keep the issues to the minimum.
(If some one want to implement it, we can talk about it in a new issue)
