### ISSUE TITLE
Overloader not stopping at unload/wait point

### ISSUE THREAD

**Issue by wjohnson048** [Courseplay/courseplay#1797]
Not sure if this issue has come up before, I searched for awhile and couldn't find any threads on it.
When using the overload function, I set my course for the auger wagon putting a wait point at a trailer to unload, but when you click drive course (with grain in the wagon) the overloader will not stop at the wait point (it will if there is not a trailer sitting there) and will continue to the end point. Now usually the first time I set up a new course and run it for the first time it will work but anytime after that, it won't stop.

**Comment by wjohnson048** [comment]
Also I tried setting up a course with debug15 active and still had the same issues.

**Comment by pops64** [comment]
What is your drive on percentage? What is the percentage of your overloader fill level? Log with debug 2 and 15 active.

**Comment by wjohnson048** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/791928/log.txt)
I started a new game as my save game2 with no mods except CP V5 and a money mod and came across the same issue, Drive on is set to 100%, I have tried this with a full overloader and one only at 10% by manually telling the overloader to drive the course to the unload spot.

**Comment by wjohnson048** [comment]
Alright so I just spent a fair amount of time doing different scenarios. Apparently (for me at least) if the overloader is unloading into the trailer at the wait point and you click on continue driver before it is completely unloaded it won't stop at the trailer for future passes, so I got it working, just the overloader has to be at 0% when leaving the wait point.

**Comment by pops64** [comment]
If you could do a video on how you are breaking it. That would be great. Has I can't seem to break it. I also meant to ask for start at percent. drive on does nothing at wait point

**Comment by nyfarmboy07** [comment]
I've been having issues with the overloader mode.  The tractors will not always automatically assign to the combines in mode 3.  Mode 2 they appear to work correctly.  I have 2 9240 combines with dual wheel option and 45ft draper headers.  When the overloader is assigned to the grain cart, I believe in automatic mode both combines should share 1 grain cart driver correct?  2 things happen, either the grain cart tractor does nothing, or will unload 1 combine, stop and then remain at the waiting point while both combine grain tanks are full.  I have been selecting 1 cart to 1 combine in manual mode, and this works.  Mode 2 appears to work correctly, except once the tipper has found the combine with the highest fill level, after unloading, the tipper will wait until that combine is ready to unload again and ignore the second combine.

**Comment by pops64** [comment]
@nyfarmboy07 your issue related to #1802. This issue is about Mode 3 not stopping at the waitpoint for unloading.

**Comment by Satissis** [comment]
@nyfarmboy07 did you place the stop point inside the field ?
The overloader needs to be inside the field when it's set to automatic search or else it don't know what field it needs to search for combines at.

It could also just be that the field you are using is too big (Here I mean really American big fields) since we have seen that if the combine is too far away, it will not always find it.

**Comment by Raints** [comment]
@nyfarmboy07  Only problem I see here is maybe your overloader course not ending inside the field.
@Satissis  Have a map with 270 ha one field, using 5 combine's and 4 overloader's with no problem at all.

**Comment by nyfarmboy07** [comment]
It is possible that it could be too far away, but originally, it was GCV field #5 and the course started and ended in the south west corner.  I was using an Optimum with duals (vanilla) and which ever was the cheapest grain buggy.  It is possible the field is too large, but many mod maps have 40+ha  fields.

**Comment by wjohnson048** [comment]
I don't have the capabilities to do a good video, my start at is set at 80%, after playing with it for awhile I found the overloader will stop at the wait point(trailer) only if it is full to a certain amount, usually around 60%-70%, anything below that it won't stop which isn't a huge deal

**Comment by Raints** [comment]
@nyfarmboy07  As I mentioned, I'm using map with only one 270ha field in it. Have no problem with 5 combine's and 4 overloader's. One thing I cant understand is "too far away"? Is it ending inside the field boundarys or not?

**Comment by nyfarmboy07** [comment]
Yes, the course starts and ends inside the field boundry.  I updated the game to 1.4.4 and after turning pathfinding off, the overloader function appears to work as it should.  The issue I was having is that the grain cart would not detect the second combine automatically.

**Comment by krambc** [comment]
I've the same problem that wjohnson048 describes. I've tried with diferent overloader's, diferent trailers.....
Sometimes the overloader stops at the waiting point, other not. But never unload. I hadn't enogh time to check with diferent drive on %. I'll try tomorrow.

**Comment by nyfarmboy07** [comment]
Version 5.01.00090
After further work, I've found two issues with the overloader.  The overloader missing or "in traffic" to the stationary trailer is the first.  The overloader works fine on load #1 assuming that the tipper trailer capacity is larger than that of the overloader.  The overloader will return to the waypoint and unload until the tipper is full.  At this point the tipper will move on to it's course to unload.  (keep in mind, the combine, overloader, and tipper are all running via CP) The overloader will stay at the waypoint until the tipper returns or if the drive on setting is low enough, return to the combine.  If the overloader does NOT continue back to the combine and continue the course, the tipper will return and either the tipper or overloader, or both will "be in traffic"  I've tried various courses, and also had many issues with the overloader turning to line up to the combine pipe and getting the "in traffic" message.  It appears the 1660 can only be used with a few tippers in order for CP to work mostly due to the collision of the pipe to the taller tippers.  

Second issue is when the overloader is attempting to unload the combine during the headlands.  I usually run 3 headlands, and on the first headland the overloader always moves off the field, typically into a fence, tree, river, ect.  Pathfinding enabled or disabled does not appear to make any different.  Once the headlands are completed, I find that the overloader works perfectly if the combine is unloading on the previously harvested area.  When unloading on the not harvested crop, this is when I have issues with "overloader in traffic" message.

**Comment by pops64** [comment]
We need a video of the original issue of this post at the very least of your combi settings tab and the course running. As well has log with debug 15 and 21 running. As we need to be able to duplicate it in order to figure out what is wrong. 

@nyfarmboy07 your issues are not with mode3 not unloading to a tipper has this post originally started out has. If you have a separate issues please create a new post. Since your issues is with traffic collision and we need pictures with F5 active(this shows traffic collosion.) to debug theses issues as well has a log with debug channel 3 active.

**Comment by pops64** [comment]
@wjohnson048 So if you can tell me if this is true for you scenario . Your fill level is bellow your start at percent and it doesn't stop at the wait point?

**Comment by krambc** [comment]
@Raints have you any video of the 5 harvesters working the same field? Are forage harvesters? I've tried to harvest field 6 in chelington with 2 harvesters and 1 tipper and ive got several problems. Tipper driving over crops, tipper driving on a harvester before it arribes at the drive on%...

**Comment by nyfarmboy07** [comment]
I will record a video as soon as I can and start a new thread.

**Comment by Satissis** [comment]
Try again with v01.00095 or higher and report back.

**Comment by pops64** [comment]
Assumed Fixed. Closed due to inactivity.
