### ISSUE TITLE
shovel position?

### ISSUE THREAD

**Issue by andreasthu** [Courseplay/courseplay#1803]
Hello Guys
i have a question about the shovel mode or mode 9.
there are 4 shovel: positions
Loading, Transport, pre_Unload and Unload.
whn i start shoveling, for example, shoveling the BGA, i start at the startpoint with shovelposition (SP) "transport", on the first waiting point cp change the SP to "loading", when the shovel is full, the SP changed also to "tranport",
a littel bit (maybe 4 courespoint) before the unlaoding point cp chaged the SP to "pre_unload" and at the unlaoding point to the SP "unlaod".
and when the shovel is empty, the SP changed to "pre_unload" and stay there so long as the Teleloader reaches the first waiting-point and the the SP changed directly to "loading".
this is a long time when the shovel is high in the air.
i think in LS15, the shovel changed 4 or 5 coursepoints after the unloading-point from pre_unload to "transport"  and not when he reached the first stoppoint.

lg
andreas

**Comment by Satissis** [comment]
Hi @andreasthu 
This guide might shed some lights on it for you.
http://courseplay.github.io/courseplay/en/manual/index.html#driveMode9

**Comment by andreasthu** [comment]
Hi Satissis
well, i know this side, and cp works still correctly in shovel mode.
but, in LS15 the cp-teleloader change the shovelposition in the "#7 reverse away from the bunker" (pic from your link) from pre_unlaod to transport position and than he drive the "#8 return to start" in transport position.
now in LS17 the cp Teleloader drives "#7 reverse away from the bunker" and "#8 return to start" "#1 Startpoint" to "#2 waiting pointNr1" in pre_unlaod Position.
is there a chance to make that the cp driver change from pre_unload to transport-position in #7 reverse away from the bunker" ?
![cp](https://cloud.githubusercontent.com/assets/24860501/23276364/46c1c5c2-fa0a-11e6-92db-a5b9406985ed.jpg)

lg
andreas

**Comment by Satissis** [comment]
It should normally do that, but I think your issue is that your stop point is very shortly after the reversing part, so cp get confused and skip the lowering to transport mode.

The way it's ment to be done is:
align the loader in the direction of the bunker silo outside of the bunker. Then press start recording, move forward until the start of the bunker and place the first wait point.
Move to the end of the bunker silo and place the second wait point and change the direction to reverse.
Now reverse out of the bunker again and and continue to your forward point and change to forward.
Drive up to the unloading spot, set the last wait point, change to reverse and reverse away.
Then change to forward and then drive up and align up to the start point direction and press the stop button.

If you do that, it should work fine.
If it does not, then could you make an video of it? and then we will take it from there.

**Comment by andreasthu** [comment]
ok, thanks
i erased the first two coursepoints with notepad
and added at the end a few points
![cp2](https://cloud.githubusercontent.com/assets/24860501/23305417/fc8bfd48-fa9e-11e6-8bf5-5f5feb6478f3.jpg)
new numbering and ready,
now it works good

lg
andreas
ps can be closed

**Comment by Satissis** [comment]
Glad you got it to work :)
I'll close as requested ;)
