### ISSUE TITLE
Q: Language support - how does it work?

### ISSUE THREAD

**Issue by gammelgaard52** [Courseplay/courseplay#1804]
Hi,

I am looking in to the application and looking to learn more about Courseplay. Starting with some very basics - the language support. Does Courseplay use its own language and can be translated to any language you'd like to or is connected to the FS17 games languages?

Best Regards, Martin

**Comment by Satissis** [comment]
Hi Martin.
We can support all the languages as Giants have in FS17. Some of the languages have not been translated yet on our side, simply because no one have translated that language yet for us.

If you want to translate an missing language that Giants have in FS17 and we don't have it yet, then here is what you need to do.

Go into the translations folder of cp and take an copy of the translation_en.xml file.
rename it so the "en" is changed to your language code and place it inside the translation folder again.
Then open that file in a text editor like notepad++ and start changing all the englist test inside the text="" fields.
Once that's done, then test it ingame to see if it's showing as intended to.

Then goto the main page here on courseplay on github and make an fork of this repository. (This means that you will have an local copy on your account)
In that fork on your account, you should then upload that file into the translations folder.
Then you should have an option to make an pull request, and once you have done that, then we can see it and check it out before we merge your translation into our master code.

If we merge it in, then your translation will be in courseplay.

Hope this answered your question.

**Comment by gammelgaard52** [comment]
It sure does, thanks a lot.
