### ISSUE TITLE
turning problems

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#1816]
possibly same as #1812 
http://imgur.com/a/3KBIX
[log.txt](https://github.com/Courseplay/courseplay/files/800880/log.txt)

tractor drives in endless circles, affecting both the CAT challenger,a nd the Magnum. also ran into this in FS15, with the modded challenger... likely related to the implemnts turning radius being greater than the tractors...

**Comment by Satissis** [comment]
First of all. You have so many errors in your log that you need to clean up your mods.
Those call stack errors you see in the log, they are really bad to have and can crash you game very easily.

Also, you are running CP v01.0071 and the latest is v01.0087 so try again with that version after you have cleaned up your mods.

You need to have debug channel 12 and 14 activated when doing the turn and send me the log with those active, or else I cant see what it's doing.

Have you manually lowered the turning circle ?
That implement do have an big turn radius and is bigger than the tractors. It should never do that turn maneuver, since it's not build for it.

**Comment by Commissar0617** [comment]
manually setting the turn circle to 16m fixed my problems...

**Comment by Satissis** [comment]
Try again with v01.0089 or higher and report back.

I just remembered that I disabled some code that could have an effect on this, due to an bug giants introduced in patch 1.4 or 1.4.2 but is not fixed in 1.4.4

**Comment by remis1989** [comment]
new version of cp doesnt work for fs17 v1.4, content of cp is missing

**Comment by gec100** [comment]
you need to change <modDesc descVersion="37"> to <modDesc descVersion="34"> in modDesc.xml

small bug

**Comment by Raints** [comment]
@gec100  You really should stop giving false info. Everything is fine with descVersion

**Comment by gec100** [comment]
yes. purpose of my life is to give false info....

probably someone fixed it in the meantime.

**Comment by Satissis** [comment]
@remis1989 Update your game to patch 1.4.4

**Comment by remis1989** [comment]
ok, thx man for a hel, now my valtra work fine on auto 9m turning circle, bu i found alternative 3 - 5m turning circle and also work fine for me

**Comment by Satissis** [comment]
alright. I believe that means that I can close here again then :)

**Comment by Hubcap-1** [comment]
Important suggestion in finding a solution to backing up. I think the programming of this mod lacks a serious portion of consideration. There is an important " geometry" consideration when backing any vehicle. This is known technically as a " Bridge rule". The " Bridge" is the distance from the attacher pivot point to the center of the rear axle ( Or the middle point between a dual or triple rear axle). This measurement is key to figuring out the input required from the " control vehicle" ,( the tractor) , for a successful reverse maneuver. I believe the formula incorporated at this time is only worked out ( oversimplified) for short wheel base rear attachments like the Horsch pronto or something similar
