### ISSUE TITLE
Question about pathfinding

### ISSUE THREAD

**Issue by remis1989** [Courseplay/courseplay#1823]
pathfindig dont work
[log.txt](https://github.com/Courseplay/courseplay/files/805246/log.txt)
![fsscreen_2017_02_28_01_01_13](https://cloud.githubusercontent.com/assets/25843387/23384149/4161e6b6-fd52-11e6-85fb-096d155c3c50.png)
![fsscreen_2017_02_28_01_03_04](https://cloud.githubusercontent.com/assets/25843387/23384150/416a432e-fd52-11e6-8333-70690cf84794.png)

**Comment by Satissis** [comment]
http://courseplay.github.io/courseplay/en/manual/index.html#hud_generalSettings
Read the manual. It does work as intended to.

Or at least give more info that we can actually use to check if it don't work anymore, like following:
https://github.com/Courseplay/courseplay/wiki

**Comment by pops64** [comment]
Pathfinding only allows the tipper to be called for unloading when the pipe of the havester is not over the fruit side. It currently has nothing to do with avoiding driving over the fruit if it is going to or from the start or stop point of your courses. Which by your pictures looks to be the problem, if it is not. Debug channel 4 in your log instead of 12 and 14. Thanks

**Comment by pops64** [comment]
Can we close here?

**Comment by Satissis** [comment]
Closed due to inactivity
