### ISSUE TITLE
Operator glitches out of tractor.

### ISSUE THREAD

**Issue by nyfarmboy07** [Courseplay/courseplay#1826]
Has anyone seen anything like this?  I'm not sure if this is Giants or Courseplay.  There does not appear to be any loss of any functionally.  It usually happens on large fields and a course has been running for a long period of time. Has been happening since 5.01.00028

![fsscreen_2017_02_20_07_04_28](https://cloud.githubusercontent.com/assets/24856526/23340910/837e2a38-fc0c-11e6-8e9d-7c204f2d86db.png)
![fsscreen_2017_02_08_22_34_23](https://cloud.githubusercontent.com/assets/24856526/23340918/b0ff5a90-fc0c-11e6-9780-c6373686208a.png)
![fsscreen_2017_02_08_22_34_59](https://cloud.githubusercontent.com/assets/24856526/23340919/b24c8dfa-fc0c-11e6-9eb5-149e40ed14de.png)

 and all you have to do is stop the course and drive the course again and the operator resets back into the seat.

**Comment by pops64** [comment]
Do you have a log?

**Comment by Satissis** [comment]
I encountered this allot before we made the beta public (back last year) and fixed it at that point.
I haven't seen this since then, except from now.
I know some people that plays FS17 on big fields for over 8 hours each day and they have not encountered that either.

So without an full log I cant really say anything at this point

**Comment by lcc1211** [comment]
I was seeing it on larger fields, but haven't seen it since about 2 game patches ago.  Not sure if the update to CP or to the game fixed it.

**Comment by nyfarmboy07** [comment]
I am running the new 1.4 version of the game.  If you can specify a bug channel you would like to see, I can try to make a nice clean and sexy bug report for yall.  It does not happen  all of the time.  I have to say that most of the time it is on large mod map fields.  It has happened on field #5 of GCV for sure, but not always. I also had it happen on Sonovaka where I combined the 3 fields south of the main farm into one.

**Comment by Satissis** [comment]
There is not any debug channel for this issue, since we don't really know where to add print's in about it.
Which is also why we are really clueless on what is causing it.
I knew what the reason for it the first time was, since that we me not removing the original driver before placing an new on in there and that made some funky stuff, but that was fixed before the beta release.

**Comment by Satissis** [comment]
I spoke with TheSilentRandomGamerDK on twitch and he showed me it as well.
After some talk, I believe I know of a way to fix this.
I'm going to add an Timer that reset the character each 10 min, like when you stop and start CP.
Hopefully that will fix it. The timer might needs to be lower, but for now I'll set it to 10 min.

**Comment by Zoochase** [comment]
Crazy.  I stopped seeing that when the Beta came out too.

**Comment by nyfarmboy07** [comment]
I have more pictures!  I have the screen shots with the time left, so you can see the progress of the driver through the window and how long it takes.
![fsscreen_2017_03_04_19_50_41](https://cloud.githubusercontent.com/assets/24856526/23641915/6375de74-02c5-11e7-9ea8-173dbc212c62.png)
![fsscreen_2017_03_04_20_31_24](https://cloud.githubusercontent.com/assets/24856526/23641919/71015fe6-02c5-11e7-8b60-6ccc9319f0a6.png)

**Comment by pops64** [comment]
So it took 30 mins for this bug to occur? Going by the clock in the upper right

**Comment by Satissis** [comment]
pops. Giants vehicle don't do this. It's a know bug since FS15 and we have no idea what is causing it, which is why I'm going to reset the character each 10 min, when I get the time to do it.

**Comment by nyfarmboy07** [comment]
Yes.  Using GPS or hired worker does not seem to cause this.

**Comment by sesmo** [comment]
Hi,

This just happend to me...
![2017-03-09 1](https://cloud.githubusercontent.com/assets/25755540/23733436/c73e72d4-0470-11e7-8ac4-befbf55dc666.png)
![2017-03-09](https://cloud.githubusercontent.com/assets/25755540/23733435/c73be032-0470-11e7-856d-2a30fa309b5a.png)

Even with the tractor stoped and the job finished.

**Comment by sesmo** [comment]
By the way...

I'm made and testing a new map... The only mod I use now is " Hired worker consumes seeds an fuel"

RP

**Comment by pops64** [comment]
Got to admit it is pretty funny that CP thinks the hired help can drive from outside the vehicle :P . This is on our very long todo list to fix

**Comment by nyfarmboy07** [comment]
I will say, this is a VERY minor issue.  Simply stopping the driver resets everything.  Thank you for all the hard work from the CP team.

**Comment by MoslessNeo** [comment]
I had this problem in the 2015 version and I managed to solve only by "deactivating" the effect of turning the player's arm in the xml file of each vehicle.
What Satissis proposed is very relevant, since the player is reset periodically, the error tends not to occur.
I believe this happens due to an excess of routes.
I work in fields of 30 to 64 hectares and the error occurs a few minutes after the vehicles start working.
This does not take the brightness of the CP!
But it's a challenge to figure out how to fix it!

ps: The implementation of periodic reset has not yet been implemented, right?

**Comment by Satissis** [comment]
No not yet

**Comment by Satissis** [comment]
Try again with v01.00108 or higher and report back.

The reset timer have been set to run each 5 min, so if it needs to be shorter please tell.

**Comment by lcc1211** [comment]
I haven't noticed an issue with this for a very long time. I think this should be closed now.

**Comment by pops64** [comment]
Alright thanks closed
