### ISSUE TITLE
Hired Worker starts when trying save course with "H" in the name

### ISSUE THREAD

**Issue by Jaguar95** [Courseplay/courseplay#1829]
Long title, i know.

I just create a course with the Fendt Harvester (from ModHub) an then try to save it. In that moment, when i try to write an "H" (Shift+h) the harvester starts as hired worker. The Capello Diamant HS8 unfold and the harvester drives on. Only when hitting "Shift+h" to write "H", it's not happening when writing an "h".
Same with Valtra N Series and Lemken Titan 11 (only for testing).

It is the first time i had this problem, with previous versions of CP i don't have that problem. But i must say, i don't try it in every version. ;)
Currently using 5.01.00090.

**Comment by DynamicXYZ** [comment]
I also have this problem. It's been getting really annoying. I have to press both right and left mouse buttons at the same time so I can actually type something into the text box. It doesn't work like it used to where as you could just type away and press Enter.

**Comment by sootysax** [comment]
I have noticed this issue for quite a while now..  happens for me when I have a course with a 5 in it (Field 15), it will start the radio.

**Comment by Satissis** [comment]
Sorry for the late reply.
I have not had this issue my self, but that could simply just be because I haven't been using those keys while testing or just didn't notice the change when they occurred.

Not sure if it will get fixed before release since it's not an game breaking bug, but I'll it to the release milestone, but as an low priority

**Comment by pops64** [comment]
Closed #2909
