### ISSUE TITLE
Güllepack monteur1

### ISSUE THREAD

**Issue by Paul2510** [Courseplay/courseplay#1834]
Hello! I know that mods are not yet supported but many could you support the manure pack of the monteur1? LG

**Comment by pops64** [comment]
Clean Link to the mod in question. And what specifically is the problem that is occurring with the mod and CP interaction. https://github.com/Courseplay/courseplay/wiki

**Comment by Paul2510** [comment]
Good Morning!
The problem is that the slurry tank does not open, close and does not turn on!
The link is https://www.modhoster.de/mods/gullepack-fs17!

**Comment by dkfiremann** [comment]
Any pictures of what you are trying to do?

**Comment by Satissis** [comment]
@Paul2510 I had an quick look at the mod video from modhoster, so I haven't played with it yet.
But my question is: can you still fill and empty it without having to use the boom loader and pipes ?
If that's not the case, then it will be really difficult to implement, since we would have to make cp take control of it and calculate an path it needs to goto.

If it however still are able to use the default way that Giants do, then it's another matter, but we would still have to consider it and if it will be added, it would first be after the first release of cp.

We are trying to ignore any new feature suggestions until after the release or we would more or less never get to an release point.

**Comment by Paul2510** [comment]
Hi! Filling is like the original! Only when working on the field is the problem that he does not open the linkage or close and must lower the linkage so it activates!

**Comment by Satissis** [comment]
Alright. we will have an talk about it and test out the mod it self, to see if there is anything that makes red flags for us to not add it.
If everything is good, then it might first be after the release. we will see.

**Comment by Paul2510** [comment]
Many Thanks! Have a beautiful Sunday!

**Comment by pops64** [comment]
Closed. Collapsing all mods into one thread #2231
