### ISSUE TITLE
Q: Woodwork/forestry

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/courseplay#1848]
Question:
As CP is not having any woodwork/forestry possibilities: is it possible to add a method that f.i. the Ponsse Scorpionking (or others) automatically find a tree, stops, cuts and make logs of it?

Thanks. CP is awesome. ;)

**Comment by Satissis** [comment]
well off cause it possible, but would require allot of advanced AI coding to get it to work properly,
which none of us really know how to start out on as we are not computer engineers in real life and lua is mostly self tough for Thomas and me.

The idea is nice and I have thought of it my self as well, but just the amount of work that lies behind it, we do not really want to involve us in that atm, and we also have other projects than CP we want to do, but have been slacked off on because of CP.

I'll close here to clean up the issues :)

**Comment by AgroWillem** [comment]
Thanks Satissis.

No problem at all.
I highly appreciate the work at CP from you guys.

Greetz from the NL.
