### ISSUE TITLE
Highlight nearest and current way-point

### ISSUE THREAD

**Issue by brnl** [Courseplay/courseplay#1915]
One thing that really frustrates me is that it some times looks random what way-point the player will take. I, of course, know it is not, but often it is hard to see. It would thus really help if the current and nearest way-points would be highlighted.

That way, it will be never a surprise what way the tractor will (try to) drive.

**Comment by manierim** [comment]
And.. once the current waypoint is highlighted would be great to have the opportunity to change him to crosspoint, wait point, etc..  would allow for easier reuse of routes!

**Comment by pops64** [comment]
@brnl It would be a great idea but it would very resource intensive to do. So it wouldn't be possilbe

@manierim PromGames is developing a CP editor that will allow you to edit courses and last I heard it will be released when CP is released

Closed to keep the issues are clear

**Comment by brnl** [comment]
FYI, if [this](https://github.com/PromGames/CourseplayEditor) is the project you are referring to, the last commit was 4 years ago. There are some other editors, but the problem I found with these are you have to quit the game to apply/load the new courses.

**Comment by pops64** [comment]
With the way CP is setup it is only possible to edit courses once they have been created by editing the course xml file. So if you would like you can edit the course your loo0ingk to add a cross point, waitpoint etc by finding that specific waypoint in the xml find and adding those identifiers to it.  I will look again but some time ago there was a issue that discussed the current version of the CP editor

**Comment by pvajko** [comment]
> by editing the course xml file

That's a great way to do it and that's how my [course generator](https://github.com/pvajko/course-generator) works (until it probably will be integrated into Courseplay), what would really help though is reloading the saved courses from disk when hitting the open button. Currently the courses seem to be loaded from disk only when the savegame is started.

On the nearest waypoint topic, I'd be happy if 'nearest' would take into account the current heading of the vehicle so that a waypoint at 5 meters ahead would be nearer than one 2 meters behind me.

**Comment by brnl** [comment]
> ... what would really help though is reloading the saved courses from disk when hitting the open button. Currently the courses seem to be loaded from disk only when the savegame is started.
This is a very good point. Being able to reload in-game would be awesome.
