### ISSUE TITLE
Fillvolumen auf einmal veraendert

### ISSUE THREAD

**Issue by cabmac** [Courseplay/courseplay#1949]
Hi, mit den letzten Versionen gehen in die Ballen auf einmal 12000liter und  das 3-Fache Volumen  in die Haenger...muss an CP liegen, nehm ich CP raus, ist alles normal..

http://www.imagehub.de/display-i4546bdgp9o.html

Diese Version geht noch:

https://github.com/Courseplay/courseplay/commit/ed31d0f784928fdc44de131374e76f09dbaba2ae

**Comment by NikDaWi** [comment]
Das Gleiche tritt auf, wenn man den Abfahrer in Mode 10 mit Schiebeschild im Silo mit Ladung am Schild abschaltet.
Er schiebt über mit einer eigentlichen Kapazität von 8k bis zu 23k, entlässt man ihn wird die Ladung des Schildes gigantisch groß.

-

The same happens when using mode 10, the shield takes up to 23k, when it's originally just capable of taking 8k.
If you stop the driver whilst the shield ist overfilled the plane immediatly grows to a gigantic 23k sized pile.
Currently at work, maybe I can deliver screenshots or logs later, if requested.

**Comment by ThomasGaertner** [comment]
Hmm, sollte eigentlich nur in mode10 sein. Hast Du aus versehen den Traktor mit der Presse mal in BunkerSilo Modus  gestartet ? Ich werde da noch eine Sicherheit einbauen müssen. Das Volumen in mode10 zu Vergrößern ist notwendig um das Silo schöner schieben zu können...

**Comment by cabmac** [comment]
ne, das witzige ist, das beim Pressen  z. B. CP ja garnicht aktiviert ist

**Comment by ThomasGaertner** [comment]
try again with v 0112 or higher and report ...

**Comment by cabmac** [comment]
Hi, it seems to be ok now...tried it with same conditions...
