### ISSUE TITLE
Driving out of field boundary (fieldwork mode) 

### ISSUE THREAD

**Issue by jhomer** [Courseplay/courseplay#1988]
Maybe this has been discussed already or maybe it doesn't happen very often but there are a few instances here (one with red arrow is the worst instance) where in order to continue Cp drives out of field to get to next waypoint to continue. Not sure if it's workable to stay in field boundary or maybe I'm doing something wrong? I'm guessing these types of instances are rare but just thought to mention it.

Course is set to do one round of headland then continue up and down.

![snip](https://cloud.githubusercontent.com/assets/7943994/25114037/3425fa38-23c1-11e7-888a-c2824a2fd0d3.PNG)

**Comment by Blackmankot** [comment]
What a complex form of a unified field! No wonder-there are bad routes! Destroy this part and there will be no bad route! The crop losses are minimal.
![rout](https://cloud.githubusercontent.com/assets/26131714/25114644/a05ddb5a-2432-11e7-8d04-baf0e1cbb60e.PNG)

**Comment by pops64** [comment]
Yes this has been discussed and it is on our Todo list as part of improving headland generation but it won't happen until after CP is released. Closed to keep issues area clean

**Comment by mixmax1988** [comment]
While they are working on it, you can have a look to https://github.com/pvajko/course-generator

This coursegenerator might suits you, its perfect for that kind of fieldshape

**Comment by pvajko** [comment]
Thanks for recommending my course generator but the result in this specific case won't be perfect as this field can't be covered in one block when working in east-west direction. It may generate a course with two blocks which does not leave the field but may require a longer transition from one block to other. 

Generating course for fields with no convex solution (like this in east-west) is far from trivial.

What the course generator is really perfect for is non-rectangular convex fields because it can generate tracks at any angle and can start the headland at any location.

**Comment by jhomer** [comment]
Thanks for suggestions, mentioning the course generator and the link . I did not know it was available and I will have to check it out!! 

Also @pops64 I was thinking back in FS15 about the possibility of the overloader or a trailer emptying a combine being able to stay inside a field boundary when heading back to the unload route. For a similar instance like the one above for L and other odd shaped fields. Again, like this issue, it's not a make or break huge deal but just an enhancement.
