### ISSUE TITLE
Whats the best methode of saving Courses? 

### ISSUE THREAD

**Issue by Paleraider** [Courseplay/courseplay#2008]
wich one is the better way to save any course ingame ?
I prefrer the " Job-Methode " 

for each job on the map one folder , for better combine and more clarity.
Fertilize
Seed
Mowing
and so on....
with subfolders for the size of the fields.

**Comment by lcc1211** [comment]
For me, I create a folder for each field and save my courses there. The I name my courses for the job.  Sow-Fertilize & Refill - since I combine as many as possible.  Muck & Refill and so on.

**Comment by pops64** [comment]
Yea I would avoid saving field work courses and only save the courses that are hard to generate. Has you game loading time will decrease with the more courses have loaded. Though it is in plans for far in the future to look at improving the save system

**Comment by rkaerner** [comment]
I save all courses in cp for fs17. The course management seems to be way better than in earlier versions. Saving the course for harvesting crops which produce straw is fundamental for me because I use the same course for collecting the straw. Combining that course with a course for bring it "home" and the hands a free for all things cp can't do (like collecting eggs, selling pigs and so on). Like lcc1211 I create folders for every field and one folder for all the tasks not relate to any field. My courses' names contain all important things. For example "seeding Horsch 9 Meter" (I am german) because the Pronto 9 DC and the Meastro 12 SW are able to use the same course. 
In earlier versions of cp (for earlier versions of the game like fs15) I splitted any course in as much parts as possible if there was a chance to avoid repeatings (for example: every rig does its way  passing the fuel station on the farm, the bunker for crops, the bunker for straw and so on, so that has been one part of a whole course) but in the actual version of cp that is not neccessary any more I think.
But I am sure that every way to save courses (or not), every way of sorting it (or not) and every way of naming it ist the best for the one who does that job because everyone has its own way to do things.

**Comment by pops64** [comment]
Closing this out to clean up the issues area
