### ISSUE TITLE
Slurry worker unexpected stop. (Sosnovka/BGA2customfield)

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [Courseplay/courseplay#2019]
CP-Version: v5.01.00127

Hello, 

I'm having trouble with a "fertilize and seeding" course from the BGA to a custom field on Sosnovka (field combines standard fields 22, 24 and 27) using a Holmer Terra Variant. 
Course is working just fine, however there are a few points where the worker just stops without a message and stands there. 
I have to drive over that point manually and then start the course again...
Here is a video for further description:
https://youtu.be/LqC5mFpG-3Y
Here is the log:
[log.txt](https://github.com/Courseplay/courseplay/files/961137/log.txt)

I hope I didn't overlook something obvious...
greets

**Comment by pops64** [comment]
Start with upgrading your CP version to 131 or higher. There were some bugs in the runcounter in previous versions. If that doesn't work.s. There also might be somthing weired in the automatically generated fieldwork course. You could try redoing that part. Run with debug channel 12 17 21. 21 Requires a screen shot your viedo of where it stops since it prints its information to the screen. Also Since everything is giants. Could you send us your savegame and the CP Courses

**Comment by TheRealRolandDeschain** [comment]
Ok, I updated to 131 - still the same. I run it with the suggested debug channels. 
Here is the link to the screenshot:
http://steamcommunity.com/sharedfiles/filedetails/?id=914208930

Here you can find the courses and my savegame:
https://app.box.com/s/9z838v8zrtxmacymlwwp9n3nwr8ojujj

Here is the new log:
[log.txt](https://github.com/Courseplay/courseplay/files/962193/log.txt)

Hope this helps. 
thx a lot!

**Comment by pops64** [comment]
Yea this is a problem with the Holmer pack not yet reintegrated into CP

**Comment by TheRealRolandDeschain** [comment]
That seems to be it. The map has a small sink there, if i drive manually over it fast, the field isn't worked on.

**Comment by pops64** [comment]
Closing this out has this something we aren't going to fix atm the moment. We may look at this again after release.
