### ISSUE TITLE
field scanner

### ISSUE THREAD

**Issue by jensjcs** [Courseplay/courseplay#2022]
Hello,

i noticed, that after i was asked for automatically scan fields, that the scanned fields won't be saved. also if i scan a field manually it won't be saved.

so everytime i start a saved game i will be asked for automatic scan again.

i hope it can be fixed soon.

thanks and happy farming
jens

**Comment by pops64** [comment]
Not sure what you are talking about. You should only be asked the option to automatically scanned once unless your are deleting your CP settings file in your savegame. Also if you manual scan a field that must be manually saved as a field. https://github.com/Courseplay/courseplay/wiki

**Comment by jensjcs** [comment]
Not sure what i'm talking about. Hm, so i try to figure the problem.

i start a new game, at first i will be asked from courseplay for automatic scans, so i say yes. if i save the game after that and i go to main menu and load the just saved game, i will be asked again from courseplay for automatic scans. the field scans won't be saved also the same for manually scans if you say save it.

**Comment by PromGames** [comment]
Courseplay save the custom field borders information in a special xml cpcustomfields.xml in the savegame folder of the map. It has to be independent for each savegame, to allow define different custom  fields on savegame basis.

Courseplay can print in the log, a lot of information about field borders, and many other things if you setup debug to true in courseplay settings.

Courseplay save the courses by map in an independent folder. This means, all savegames with that map will use the same set of courses. (This is new in FS17)

When you create a custom field border, after saving, you have to see the cpcustomfields.xml in your savegame. Otherwise, something goes wrong.

Prom

**Comment by pops64** [comment]
Yea this sounds like your computer is preventing mods from creating their files. You should look at your savegame folder and see if there is couresplaysettings.xml file in there

**Comment by jensjcs** [comment]
hi again. i found out today which mod caused the problem with the coursplaysettings savefile. the mod ist "Swiss Bank". but i dont know why that mod wont work together with courseplay.

**Comment by PromGames** [comment]
I suppose it has to be with the saving process that maybe Swiss bank is interfering. If you are ok now, please close the issue.
