### ISSUE TITLE
Big Bud DLC

### ISSUE THREAD

**Issue by MrScsi** [Courseplay/courseplay#2052]
When using EITHER the Bednar or Seedhawk when CP is activated it lowers the seed boom. This doesn't happen in reg AI. I won't even begin to assume why... I will leave that up to experts

**Comment by pops64** [comment]
Try with version 135 or higher and report.

**Comment by MrScsi** [comment]
Solved with 136 THANK YOU

**Comment by pops64** [comment]
Plough Adjustment todo

**Comment by 37cee** [comment]
Big Bud DLC Feedback for version 138 
(all setting are the default recognition when calculating the course, turning on the field is enabled)

Both seeders (Hatzenbichler and Seedhawk) seem to work reasonably well, they turn fine at the end of the field, but dont seem to "care" about turning on the fiel. Although i cant see why such seeders should reverse on the fields.

The cutivaters are more troublesome when turning on the field is enabled. The Agrisem Cultiplow turns fine, but when the ai is reversing back to the field edge is cant keep the cultivator in a straight line.  Same goes for the Bendar Swifter and the Flexicoil ST820. Both the Swifter and ST820 were mentioned in your post above, but you might have missed the Agrisem Cultivator.

**Comment by pops64** [comment]
Yea the 2 seeders have reversing on the field disabled. I may disable the cultivators as well and definitely the plough

**Comment by 37cee** [comment]
Thats fine with me, i dont really use reversing with many towed implements. 

The only implement, that should be able to make the turn might be the Agrisem Cultiplow (the 8m Subsoiler). The large Cultivators dont really need it because one headland makes (nearly) enough room to turn on the field anyways. With the "small" version its more like 2-3 headlands.

**Comment by pops64** [comment]
It is a problem of can CP handle reversing. So if the tool is offset like the plough we just disable reversing completely. The seeders are an issue of to many pivot points. The Cultivator might not be reversing right because the turn node may not be calculate correctly which is something I am not sure how to adjust and would be something Satissis would have to look into. But the tools I mentioned raise before the field edge which is something I can adjust.

**Comment by pops64** [comment]
Try with version 140 or higher. Edge detection should be fixed for all tools mentioned. I have disabled reversing for all cultivators. I do not have the knowledge to fix them atm. @Satissis will have to look into it.

**Comment by MoslessNeo** [comment]
The new GRÉGOIRE-BESSON SPSL 9 are working perfectly. The CP detects the horizontal working distance automatically.
The ideal is to use 2-3 headland and at least 2 tractors.
When tractors are articulated the field symmetry must be activated.

**Comment by pull2play** [comment]
I'm seeing an issue with the Seed Hawk on field 5 in GCV. Running it behind a Quadtrac, with a double headland (it would get stuck on hills and obstacles with just a single headland) - when it gets to the very last pass, it gets stuck in a turn and just continues going on in circles.

**Comment by pops64** [comment]
Yea there is going to be nothing we can do about that. Unless you provide with more information. Cause it sounds like it failing to turn on the headland which doesn't have any turn maneuvers and goes from point to point.

**Comment by pull2play** [comment]
What additional info do you need?

**Comment by pops64** [comment]
What version are you using. I know in 140 I didn't update the turn radius for it so in 141 or higher or issues might be fixed. If you are running the latest version. Could we get a picture of where it is happening with the waypoints on. Cause I know with this tool turning up hill tractors will struggle and get pulled back down which causes issues

**Comment by pull2play** [comment]
I checked with 140 and 141, and it does look like you're right. When I set the course from the south east rather than from north west, the tractor completed the course without any issues. I guess it's going to be trial and error with this one and it won't work on every field, but I understand that's not something that can be easily fixed, if at all. Don't worry about it.

**Comment by pops64** [comment]
Can we close here. I have talked with @Satissis and the cultivators are going to be permanent can't reverse because of giants side things.

**Comment by pops64** [comment]
Closed. Has CP has been updated to the best compatibility with this DLC has it can.
