### ISSUE TITLE
The problem with this type of truck.

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2060]
Good afternoon! Is it possible to solve this problem?
[log.txt](https://github.com/Courseplay/courseplay/files/993798/log.txt)
![2017-05-12_00-23-01](https://cloud.githubusercontent.com/assets/26131714/25961179/f5c2faf4-36ab-11e7-9a72-ed6c266d43c5.jpg)
![2017-05-12_00-27-02](https://cloud.githubusercontent.com/assets/26131714/25961182/f9ab05ee-36ab-11e7-9214-2d712faf1813.jpg)
![2017-05-12_00-27-52](https://cloud.githubusercontent.com/assets/26131714/25961189/fea475a8-36ab-11e7-9254-d8ebb271610f.jpg)
Video.
https://youtu.be/TOHawdmFlo4

**Comment by gary-albano** [comment]
Just to note i have the same issue, Even if i use a non mod truck straight truck or combination

**Comment by ThomasGaertner** [comment]
please try again with v.0154 or higher and report....

**Comment by gary-albano** [comment]
is there a good test map you all use? 
I am mid starting up a new map and don't have an ideal field, so i tried a stock new map and have to buy a field and edit the money and all that setup just to test.

even if i buy all the fields and what not, I think a better test would be to have fields with control use cases IOW for this a wide open field as i keep hitting trees because i am rushing a setup :)

however it looks like its working as it should, If there is a good test map, I'll test some more

**Comment by pops64** [comment]
Test it with what ever you were able to produce the bug with in the first place. We don't care how just as long has you can't reproduce the bug.

**Comment by gary-albano** [comment]
ya, I don't recall what map and field I was on, ( 6 weeks ago ) and as I said above it looks like its working.

**Comment by pops64** [comment]
Ok. We will wait to see what the OP finds out. Thanks for the reply

**Comment by Blackmankot** [comment]
Checked with version .158. There is no error, this type of transport started working correctly. Thank you for your work!
The question closes.
![2017-07-04_00-32-58](https://user-images.githubusercontent.com/26131714/27801750-484f645e-6052-11e7-8a66-8762851a4fda.jpg)
![2017-07-04_00-40-19](https://user-images.githubusercontent.com/26131714/27801752-4d17f6f4-6052-11e7-9669-84304949c578.jpg)
![2017-07-04_00-40-10](https://user-images.githubusercontent.com/26131714/27801753-4ffe0aca-6052-11e7-890d-8f4bb2892ac8.jpg)
