### ISSUE TITLE
Suggestion: Enable Mode1 for URSUS T-127 (round bale auto loader)

### ISSUE THREAD

**Issue by Brzzl** [Courseplay/courseplay#2125]
Hi guys!
The ModContest brought as some new and (partially) amazing mods I have a suggestion:
to transport (and unload later) the round bales, which are created with the Goweil LT-Master (https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=79815), is it possible to enable mode1 for the stock round bale auto loader?
The driver can wait in front of the machine until the wagon is fully loaded and then drive to an unloading point/stable/biogas plant and so on, to unload the bales there.

**Comment by pops64** [comment]
Unfortunately, that would require a major redesign of mode1 in order for that to work. And I don't think it would work that well anyways. Because of traffic collisions. I would recommend using mode 5. And use wait points at where you want to pick it up at and drop it off at. And manually handle pick up and drop off. Closed to keep issues area clean
