### ISSUE TITLE
Mode 2 with pathfinding, tractors no longer evading each other

### ISSUE THREAD

**Issue by Brzzl** [Courseplay/courseplay#2200]
Hi guys!
Since the update on pathfinding (which works very well!) I've recognized an issue with the drivers:
while pathfinding wasn't working that good (must be pre 0173dev) the drivers were crossing the field and in case of collision they were evading each other.
I'm now using the 0173dev and with a chopper and a generated field course with headland in mode 6, the drivers are no longer evading each other and are driving on the fruits edge till they collide.
Is there any chance to get this fixed?

**Comment by pvajko** [comment]
Glad you like the pathfinding. The problem is that the existing collision avoidance is looking straight ahead of the tractor and not where the course leads. This is a problem on tight fields when going around the fruit in corners sometimes the tractor tries to avoid obstacles outside of the field and ends up somewhere in the woods...

I have something which solves that in mode 2 but not confident enough yet to push it to the master branch. Hopefully will have some more time next week.

**Comment by pvajko** [comment]
I have reasonably good solution for this now on the pvajko branch, if you are familiar with git you may try it.

I'll be traveling the next few days, so won't be merging this to master until probably Monday.
