### ISSUE TITLE
loadingscreen freezed

### ISSUE THREAD

**Issue by nafurim85** [Courseplay/courseplay#2205]
Hello I play on the North Frisian march and wenn I want to load the savegame with activ courseplay my game freezes  please help me.

here the link from the log: 
https://gist.github.com/nafurim85/3ddbf40bef49e5bb080ac3d0e61367d8

**Comment by pops64** [comment]
There is nothing wrong. My guess is that you save every course. After a while this will start slowing down your game. Either delete your course play course folder which will delete all your course. Or it wait for it to load then start deleteing easily reprodceable courses until your load Tim is manageable. If you manage to produce a log with an actual error I will reopen this otherwise closed
