### ISSUE TITLE
FS15 Question: Did the layout of "courseplay.xml" changed shortly?

### ISSUE THREAD

**Issue by DaEddie** [Courseplay/courseplay#2233]
Hi there,
in case that I am wrong here I apologize.

I use notepad++ to edit courseplay.xml rather than the app coursedrawer and for me this way worked pretty good since some days ago.
When I save a course now from within the game using courseplay UI the order of the attributes of courses and waypoints has changed.
Just have a look at the last four courses.
![image](https://user-images.githubusercontent.com/30975419/29248942-258b7d3e-8025-11e7-80f4-af3a1b0df4a8.png)
Or here, when I try to combine to course using copy/paste
![image](https://user-images.githubusercontent.com/30975419/29248982-ff9337ba-8025-11e7-8c5e-13dbd7a2477b.png)

So what happened? It is terrible to work in mixed up file...
Is there a way to adjust those order? Any help is highly appreciated.
Thanks for listening and kind regards.
DaEddie

**Comment by pops64** [comment]
First, FS15 is no longer supported. Second, I have no clue what your trying to do but beyond adding crossing or wait tags to the way points for courses I wouldn't recommend doing any changes to the course xml file. 3rdly I don't think cp particularity cares what order everything is in the xml just has long has there are no duplicates in the same line. You had to do something else to get this change because the way CP writes theses files is hard coded. The fact you have no way points in the last four courses probably made CP upset. Closed because 15 is no longer supported
