### ISSUE TITLE
Refill Course stopping when two fill types are needed

### ISSUE THREAD

**Issue by Willykeen** [Courseplay/courseplay#2262]
Hi! 
im having an issue.
i have a refill course for sowing from a certain field.
the problem i am having is the tractor will stop at fert trigger and refill but wont continue to the seed trigger. i am having to manually press "drive now" which is annoying especially when im busy doing something else.
the sowing machines that only use 1 fill type aswell as fert spreaders/sprayers work fine.

**Comment by pops64** [comment]
You have to make sure the fertilizer is being filled to above the refill % default 100. otherwise you'll get this issue. Are you using a modded fertilizer trigger?

**Comment by pizman** [comment]
Thats sounds like the Problem i posted some days ago. [https://github.com/Courseplay/courseplay/issues/2251](url)

The Problem is the fill level is a summary of Fertilizer and Seed,   for Example a Machine got 3000 Fertilizer and 2000 Seed .... If you define 100% then on Fertilizer Station it stops....     It can only fill 3000 Fertlizer what is 60% Fillrate....  But Cp Wants 100%. and wait forever !
If you Reduce Fill Rate to 60% it should drive automaticly after filling.... But then it not stop again on Seed Trigger cause he already reach the 60% (final Fillrate)  you define.

My solution that was recommend from pops64....
Load the Mod " ProSeed".   There you can disable the fertilizing Mode in the seeding machines.
Fill up the Fertilizer on first use....  It will not be used now.   so the machine is working like a "Seed Only" machine and can be filled with currently CP technics.

**Comment by pops64** [comment]
Your issue of it not loading to me sounded like a mod issue. This I have no clue because no answer has been given.

**Comment by Willykeen** [comment]
I found a solution.
If i refill seeds back along the course somewhere it will then continue on
and fill fertiliser.
But if the triggers are too close it wont refill.
