### ISSUE TITLE
With newest update (193) two problems. Mode 6 and Mode 9 

### ISSUE THREAD

**Issue by bigjoker76** [Courseplay/courseplay#2312]
Hello,
with the new update I got two problems:
Mode 6: Combine (sugarbeet) with unload course to unload on a heap: When starting the course it says "too many unload points". Yesterday with version 191 no problems, nothing else changed

Mode 9: Game freeze as soon as the shovel is full and trying to drive backward. Error in drive.lua

Sorry for this not so detailed description...unfortunately I don´t have too much time for do some logs...

Maybe one of you guys saw the same...

Regards Jochen

**Comment by pvajko** [comment]
'Too many upload points' fixed by @ThomasGaertner  in 194, I must have changed that accidentally in 193, sorry about that.

The other probably came in with 192, difficult to tell without the log, which you obviously looked up because you know it was an error in drive.lua, if you just pasted in that line than we would know a lot more...

**Comment by pops64** [comment]
https://github.com/Courseplay/courseplay/wiki Follow this always post a full log.

**Comment by bigjoker76** [comment]
Ok..the problem with Mode 9 is gone. Until now I was not able to test, if mode 6 is running ok now...

Thanks so far fro your help
