### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by SevenFifty1996** [Courseplay/courseplay#2330]
Loading time.
Has courseplay been tested by you on big cards? I do not know how exactly I should describe this. I have generated courses on a 4-fold map, where threshing machines, plows, collecting vehicles and cultivators have done their work. Then the load time, the game has grown to 10 minutes. Has it ever been tested?

**Comment by pops64** [comment]
No it hasn't but I know if you start saving courses you will impact your loading times the more you have. So you playing on a 4x map which means high way point courses. Which equals a lot of courses on the smaller maps so if you start saving the auto generated courses you will severely impact your loading times. A good rule of thumb is to always save what isn't easily duplicated(Manually generated routes) and just recreate the auto generated ones. CP does have the option to use the last used position instead of current position when generate a course so you don't have to worry if you quit in the middle of a fieldwork course. Closed has this nothing we can fix at the moment
