### ISSUE TITLE
Is "waiting for combine to turn" removed from CoursePlay?

### ISSUE THREAD

**Issue by blaz62746** [Courseplay/courseplay#2331]
Is this method removed? I think it was better with this because when I use mode 2 to harvest chaff, my tractor sometimes just goes wild. Before it was better when combine reached the end of the row and turned while tractor was waiting to combine tu finish his turn and then he went to combine.

**Comment by pops64** [comment]
Chaff harvester no longer follow that.  Regular Harvester Still do. If you have a bug please follow https://github.com/Courseplay/courseplay/wiki

**Comment by blaz62746** [comment]
Do you know which version was last with this feature enabled?

**Comment by pops64** [comment]
It was a long time ago. Was turned off with new tipper turn manuver

**Comment by pops64** [comment]
try again with version 199 it still doesn't wait for the combine to turn but I have improved the behavior

**Comment by blaz62746** [comment]
I tried it and I see the little difference. However, I'm using trailer that uses dolly and I think that is the my problem. When I see the tractor reversing, it is clear that the code is written for non-dolly trailers (I hope I'm not wrong, this is just my guess because I saw similar behaviour in fieldwork mode when turning and it looks awesome there). If I remember, before tractor waited outside of the field and waited for combine to turn and then he came next to combine from behind. Now he goes diagonally in front of him and then reverses next to him. This is where the problem occurs because of dolly and complexitiy of reversing that kind of trailer. I agree that this kind of turn for tractor is better and looks staggering but I think the old way was way more universal. Ormaybe imlementing some king of feature where users can choose what type of turning they want.

**Comment by pops64** [comment]
No. The dolly tool was never tested for compatibility. It the tool your using can't be reversed it will use the old way. We will update the code to include the dolly

**Comment by fudoido** [comment]
downloaded last version some days ago, it does show that option on my CP, however i am having an issue with it.
when doing chaf harvesting, tractor goes away to give space for combine to turn. however, since its a direct cut harvester (no deposit), it stops while doing the curve to the new lane, waiting for tractor to come nearby so it can start throwing chaff into trailer, but tractor will not go to harvester because its "waiting for combine to turn", getting it into a halt.
this is even more noticeable if i use the vehicle ai mod when doing a circular harvest, when combine makes a 90 degree turn for new row (instead of a tipical back turn as regular helper usually does).
this situation wouldnt happen on fs15 even when using the auto-tractor mod with same functions.
any way to get this sorted?

**Comment by pops64** [comment]
Closed due to inactivity, Believe this bug has been fixed.
