### ISSUE TITLE
Items gone. Text instead

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/courseplay#2365]
With update 5.0200007 the items in CP are gone and English Text is instead.
![cp-txt](https://user-images.githubusercontent.com/23076511/31573752-6f4f51ca-b0c2-11e7-9504-1fab6ae371e1.jpg)
It is on all screens.
When i go back V 5.0200002 everything is normal.

Is it something by me?

Grtz,

**Comment by ThomasGaertner** [comment]
which language ?

**Comment by evybart** [comment]
also in dutch i have to ga back to the version before and was ok back

**Comment by AgroWillem** [comment]
It was Dutch indeed.
With version 5.0200008, problem is solved.

Thanks!

Dutch greetings.

**Comment by evybart** [comment]
ik denk dat ik in het nederlands kan dit agrowillem kun je eens kijken er staat tekst over elkaar ik denk dat het nieuwe fucties zijn voor de ploegen over het veld te laten gaan

**Comment by pseikoNL** [comment]
@evybart, graag in Engels communiceren / please communicate in English.

As @AgroWillem already mentioned the problem is solved after he has update to newer version == problem solved. If you still have the same issue as AgroWillem please take a look at your CP version and update or reinstall to the latest dev version.
