### ISSUE TITLE
vehiclesort ?

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#2366]
Hello a question I use vehiclesort (vhs) when the trailer via cp unloads  and via vhs to the trailer go he stops with tippen and he drive's the route  further .
No cp no fs best mod in the world

**Comment by pops64** [comment]
What does vehicle sort do? And do you have a clean link to it.(Giatns Modhub, FS-UK, mod hoster etc.)

**Comment by evybart** [comment]
https://www.modhoster.com/mods/vehiclesort 
is a mod then must you not tabbing all vehicle commes direct on your screen and whit youre mouse can you pic one

**Comment by Maxcdr** [comment]
I have the same issue with VeGS mod (VehicleGroupsSwitcher) that I described here: https://www.fs-uk.com/forum/index.php?topic=187984.msg1291209#msg1291209

But I tested without Courseplay and the issue is still there. So I don't think the issue is due to Courspelay but to VeGS.

@evybart : Did you test without Coursplay?

**Comment by evybart** [comment]
no i have not tested without cp but  thanks for testing it and  solve the problem grtz

**Comment by Maxcdr** [comment]
> when you tab instead vhs then he dont stop whit tippen read i this correct ?

Correct.

**Comment by pops64** [comment]
Alright closed has this is something we can't fox then
