### ISSUE TITLE
Tractors don't lower shield in mode 10 "leveling/compacting"

### ISSUE THREAD

**Issue by Pointer-de** [Courseplay/courseplay#2384]
Hi.
Tractors don't lower shield in mode 10 "leveling/compacting" mode.
CP 5.02.00010
LS17 1.4.4.0 1.4.4RC8
original GCV-Map
mods: disableVehicleCameraCollision (Version: 1.0.0.0), FS17_cFliegl_ASW_271c_V2 (Version: 2.1.1), FS17_kroneBigXPack (Version: 1.0.0.1), Inspect17 (Version: 1.2), ZZZ_Courseplay (Version: 5.02.00010)

I've tryed to set the waypoints as a line manualy too, but no Change. The shield doesn't lower at all. Tryed several tractors, too.

[log.txt](https://pastebin.com/949wMMTJ)
[Link to my Video where everything can be seen](https://youtu.be/127IDKL7nVA)

**Comment by ThomasGaertner** [comment]
thats because, with hours of testing I figured out, the best way to level and compact for driving throught unloaders is simply going up and down throught the whole silo without using the blade. thats why I set it fix to "up" . for technical reasons, you still need the blade attached, otherwise I would need to rewrite the whole process...  Just read in the german forum concerning the side offset: it will be calculated for offset tools e.g. ploughs or potato harvesters while attaching, but it should be restet while detaching. If this is not working, I would ask you to open a new issue for this.

**Comment by Pointer-de** [comment]
Ah, ok. Thank you very much for the quick answer.
Because of the matter with the Offset I've to find out when it will set wrong. It comes sporadically. Mostly it's set correct, but sometimes there is a 0,8m offset. Not only when the blade is attached, also with the baler or something else where no offset should be set. I'll open a new issue if I could reproduce the error.

**Comment by ThomasGaertner** [comment]
elseif object.cp.isAmazoneCayron200 then
		automaticToolOffsetX = 0.8; -- ToolOffsetX is 0.8 meters to the right

       elseif object.cp.isLemkenTitan11 then
		automaticToolOffsetX = 0.8; -- ToolOffsetX is 0.8 meters to the right

**Comment by pops64** [comment]
Thomas. I know updateworktools is some times called be detachment of the tool. Rest is only called when stop function is called. I think in pivotal it is on my Todo list to improve this. Has for the original post which function in mode 10 are you using? Pic of mode 10 page would be great. Has I understand Thomas you only applied the up fix to drive through filling and not the other two options. If your talking the option that keeps the blade down 100 % did you fix that? Before your up fix it sometimes wouldn't lower all the way and be .25 m off the ground

**Comment by pops64** [comment]
inactivity
