### ISSUE TITLE
Ability to restrict CP to single savegame?

### ISSUE THREAD

**Issue by BenB78** [Courseplay/courseplay#2437]
So, I just had a moment of panic. I loaded the game and half of my CP courses were missing. It's taken the better part of 9 months to make them, and then they were gone. You see, my 8-year-old son plays FS17 too, and he had started a savegame on the same map as me. Then he found CP and experimented with it. Boom. All gone.

After I changed my pants, I did some digging and found that he hadn't deleted my courses; just moved them into other folders. With a few clicks, all is well again. For now.

My question is: Since CP is linked to the map instead of the savegame, is there any way that there could be an option to specify a particular CP folder should only open in one savegame, to allow multiple users to use the same computer? Like, say, a "Unique User" checkbox that will restrict CP to only that save game. Or do you have any ideas? Right now, I'm copying and pasting the correct Courses folder from a storage location each time one of us uses it, as a manual way of doing this. Not ideal, but it works.

If CP can't do this, do you know of a way to duplicate a game map with a different map ID, so that the game thinks it's two different maps (and therefore CP makes two different folders)?

And now I keep a secure, off-site backup too. :)

Thanks very much and keep up the good work.

**Comment by pops64** [comment]
I think with the way things changed from 15 to 17 having this sort of save system was our only option to keep things working. @Satissis would have a better answer for you.

**Comment by magicmana** [comment]
want a batch for windows   dos for do that ?  
can make it quickly

**Comment by magicmana** [comment]
script  is down :-)
sorry to the capture but have only  a french windows

- 1 download  this . txt and  put  in  a folder
[create.txt](https://github.com/Courseplay/courseplay/files/2257245/create.txt)




- 2 rename it  from .txt to .cmd
![5](https://user-images.githubusercontent.com/32802279/43641736-166d58fa-9725-11e8-85b2-6508d7b4581c.png)





-3 click on yes. when  you have a popup message
![6](https://user-images.githubusercontent.com/32802279/43641876-8dacf06a-9725-11e8-86be-e3a07467a4b0.png)




-4 normaly  the picture of the file is differrent now.
![7](https://user-images.githubusercontent.com/32802279/43641898-a261d2dc-9725-11e8-8e01-ea87b997937d.png)





- 5 double click on  the batch
![8](https://user-images.githubusercontent.com/32802279/43641948-d2f8fdb2-9725-11e8-8afc-6d7d69eb76b6.png)
 




-6 open  the parent  folder of  CousePlay_courses
![9](https://user-images.githubusercontent.com/32802279/43642187-d54e7b90-9726-11e8-8b93-e47bd07c12af.png)

and  drag and drop  the CousePlay_courses directly in the black windows and press enter
(that move nothing   just paste  the waypath to the folder)

![10](https://user-images.githubusercontent.com/32802279/43642027-34ff5ca4-9726-11e8-80e9-26ffcea126c2.png)


-7  create the folder  where  you want backup go
and paste  it with the same method when asked
you can use the folders where script are  ,  if you want,  just drag it in the black windows when asked

-8   if you want  start a backup each time you start FS17
drag the .exe of fs17  on the black windows  : 
for  find  it : 
make a  right click on the shortcut  of fs17  that you use : 
![12](https://user-images.githubusercontent.com/32802279/43642925-aad88c86-9729-11e8-9a0f-ec84485a4e90.png)
select " open the folder where  is this file" or something  like that



![13](https://user-images.githubusercontent.com/32802279/43643517-cd4bcf1a-972b-11e8-9a94-f7e5261a2ea5.png)


and  drag  the .exe  in the black  windows

9. after that  the black window ask to press sometime key and close.
now in the  folder  of  create cmd  you  have 6 new scripts 
![14](https://user-images.githubusercontent.com/32802279/43643584-0631429c-972c-11e8-9408-db6755641ab4.png)

10  double click on the save.cmd  for make a backup
![15](https://user-images.githubusercontent.com/32802279/43643694-6929b410-972c-11e8-8bc8-0f6aaecb28bc.png)

11 the save script create 5 folder name 1, 2, 3, 4 and  5
now  you have a backup on  the folder 1

![16](https://user-images.githubusercontent.com/32802279/43644353-ba26cacc-972e-11e8-98c9-40e6f520e16d.png)
![17](https://user-images.githubusercontent.com/32802279/43644355-bda18b88-972e-11e8-8a6d-6a0961958bcf.png)
![18](https://user-images.githubusercontent.com/32802279/43644360-c041a21a-972e-11e8-80e1-2098f1ae3f59.png)


now  each time you make a backup  
- previous  backup 5 is erased
- previous  backup 4 is moved to 5
- previous  backup 3 is moved to 4
- previous  backup 2 is moved to 3
- previous  backup 1 is moved to 2
-current backup go in folder 1

12  for restore a backup  : use the script  with the number of the save you want restore 



13  now  for save you can : 
-make a manual backup  with a double click  on save script

-create a scheduled task   for  start the save script each.. day.. week..mouth.. as you want 
[https://www.digitalcitizen.life/how-create-task-basic-task-wizard](url)

-use the start script (if you have drag and drop the .exe of fs17)
this script make a backup and when is down  he start fs17.


14  if you want save  all the FarmingSimulator2017 the create  script work too
just drag the FarmingSimulator2017 instead of CousePlay_courses
he backup savegame  , keybinding  ,etc ...
BUT  the save batch  need fs17  aren't started.
use with a scheduled task  not recommended
and the save take more time

**Comment by pops64** [comment]
Closed #2909
