### ISSUE TITLE
Suggestion:  Ploughing and Refueling

### ISSUE THREAD

**Issue by lcc1211** [Courseplay/courseplay#2442]
If this can be done already, please tell me how, but playing on these large maps with very large fields such as field 13 on Hobbs Farm, my New Holland T8 ran out of fuel.  I would like to be able to generate a course like with a sower where it can go to the seeds/fertilizer and refill once empty except in this case, when the tractor is down below the 20% threshold.

**Comment by Blackmankot** [comment]
Do you need seeding and fertilizing? Or fuel?

**Comment by lcc1211** [comment]
Strictly needing to fuel a tractor that is either cultivating or ploughing.  I always combing a run by the refuel point when I refill the sower, so that isn't an issue for me.  I just thought it would be nice to be able to do the same in other situations.

**Comment by pops64** [comment]
The only thing I could think of that might work is adding a refuel course to the end of the fieldwork and when you get low on fuel hit the drive now button. This may or may not work has this function is not intend for this. Per you suggestion I don't think we will be able to to implement because not all unloading/loading courses drive past a fuel trigger and it would just become a mess to implement this. I will close this for now and discuss with the rest of the team and we may reopeon this if the team thinks of a better way to implement this.
