### ISSUE TITLE
Sowing and Slurry Mode + Refill Course: Speeds

### ISSUE THREAD

**Issue by frm274** [Courseplay/courseplay#2476]
Hi.
Im using a Field Course merged with an refill Course at Field Border in Sowing Mode. 
if the Worktool is empty, tractor is heading back to refill with "TURN-SPEED".
Driving back with filled Tool to last field waypoint tractor uses "ONFIELD-SPEED".
Could you set both maneuvers to "ONFIELD SPEED", because turnspeed is set generally quite low.

And, please dont forget to get the tools of the "Horsch-Addon" into "specialTools.lua" ;)

**Comment by pops64** [comment]
Enroute to the first waypoint. It should be using field speed. Entroute to where it left off after reaching last waypoint should also be using field speed. There is a bug on our list to fix that if the big bag you are filling from empties before the sower is refilled it will cause it to stay stuck in turn speed. This can be fixed by starting and stoping CP

**Comment by frm274** [comment]
<a href="https://www.pic-upload.de/view-34445428/refill.jpg.html"><img src="https://www2.pic-upload.de/thumb/34445428/refill.jpg" title="Bild hochladen" /></a>

**Comment by pops64** [comment]
I'm going to see if @pvajko knows what is going on. Many with the new algent course it starts in turn speed. I'm not to sure what he is doing. Also is your refill course on the field?

**Comment by pops64** [comment]
Closed due to inactivity.
