### ISSUE TITLE
Mode 8 liquid transport and Fabrikscript

### ISSUE THREAD

**Issue by Fendt105** [Courseplay/courseplay#2497]
I've looked at a lot of comments both here and at Fabrikscript support forums about this problem. Courseplay somehow doesn't recognize the triggers using Fabrikscript.

I'm currently playing Mavericks Farm, wich is using the Fabrikscript a lot. Because of the size of the map you just can't play without Courseplay either ;)

Looking in Giants editor I can see that different types of triggers are used for the refill of water to the different factories. The Paperfactory for instance uses a waterrefilltrigger that you need to activate with r. The water at the Multigreenhouse is filled using a tiptrigger you can ingame activate using the standard unload key, i. When i set up a refill course for either one of them they refuse to unload. At the Paperfactory it waits at the waitingpoint forever, at the multigreenhouse it just drives on. When i set up a course refilling the cows watertrough it works perfectly.

Is there any way to bypass this problem?

If it is helpfull i can provide you with testcourses or debugchannels, just let me know what you guys need.

using CPversion 2.00038
Vanilla truck MAN
Kotte universla pack trailer
Mavericks Farm 1.06

And last but not least, thanks for creating this mod, wouldn't play FS17 without it.

**Comment by pops64** [comment]
No. For now using mode 5 should stop at waitpoint but would involve manual unloading and loading. The problem is mode 8 is static and every fill type needs to be handled on a case by case bases. The problem with the tip trigger is if remeber correctly is it set to overload in a tip triggers that accepts water. Which is different from unloading into water trigger. See #2331 this is apart of the milk trigger issue. Closed for now
