### ISSUE TITLE
Cannot calculate field edge path

### ISSUE THREAD

**Issue by SunkenL** [Courseplay/courseplay#2511]
Have tried two different fields that i have created(plowed together) and the game just freezes. 
Any help?
[log.txt](https://github.com/Courseplay/courseplay/files/1583254/log.txt)

**Comment by pops64** [comment]
I'd start by cleaning up your log file, you appear to have a few bad mods in your game this probably won't affect it. I am assume you are making one very very large field.(Combing 2 large fields on a x16 map?) I would have to say then it is just the size of the field, your game is freezing because the shear calculation required for such a large field. If let it sit for a while it should come out of it and make sure you save the field definition and turn off auto scanning. You can do this by opening the courseplaySettings file found inside your savegame folder and adjusting the settings there. If this still does work increase the scanStep has this will reduce the calculation but you need to insure the next closest field is farther away then this step size.(So it doesn't accidentally include that field)

**Comment by SunkenL** [comment]
Actually the field is half a 16x map. Just wanted to try the limit! To bad courseplay limits the number of workers to 8 on a course. I wanted more for this. I will try this

**Comment by pops64** [comment]
Yea that is the problem right there. CP by defaults scans every 5ms for field boundaries. Your going to have to increase step size regardless because this is another internal limit of 1000 * the stepSize(i believe) once it has scanned that much it just stops. Close this is out has this is something we can't fix.
