### ISSUE TITLE
CP ignores manual settings of DC

### ISSUE THREAD

**Issue by ceemosp** [Courseplay/courseplay#2537]
When setting the Drive control to 4WD + locks on field (all diff-locks on) manually, courseplay ignores those and only activates 4WD instead.  This happens in mode 3 and can be repeated ad-infinitum.
![cp-dc_issue](https://user-images.githubusercontent.com/5932768/34639863-54b8c20c-f2e8-11e7-8227-bb6e32a871cb.jpg)

**Comment by pops64** [comment]
Turn off all mods besides CP and drive control and report back

**Comment by pops64** [comment]
Also with the way I did this, mode3 isn't currently on the field because it is heading towards waypoint 8. I set up it so with your at the last or first way point it is assumed you are on the field. This isn't something I am going to fix.

**Comment by ceemosp** [comment]
Very unsatisfying solution. It does create plenty of issues - especially when using terrain/traction modifying add-ons (Seasons, Ground response etc), where there are plenty of situations the diff-locks would be needed. I can't see the reasoning behind the changes from previous versions where the locks were available in mode. Be it as it may - as you are not willing to change it I will have to deal with the status quo.

**Comment by pops64** [comment]
Well. my solution works for most cases or use to.  I don't see why CP is jumping to waypoint 8.  The only case my solution won't work for is if you're starting from nearest waypoint. Otherwise CP should always be set at last or first waypoint when unloading a tipper or proceeding to the unload route which is the only time mode 3 is on the field.
