### ISSUE TITLE
Automatic Course Generation

### ISSUE THREAD

**Issue by frm274** [Courseplay/courseplay#2542]
Ive generated two Courses on the same field in automatic mode, starting in the same field corner.
First 4m workwidth, 2nd 26m workwidth. 
Why is the 4m course alingned to one of the field borders (looks realistic), and the 2nd to the longest distance found in the field (looks totaly unrealistic)?
And, would it be possible, to generate the course automatically, but alinge it to nearest field border from vehicle position?
<a href="https://www.pic-upload.de/view-34624282/autocoursegen.jpg.html"><img src="https://www2.pic-upload.de/thumb/34624282/autocoursegen.jpg" title="Bild hochladen" /></a>
  
Edit: Since the laste update, "island avoidance" is only chooseable in automatic genearion mod, not in manual mode

**Comment by pvajko** [comment]
In automatic mode the course generator tries to find the course with the fewest turns, checking every angle between 0-180 in 2 degree steps. What makes this case complicated is those two little protrusions on the northern end of the field. A course aligned with the longest edge of the field (approximately NW-SE) with 4m work width would result in a non-convex solution, meaning you would have two little areas in those bulges which you wouldn't be able to cover with one up/down row, you'd have to work on the top one first for example and then move on to the bottom one.
That can get really complex so the course generator prefers the convex solutions where the entire field can be covered in one single block. That's why it picked the NE-SW direction.

On the screenshot on the right side, with 26m work width, the headland is wide enough to cover those bulges so the NW-SE direction becomes a convex solution with the least amount of turns.

Aligning with the field border nearest to the vehicle position may result in a non-convex solution and therefore is at the moment not enabled (although the course generator could handle it, see more on this topic [here](https://github.com/pvajko/course-generator/issues/12).

**Comment by pvajko** [comment]
As to the island avoidance, it is a feature of the automatic mode, it has never been available in manual mode (in case you mean choosing N-W-S-E directions as 'manual' mode)

**Comment by frm274** [comment]
Mh okay, thanks so far.
I also had a little look in your scripts and halfway understood  how you calculate the best direction for the tracks. I think its not really perfect yet, because i dont want to drive diagonal trough the field just because i need a few turns less. And i dont have this issue just on this field and also with smaller workwidth.
I tried to set the tractor direction = bestAngle, but i failed to import the direction which i calculted in your cp.lua into the center.lua. 
Not enough skills, our maybe an asolute wrong approach.

**Comment by pvajko** [comment]
It's on my [todo list](https://github.com/pvajko/course-generator/projects/1) to allow setting the direction manually.

**Comment by frm274** [comment]
nice to hear!
