### ISSUE TITLE
Grass loader stops when full instead of unloading when picking up grass windrows

### ISSUE THREAD

**Issue by Rockfarmer75** [Courseplay/courseplay#2543]
Hello, 
This is my first time submitting a bug, so please let me know how I can best help you.

- I cut a grass field (either a 'real' field or just free grass).
- I collect the grass in windrows with a rake and record the course as i go along (field work mode).
- I record a separate path (field work mode) from the grass collecting area to a placeable silo (mod), that accepts grass and then back to the field. I save this path.
- I then load a tractor with the rake path, and then append the unloading path, still field work mode. 
 - I send the tractor along the course with a grass loading trailer. It picks up the grass. Once the trailer is full, the tractor stops with "work tool needs to be unloaded". 

I expected it to drive along the unloading course, similar to fertilizer refills, combine/overloading courses. I am using the latest version of courseplay from this GitHub.

regards.

**Comment by pops64** [comment]
step 2 is probably the problem. You either need to auto generate the course. Use the same workwidth has your windrower(If it drops in the center. A little more advance if it doesn't but still doable). Or if you can't auto generate. The other method is to make sure that the first and last waypoint of the field work portion of the course must be a waitpoint. Otherwise CP doesn't know what portion of your course is fieldwork and what is just transport. I would honestly always use CP to generate courses for your field work. Has this saves time and ensures nothing weired goes one(eg. Missing a turn maneuver waypoint). For grass atm I would recommend using the old course generator for mowing(Or the very least the windrower and collection) has the new one isn't repeatable in some cases(Which is needed to ensure the forage wagon/baler picks up 99% of it)

**Comment by Rockfarmer75** [comment]
Thank you. Defining a field and autogenerating a course worked. 

I also tested a manual path where I use the waitpoint at the beginning and the end, and then append the unload course -  which also works :) Thanks for the clarification.

Is there a way to define an island in a field you are defining yourself at the moment?

**Comment by pops64** [comment]
No your going to have to use the new course generator to go around islands.
