### ISSUE TITLE
Turn on field and mods

### ISSUE THREAD

**Issue by And-V** [Courseplay/courseplay#2594]
Recently I ran into a problem in my mod. When the internal turn is executed, the seeder moves to the side and the tractor travels in a circle. I would like to know if this can be corrected through the seeder's xml. Screens and mod link included
ModLink - http://sharemods.com/sppuyoxrd34v/FS17_EqPack.zip.html

![fsscreen_2018_02_20_20_06_23](https://user-images.githubusercontent.com/28305463/36438211-46cef584-167a-11e8-9f45-74a868d4aca2.png)
![fsscreen_2018_02_20_20_06_27](https://user-images.githubusercontent.com/28305463/36438208-4692c87a-167a-11e8-849f-eb6673c98c1e.png)
![fsscreen_2018_02_20_20_06_34](https://user-images.githubusercontent.com/28305463/36438210-46af4fe0-167a-11e8-92ec-c1fc93b1aea5.png)

**Comment by pops64** [comment]
This is something corrected in special tools lua file of CP. CP thinks this tool can be used in three point turn. It has to be told that when using this tool that the wheels of the tool remain on the ground so not to do a three point turn. It may also have to be told not to reverse with this tool as well. In the known mod issue thread I think I have provided theses instructions for a different mod. They should work here you just have to use this mods xml name instead of the one in the instructions

**Comment by And-V** [comment]
Thanks.
How do I understand this problem can not be solved without interfering with the CP scripts?

**Comment by pops64** [comment]
Your really not interfereing with our script. Some of the special tools lua is designed to add mod and dlc complatibity without making any changes to the how CP works. The variables placed in there are designed to tell CP that there is a special case we have desgin a work around for and to use the work around instead of normal operation. I'll post the 2 lines of code and where you need to add them a little later

**Comment by And-V** [comment]
Thanks!
The xml names is  SZT_54.xml and SZT_54E.xml. 
PS: They have the same model, but different textures.

Do you include these lines of code in any further updates to the CP?

**Comment by pops64** [comment]
Add this after line 196 in special tools.lua
```
elseif workTool.cp.xmlFileName == 'SZT_54.xml' or workTool.cp.xmlFile == 'SZT_54E.xml' then
		workTool.cp.implementWheelAlwaysOnGround = true;
```

We probably wont add this into the main branch unless it starts becoming popular. Has this was the intent of specialtools.lua to handle mods and dlc and standard equipment that doesn't follow normal operations. If turn on field doesn't work then add
`workTool.cp.notToBeReversed = true;`

**Comment by pops64** [comment]
inactivity
