### ISSUE TITLE
Seeding & Cultivation in one pass doesn't work

### ISSUE THREAD

**Issue by dicktimmerman** [Courseplay/courseplay#2604]
Hi,

I love to use the Lemken K600 Rotary Harrow with the Lemken Monosem Seeder. With the standard helper the harrow and the seeder are started correctly but with CP in seeding mode will not start the harrow and the other way around CP in Field work mode will not start the seeder. Also the lowering and raising of the implements will not work correctly.

**Comment by TinyCrocodile** [comment]
Is this a setup like in the Kuhn dlc hr4004 and  btf 4000 in combination? If you have the Kuhn dlc does it work there?

**Comment by pops64** [comment]
The problem here is that CP stores in memory if a tool can be used in the mode your currently using.  Only the tools that have been stored can be accessed easily. Which is how things are turned on and off because the access is already setup for the tools belonging to that mode. I'm going to postpone this because it will involve a quite of bit of doing and we're very busy atm with RL

**Comment by pops64** [comment]
added to the list
