### ISSUE TITLE
Combine and tractor stuck at the end of a row trying to fill.

### ISSUE THREAD

**Issue by GoodolOzzy** [Courseplay/courseplay#2608]
This happens while you're doing paid work on a field and your combine and tractor are working on one of your own fields.
When the combine is at the end of a row filling a trailer,  the animation of the grain dispensing is visible but the combine isn't emptying and trailer isn't filling. 
To get things moving on you need to exit the field you're working on or tab into either the combine or tractor.

**Comment by pops64** [comment]
Using CP while on field missions is not supported by Giants or us. This is something we won't fix

**Comment by GoodolOzzy** [comment]
That was scanty response. I didn't expect support from Giants since CP is a mod. What exactly warrants an issue; so as I won't be wasting time posting anything else that won't be investigated?

**Comment by pops64** [comment]
Anything that is a bug or suggestion for improvement. That isn't already been listed. Expansion on my answer. This isn't supported by Giants because without CP you couldn't preform work on other fields during a field missions even with the standard helper. CP let's you cheat this system which why we don't support it plus there are bugs like you listed here that are probably a result of cretetian Giants functions we rely on that don't work. Can't say for sure because we haven't put any effort into for the simple fact that CP let's you cheat when doing field missions
