### ISSUE TITLE
Starting Corner doesn't align with actual course(New)

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2635]
When using the starting corner feature the course that is generate doesn't align with the corner selected
![farming simulator 17 3_11_2018 09_13_55](https://user-images.githubusercontent.com/10678220/37253849-b35ee988-250d-11e8-9b53-eb3c02a72ae9.png)
![farming simulator 17 3_11_2018 09_18_58](https://user-images.githubusercontent.com/10678220/37253850-b54e08aa-250d-11e8-98b5-91427ee9ce1d.png)

**Comment by ThomasGaertner** [comment]
please do me favor and toggle your setting for "headland before or after" in head lands settings. I could see that it will be considered even if there is not headland set in this moment.

**Comment by pops64** [comment]
Didn't try that but I did toggle the number of headlands. Look into it later

**Comment by Blackmankot** [comment]
Now if you set the starting angle without a turning strip, then the angle on the field is the same as the given one.
![2018-03-24_14-42-53](https://user-images.githubusercontent.com/26131714/37875773-3c933272-3076-11e8-9d48-ace85fe5d7e9.jpg)

And if you specify a turning strip, then the angle does not match the given one.
![2018-03-24_14-43-51](https://user-images.githubusercontent.com/26131714/37875792-7ea91a0a-3076-11e8-9844-a6136bfb28f2.jpg)

**Comment by pvajko** [comment]
This is a cosmetic issue only, the second pic is completely ok as the settings say that the finish location should be at south west which it is. as you start with the up/down rows and end with the headland.

In the first pic the finish location label should have changed to start location when there's no headland.

**Comment by Blackmankot** [comment]
@pvajko Good afternoon. Is this possible to fix?

**Comment by pvajko** [comment]
@Blackmankot good morning. My understanding was that this is a cosmetic problem only and you can still generate any course you want. If that's not the case, let me know (with a detailed description, as my Russian is not as good as it was 30 years ago:) what exactly the issue is.

I'm working on a new course generator settings GUI similar to the built in ones. It'll definitely be fixed in that but I haven't decided yet if I then remove those settings from the HUD.

**Comment by Blackmankot** [comment]
@pvajko Did you ever speak Russian? My respect to you :)) Alas, unfortunately I do not know English very well, that's why I use Google translator. And he does not always translate correctly ... If I write in Russian, can you understand me?

Yes, with the given settings, the course can be created with the processing of the field! And you are right, this is not a critical error, when the genius, the starting angle does not coincide with a given angle! From myself I will add that I really like the new algorithm for generating work on the field! Thank you very much!
