### ISSUE TITLE
Courseplay 5 Not Updating

### ISSUE THREAD

**Issue by WolfWarrior619** [Courseplay/courseplay#2644]
I'm running Courseplay 5.0.0 on FS 2017 with a Mac OSX 10.11.6. 
First I tried the standard version and now I am running the developer version.
In my mods menu in FS2017 it shows Courseplay is wanting to update to 5.2.0. When I click update it says pending, then loads some files, but then it defaults back to update. I cannot get it to update to 5.2.0.

I'm not aware of what features are in the new update but currently I dont have combine convoy or any other new features I see on YouTube tutorials.

Any help is greatly appreciated.

The map I am using is Beaver Creek by Stevie.

**Comment by pops64** [comment]
The update show in game is for the release version. Which for the time being is 5.2.0 The Dev version is 5.2.60 or something like that atm. Just ingore the update offered by Giants. They only have 5.2 and since it's hash doesn't match the dev version it thinks it is a update. You have to manually update the dev version until we release 5.3 to Giants for approval. Which won't be a while

**Comment by WolfWarrior619** [comment]
If that is the case, then how do I get options like combine convoy?

**Comment by pops64** [comment]
Only on dev version off GitHub. http://courseplay.github.io/courseplay/en/installation/index.html

**Comment by WolfWarrior619** [comment]
Thank you. I had some remnant files from an earlier version and doing a
fresh install now.
