### ISSUE TITLE
Not the correct maneuvers of two combines.

### ISSUE THREAD

**Issue by Blackmankot** [Courseplay/courseplay#2666]
Good afternoon. This is the strange behavior of the combine harvester when turning, if two combines are working on the field, it is not symmetrical and not in tandem.
Video - https://yadi.sk/i/NM6iVg6Y3Tyoha

**Comment by o0Kyoshou0o** [comment]
hi,
i have the same problem in symmetrical and tandem (cf the following picture).
i try multiple combine mods (FS17_Claas_Lexion_700_Stage_IV_MW_Edition and John Deere S690i Pack) to search a solution in xml file because it would seem that all is clear with another combine particular mod.

![20180406222303_1](https://user-images.githubusercontent.com/30392058/38443532-4b4c8000-39ec-11e8-9087-70ce2cf97b35.jpg)
![20180406201100_1](https://user-images.githubusercontent.com/30392058/38443546-59f7be44-39ec-11e8-920d-f578a1d99094.jpg)
![20180406201101_1](https://user-images.githubusercontent.com/30392058/38443550-5b43f3ee-39ec-11e8-9b7a-32878f7c410d.jpg)
![20180406201103_1](https://user-images.githubusercontent.com/30392058/38443554-5d80f346-39ec-11e8-948b-750c5d9d05da.jpg)
![20180406201106_1](https://user-images.githubusercontent.com/30392058/38443555-5e80840a-39ec-11e8-949a-80e090ebf4b0.jpg)
![20180406200427_1](https://user-images.githubusercontent.com/30392058/38443560-60ab25aa-39ec-11e8-9471-a495c92b5df3.jpg)

**Comment by o0Kyoshou0o** [comment]
hi,
after several test, i' ve observed that problem could come of crawler gestion ( because lexion with classic wheel works). therefore, i put in xml lexion the wheel of newHollandCR1090.xml. but i have the same problem.
i 've observed too an acceleration in the field way out before turn whereas with the new holland, CP stop some seconds and go
Someone have an idea?

**Comment by o0Kyoshou0o** [comment]
hi,
after i3ds and xml comparison with a not relevant gap. i m turn to CP  code but i am not a specialist.
i see that CP does crawler gestion
`		elseif spec == Crawler 			   then workTool.cp.hasSpecializationCrawler			 = true;`

Can that comes from it?

**Comment by Blackmankot** [comment]
Hey. I'm not very good at code. Therefore, I have no idea ...

**Comment by o0Kyoshou0o** [comment]
are you sure that is mod issue ThomasGaetner ?
because i 've tested a lot of parameters, modified i3ds xml and  compared to CR1090. But i don't see where the problem can be come.

**Comment by Blackmankot** [comment]
@ThomasGaertner Hey. I also think that this nuance is not a mod problem. I used the default combine CP 10-90.

**Comment by ThomasGaertner** [comment]
test v79 or higher and report....

**Comment by o0Kyoshou0o** [comment]
Nice work Thomas! ;-), it's work apparently. what is the CP code which was modified for the correction?

I 'll test with several situations and i'll confirm you the closing issue tomorrow

**Comment by o0Kyoshou0o** [comment]
hi,
after different test, i think that all is good
