### ISSUE TITLE
Courseplay did not work after Update to 5.02.73

### ISSUE THREAD

**Issue by Chris-KB** [Courseplay/courseplay#2677]
I had a big problem since i have updated my Courseplay to Version 5.02.73

It crashes during the load of any Map.

> Error: Running LUA method 'loadMapFinished'.
C:/Users/Jack/Documents/My Games/FarmingSimulator2017/mods/zzz_courseplay/hud.lua:96: table index is nil
[log.txt](https://github.com/Courseplay/courseplay/files/1896620/log.txt)

**Comment by pvajko** [comment]
Actually, the real problem is this:
Error: C:/Users/Jack/Documents/My Games/FarmingSimulator2017/mods/zzz_courseplay/courseplay.lua:109: 	COURSEPLAY ERROR: could not load file C:/Users/Jack/Documents/My Games/FarmingSimulator2017/mods/zzz_courseplay/course-generator/CourseGeneratorScreen.lua

Could you please double check if that file is there and you updated your mod directory correctly? I changed it from lower case C to upper case recently, don't know how exactly you are updating but it may have skipped this file?
