### ISSUE TITLE
turn on field option 

### ISSUE THREAD

**Issue by evybart** [Courseplay/courseplay#2716]
when i choose for turn on field cp does the opposite and vice versa and this is in mp 

grtz bart

**Comment by teneco** [comment]
What happens if you restart the clients and the server?
I've seen several issues on mp-map: for one player the engine is on for the next player the engine is off or a certain vehicle is not controllable anymore. Or I can not leave the client SW anymore. Those problems vanish after restarting the server.

**Comment by evybart** [comment]
ok thanks for the advice i gonna try the next time
