### ISSUE TITLE
Wrong Courses loaded from library on server

### ISSUE THREAD

**Issue by teneco** [Courseplay/courseplay#2727]
Strange thing happens from time to time on dedi Server: I#m using CP 5.02.00091. When I try to load a course from library I get the rihgt course markers for the course but another title in the buttom left corner of the HUD (from another stored course). When I try to start the helper it tries not to follow the visable course but the wrong course.

**Comment by oschuhm** [comment]
I'm observing the same issue in version 5.3.13 in Multiplayer (on Dedicated Server)
Load course  "A" via CP HUD. On the screen it will show me the waypoints of course "A".
In the CP hud it will show me that course "F" was loaded.
Helper wants to follow course "F" when hired.
This happens at irregular intervals.
In most of the cases it is reproducable by deleting saved courses and create new ones.
Restart of the local game on the client machine will not help.
Restart of the server will fix this issue for a short period.

**Comment by Sim-ian** [comment]
Hi all

I'm having the same issue V5.03.00012.dev Have tried the scroll trick but not successful. I then tried clearing out some saved courses from folders i had previously used but no longer needed and found that the courses were not being deleted courseManager.xml and the courseStoragexxxx.xml files still existed. I tried a manual save through the game GUI but no change and i waited for a server autosave.

After 2 autosaves there were no changes in the courseManager.xml file, so i don't know when courseplay is actually supposed to be updating it's files. I also created a new folder which was updated in the file straight away, I then recorded and saved some short test courses and moved them in to the test folder but again the xml file was not updated and the parent was still showing as zero parent="0" i.e. the root folder.

It seems like recorded courses and folder creations are being saved correctly but folder management and deleting courses is not being updated in the files.

As usual i know I'm working on a mod map "Snettertons Farm" by stevie and have several mods running so some of the issues could be caused by that fact, I am willing to try on a clean game on a default map if needed as i run a home hosted dedicated server it's fairly easy to setup a new server. If you need any further info or testing please let me know.

As a side note, would it not be worth thinking about using a system based on the single player where each person creates and saves there own courses with may be a way to swap course files which could be that one person loads a course and player two uses the Copy course option to get their own copy of the course. These courses would then be saved to a folder base on the server name rather than in the main map name folder. this could be simpler than working out the issues that are currently happening.

**Comment by oschuhm** [comment]
any news / update on that issue?

**Comment by pops64** [comment]
We will get to it when we can. I am not set up for MP testing. I may post a day were I might be looking for MP testers to go through all the MP bugs

**Comment by pops64** [comment]
Closed #2909
