### ISSUE TITLE
Seeder cover opening when empty

### ISSUE THREAD

**Issue by Haka1a** [Courseplay/courseplay#2733]
Hello!

I was just noticing while playing that if a seeder runs out of seeds or fertilizer, it will stop and notify it has ran out of supplies, but doesn't open the covers of seeder. Personally I would like it to open the cover, so I could drive next to it with overloader and fill the seeder. Now it just stops and keeps covers closed so that the tool cannot be filled.

Just bringing up the idea.

**Comment by AndyK70** [comment]
The cover opens automatically when there is a refill possibility nearby. So once you're close enough with a i.e. big bag, the cover will open.
But I do know, that when I want to refill the potato seeder I can't do it at normal silo pipes as the seeder wants seed instead of ready harvested potatoes but I can still refill it with potatoes using a shovel.
Therefor I think you'll have to stick with the manual opening of the cover when refilling with an overloader instead of a service trailer or trailer with big bags loaded.

**Comment by pops64** [comment]
Has AndyK70 says the cover opens automatically in range of a fill trigger CP closes it most of the time

**Comment by Krahazik** [comment]
I have run into the same problem. 
My guess is that the overload pipe from an auger wagon is not recognized as a fill trigger?

**Comment by pops64** [comment]
I would make a new issue as this is FS17 issue so who knows if this was carried over
