### ISSUE TITLE
Suggestion for unloading chaff in bunker silo

### ISSUE THREAD

**Issue by SebStu** [Courseplay/courseplay#2746]
The productivity of a chaff harvest is limited by the capacity of the leveling tractor especially in those wide and long closed silos where every leveling circle takes a long time.
Is it possible to let the tractor with the full trailer back up into the silo until it reaches the end of the course, the edge of the piled up chaff or can't push the trailer any further up the pile and let it unload at this point? The feature could be for example activated by putting an unloading point at the end of the reversing course inside the silo instead of just reversing the tractor. 
This way several unloading courses could be set side by side inside the silos and the leveling tractor's job would be much easier. Instead of pushing the chaff all the way to the back it only has to even the ramp of the pile for the next unloading trailer.

**Comment by pops64** [comment]
We won't fix placing the unload point inside of the trigger due to the difference between the two systems. If the pile it is currently unloading at is full it will move forward. Has moving the tip point we will discuss it internally but it would involve many different systems that we have found a balance to get them all to work most of the time

**Comment by pops64** [comment]
Closed for now will revisit in the future
