### ISSUE TITLE
Multiple Tractors Reversing

### ISSUE THREAD

**Issue by matticus9473** [Courseplay/courseplay#2749]
Just a question to start: 

When harvesting root crops, I set up a combi course where the tractor reverses into an unload point and unloads before driving back to the field. With one tractor it works perfect but when I run a second tractor on the same course, at some point they meet up and while one is trying to reverse into the unload point, the other one is running up the back of it. Is there any way of getting the second one to wait while the first tractor reverses and tips?

Thanks

**Comment by MoslessNeo** [comment]
Just to complement the post
Placing a stopping point before starting the download process does not solve; the time to wait seems not count the point where the tractor starts the route, but since it comes out of the combine and continues to discharge;
So if I put a 3-minute wait time, depending on the size of the field, it may not resolve.

**Comment by pops64** [comment]
I would just use two separate courses with unload points next to each other for now. We will discuss this at a later time

**Comment by pops64** [comment]
Closed for now will revisit in the future
