### ISSUE TITLE
Trailer Tipping Side

### ISSUE THREAD

**Issue by AchhammerSebastian** [Courseplay/courseplay#2759]
Hello,

is it possible to choose the dump side for dump trucks?
Because they always tip to the wrong side and that does not look so pretty.
Would it be possible to integrate a corresponding setting?

**Comment by nuu5t1k** [comment]
That would be really great for mode 2 with unload course in bga silo. I changed manually sides. But it changes back automatically to compensate reverse trailer unload failing course.

**Comment by pops64** [comment]
In reverse it will always select the back. With all the others it will select the best side

**Comment by nuu5t1k** [comment]
Yes thats right but wont it be possible to make the tipside manual and autimatic? My trailers always tip on one side because they reverse the same way. So it becomes a problem when six of them are doing the same. My point is that they could be set manually. 3 if them tip left and others right side. Or the silo has a big chunk of chaff against the wall. It comes a problem for leveling tractor.

**Comment by pops64** [comment]
It should always dumbimg out the back in the BGA, and most defintanly for reverse so unless your using a mod this shouldn't be happening
