### ISSUE TITLE
Bypass island circle mode not compatiable with non reversing tools

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2764]
When transitioning back to the headland from island bypass it jams it into reverse isntead of driving straight into the headland see pic. Gamsting map field 7
https://www.dropbox.com/s/fkgbat48iwacc2z/cpFields.xml?dl=0
![fsscreen_2018_06_21_19_09_51](https://user-images.githubusercontent.com/10678220/41749868-ed7e6778-7586-11e8-9261-691568fa33aa.png)

![fsscreen_2018_06_21_19_15_41](https://user-images.githubusercontent.com/10678220/41749986-813eb51c-7587-11e8-9bec-8237d5abfcda.png)

Also a question how many laps around the island is determined? Has I don't think 3 would be enough to clear the island in a turn maneuver in updown mode

**Comment by pvajko** [comment]
Reversing is intentional to prevent missing fruit. Will not fix here, we have other, more generic issues for reversing with non-reversible tools.

Headlands around islands is currently limited to 3 to make life easier for the developers :) Just think of islands close to the field boundary. Open to any suggestions how to solve this with reasonable effort.

**Comment by pvajko** [comment]
For the record, #2724 is the one to deal with the reversing.

**Comment by pops64** [comment]
Yea that issuse is avoidable by not using turn on headlands this can't be. Didn't know this was intentional will leave open has there are a few other tools that can't reverse and we don't need duplicates

**Comment by pops64** [comment]
Closed #2909
