### ISSUE TITLE
Minimum Turn Radius in Mode 4/6

### ISSUE THREAD

**Issue by dominiczeth** [Courseplay/courseplay#2811]
Hi folks,

i've a Problem with the Great Plains YP-2425A and the Big Bud 450. When using it it goes to an endless Turncircle when he reach a turning point on a generated course. 
The Problem is that there is no option for the Turn radius in Mode 4 and 6. It needs a bigger turn Radius otherwise it can't reach the next waypoint. Even if i set the course to leave out a lane it's too much. Same for the "Hard" curves in the generated course. 
Is there any way to add the turn radius option to these modes? 

Edit: That's because the strange turning behaviour from the Great Planes seeder. It pulls the tractor to the inside of the curve when turning hard. So he can't reach the next waypoint. 

I'm using the Modhub Version. 

Edit2: Ok now i tested the actual Dev Version and with leaving out one lane it works. Still it has problems in Harder Turns.

**Comment by pops64** [comment]
Try adjusting the turning radius found under the combi settings mode, And in version 5.03.08 or higher there is definitely a turning radius option in course generation. If you talking 180 degree turns on up/down thats handled differently and would be fixed by increasing the turning radius. though if it is DLC and not a mod it should be set right to begin with
