### ISSUE TITLE
unable to create course

### ISSUE THREAD

**Issue by n4396t** [Courseplay/courseplay#2821]
I'm using 5.03.00013 and I'm having problems with the island function.  No islands, no problems.  I tried to generate a course 4 or 5 times and then started the logging function for course generation, I'll will attach it, but it looked to me like the problem was that it said it couldn't add any more headlands on a 75 HA field. I had been trying to set the headlands at two so I went to one and had the same problem.  I had used the same setup on a field with no island last night and had no problems at all.
[log.txt](https://github.com/Courseplay/courseplay/files/2268778/log.txt)
Thanks Rambler

**Comment by pvajko** [comment]
This log does not seem to have any debug channel turned on, turn on channel 7 and post the log. Also, it helps a lot if you tell us which field on which map this.

Even better, post your field definitions, see the wiki, especially https://github.com/Courseplay/courseplay/wiki#how-to-post-your-field-definitions.

**Comment by pvajko** [comment]
There are two issues with the field you posted, that little zigzag on the left and the island in the upper right corner which I think does not supposed to be there, both likely caused by your editing:
![capture](https://user-images.githubusercontent.com/2379521/43895681-6a877028-9bd6-11e8-8cf8-bd92e3a453ad.PNG)

This is a big field but 6 minutes seem to be a bit slow, do you have the log with debug channel 7 for that?

**Comment by n4396t** [comment]
pvajko, you were correct, I was going around the field with the roller because there were some trees actually in the field.  When I just split the field and didn't go around the edge all worked good. Thanks for your help. 
Rambler
