### ISSUE TITLE
Issue with unloading grass in bunker

### ISSUE THREAD

**Issue by Denstorebandit** [Courseplay/courseplay#2902]
When i setup a course to empty my grass into the bunker mainfarm "South mountain map", it empty everything besides 4-8 grass. Then it close the trailer, drives a bit forward and stop the course.

During this error, some of the other active courses fail and those combine/tractors go straight into whatever is in their path tree, fence etc

I disabled  all mods beside the map, tried both the modhub version and developer v. 5.03.00043

First time i tried use pastebin, but the log should be here: https://pastebin.com/cLekBn7P

- note: tried different loading wagons + the BGA on lone oak map, same issue

It seem as someone had same issue back in "Reverse unloading in BGA #2041"

New information, doubt its CP.. with manual unload it keep 6 grass in trailer to

**Comment by Denstorebandit** [comment]
![fsscreen_2018_10_26_20_31_56](https://user-images.githubusercontent.com/44508259/47585759-88330b80-d95e-11e8-877d-42256a31f4a3.png)

**Comment by pops64** [comment]
Few things, nothing in your log shows that CP would fail like this. That behavior is usually a result of a nil error or index error which both would appear in the log. 2nd thing your course is not proper. When ever unloading CP must see a FWD waypoint in front of it otherwise you get random behavior from that vehicle. So you course leaving the bunker is not straight enough.(Remember when pulling away that you need to imagine a trailer behind you and give enough straight length to account for that) Third thing you should always drive at least half way into a silage bunker that what the code will work properly and not spill out in front of it

**Comment by Denstorebandit** [comment]
Ok I'll have that in mind when doing new courses. But I think the issue is game related.. with CP not loaded I can't clear a trailer completely

**Comment by Denstorebandit** [comment]
I'll check on a map with better option to make straight courseplay route from bunker and out..

Ill try have it setup by tomorrow and see if it solve the issue

**Comment by Denstorebandit** [comment]
I managed to setup a better course, it solved the issue... closing topic
