### ISSUE TITLE
FS 19 Status

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#2912]
We are currently hard at work updating CP for FS19. When we are ready for beta testers we will make a push here. Until that time you won't see any commits to GitHub but do not worry has we are busy working on updating CP. I will include a list that we will try to keep updated on the current bugs that CP has with FS19

- [x]  Hud is broken. Giants has overhauled the functions we were using. 

- [x]  Input Bindings have been overhauled. Can't test changes.

- [x]  Camera doesn't freeze prohibiting mouse movement on HUD open

- [x]  Field Scanner doesn't work due to Giants Changes

- [x]  Tools Don't Drive with Courseplay due to attacherJoints being overhauled

- [x]  Saving variables and courses is broken

- [ ]  Debugging and updating all modes to ensure compatibility with FS19

- [ ]  Fixing CP traffic system. Giants moved some things we were using for this functionality 

- [x]  Waypoint marker needs to be updated to FS19

- [ ] Misc. Hud functions don't work

- [ ] Misc. Bugs due to Giants overhauling the Util functions to Manager functions

- [x]  Triggers are not working due to Giants removing code that we were using to enable this(Mode 8 need looked at still)

- [x] Reversing Trailered Tools doesn't work

- [ ] Mode2 doesn't work very key variables being moved and key functions being removed

 - [x] Mode 4 is working

- [x] showstopper:  problems with leaving and returning to the tractor when Cp is running it

~~As you read from the items on our list we can't fully test CP functionality until ~~the HUD and input Bindings are working again~~ the key components are fully working~~  . Also a script reference for 19 has yet to be released which is making things slow going until then. Things not on the list yet but could be problems are the Lode King, Wilson Tipper Trailer, Seed Cart and Cotton Harvesting. CP currently has no code to support theses new features. Please do not forget that this may be an expanding list has we start getting more things to work it allows us access to things that may or may not work

**Comment by pvajko** [comment]
Just a heads up: we will do incremental releases of CP, starting with a limited functionality and adding back features step by step. We hope that this benefits more the community than the a bang approach where the complete functionality is released after a long period.

You can expect the first (beta) release to include the basic functionality for modes 1, 2, 4, 5 and 6 (grain transport, combi, fertilize/seeding, transfer and fieldwork.  

And no, no date yet. We'll let you know.

**Comment by ThomasGaertner** [comment]
guys:
currently we have 3 showstoppers which prevent us from going to public beta and we are at the moment not able to solve them alone, but hopefully with the help of Giants

The problems are in order of priority:
- trains are not in g_currentMission.vehicles when starting a new savegame and cp
	start a new savegame vanilla - no problem
	start a new savegame and cp - locomotive is not in g_currentMission.vehicles
		trying to enter throws 'dataS/scripts/BaseMission.lua(1876) : attempt to index field 'controlledVehicle' (a nil value)'
		trying to save throws call stack '2019-01-16 23:21   dataS/scripts/trainSystem/TrainPlaceable.lua (220) : setXMLInt'
	start the crashed savegame with cp  -same issue
	start the crashed savegame without cp - no problem -> saving no problem
	start again with cp - no problem anymore
	
- tools dont refill on loadTriggers when nobody is in the tractor 
	it works, when I'm in the vehicle but not if not
	
	
- if an engine is stopped , it is not able to restart by order
	the FS17 solution doesnt seem to work here...
	
as soon  as we have solved this, we will prepare the public beta...

**Comment by pvajko** [comment]
Dear Courseplay Users,

we decided to move back to GitHub as with the valuable help of our beta testers and some of the Giants developers we think we now reached an acceptable level of functionality and stability which allows for a wider audience to enjoy the benefits of Courseplay.

Remember, only modes 1, 2, 4, 5 and 6 are functional and there are many known bugs (as the Courseplay console message says "the Courseplay team will not take any responsibility for crop destroyed, savegames deleted or baby pandas killed"), because yes, this is still beta software.  We will be enabling functionality step by step so probably your favorite Courseplay feature may still be missing. Be patient. What you have now is better than nothing.

If you see problems, please post an issue, see our [Wiki](https://github.com/Courseplay/courseplay/wiki) on how to create a useful bug report.

Again, be patient, we have a life, family and job. For days or weeks we may not even look at the issues you post. We may defer fixing some of the issues or not fix them at all. 

If you can't wait for an issue to be resolved you are more than welcome to fix it yourself and open a Pull Request.

Your Courseplay Dev Team

**Comment by Tensuko** [comment]
Closed.
