### ISSUE TITLE
How can the community can help

### ISSUE THREAD

**Issue by NathanJ4620** [Courseplay/courseplay#2917]
As an avid user of Courseplay and someone with a basic knowledge of Lua how can a someone like me aid in the development of Courseplay?

**Comment by Goten87** [comment]
we cant yet until they have the base done and we get our hands on it

**Comment by Satissis** [comment]
@NathanJ4620 atm there issen't really much you can help with, since allot of the stuff we are working on is stuff we need direct contact with Giants for (Which we do have)
The GDN script ref not released, slows down that progress allot as well so the only thing I can say is until we got a fully working version running we cant let new people in due to the time needed to help new people get around the code.

**Comment by NathanJ4620** [comment]
Thank you for the quick response! Best of luck on the development!
