### ISSUE TITLE
HUD does not open for some vehicles.

### ISSUE THREAD

**Issue by kjellskogsrud** [Courseplay/courseplay#2941]
Opening the HUD stops working for some vehicles. CP version v6.00.00033
Lots of mods in use, but you can see that from the log file. [GIST](https://gist.github.com/kjellskogsrud/7cdbcd9e298425e0d41b63cd55826f71).

The HUD opens in some vehicles, and not at all in others, 
IE. Fine in the JD combine, and not at all in the JD 6R.

**Comment by INDEFITY** [comment]
I would advise testing the courseplay without third-party mods

**Comment by godofgta42** [comment]
I have a smilar problem. Although with me its more random. Sometimes the GUI opens, sometimes not. Sometimes it works when i press STRG+DEL followed by a right mouse click, sometimes the other way around, sometimes just STRG+DEL works fine. And it changes midgame too.. Works great for a time, then breaks and i can't get it to open at all. My [logfile ](https://gist.github.com/godofgta42/3d44c5e920558e72c880becc85c6f9b1) has no error when i press a button though.

**Comment by HungryCow212** [comment]
During the closed beta we were advised to reset keybindings to fix this issue.  You might want to give that a shot after backing up your current keybindings xml.

**Comment by Ravlie** [comment]
Similar problem with mine. I can use HUD when I'm inside a vehicle but once set-up and running and re-enter vebicle again from another one it won't open again. I have a lot of mods and I'm playing on Hopfach map and driving original vehicles.

**Comment by 37cee** [comment]
I sometimes have the same problems  godofgta described. 
When loading a savegame, i cant open the CP menue. The vehicle with the lowest vehicle id always seems to work so far. The rest most of the time but not always, though repeating using the ctrl+del keybind sometimes make the menu pop up after several attempts. When buying new vehicles it rarely works, only saving and reloading seems to help.

PS for testing pruposes i dont use any mod for CP right now.

**Comment by Satissis** [comment]
It's know that CP don't like mod vehicles atm so not sure if that could be the reason

**Comment by godofgta42** [comment]
Right now i'm using the Version 6.01.00015 and the Problem seems to be gone for me. I can open the window with a right click on any vehicle so far. I started a new savegame though, not sure if that was it.

**Comment by Satissis** [comment]
Possible, but could not tell, since I haven't looked into this yet

**Comment by Crinouche** [comment]
Hello,
Problem # 3162 is fixed with version 6.01.00052, but now I have a problem to open the hud with some vehicles.
On some vehicles, I can open the hud with the mouse, but not with CTRL + DELETE and on others, it's the opposite, I can not open the hub with the mouse, but it's OK with CTRL + DELETE.
I tested by removing all the mods from the mods folder, but the problem remains the same
Regards,

**Comment by Crinouche** [comment]
Hello,
Sorry I made a mistake. Everything works perfectly.
I was wrong in assigning keys.

**Comment by Innallas** [comment]
Issue ReCreated here recently https://github.com/Courseplay/courseplay/issues/3329 , i had fixed it with a pull request.... there is a bad condition/var assignation (ternary function created to be used for, script don't know it)

Pull Request : https://github.com/Courseplay/courseplay/pull/3342

I already made it but was close without implementation... my god, do you even know what is a ternary operator ? the script clearly dont have natural syntax for it.... your crap create a HUD bug.... as i said you dont even test & apparently dont know what your doing in the code.... (like in last version the unload distance isn't respected anymore, look like "static" somewhere & not calculated)

**Comment by sootysax** [comment]
![banhammer](https://user-images.githubusercontent.com/6591048/53689445-34796a00-3d24-11e9-8ed1-2aa39ad82957.png)

**Comment by Innallas** [comment]
Did you try before tick a bad appreciation ?? Its working ... you should launch the game 1 day.

**Comment by pseikoNL** [comment]
@Innallas, if you think you know it all so well, why you don’t create your own kind of courseplay mod instead of rant on the CP devs, you do not know why there is chosen for different modes for normal transport and liquid transport. Fertilizing and seeding mode is also fieldwork, but yes it has it’s own mode as fieldwork job, why? Because it needs to handle things on a different way, just as liquid transport mode has to be done. Of course you can put all kind of modes in one mode but makes that developing, testing and working things good? No it didn’t. So stop ranting on the CP code or the devs and contribute in a proper way, or go make your own shit, o and then don’t use bits of the courseplay code, as you said its bad code.

Kind regards

**Comment by ThomasGaertner** [comment]
@pseikoNL : he cant answer you. I blocked him because of #3346

**Comment by ThomasGaertner** [comment]
try again with v.151 or higher

**Comment by sootysax** [comment]
I am still having issues on having key commands not work when tabbing into vehicles..  

If I use E to exit the vehicle and get back in, then the key commands will work..

Disconnecting and then reattaching a tool also gets the key commands working as well.

**Comment by ThomasGaertner** [comment]
try again with v.152 or higher

**Comment by Tensuko** [comment]
Outdated, as HUD got reworked.
Closed.
