### ISSUE TITLE
Menu Wont Work More Details In Message

### ISSUE THREAD

**Issue by Fourmula** [Courseplay/courseplay#3047]
When in Game On Some Tractors And Equipment The Menu To Load Courses ETC. Just Wont Wanna Work And I've Changed The Key binds In The Binds Menu And Nothing Seems To Work , Am Doing Something Wrong? Or I Follow Farmer Kelins Install Manual And It Works So Far Done All The Basic Stuff Just Sometimes It Wont Open (ALSO Changing The Tractors Customize Options The Paying For Them Then Going Back To The Beginning Options SOMETIMES WORKS. Thanks For Reading                          

 Im On Courseplay Verson V6.01 .00015.DEV

![](https://user-images.githubusercontent.com/47197301/52020842-6050c800-24b8-11e9-9d70-6ec26edc1af5.jpg)

**Comment by Fourmula** [comment]
![20190130175522_1](https://user-images.githubusercontent.com/47197301/52020842-6050c800-24b8-11e9-9d70-6ec26edc1af5.jpg)

**Comment by Fourmula** [comment]
Likes To Do That Also Just Not Open Menu And Remove "AI Driver"

**Comment by Satissis** [comment]
So just to be sure.
Some times you can open the hud on a vehicle and later you cant open the hud on that same vehicle again ?
Or is it one some vehicles it cant open at all ?

**Comment by Fourmula** [comment]
It Happens After Starting Them On A Course For A Field And Then Clicking The X On The Menu And it Just Will Not Open Again On That Tractor

**Comment by Fourmula** [comment]
So They Get Stuck In The Stop Point And Will not let me stop the course at the end

**Comment by Fourmula** [comment]
And Also It Happens When i Change It To The Second Way To Open It I Have The Second Way Set To : LCtrl And Delete

**Comment by Satissis** [comment]
Right. I'm afraid this will have to wait until I get to rewrite the whole keybinding thing for now

**Comment by Fourmula** [comment]
Dang Thats Sad

**Comment by TinyCrocodile** [comment]
Try resetting the veicle instead of selling. On fs 17 i belive this resetted cp as well.

**Comment by operinko** [comment]
That's actually what I tried before resorting to selling.

**Comment by Hubcap-1** [comment]
I am Having the exact same issue . I can add that resetting does not help. I also find that The problem seems to be vehicle related. I have several of the same tractors. Important note . It seems to happen to the one outfitted with dual tires ( front and rear), almost consistently. I have also found, leaving the tractor for some time ( like 25 minutes to an hour), it will suddenly come up again. I have also found that the default right click might bring it upon some tractors....then when i switch the key binding to lctrl+Del, and push the key binding I get the click but hud does not display, and if it had just stopped at last way point having finished the course  the tractor starts a high speed run of the same course in an endless loop with no way to stop it until i resart the game.

**Comment by Fourmula** [comment]
Any Luck
And Why Was This Closed @Satissis

**Comment by Satissis** [comment]
@Fourmula This issue is not closed.
it was another issue that was closed due to duplication.
And no news on this as it's postponed until we get some other stuff fixed first.

**Comment by Messy71** [comment]
Still happening with:
Courseplay v6°01°00049
Farming Simulator 19 (Steam)
  Version: 1.3.0.0 b3694
In log,around the time that happened:
2019-02-08 23:09 Warning: DensityMapVisualizationOverlay is being reset, because a DensityMap it refers to was deleted.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 1' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 2' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 3' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 4' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 1' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 2' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 3' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 4' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 1' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 2' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 3' before all triggers are removed.
2019-02-08 23:09 Warning: Deleting object 'cpAiCollisionTrigger 4' before all triggers are removed.
2019-02-08 23:09 Warning: DensityMapVisualizationOverlay is being reset, because a DensityMap it refers to was deleted.

**Comment by Fourmula** [comment]
do you know how much longer?
@Satissis

**Comment by Hubcap-1** [comment]
I believe I have been using this, " Mysterious fix" ,for some time now ( it is a replacement " Turn LUA " file). It works with the 1050 as well if you only have 1 headlands selected ( 2 and it gets lost at the point to transition to up / down). However it is the attachment that is partially to blame...long wheel base seeders are the problem. The code for this mod must have the ability to read the " Bridge" distance. Basically  bridge is the distance from attach point to the rear wheel base which determines " turn radius " ( formula in geometry )for backing up.

**Comment by Redline1969** [comment]
What I have found is that this seems to happen to with my combines doing field work that most. I use the right mouse button to open the Courseplay HUD and I generally leave it open. It seems to be random but after some time I will click on the Course Generation button in the HUD and the entire HUD along with the machine controls menu in the upper right seems to disappear. After some further investigation, I have found that the HUD is still there, but it is invisible. Without the HUB being visible, I can click on another button (or at least where the button should be visible) and the HUD reappears. If I select the Course Generation button again, the HUD becomes invisible again. Exiting the game to the main menu and coming back in fixes the issue.

**Comment by Fourmula** [comment]
Any Update @Satissis

**Comment by Fourmula** [comment]
@Satissis @Redline1969 @Hubcap-1 @Messy71 @operinko  It Is A ***MOD CONFLICT*** I Wiped My Mods Folder Put Essential Mods In And Boom Fixed

**Comment by Hubcap-1** [comment]
Actually if you deactivate pathfinding it's fixed too
