### ISSUE TITLE
Hatzenbichler Terminator will not work unless I set Helper Refill Seed to ON

### ISSUE THREAD

**Issue by Rbk3** [Courseplay/courseplay#3050]
I get the error message "work tool needs to be refilled" even though the seed compartment is full.

**Comment by pvajko** [comment]
Post a log with debug channel 14.

**Comment by Bigmack73** [comment]
I have a similar issue, I am not able to use the same seeder. Keeps saying it needs to be refilled when its completely full of seed and fert. Just says it needs to be refilled.

**Comment by ftasch** [comment]
Here you go: 
[log.txt](https://github.com/Courseplay/courseplay/files/2821739/log.txt)

But i think the problem is in the way this seeder works. Since it does not have its own storage of seed and fertilizer, but rather requires a second vehicle (Hatzenbichler TH1400) to be pulled in front.

Guess Courseplay is looking up those values in the seeder itself, who does have these filllevels, however they always remain at 0.0. I suppose to fix this, courseplay would have to check wether there is a second vehicle with fertilizer and/or seed. Dont know though if that is simple to fix or requires more extensiv work.

**Comment by ftasch** [comment]
Oh just as i was writing this you already uploaded the fix, working fine now.

 Thank you very much!
