### ISSUE TITLE
Cant open UIs

### ISSUE THREAD

**Issue by MorganLtd** [Courseplay/courseplay#3057]
if they are set to open with "shift+rightclick" and a worker is driving another tractor.

**Comment by Kuktar** [comment]
I am having the same issue. I tried resetting my keybinds which was suggested by another user. any advice?

**Comment by Kuktar** [comment]
Ok total noob mistake. I had to select it after i opened my savegame. Like all tractor mods it is de selected by default. I think maybe putting that in the insturctions for install for us noobs out there lol

**Comment by Redlght** [comment]
My issue when I bring up CP hud I can not click any thing such as start recording I click it does nothing even using the left ctrl key plus mouse click.

**Comment by Redlght** [comment]
I found it does not work when i use my wingman game pad controller, if i unplug it then cp is clickable with mouse

**Comment by Satissis** [comment]
Please check your keybindings.
If you used the leaked CP version when in closed beta, we had allot of changes regarding the keybindings, since they didn't work in the start.

For opening the hud the default is right mouse button alone, without Ctrl.
In the keybindings, the primary and secondary mouse action to be set is the left and right mouse button.

If this does not help, then the only thing I can suggest is resetting the keybindings fully.
And again if that don't work either, then I'm afraid you will have to wait until I get the time to do the full rewrite of the keybindings functions, since they are handles a bit different in FS19 than FS17 and have only make a temporary fix for it atm.

**Comment by Fourmula** [comment]
I Have This Problem After Telling The AI To Do Field Work And It Just Dosnt Open After Clicking The X On Courseplay Menu

**Comment by Redlght** [comment]
It only fully works if i unplug the usb controller, I can live with it till the keybindings are redone. Thanks for your help. ☺☺☺☺☺

**Comment by Morgan81** [comment]
1st: I meant "Ctrl+Del", sry
2nd: Only downloaded PublicBeta from here, not pre leaked stuff.
3rd: By resetting keybindings, you technically mean deleting the CP entries from the vehicles.xml?
4th: 3rd didnt help. Set a truck to "Ctrl+Del"; started a vanilla helper on another vehicle; wont open Trucks UI with Ctrl+Del.

**Comment by Satissis** [comment]
By resetting the keybindings I mean go into the game settings under controlls and press the reset button.
Or go down to the CP area and set the keybindings manually but resetting would be the easiest and most reliable way to do it

**Comment by edjon2000** [comment]
Yep I am also having the exact same issue, to expand on this a little if there are any other courseplay courses running on the map you are unable to open the UI for cp if however you stop the running course then you can open the ui on all other vehicles, if you leave the ui open on other vehicles and then start the CP course then the UI stays open on any other vehicles and you can then set up or run other courses, I hope that helps a little

**Comment by ThomasGaertner** [comment]
is it still an issue with the current version `?

**Comment by edjon2000** [comment]
Hi Thomas, as of version 6.01.00162-dev it seems to be fixed, Thank you
