### ISSUE TITLE
Turn on field not working 6.1.17

### ISSUE THREAD

**Issue by skmcconnell361** [Courseplay/courseplay#3065]
The turn on-field option is not working. Using the Fendt 515 tractor and plow on field 18 and 19 in Revenport map fs19. Also tried with the weeder tool on field 19

**Comment by Messy71** [comment]
I don't want to be **that guy** but did you try to activate it after CP starts driving?

**Comment by Satissis** [comment]
Some Plows cant be reversed with, so it will not try to stay inside the field.

**Comment by tjBerlin** [comment]
Maybe I just the wrong plow, it is a cultivator for deep cultivating, so called "tiefengrubber". I used cp version .00044 on FELSBRUNN. Cultivating field 20 and "turn on field" on. But driver turns out side the field. 

![Uploading Bildschirmfoto 2019-02-06 um 12.12.11.png…]()

![bildschirmfoto 2019-02-06 um 12 11 29](https://user-images.githubusercontent.com/24283753/52345932-afe64500-2a1e-11e9-938e-5535e9f80f82.png)

[log.txt](https://github.com/Courseplay/courseplay/files/2836561/log.txt)

**Comment by pops64** [comment]
The above pictured tool could not be reversed in FS17 due a conflict with a Giants node. I could not figure out was causing this in 17 and so I just disabled the reverseing on this tool. Not sure if the above Giants bugged carriered over to 19

**Comment by Tensuko** [comment]
Very old Version and changed a lot for turning, so closing this.
Any Tool Problem on turns for Vanilla or ModHub Tools, make new Issue.
