### ISSUE TITLE
Problem with turning in headland

### ISSUE THREAD

**Issue by Schrecke1989** [Courseplay/courseplay#3102]
at version 06.01.00017- 06.01.00019
the turn works quite well from version 01.06.00028 I noticed that the turn does not work but hang in endless loop

**Comment by Hubcap-1** [comment]
I too am having troubles with Headlands. It drives the first long edge of the field, but when it must turn 90 degrees it starts backing up with the seeder " Jack knifed" in an endless circle in reverse never attempting to go forward down the next length of the field to complete the headland pass. I have tried everything from changing the reverse from straight to curved.turn on field activated and not activated....have run out of options. Even tried increasing the turn distance

**Comment by Hubcap-1** [comment]
Thank you I have tested it it seems to work really well for fixing this
problem however I will point out there is still a problem with it.it works
perfectly fine if you only have one lap of Headlands applied.I had 2
selected it did the first lap no problem but the transition to the second
lap it just started going forward in circles this time instead of starting
the second lap

**Comment by Nazlund** [comment]
I have the same issue and a few more all related to this. So I set up a course for a square field. I set the working with to 40.5m or three 13.5m straight cut headers. I set it up to do as many headlands as possible so that the unloading auger is never on the wrong side. I then generate the course.I then set the lanes of the combines to be offset. One 13.5 to the left, one in the centre and so on. I position the combines and start them one after another. The combine on the outside (left offset) and in the centre do the first headland with no issue. The inside combine (right offset) makes it to the first spot where it needs to make the 90 degree corner and then it starts messing up. Drives in a circle to the right and then comes to a stop and shuts off. it doesn't move until I occupy the combine myself. Then it starts to move slowly but then stops. I leave the combine and then come back and it does the same thing. Continues to do this never correcting itself. The other two combines make it around the first headland but then when the need to transition to making the second headland they do the same thing. If I leave them and go back into them enough they do find their way to start the second headland but they no longer have their machine engaged and just drive over the crop not harvesting it. 

I'm new to GitHub so I hope I have attached my log file correctly. Just trying to help out :).
[log.txt](https://github.com/Courseplay/courseplay/files/2834322/log.txt)

**Comment by pvajko** [comment]
Don't know where did you get your Courseplay copy but you are running version 6.01.00001. You are 42 versions behind the current dev version. Try with the latest.

**Comment by Hubcap-1** [comment]
I have found a “small improvement” if you replace the  ,” turn LUA” file with this one. You will need to use it In all the update patch’s as there has not yet been a solution….save this and replace the turn LUA 

Sent from Mail for Windows 10

**Comment by pvajko** [comment]
Try with v6.01.00073, reopen if it does not work.

**Comment by Schrecke1989** [comment]
I have the version 00073 to 00076 tested the function is up to machine sizes Horsch DC9 given but machines like the Amazon condor 15001 or even the Stara estrela32, there are problems that they end in endless round (Amazon) or extreme auscult (stara) believe the same problems with Courseplay v. 5 for FS 17 too

**Comment by Hubcap-1** [comment]
> I have the version 00073 to 00076 tested the function is up to machine sizes Horsch DC9 given but machines like the Amazon condor 15001 or even the Stara estrela32, there are problems that they end in endless round (Amazon) or extreme auscult (stara) believe the same problems with Courseplay v. 5 for FS 17 too

As I use the Condor 15001 predominantly and also use seed hawk ( i think its called 32 meter )I can agree with you to a point. The 32 meter will do smooth turns but no backing up. The Condor can back and " Turn" on 90 degree turns and greater than 150 degree turns. The odd angled turns seem to be an issue. At least with the custom Turn LUA file i input on every version since version.000040. I include the file here for anyone wanting to try it. I am not the author
[turn.txt](https://github.com/Courseplay/courseplay/files/2873423/turn.txt)
 of the file.

**Comment by Hubcap-1** [comment]
> So, let's ignore the turn on headland part of this issue as there are a lot of those already open and focus on what @Hubcap-1 found, the transition. Post a log with debug channels 12 and 14 when that's happening.

How do you do that( Not the post part)
