### ISSUE TITLE
vehicule dont recall custom turning circle after save/exitgame/load

### ISSUE THREAD

**Issue by Cassio38** [Courseplay/courseplay#3131]
![image](https://user-images.githubusercontent.com/20385247/52291618-05fdae80-2973-11e9-8e4d-d1d6460f8a35.png)

this particular setting need to be re-setup everytime you load a game. would it be a way to store it inside vehicules ? pretty usefull with wide cultivators/seeders !

Thanks guys =D

**Comment by Messy71** [comment]
I don’t think it should be stored (hardcode’ed) in vehicules because at the moment reversing with a hitch implement doesn’t work pretty well on inclined turns untill that problem it’s fixed some people play with that setting to get things to work.

**Comment by Cassio38** [comment]
maybe it would be cool to track that setting into the course itself then ?

**Comment by Messy71** [comment]
Save it with the course and be able to change it after loading a course will be the best implementation.

**Comment by Satissis** [comment]
Well spoke with Thomas about it and to be honest, the best way would be to save the value when saving the game and set it on game load again.
but it will only be if have been set manually and attaching/detaching an tool will reset it back to automatic.
The above is not implemented yet but is an easy fix when we get to it.

Regardign saving it to the course is kinda a bad idea, since you can use the same course for different tools and setup and each tool don't have the same turn radius so if it's set too low for one tool, you will be in trouble again.

**Comment by pAnFarmer** [comment]
Hi all. Could it be another workaround to change the turning value CP gets from the attached tool? Or where is CP retrieving those values? If so: which variable of the attached tool should be changed?
Regards
pan

**Comment by ThomasGaertner** [comment]
I decided to let it be as it is: if you are changing it to manual, you are responsible to reset it to auto if not needed anymore
