### ISSUE TITLE
Error: Running LUA method 'onSaveStartComplete'.

### ISSUE THREAD

**Issue by OhExcuseMe90** [Courseplay/courseplay#3143]
I keep having an issue with courseplay when saving the game. The game does not save and FS19 just freezes and I have to force quit via task manager.

The log is below, I have no idea what is causing the issue. 

[https://pastebin.com/ZiwSGzZQ](url)

I am using mods but the error has only just started since updating to the latest available version this afternoon.

Edit: I going to try with just Courseplay and GPS and see if the error happens again if it does then it is not the mods, if not it is a mod a fault, I realize now that I should have does this before posting the issue apologies.

**Comment by OhExcuseMe90** [comment]
Ok after some testing I found the cause of the issue I believe to be the enhanced vehicle mod it seems to have some sort of conflict with courseplay. After removing the mod the error has happened since when saving.

So I will consider the issue closed,

**Comment by sootysax** [comment]
Are you crashing while saving after coming out of a paused game?  Because that seems to be a bug on FS19, not any mods.

I've wound up turning off Auto Save in the menu, because whenever I came out of pause, and it auto saved, it would freeze FS19 and I would have to quit from task manager (but at least it successfully saves first)
