### ISSUE TITLE
Mode 1 does not wait to be filled if the first waypoint is not on a trigger

### ISSUE THREAD

**Issue by GeorgeEarslight** [Courseplay/courseplay#3153]
As per title, v00046, Felsbrunn easy start farm, no mods. 
[Gist link](https://gist.github.com/GeorgeEarslight/39f095a5000bb01bde7a832d94393ac7)

Steps to reproduce:
1. Record a course that does not start on a loading trigger. For example on a field edge.
2. Go to Mode 1 and start the course. 
3. The vehicle will drive through waypoint 1 (briefly printing capacity), even if empty.

Remarks:
- COURSEPLAY_LOADING_AMOUNT is printed so 
~~`GrainTransportAIDriver.lua:175` is true or `mode1.lua:12` is true~~
I tried to locate the flow control where it prints that but you're using it in too many places.

**Comment by tjBerlin** [comment]
see #3043 

cp version .00046, RAVENPORT, no mods, trailer JOSKIN.

As George said, I tried to set the first waypoint very near to the trigger. In that case cp driver stopped, but the loading didn't start. 

![bildschirmfoto 2019-02-07 um 18 41 50](https://user-images.githubusercontent.com/24283753/52433029-52c8bd00-2b0c-11e9-9c50-a630ed2db2a6.png)
The trailer is a bit filled, because I tried the trigger point manually and it worked.

[log.txt](https://github.com/Courseplay/courseplay/files/2842150/log.txt)

**Comment by sootysax** [comment]
http://courseplay.github.io/courseplay/en/manual/index.html#driveMode1

**Comment by sootysax** [comment]
http://courseplay.github.io/courseplay/en/manual/index.html#driveMode1

**Comment by GeorgeEarslight** [comment]
> http://courseplay.github.io/courseplay/en/manual/index.html#driveMode1

"This can happen at a silo, at a field edge or anywhere else. As soon as the fill level reaches the set percentage (Drive on at %), the driver starts to drive the course."

Your point being?

**Comment by tjBerlin** [comment]
Hi, just tested it again with CP version .00047, same conditions. CP driver didn't start the course. 

![bildschirmfoto 2019-02-08 um 13 23 25](https://user-images.githubusercontent.com/24283753/52478635-47c26b00-2ba6-11e9-92f5-f9ee908d2c78.png)

[log.txt](https://github.com/Courseplay/courseplay/files/2845108/log.txt)

**Comment by ThomasGaertner** [comment]
guy, this is not a chat, please check you issue with the issue basically posted and decide whether its tha same or not. Its very complicated to figure out the real issue if you mix them over .... This Issue is about mode 1 not waiting , when ther is no silo trigger (filling by shovel or overloader) ... all other issues will be ignored here

**Comment by ThomasGaertner** [comment]
unfortunately I cannot replicate it. can you give me the savegame and courses ?

**Comment by tjBerlin** [comment]
Sorry, I open a new issue.

**Comment by GeorgeEarslight** [comment]
@ThomasGaertner Just created a new v00046 savegame on Felsbrunn but I cannot reproduce it either.
Sorry for this, please close the issue and I will re-open it if I come across it and have a savegame.
