### ISSUE TITLE
Vehicle doesn't stop at Loading Trigger

### ISSUE THREAD

**Issue by gabriel170603** [Courseplay/courseplay#3186]
When having a Course on Mode one to load grain at the silo, and drop it off at "sellpoint" the vehicle doesn't stop at the Loading Trigger to Load the trailer. 
Having the issue on .00054

**Comment by ThomasGaertner** [comment]
can you make at least a screenshot of the situation ?

**Comment by tjBerlin** [comment]
See #3170, maybe that helps.

**Comment by gabriel170603** [comment]
https://imgoat.com/uploads/84b6fbb107/195321.png
https://imgoat.com/uploads/84b6fbb107/195322.png
https://imgoat.com/uploads/84b6fbb107/195323.png

**Comment by gabriel170603** [comment]
![farming simulator 19 10_02_2019 11_55_18 pm](https://user-images.githubusercontent.com/47365537/52532884-73a14480-2d90-11e9-8f1f-360e4a51715a.png)
![farming simulator 19 10_02_2019 11_55_57 pm](https://user-images.githubusercontent.com/47365537/52532885-73a14480-2d90-11e9-8e07-23485a5bd444.png)
![farming simulator 19 10_02_2019 11_56_05 pm](https://user-images.githubusercontent.com/47365537/52532886-73a14480-2d90-11e9-8208-f03daff96232.png)

The vehicle is driving with the trailer under the loading trigger but is not stopping to load

**Comment by Messy71** [comment]
I don’t know if it’s same/similar problem but when i set up a course for lime spreading in Fertilize and Seeding mode and append the refill course at the end  it doesn’t drive the second course and says “ work tool needs to be refilled”.
If i load only the refill course  and start it in Grain transport (Mode 1) it drives the course but doesn’t refill ( folded tool , cover opened).
If i start it in Fertilize and Seeding mode  first waypoint at the lime silo it unfolds the tool and says “ work tool needs to be refilled”. ( same thing happens in both cases when first waypoint of the refill course it’s on the field)

**Comment by sootysax** [comment]
#3179

**Comment by ThomasGaertner** [comment]
@gabriel170603 :cant replicate it, do you have the savegame and course for me ?
@Messy71 : its not the same issue
but please test it with v56 before 

Thanks

**Comment by bawi81** [comment]
Ich hatte genau das selbe Problem. Mit dem neuem Update geht es bei mir wider mit dem aufladen von Getreide :+1:

**Comment by Messy71** [comment]
It works ( with Courseplay v6°01°00056 / FS v 1°3°0) but sometimes it's hard to make it work.
You have to start the course recording aligned with the pipe of the silo
 and in the center (front to back), 
drive at a relative slow speed (5kph),
speed up (the fastest you can manage to keep it on the road, because if you change the speed to maximum it messes up with the triggers {loading/unloading}).
Once you arrive at the unloading point start driving at 5 kph before the front of the tractor/truck it's 3-4m before the unloading grill,
keep that speed until the end of the trailer it's 3-4m away from the grill.
Drive as fast as you can manage towards the silo and when you are near it drive again at 5kph until you are about to hit the start point of the course hit the brakes(at this point the trailer should be under the pipe) and end course recording.

PS:
In the Settings Combi Mode you should have Start at: 0%, Drive on at:100%, Refill until: 100% (not sure if it changes something didn't test it yet)
In the Speed limits menu, Speed : from recording (**if you change it to maximum and change the street speed limit to a speed lower then the max speed that you recorded your course, it will stay at that speed when you change back to _Speed: from recording_**)
For the triggers at the silo/selling point you can change in the
Driving settings Menu the Load/unload/wait offset vertical [front<->back] to change the positioning of the trailer triggers **(helps if doesn't load/unload)**

**Comment by gabriel170603** [comment]
@ThomasGaertner I can give you the save game later, but how can I give you the course? Never did that before...

**Comment by PromGames** [comment]
Just look where your savegame folder are and zip the content of the courseplay-courses folder. That's what needs thomas

**Comment by gabriel170603** [comment]
[Savegame gabriel170603.zip](https://github.com/Courseplay/courseplay/files/2849814/Savegame.gabriel170603.zip)
[Courseplay Courses gabriel170603.zip](https://github.com/Courseplay/courseplay/files/2849815/Courseplay.Courses.gabriel170603.zip)

**Comment by Danatru** [comment]
I don't know if this is related but for me with Grain Transport mode (been using courseplay since FS15) is that you CAN NOT start a Grain Transport course at the first way point, because it will do an empty run and start filling the next time it comes to the silo. If you've just recorded the grain transport course, back up your vehicle a little bit so you're behind the last waypoint and then start at nearest waypoint, not first waypoint.

**Comment by sootysax** [comment]
https://gist.github.com/sootysax/e275106f72b04f27defe100d74422388

![fsscreen_2019_02_11_14_31_11](https://user-images.githubusercontent.com/6591048/52588144-d125a780-2e09-11e9-972c-e009aaf5f09d.png)
![fsscreen_2019_02_11_14_31_16](https://user-images.githubusercontent.com/6591048/52588155-d551c500-2e09-11e9-9714-38d14ebb57eb.png)

**Comment by gabriel170603** [comment]
As far as I know is that problem with the new update solved. I hope everybody is alright with closing that issue now.

**Comment by GeorgeEarslight** [comment]
I wasn't able to make a loading course on Marwell for the life of me, but v000069 did it. Thanks @ThomasGaertner .

**Comment by Markojag27** [comment]
Hi
I have this kind of problem with modded silo. However if i manage to click R while the trailer is under pipe, tractor stops and wait until trailer fill up.
