### ISSUE TITLE
Sugar Cane harvester drives on too early after turn

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/courseplay#3195]
Hello,

Map. Felsbrunn
Mod: Only Courseplay and refillable silos from the mod hub
Version of Courseplay: 6.01.00057
Version of FS: 1.3.0
Log: https://gist.github.com/StefanBraun2001/0b353b46378b03b826ceb3835bb8d8df

When sugar cane is being harvested at the end of the field the combine and the tractor with trailer in mode 2 starts to turn. The combine turns faster than the tractor. The tractor drives backwards, the combine drives on a few meters and stops. Then the tractor reached the fiel end he countine driving next to the combine. It takes about 5-10 seconds until the trailer is below the pipe of the harvester. The harvester don´t wait and is driving on while the trailer is not below the unloading pipe and so you are loosing sugar cane. I took the big sugar cane harvester (Case IH Austoft) Why does the combine not wait for the trailer?

**Comment by Messy71** [comment]
@StefanBraun2001 since the harvester doesn't have any capacity it unloads continuously  (it has an attache point for a trailer), the tractor with trailer isn't able to do such a tight turn at the speed of the harvester or a bigger speed.
The wait for trailer to unload mode isn't implemented yet (don't know if it will be) but the developers are trying to resolve the issues with modes 1,4,6 then will work on the other features of Courseplay.

**Comment by pops64** [comment]
This sounds like the specialtools file needs the XML name changed for this tool as there are some key variables that change the turning behavior that aren't turned on unless the XML file name is correct.

**Comment by ThomasGaertner** [comment]
#3140
