### ISSUE TITLE
Stuck in Traffic (LOG) with parking Car

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#3196]
Hi,
On my selling Course the Tractor stops and says Stuck in Traffic where is no traffic.
Ill take a wild guess and say ist the parking cars at this Point of the Map.

Screenshot:
![screenshot 2019-02-10 18 05 27](https://user-images.githubusercontent.com/47121919/52536735-cd891680-2d5e-11e9-9d7e-8bb778a53bf8.png)

LOG:
https://pastebin.com/86EJ3ahU

Greetings 
Markus

**Comment by Karlshoj** [comment]
For me the issue seems to be solved by v57. Thanks

**Comment by Mannelig83** [comment]
i already use v57.
Thanks for the hint anyway

**Comment by pvajko** [comment]
Since I have no more time this weekend for fixing (let alone testing) CP, stopping on traffic collision is now disabled by default, message will still display. 

If you want to play with it, turning debug channel 3 on will enable stopping on traffic again, if you then bump into problems please open an issue.

**Comment by ThomasGaertner** [comment]
try again with v00062 or higher and report

**Comment by Mannelig83** [comment]
Tested same Course and same tractor and it worked like a charm.
This issue seems done.

Thanks dude.

Greetings
Markus
