### ISSUE TITLE
Suggestion: Disable Steering Back Speed for vehicles Courseplay is currently driving.

### ISSUE THREAD

**Issue by Goof245** [Courseplay/courseplay#3299]
As in the title, vehicles seem to have a much easier time navigating their turns when steering back speed is at 0%. When it's on, the tractor is constantly fighting courseplay trying to straighten out the wheels, causing missed turns and infinite circles on tracks that otherwise work well.

If there's a way to disable or bypass it per - tractor instead of just disabling it globally I'd be very happy, as I use it while driving machinery around manually. Having to drive without it on every time I need a CP worker active is painful to say the least...

**Comment by pops64** [comment]
That setting shouldn't effect CP at all. If you're talking about the wheels recentering when turning that is due to another cause. The turns are made up of many waypoints and it is always driving towards. Which means the closer it gets to it the straighter the wheels are. Then the tractor reaches a point where CP updates the next waypoint where it causes the tractor to turn to that point. That is why the wheels flick back and forth.

**Comment by Goof245** [comment]
So why does the flicker stop when steering back speed is disabled?

**Comment by pvaiko** [comment]
@Goof245 so do you have a savegame and a course set up to demonstrate this working fine with 0% and circling infinitely with another setting?

**Comment by Goof245** [comment]
Hmm, seems to be ExtendedVehicle's difflocks causing it, doesn't happen without them on...
