### ISSUE TITLE
Question about aiTrafficCollisionTrigger

### ISSUE THREAD

**Issue by Mannelig83** [Courseplay/courseplay#3302]
Hello,
on some Vehicles (mods and Vanilla ones) i get the message:
aiTrafficCollisionTrigger missing. Traffic collision prevention will not work!

My Question is:
What is the result of this? Does it just matter with AI Traffic or does it include other courseplay traffic?

And Second:
The missing triggers are they a Courseplay Thing or a Vehicle Thing?
Can they Maybe implemented by myself?

Thanks and sorry that i have opened a issue for that but im curious

Greets
Markus

**Comment by ThomasGaertner** [comment]
i'm currently working on a solution for #3239 which should also be suitable for vehicles without own trigger . the missing triggers are a vehicle  thing: whether they are not, where we expect them to be or they dont exist. for us its the same result... I will close here to keep the issues clean

**Comment by haamic** [comment]
Hello,
i have fetched a mod from FS17 to FS19 and i also have the error message
 **## Courseplay: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work**
What do I have to do on the vehicle or what is still missing so that the fault disappears?
Greetings Micha
+++++++++++++++++++++++++++++++++++++++++++++++++++
Hallo,
ich habe einen Mod von LS17 nach LS19 geholt und habe auch die Fehlermeldung:
 **## Courseplay: aiTrafficCollisionTrigger missing. Traffic collision prevention will not work**
Was muss ich am Fahrzeug machen, bzw. was fehlt noch, damit der Fehler verschwindet?
Gruss Micha

**Comment by haamic** [comment]
done..... my trigger was called "trafficCollissionTrigger", after renaming it to "aiCollisionTrigger" the error disappeared.
+++++++++++++++++++++++++++++++++++++++
erledigt...... mein Trigger hiess "trafficCollissionTrigger", nach umbenennen in "aiCollisionTrigger" ist der Fehler verschwunden.
