### ISSUE TITLE
About mode 1 and liquid transport

### ISSUE THREAD

**Issue by Innallas** [Courseplay/courseplay#3343]
I just want to say that it's perfectly working, i looked the code and the huge difference in FS19 is that even liquid are considered as a fillType like any other bulk for all trailers, so it's perfectly working with mode 1, there are no need to keep mode 8 by example i think. I'm refilling all liquids and transporting/refilling slurry without troubles. 

It's just with the current master code > there is a problem who make the tractor to keep moving forward and discharging even on the ground if he can ! It also do this with some tippers who have unloading on side.

**Comment by ThomasGaertner** [comment]
@Innallas : mode 1 is : transport from A to B , mode8 is: transport liquids, from A to B or to a wait point and wait there till i'm empty, maybe we have to force the filling of the liquid taking vehicle. I don't know yet because mode 8 is not ready yet !
And congratulations, you are the first tester, we are asking NOT to contribute something to the development. your comments are not useful and your pull requests are not as well.
You're binding resources and wasting time. Sorry for that clear words. I and other guys tried it nicely more than one time, but it had no influence of your behavior.
