### ISSUE TITLE
2nd harvester does not "turn on field"

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#3382]
https://gist.github.com/sootysax/d25ba5059f96bb847c45ee8c4cada29d

The first harvester complies with the 'turn on field' setting and turns correctly.. 

![fsScreen_2019_03_09_14_37_44](https://user-images.githubusercontent.com/6591048/54076384-2b831e00-4279-11e9-853e-3359b307a31f.png)

The second harvester will not comply with the setting, and crashes into the fence.
![fsScreen_2019_03_09_14_34_18](https://user-images.githubusercontent.com/6591048/54076386-350c8600-4279-11e9-9435-1a7898eda60c.png)

Incidentally, the 'Opposite Turn Direction' seems to have no effect at all in any fieldwork course.. but maybe a seperate issue.

**Comment by sootysax** [comment]
ALSO:  on the other side of the field, the 2nd (right offset) harvester is not even generating a turn event and just curves around the turn and misses crops.

![fsScreen_2019_03_09_14_46_13](https://user-images.githubusercontent.com/6591048/54076503-60dc3b80-427a-11e9-885c-ed85bf425e23.png)
![fsScreen_2019_03_09_14_46_21](https://user-images.githubusercontent.com/6591048/54076511-6fc2ee00-427a-11e9-8813-5283c0e981d8.png)
![Uploading fsScreen_2019_03_09_14_46_28.png…]()

**Comment by pvaiko** [comment]
For your first issue it is difficult to tell what's going on as your working example is performing a different turn. It would be interesting to see what the first harvester did at the exact same turn.

You second issue has no log.

**Comment by w20101418d** [comment]
Same problem
The second tool did not turn at the edge of the field
![Farming Simulator 19 Screenshot 2019 03 15 - 23 10 46 50](https://user-images.githubusercontent.com/48384456/54441985-c51a6600-4778-11e9-930a-76eefbbbe6e7.png)
![Farming Simulator 19 Screenshot 2019 03 15 - 23 11 46 58](https://user-images.githubusercontent.com/48384456/54442036-db282680-4778-11e9-85fc-3cc46e26ff38.png)

**Comment by w20101418d** [comment]
@pvaiko
[log.txt](https://github.com/Courseplay/courseplay/files/2971872/log.txt)

**Comment by Tensuko** [comment]
Both Harvesters always generated a turn for me on all sides of the Field. (your 2nd Issue, pls try again with higher version).

The Option 'Turn on Field' got no impact on this. (Guess cause of Headlands, haven't tested all situations yet).

The Problem is, that the wide turn is basically 3 rows ahead. (unless you change the symetric lane switch).
That means he perform a turn with more distance, as he don't have to back up.
The Problem now is your Field Angle. One more Headland could solve this.

![fsScreen_2019_04_05_14_38_11](https://user-images.githubusercontent.com/27344744/55630628-6a43bf80-57b6-11e9-88b8-ed7272a84094.png)
![fsScreen_2019_04_05_14_39_12](https://user-images.githubusercontent.com/27344744/55630629-6a43bf80-57b6-11e9-9c47-851870dc933f.png)

**Comment by Tensuko** [comment]
Outdated.
If still got Issue, make new one.
Closed.
