### ISSUE TITLE
mode 2 combine unload to trailer

### ISSUE THREAD

**Issue by fudoido** [Courseplay/courseplay#3418]
hey guys.
Testing in map "Rolling Hills", but dont think map has anything to do with it.
Using combine case 9240 and grain header, man tgs 18.500 + krampe ks950
When truck approaching combine, it doesnt auto adjust to pipe exaust, staying just a litle asside of the header but in the space between header and pipe exit, making it so that combine is unable to unload into trailer since its not properly lined up with discharge point.
Did test also with bison combine, fiat tractor and a smaller trailer and same issue happens, the pipe goes to the left limit of the trailer out of discharge position and doesnt unload.
only way at the moment is to set the distance manually.
using latest version as of this moment, 132.

Also tryed to send and recall driver from combine menu several times and it never adjusted properly.
Didi this option because i remember in a older version this issue would happen only on 1st time approach to combine, working on 2nd and following approaches, but now it keeps always out of discharge position all the times.

**Comment by StreelRodent** [comment]
I've had the same problem, but someone else already reported it so didn't bother bringing it up. At the moment CP seems to decide its position relative to the edge of the header, which doesn't work with the big case harvester because it has an extended pipe. It's a similar problem with all the smaller combines (under 9 meter) where the only available corn/sunflower headers are smaller than the regular headers - because it sets the position relative to the header instead of the machine, the unloading vehicle ends up being too close.

**Comment by fudoido** [comment]
i tryed to search an open issue about it but didnt find one, so i started this one. if repeated, my appologies.

**Comment by sootysax** [comment]
@fudoido #3311

**Comment by fudoido** [comment]
ok got it. going to sub that topic in hopes of solution updates.
Thanks @sootysax
