### ISSUE TITLE
fahrzeuge 

### ISSUE THREAD

**Issue by jan1609** [Courseplay/courseplay#3453]

**Comment by jan1609** [comment]
fahrzeuge fahren im abfahr modus immer über den haufen. als bleiben nicht hinter  einander stehn.der zweite  dritten immer weg. und auch auf dem feld fahrn sich immer über den haufen.
und frage wann kommt der überlade modus.

**Comment by Chris2996** [comment]
Answer in german bc i think he wouldnt understand otherwise.

Moin Jan, wie du vielleicht gesehen hast ist dieses GitHub Repository englischsprachig. Darum sind die Isses auch auf Englisch einzureichen Weiterhin ist es wichtig eine vernünftige Problembeschreibung zu liefern. Infos dazu findest du hier: https://github.com/Courseplay/courseplay/wiki

Ohne Infos zu Version, deinen Einstellung, etc. (am besten inklusive Screenshots) und einer **ausführlichen und verständlichen** Erläuterung wirst du hier entweder keine Antwort bekommen oder es wird dir niemand helfen können.

**Comment by Tensuko** [comment]
Überlademodus komm später.
Genauso wie Kollisionserkennung.
CP ist aktuel noch Beta, also etwas geduld.
Benutze solange nur ein Fahrzeug pro Feld.

Da dies keine Fehlerreport ist close pls.
