### ISSUE TITLE
Saved Course Menu: Course Loading

### ISSUE THREAD

**Issue by Tensuko** [Courseplay/courseplay#3465]
Hard to get a Titel for this:
In Course loading Menu, you can add Course together by clicking the Folder without the +
So the Folder with and without got no difference.

**Comment by Scaracuila** [comment]
Hi Tensuko,
do you mean putting courses together with and without +?
There is definitely a difference, but the crossing points of the courses must be set correctly! For example, I only drive on the maps the basic courses, in addition the field accesses to the basic courses, sales points of the basic courses and of course also the courses on the farm (bunkering, seed and fertilizer fill up, Animals feeding...)

From these courses I merge on some maps partly over 20 courses!

For your understanding: 
the folder with the + means: add the course behind the existing one.
the folder without + means: merge the course with the existing one (this requires the correct crossing points)

Hope I could bring that a little bit closer to you, otherwise I can also upload you a version of my CP courses with an explanation!
 
Best

**Comment by Tensuko** [comment]
I never saw it work like this at least for me.
Normal load always overwrite the current loaded course, the one with + add the course at the end, yes.

**Comment by Scaracuila** [comment]
I can give you courses from Kandelin or FlusstalXXL and give you a sample list!

**Comment by Tensuko** [comment]
Ok, this was my bad I think.
I guess I always deleted course before I load a new one and just today after all this hours it happend that I merged the course. 

My Bad! I guess I am getting old...
