### ISSUE TITLE
Error: Running LUA method 'update'

### ISSUE THREAD

**Issue by VinDivertido** [Courseplay/courseplay#3466]
CP Stops all Vehicles 
[log.txt](https://github.com/Courseplay/courseplay/files/3000287/log.txt)
what can i do?

**Comment by Hovan** [comment]
I have a similar problem but I get warnings instead. Moved courseplay out of mod folder and the warnings were gone moved it in again and they are back.
[log.txt](https://github.com/Courseplay/courseplay/files/3000841/log.txt)

**Comment by ThomasGaertner** [comment]
@Hovan : please update to current version
@VinDivertido : do yo  have slightly more details for me like map, tools situation .....

**Comment by Hovan** [comment]
Thanx for your help Thomas, now log is error free.

**Comment by Th301** [comment]
Since some versions I have the same problem.

My log is full of this lines:

2019-03-29 17:20 Error: Running LUA method 'update'.
2019-03-29 17:20 C:/Users/stefa/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay6/combines.lua:50: attempt to index local 'fieldData' (a nil value)

These are repeating at least 100 times per minute in the log.

I would not really care about the error in the log but it crashes the game. Everything stops and I cannot move the camera anymore. It looks as if I can save the game but it is a fake. Everything what happend from the moment the error occures is lost. In some situation I even think, that the minute before the game freezes is lost too.

I would have postet my log but it seems as if Gist does not accept any content at the moment.

**Comment by VinDivertido** [comment]
@ThomasGaertner Hi I'm sorry to answer so late. I wanted to be able to reproduce the mistake. The logged LUA error always occurs when a mission is completed and the driver returns to the field for transport. The mistake also makes all vehicles uncontrollable. The problem I'm going first in which I store the crop in the yard silo between. The error is stopped when I dismiss the corresponding driver. Danke. MfG Vin

**Comment by Th301** [comment]
After some additional tests, I think VinDivertido is right. In my case, it was always a combine finishing a mission when the game crashed.
I finished it without cp and now everything is working fine again :)

**Comment by ThomasGaertner** [comment]
try with V.157 let the mode2 driver wait on the field while the combine is finishing the contract work

**Comment by Th301** [comment]
Working fine, thanks !!

**Comment by Tensuko** [comment]
Closed.
