### ISSUE TITLE
Abfahrer erkennt Fülltyp nicht 

### ISSUE THREAD

**Issue by Hendirk** [Courseplay/courseplay#3483]
Was muss ich da machen
Ich wollte das Silo leer fahren und habe Füllart Weizen eingestellt und vor dem Silo sagt der Abfahrer Fülltyp nicht vorhanden obwohl Weizen im Silo ist
Als Courseplay ist Beladung am Startpunkt eingestellt, was auch immer funktioniert hat, nun funktioniert ist nicht mehr und ich habe Patch 1.3 installiert!
![fsScreen_2019_03_23_21_21_25](https://user-images.githubusercontent.com/47453761/55006543-34e0ea00-4fde-11e9-8924-21276152a655.png)

**Comment by ThomasGaertner** [comment]
#3473

**Comment by ThomasGaertner** [comment]
please update to the current version and try again...

**Comment by andreasthu** [comment]
ok, neuer thread,
bei mir auch so ähnlich:
![fsScreen_2019_03_26_17_02_32](https://user-images.githubusercontent.com/24860501/55013272-116f6c80-4fe9-11e9-9411-6ab2d5f341cb.png)
habe die v6.01.0150
wenns an den Dünger u. Saatgutsilo liegen sollte, die stehen da schon seit Dezember 2018 dort und CP hatte mit denen noch nie probleme, kann die version nichtmehr genau sagen, denke, das letzemal hab ich mit v6.01.0143 oder so etwas diese Kurse gefahren, da funktionierte alles bestens.
google translate:
have the v6.01.0150
if the fertilizer u. Seed silo should be issue, they are there since December 2018 there and CP had never had problems with those, the version can not say exactly, think, the last time I drove with v6.01.0143 or something these courses, because everything worked fine.

lg
andreas

**Comment by ThomasGaertner** [comment]
could you give me the savegame ?

**Comment by andreasthu** [comment]
i hope, this work with this drive google link:
https://drive.google.com/drive/folders/13nxOYzeH58Lwv3o0XeP_uHOsJWgr4mYV
filehorst is broken now, ev later i can upload on filehorst
lg
andreas

**Comment by Hendirk** [comment]
Gesendet von Mail für Windows 10

Von: Thomas Gärtner
Gesendet: Dienstag, 26. März 2019 20:58
An: Courseplay/courseplay
Cc: Hendirk; Author
Betreff: Re: [Courseplay/courseplay] Abfahrer erkennt Fülltyp nicht (#3483)

could you give me the savegame ?

**Comment by andreasthu** [comment]
so, here is a new uplaod,from File-Upload.net:
https://www.file-upload.net/download-13551163/all_you_need.zip.html
savegame, map, mod and pic with courses
the Steyr, JohnDeere and MAN are ready with mode1 courses
lg
andreas

**Comment by ThomasGaertner** [comment]
test with v.153 or higher ...

**Comment by andreasthu** [comment]
> 
> 
> test with v.153 or higher ...

yes, it works now here:
![fsScreen_2019_03_28_09_57_56](https://user-images.githubusercontent.com/24860501/55144171-80aba480-5140-11e9-9612-8d9bd3434984.png)
![fsScreen_2019_03_28_09_59_15](https://user-images.githubusercontent.com/24860501/55144174-82756800-5140-11e9-8b11-66ef3f013343.png)

and by you, @Hendirk ?

lg
andreas

**Comment by Chris2996** [comment]
Fixed with v.153

**Comment by Tensuko** [comment]
Closed.
