### ISSUE TITLE
Feldhäcksler arbeitet nicht in Mode6

### ISSUE THREAD

**Issue by Autobosl** [Courseplay/courseplay#3489]
Gerade wieder mit Version 6_1_153 getestet.
Original Ravenport Map.
Feldhäcksler auf Feld 8 mit Mode6 eingestellt.
er startet ganz normal. sobald der erste Abfahrer voll ist und der zweite zum Beladen heranfährt wird ohne zu Ernten weitergefahren.

**Comment by Autobosl** [comment]
![fsScreen_2019_03_27_19_28_01](https://user-images.githubusercontent.com/26477352/55104091-02acb680-50ca-11e9-9fcd-067cc2a16552.png)

**Comment by Scaracuila** [comment]
please read the Wiki first

[](https://github.com/Courseplay/courseplay/wiki)

Wenn du ein Problem mit dem Englischem hast, dann benutze deepl (ist deutlich besser als Google translator!) - der kann dir auch das Wiki übersetzen!

Now to the problem:

this is only since version 6.01.00145, I think it has to do with implementing the auto engine stop/start regarding suggestion #3379! The engine starts and the harvester begins to drive, but the working mode is not activated.

In version ...144 the harvester was still running permanently in working mode.

Here is my log:
[log.txt](https://github.com/Courseplay/courseplay/files/3015329/log.txt)

Hope this helps...

**Comment by turbodani** [comment]
Hab das selbe Problem mit der aktuellen Version - kann es allerdings "umgehen", indem ich den Kraftstoffsparmodus deaktiviere. So bleiben der Motor UND der Arbeitsmodus aktiviert.


Grüße

**Comment by Lustiger-Hubi** [comment]
Haste schon mal selber in deiner Log geschaut?
Warnungen ohne ende
sogar LS 17 noch drin
Mod loaded: Kandelin by LS17 Projekt ??????
Mach mal alle mod´s mraus und probiere dann nochmal & zeige uns dann mal die log
Danke

**Comment by Lustiger-Hubi** [comment]
Ich habe das jetzt mal getestet
und Autobosl hat recht
wenn der zweite Abfahrer kommt fährt der Häcksler
ohne zu hexsel weiter! 
[log.txt](https://github.com/Courseplay/courseplay/files/3025759/log.txt)

**Comment by Tensuko** [comment]
Funktioniert das jetzt ?
Eine Rückmeldung wäre ganz nett!

**Comment by Lustiger-Hubi** [comment]
Sorry war nicht online, gerade gesehen & schon getestet!
Alle super Funktioniert jetzt!!
Danke

**Comment by Tensuko** [comment]
Suppi, dann kann das ja zu. Closed.
