### ISSUE TITLE
 Error: addRequiredCropType foliage must match the size of the ground terrain detail.

### ISSUE THREAD

**Issue by Fumbi3** [Courseplay/courseplay#3503]
Hallo ich bekommen diesen  Error: addRequiredCropType foliage must match the size of the ground terrain detail. wenn der Drescher den befehl gibt das der abfahrer zu ihm fahren soll.
und der error wiederholt sich ständig

**Comment by Tensuko** [comment]
Komplettes logfile bitte anhängen.
Einfach die log.txt per Drag and Drop in den Kommentar ziehen.

Bei welcher aktion ist der Fehler denn aufgetreten ?

**Comment by Fumbi3** [comment]
beim dreschen von Raps

[log.txt](https://github.com/Courseplay/courseplay/files/3026488/log.txt)

**Comment by Fumbi3** [comment]
Also der Fehler ist aufgetreten wo der Drescher bei 80% Korntankvolumen den Abfahrer ruft bzw. wenn der Abfahrer das Signal bekommt das er zu Drescher fahren soll

**Comment by Tensuko** [comment]
Aktualisiere mal CP auf die neueste Version und probiere es noch einmal:
https://github.com/Courseplay/courseplay/releases/tag/6.01.00157

**Comment by Fumbi3** [comment]
ok probiere ich

**Comment by Fumbi3** [comment]
so habe es ausprobiert und der fehler kommt wieder 
[log.txt](https://github.com/Courseplay/courseplay/files/3026497/log.txt)

aber mir ist gerade auch aufgefallen das der Abfahrer den Motor nach einer gewissen zeit ausmacht wenn er wartet bis der Korntank des Dreschers bei 80% ist. er schaltet zwar den Motor aus aber der Motor stottert so komisch hört sich zwar komisch an aber das ist mir auf gefallen

**Comment by Tensuko** [comment]
Könnte noch mit der Map zusammenhängen:

2019-03-31 12:52 C:/Users/Jan Gluttig/Documents/My Games/FarmingSimulator2019/mods/FS_19Kandelin/maps/newFruits/foliage/barley.i3d (18.55 ms)
2019-03-31 12:52 C:/Users/Jan Gluttig/Documents/My Games/FarmingSimulator2019/mods/FS_19Kandelin/maps/newFruits/foliage/alfalfa.i3d (9.09 ms)
2019-03-31 12:52 C:/Users/Jan Gluttig/Documents/My Games/FarmingSimulator2019/mods/FS_19Kandelin/maps/newFruits/foliage/spelt.i3d (15.85 ms)
2019-03-31 12:52 C:/Users/Jan Gluttig/Documents/My Games/FarmingSimulator2019/mods/FS_19Kandelin/maps/newFruits/foliage/millet.i3d (2.12 ms)
2019-03-31 12:52 C:/Users/Jan Gluttig/Documents/My Games/FarmingSimulator2019/mods/FS_19Kandelin/maps/newFruits/foliage/poppy.i3d (7.48 ms)

**Comment by Fumbi3** [comment]
OK aber es gibt doch jetzt schon viele karten mit neuen Früchten in LS19 sonst währe ja bestimmt schon bei den ein oder anderen der fehler aufgetreten oder liege ich dort falsch

**Comment by Tensuko** [comment]
Ja schon, schließt aber nicht aus, dass bei der Kandelin etwas falsch oder anders gemacht wurde als bei anderen Karten.
Muss auch nicht das Problem sein, aber es geht ja um foliage, liegt daher nahe.
Kenne mich da auch nicht so gut aus, aber man muss halt ausprobieren und schauen worann es liegt, habe die Karte aber (noch) nicht.

Mal sehen ob @ThomasGaertner das besser weis :)

**Comment by Fumbi3** [comment]
OK danke dir den Warte ich ThomasGaertner dazu sagt

**Comment by Fumbi3** [comment]
Hallo habe Fehler kommt auch nach einer gewissen Zeit ob wohl kein Abfahrer eingestellt ist (Combi-Modus)

**Comment by Ralleran** [comment]
Hallo gibt´s schon was neues? Bei ist der Fehler auch aufgetreten.. auch auf der Kandelin map

**Comment by Tensuko** [comment]
Wenn es etwas neues gibt, wirst du das schon mitkriegen.
Momentan wird an anderen Dingen gearbeitet, da muss man erstmal abwarten.
Allerdings ist der Fehler bei mir noch nicht aufgetreten, daher schwer nach zu vollziehen, worann es liegt.

Da jetzt schon 2 mit der Kandelin Map den Fehler haben, liegt es nahe, dass es doch an der Map liegt.
Auf der Provance habe ich den Fehler noch nicht gehabt...

**Comment by stangman04** [comment]
I have had this error too. This is on Kiwi 4x map. When using courseplay for combi mode to empty my combine. I tried again today without using courseplay and just running Followme mod next to my combine without issue. Attached my log file last time I used courseplay. This issue causes my game to freeze for about 5 seconds or so.
[log.txt](https://github.com/Courseplay/courseplay/files/3050943/log.txt)

**Comment by Tensuko** [comment]
Like I guessed. It is the extra fruits.
But when this is related to Mode2, that wont get fixed now.
Going to make a test on Suedhemmern Multifruit with Mode2.

**Comment by Tensuko** [comment]
Didn't get the Error with a ModMap Fruit and old Mode2 used.
Is Kandelin a 4x Map just like the Kiwi Map ? Maybe there is the issue ?

**Comment by stangman04** [comment]
If a map was the issue wouldn't this issue persist with courseplay not running? I played last night without courseplay and no errors in my logs. Normally this error is for incorrect sized textures within the files (not 4096x4096 or something like that). 

I suspected the map too until someone on facebook said they didn't have this issue and to check my mods. AIVehicleExtension has caused me issues recently while that has been worked on and the mod creater has resolved those issues, so suspecting that I disabled that mod and it remained.

I also checked the map and it appears the AI does not plant the new crops in unowned fields and my only field had Canola in it. I was harvesting field 21 which was a contract to harvest Barley.

 I figured for grins I would rest without courseplay running my trailer in mode 2 since I was running the combine manually anyways and it was only happening while I was harvesting the field. I switched to use followme mode and that ran fine all night with no errors relating to this mod.  

If you would like to check the map I am using I can upload it somewhere if you wish from my mod folder. Here is the download link where I downloaded [Map](http://www.modhub.us/farming-simulator-2019-mods/kiwi-farm-starter-map-4x-multi-fruit-patch-update-1-3-v2-0/)

**Comment by stangman04** [comment]
Harvest time, decided to harvest my canola and use the courseplay for my trailer again in mode 2. Here is the log...

[log.txt](https://github.com/Courseplay/courseplay/files/3051750/log.txt)

**Comment by Tensuko** [comment]
I guess it is more a combination of things happening there.
Maybe CP use something, what the map don't have.
AI not planting crops on unowned fields is maybe something missing.
Conflict with the Contractsystem ?
It is enough when specific actions happen, that you get an Error.

Map Erros doesn't have to do anything with CP, even when only happens if CP is used.
Hard to tell what causes this Error. On my Provance map I don't get any Error with several Mods in it.

**Comment by stangman04** [comment]
> I guess it is more a combination of things happening there.
> Maybe CP use something, what the map don't have.
> AI not planting crops on unowned fields is maybe something missing.
> Conflict with the Contractsystem ?
> It is enough when specific actions happen, that you get an Error.
> 
> Map Erros doesn't have to do anything with CP, even when only happens if CP is used.
> Hard to tell what causes this Error. On my Provance map I don't get any Error with several Mods in it.


I only notice the error because in game when the fill limit is reached for the trailer to come to the combine (usually 80% or so) that is when I see a freeze for about 5 seconds or so which is probably when the errors are being written to the log. I am wondering if when the courseplay is triggered to drive to the combine if it reads the crops the trailer can fill hold or something and that has a problem with the newer crops or something? Maybe courseplay reads the crops as a standard size map texture but is actually on a map that has textures larger than what courseplay is expecting? Like I said I only notice the issue when courseplay calls the trailer to move in combi mode 2. Everything is fine when the trailer is sitting waiting for fill level to be reached.

Have you tried to replicate the error on a 4x map? Or on a map with new fruit? I would guess that could be a way to see what is causing the issue by eliminating factors whether it doesn't like 4x map texture sizes or if it doesn't like new fruits? 

In terms of gameplay

**Comment by Fumbi3** [comment]
Habe den Fehler gefunden und zwar sind die GDM-datein (cultivator_density) in der MapDE der Karte unterschiedliche Skaliert und damit kommt CP nicht klar
Habe alle GDM-datein der Karte auf der gleichen Größe angepasst und der Error ist weg

**Comment by stangman04** [comment]
> Habe den Fehler gefunden und zwar sind die GDM-datein (cultivator_density) in der MapDE der Karte unterschiedliche Skaliert und damit kommt CP nicht klar
> Habe alle GDM-datein der Karte auf der gleichen Größe angepasst und der Error ist weg

Interesting, in poking around (I needed to learn how to convert the gdm files into png to see the sizes).  I see the cultivator_density and the fruit_density being 8192x8192 in pixel size which should be for a 8x map..... Other files I am seeing are the correct 4096x4096 which appear to be correct. This may be a map issue but only courseplay has brought these errors out. I will tinker with these files tonight and see if that resolves the issue.

**Comment by ThomasGaertner** [comment]
CP benutzt hier einee standart Giants-Funktion: FieldUtil.getFruitArea() und die schmeißt den Fehler. so von unserer Seite ein klares can't fix ...

**Comment by stangman04** [comment]
> CP here uses a standart Giants function: FieldUtil.getFruitArea () and throws the bug. so from our side a clear can not fix ...

So sounds like if we are using a 4x or larger field we will have to live with the errors from this bug? Sigh

**Comment by Tensuko** [comment]
I guess the issue is found and this can be closed now.
Sry we cant do anything about it, but thats left to the mapper then.
Closed. #3503

**Comment by Trojaner77** [comment]
Hallo ich habe genau das Gleiche Problem nur allerdings nicht auf der Karte wo ihr die Probleme Habt sondern auf der MMMC Hatte Beide Mods Drauf (Neuste Version von CP und GPS) Ja der GPS Macht Probleme in denn Fahrzeugen die es verbaut haben und über CP gesteuert dann werden, Habe dann denn GPS bei mir Raus genommen und es Läuft Wunder Bar ;-)

**Comment by Scaracuila** [comment]
@Fumbi3 Hi, besteht die Möglichkeit die geänderten Dateien zu teilen? Ich bin schon an diversen Versuchen gescheitert...
Viele Grüße

**Comment by chroboss** [comment]
@Fumbi3 
Sorry, das ich den Thread nochmals aktiviere, Ich habe nun auch dieses Problem.
GMD, wo finde ich die und was genau ist zu verändern?
Wenn Du netterweise mal hier berichten möchtest, freuen wir uns sehr.
Herzlichen Dank.
