### ISSUE TITLE
Forage harvester does not wait for tractor

### ISSUE THREAD

**Issue by Crytiv** [Courseplay/courseplay#3574]
Hello,
First of all i would like to thank you for  your time and effort on continuing on developing this mod.
Now, ive encountered a couple problems while harvesting corn with forage harvester. As you can see in the first video, as soon as the pipe "acquares" the trailer while the tractor is driving backwards, the harvester starts driving forwards, not waiting until tractor is fully in position to follow. In the second video(sadly ony managed to capture the end of the maneuver) the tractor made a wide turn instead of backing up and the trailer was empty, so it could catch up to the harvester faster.
https://youtu.be/PCcHp5rAm0A
https://youtu.be/Yt7i0jAdjzQ

The second problem is not related to this issue and if needed ill create another post. While backing up with a standard tailer(not semi), the CP does not compensate for a trailer to go straight, instead its just backing up and gets stuck along with the trailer.
https://youtu.be/Szr49CPTM1k

**Comment by pops64** [comment]
1st problem is not a mode2 issue. The combine is driving away from the tractor before the pipe does anything. This is a problem with the refactoring of mode6. In 17 I encountered the same problem with sugar cane it was caused from this line of code found on line 611 of mode6 of the latest dev version of CP in 17.

`local ch, gr, sc = FillUtil.FILLTYPE_CHAFF, FillUtil.FILLTYPE_GRASS_WINDROW, FillUtil.FILLTYPE_SUGARCANE;
					if (tool.pipeParticleSystems and ((tool.pipeParticleSystems[ch] and tool.pipeParticleSystems[ch].isEmitting) 
					or (tool.pipeParticleSystems[gr] and tool.pipeParticleSystems[gr].isEmitting)
					or (tool.pipeParticleSystems[sc] and tool.pipeParticleSystems[sc].isEmitting))) 
					or pipeState > 0 
					or vehicle.cp.turnStage ~= 0 then`

Quick search in combineAIDrive shows that this line is missing which is a crucial function of choppers for CP. Because the pipe may be in range of the tipper but that doesn't mean that the pipe is discharging to the tipper. The above code prevented choppers from moving in 17 until this occurs. I am not sure of the FS19 conversion for the pipeParticleSystems

**Comment by Crytiv** [comment]
Would it be possible to make and option to instead of backing up like this to the harvester, the tractor would do a turn ? This would solve the problem for collecting chaff with these kind of trailers.

**Comment by pops64** [comment]
The functionality is there #3578. Got removed in the HUD refactoring

**Comment by Tensuko** [comment]
I would still see this as a Mode2 problem, as the Harvester could wait, till the Mode2 Driver finished its turn. But actual (as far as I knoiw) is no Communication between those. Else you could just say, wait till Mode2 turn is done, then continue harvest, but thats not happening right now.

What you discribed is something else and also happens if the Mode2 driver is to far away from the Harvester, can easy reproduce by increasing the distance.

**Comment by pvaiko** [comment]
Number is a mode 2 issue of course.

Also, not really sure what the problem is with the chopper driving away from the tractor before the pipe does anything.  The pipe is not going to do anything until the chopper start moving and actually harvests some fruit.

**Comment by pops64** [comment]
It is an issue because of Giants Design. The pipe emitting distance is smaller than the pipe in range distance. And has shown in the video you also have to wait for the pipe to relocate the tipper. Then you add the fact the combines can accelerate faster than a loaded down tipper can. And you end up with about 3m or so of fruit that disappears into oblivion. I know this for a fact when I was fixing sugarcane for FS17 and came across this. And discover the above linked line was missing sugarcane

**Comment by Tensuko** [comment]
Two problems:

1) pipe range distance smaler then pipe emitting, as I said, can easy be recreated by increasing the distance

2) Mode2 does not communicate with the Harvester! Thats why the Harvester doesn't wait till the Mode2 Driver finished its turn. You can see that by turn on the debugchannel and look at what the Mode2 does on turn, and watch the Harvester start as soon as the Mode 2 is near. It is clear, that the Mode2 will finish his turn before start accelerate again to follow the Harvester. At the same time, problem number one comes in the case. While Reverse, Mode2 gets near the pipe emitting distance, and while Mode2 still reverse and Harvester starts, it stays in that distance for a while, untill the Mode2 Driver get back to the right position where the pipe is in range. If the Harvester would talk with the Mode2, you got to add a wait untill turn finish and wait for the Mode2 to be in Range, then Mode2 accelerate to max speed of Harvester workspeed and Harvester fallows that acceleration. All that is only doable, when Mode2 is reworked and back in action.

That is what I see and what should be done, from a none programming side.

**Comment by pops64** [comment]
You can't adjust number 1 as far as I know. And the above code would still need to be included cause your forgetting one information. That combine acclerates faster than the tipper. So the only choice would be to either spend a lot of time ensuring the new mode 2 would always be in range. Or the easier method of just putting a fail safe into mode 6 which is what the above line of code did in 17 and more than likely 15 and earlier

**Comment by pvaiko** [comment]
... or just look at the Giants documentation and see if there is a proper way to get that information instead of misusing the particle system? Have you tried for example getDischargeTargetObject()?

**Comment by pops64** [comment]
I look into it. It might still return false positives with respect to dischargeing into the tipper
