### ISSUE TITLE
Small issue : Fold implements before "Return to start"

### ISSUE THREAD

**Issue by Simon-AK** [Courseplay/courseplay#3739]
Not sure if it's an issue only on my side but, when a field work is done and my tractor return to start, it keep the implement unfold.
So let say a 20m cultivator returning to start across the field unfolded, it collide into my other tractor more often than not.
BTW thx for your awesome work, for me and a lot of us, Courseplay make this good game an incredible game. I would just not play this game without it.
Thx a lot

**Comment by FS19-CP** [comment]
I agree, on the return to first point when not going for refill... implements should fold on the trip to first point. I would also like to see the implements get folded upon completion of field work, as I tend to set up a series of courses... as in I can tab to a spreader, click stop driver, click transport, load a route to the next field, and click start. Manually folding the implement is an additional step, and it gets chaotic quickly if you forget to fold everything. Lol. I farm in a very fast-paced fashion, so any such streamlining is awesome to me.

Thanks guys... my opinions are the same, I would not play FS19 without Courseplay, and cannot wait to see the work that is being done on Mode 2! I've been contemplating creating a well edited FS video, showing a form of corn chopping that I have been a part of for many years IRL, involving a leapfrogging spiral-pattern, and a specific staging of "trucks," as well as teamwork of choppers. I don't know what you guys have planned for Mode 2, how far along you are, or whether the system I have in mind would be workable, but if any of the developers are interested in something like that, let me know....

**Comment by pvaiko** [comment]
@Simon-AK we are working on moving the 'return to start' option from the course generator to the driving options you can set on the fly.

Starting with 6.01.195, if you generate the course **without** the 'return to start' option, the vehicle will always return to the first point if the course started at the headland and will fold all implements.

**Comment by pvaiko** [comment]
@FS19-CP we are absolutely interested in advice based on real life experience as we want to make this as realistic as possible.

**Comment by FS19-CP** [comment]
Sounds good. I'll try to get something put together... I'll be working within the confines of the current Mode 2, so it may be interesting to get something edited that shows the function well, but I'll do my best. The system would work efficiency-wise with standard up/down rows, but it's not what is generally done.. what I have in mind would be more dependent on a spiral, or what you guys reference as "racetrack," so there may be too much dependance on what is generated or recorded as the harvesters course. Having said that, what I have been doing lately is recording a harvester course that includes realistic turns while cutting headlands.... going to the extreme of the corner, backing to align with the new direction, and continuing forward. Even with the current Mode 2, I can get the tractor to follow the harvester around such a corner, if he's on the outside, and the harvest course is recorded correctly(slightly turning in the new direction to prep the tractor, then backing/turning slowly to allow the tractor to maintain lock on the spout, so he follows when the chopper continues. The main issue currently is the untrustworthiness of the Left/Right harvester selection, or the pathfinding. The tractors always seem to find themselves in the fruit, which is nearly ALWAYS the inside of the turn currently. I would think it would be workable, if the following tractor could pick up on that corner, and was outside of the fruit as he should be... but the current course generator doesn't support such a backing turn, so it's manual recording only... which is far too variable for the end user. The headlands, or "opening" of the field, is generally a three or four pass job, with the tractor following directly behind for the first pass, and moving to the outside for the remainder. After opening the field, the first chopper would count rows down to select a chunk of the field, then "blow a hole" with the truck following directly behind once more... the harvester can then return to the starting edge and begin the racetrack pattern, with the truck switching sides everytime. When the truck is on the inside of a turn maneuver, it would turn away from the harvester, and stage up on the outside of the next pass... ultimately allowing space for the chopper to also stage, so they can keep moving... thus why there's three or four opening passes. Once that chunk is finished, another hole is blown and the process starts again. The idea, in practice, is that neither chopper or truck has to completely stop for any period of time. Corn harvests are often muddy... Corn fields are also planted in rows, and travelling across those rows is kept to an absolute minimum, so the trucks would always stay on the ends of the harvester passes, until they reach the harvester lane they are needed in... crossing up to another end for that purpose would be done in another lane not being used, and the staging truck following the truck being loaded would transpire on the 2nd to last pass, so he can follow through the last corner, and be ready to continue into the spout when the loading truck is full. Again, real life dictates keeping the machines moving as much as possible to minimize wear, cost, payroll, or harvest length... all applicable to the simulation, I feel.

I don't know. Lots of ideas, but I'm far from a developer... I'll try to "film" something that shows how a fieldwork design would work in practice. Thanks.

**Comment by FS19-CP** [comment]
PS..... the turn maneuvers of both the harvester and loading truck would, in theory, be on the exact same time scale... both arriving at the completion of their turns in sync. Not being a developer, I don't know of the challenge... but the truck would have to vary its speed depending on the situation. If he's on the outside, he would slow after the end of the pass, and SLOWLY begin turning as the chopper clears the way, then speeding up in such away to arrive at the chopper as he stages again. It would be opposite if the truck was on the inside... once the spout was empty, he would need to rapidly speed out of the way, get clear of the choppers path, then slow at the end of his staging on the next pass to allow the chopper to stage before they both continue at the harvest speed.

It sounds like a complicated set of code to me.... but that's the reality of corn harvest in my neck of the woods, and I would guess many others with square fields.

**Comment by pvaiko** [comment]
@FS19-CP thanks, very interesting, you may want to take a look at #3250 and #3282. 

A drawing or a video would be great especially to illustrate the pattern. 

Regrading the headland turn, we already have this: https://github.com/Courseplay/courseplay/issues/2242#issuecomment-324183586
it is just not used at the moment, maybe this is what you are describing.

**Comment by FS19-CP** [comment]
Nice! Everything you referenced is cool to see, you guys are working ahead of the ideas I have in my head, so that's exciting!

I have some chopper patterns worked up that runs them exactly as I would prefer, so I can simply follow in a tractor, and document a bit of how that pattern would operate for both machines... ironically enough, the chopper pattern I worked up works really well for the current Mode 2 even, as you can pick the correct side for the tractor, and he can stay there through the entire harvest... he just runs through the fruit on half the passes, but that's better than running through the chopper on almost every pass. Lol.

The headland turn is very similiar to what I've been recording, the only exception is that I'll have the chopper slightly turn in the new direction after passing the last of the fruit, back up turning the opposite direction, then turn back towards the fruit to finish the turn.... it minimizes the turning radius, while also minimizing how much the machine leaves the field. The header may run through the corner of the fruit while backing, depending on the turn, but that in itself is realistic with a chopper.... they're big machines. In turning situations that are too tight for even that(ditch tight against the field IRL) we would cut a pocket first like suggested in 3282, meaning the truck following directly behind would back up with the chopper, then move forward within that first cut as the chopper is turning into the new cut and straightening out... after that new cut, the truck would back again, the chopper would back in an s-curve, then stage in the new direction for the truck to pull up directly behind and start. I don't know if that's too complicated to implement with the chopper and tractor, but there is definitely some merit to cutting a pocket in the corners... for choppers and combines both.

I noticed last night, with the pattern I'm running, that even the pathfinding seems to begin functioning better... that gives me hope that I'm not being overzealous in wanting keep equipment out of each others way. I can see where an issue would come up though, in blowing the hole across the field, as there is nowhere for a truck to exit when he's full... except backing up the entire length of the field or cutting through the corn. IRL, we purposely open fields with the larger belt trailers, and clarify that one more pass will fit on the truck before beginning to cut a hole. I'm not sure if an algorithm could be developed that assessed how many liters are harvested on a pass in the same direction as the "hole," but.. if so.. the harvester could send the nearly loaded truck off, or just have him wait on the previous pass, if he doesn't have the room, to have an empty truck to make that opening pass. We do that at times.  IRL, we try to start with an empty truck, and use the skilled drivers... so we make the first pass with the truck following behind, spin the chopper around at the end, have the truck back up ALLLL the way across the field with the chopper on one side, then go back foward again with the chopper on the other side. You have a three pass hole, with the truck running over the same compacted track.  THAT sounds like too much stuff to even attempt on CP, but that gives you an idea of the types of things that are done to minimize truck movement. But, this is chopping thousands of acres of corn with three choppers and ten or fifteen trucks.... hardly a situation that most players find themselves in using courseplay.

I'll get a video for you, maybe give some ideas at least.

**Comment by Simon-AK** [comment]
Thx a lot for the quick answer and fix, wow.

**Comment by FS19-CP** [comment]
#3760....
