### ISSUE TITLE
Turn off windrower when turning.

### ISSUE THREAD

**Issue by Simon-AK** [Courseplay/courseplay#3744]
Haven't test all windrower but I think they're all the same.
When windrower turn, they raise but stay on, but when raised, it 's not high enough to not touch previously rowed grass (after a couple cycle of cutting), messing up already rowed line.
On the other hand, (not sure about this one, might cause issue) loading wagon do raise and turn off when turning, if they didn't, they could maybe pickup the grass that got pushed outside the field by the windrower at the end of a line.
Thx
Have a great day

**Comment by FS19-CP** [comment]
Your best bet, and the most realistic, is to run the windrower on your headlands last. 

In real life, you wouldn't kick your PTO out after every pass, you would just lift the rake, then your final pass on the outside would even out the ends and pull your turns out into the end. This is how I record or generate my raking courses... then I record a forage wagon course that picks up every bit of the windrows, starting with the outside, then working the field. There's no guesswork after you establish your courses that way, everything gets raked, and everything gets picked up.

**Comment by Simon-AK** [comment]
Nice tips, I'll try like this next time. thx
