### ISSUE TITLE
Mode 2: HUD verschwindet

### ISSUE THREAD

**Issue by stueja** [Courseplay/courseplay#3776]
Habe einen Kurs für Modus 2 eingefahren und gestartet, danach war das HUD weg und läßt sich bei diesem Traktor nicht mehr öffnen. Bei anderen Fahrzeugen geht das HUD nach wie vor.
[log.txt](https://github.com/Courseplay/courseplay/files/3172710/log.txt)

**Comment by Tensuko** [comment]
Ähnlich wie #3769 

Fällt eigentlich unter die Kategorie #3311 

Welches Fahrzeug war es denn in deinem Fall ? Das bitte immer mit dazu schreiben, wenn es bei einem Gespann passiert. Klingt für mich erstmal nach Mod Conflict/Mod Issue. Auch der eventuell eingestellte Drescher spielt eine Rolle.

**Comment by stueja** [comment]
Ah, vergessen. Alle Fahrzeuge waren Nicht-Mod-Fahrzeuge.
Drescher: MF Activa 7347S
Traktor: Valtra T.234
Hänger: Kröger Agroliner TKD 302

**Comment by game455** [comment]
Das Problem kenn ich auch mit Warrior und Krampe KS950-Anhänger.

**Comment by stueja** [comment]
Welche UserAnswer kann ich noch geben? :)

**Comment by Tensuko** [comment]
Hab nur noch kein Label für 'try to reproduce' oder sowas :)
Muss halt wenn ich zu Hause bin und Zeit habe mal gucken ob und wie ich das reproduzieren kann, bzw rausfinden kann, woran es liegt.
Es ist nicht auszuschließen, dass es durch andere fixes jetzt passiert und ob das nur in Mode2 ist, wenn ja wird man auf #3311 warten und dann alles auf den aktuellen Stand bringen.

**Comment by Tensuko** [comment]
Also ich hatte das Problem eben nicht.
Verschwindet das HUD beim Kurs erstellen oder Fahrer einstellen ?
Wenn bei Fahrere einstellen: Welche Fahrzeuge hast du in deinem savegame aktuell ?
Weil: Normal steht CP ja auf 'Automatisch'... wenn da jetzt ein fehlerhaftes Fahrzeug (Mit Abladerohr oder ähnlichem Trigger) auf der Map ist, könnte das eventuell für Fehler sorgen. Ist jetzt nur eine Vermutung, hab ehrlich gesagt kein Plan ob das sein kann :)

**Comment by stueja** [comment]
Den Drescher hatte ich manuell zugewiesen, meinst Du das, wo normal "Automatisch" steht? Und das HUD verschwand beim Fahrer einstellen. Beide Kurse (Drescher und Traktor) waren schon eingefahren.

**Comment by Tensuko** [comment]
Also ich konnte das gestern nicht reproduzieren, trotz meiner menge an Mods.

Hast du die möglichkeit, die gleiche Situation einmal ohne Mods im Modordner zu probieren?
Also gleiches Savegame (kannst es ja kopieren) ohne Mods laden und nochmal versuchen?

**Comment by game455** [comment]
Ich bin aber leider jetzt für 2 Wochen urlaubsmäßig außer Haus, so dass ich erst nach Rückkehr Zeit dafür habe.

 

Komischerweise ist nur einer meiner Warrior von dem Problem betroffen.

Das HUD-Problem ist schon seit mehreren Tagen an diesem einen Fahrzeug (von 3 identischen). Sobald CP aktiviert wird, verschwindet das Fahrzeug-HUD sowie auch das CP-HUD. D.h. wenn CP fährt, kann ich keine Einstellungen ändern und beenden geht auch nur mit Strg+7.

 

Ich melde mich, sobald ich wieder da bin.

 

Danke für deine/eure Arbeit – großartig

 

Gruß

Gerhard

Von: Tensuko [mailto:notifications@github.com] 
Gesendet: Mittwoch, 15. Mai 2019 07:49
An: Courseplay/courseplay
Cc: game455; Comment
Betreff: Re: [Courseplay/courseplay] Mode 2: HUD verschwindet (#3776)

 

Also ich konnte das gestern nicht reproduzieren, trotz meiner menge an Mods.

Hast du die möglichkeit, die gleiche Situation einmal ohne Mods im Modordner zu probieren?
Also gleiches Savegame (kannst es ja kopieren) ohne Mods laden und nochmal versuchen?

**Comment by Tensuko** [comment]
Könnte es sein, dass du mit dem einen Fahrzeug in einer der Vorgängerversionen von CP mal einen Error hattest ?
Es gab da einen der kam immer wieder, wenn man ein Geräte angehangen hat.
Nachdem man das Fahrzeug und das Geräte zurückgesetzt hatte, ging alles wieder.

**Comment by panther5** [comment]
habe das mit einem T7.315 und dem Ideal Drescher.
Das Hud ist nicht sofort weg, erst nach einer weile, keine ahnung was das auslöst.
Es ist ja nicht so das CP den Dienst quitiert, es ist nur nicht mehr aufrufbar von eben diesem abtankendem Fahrzeug (anderstwo geht es noch).
Muss mal schauen was ich letztens noch so aktiviert habe...

**Comment by game455** [comment]
Das möchte ich nicht ausschließen. Bin aber erst am 27. wieder zuhause um das zu testen. DankeVon meinem Samsung Galaxy Smartphone gesendet.-------- Ursprüngliche Nachricht --------Von: Tensuko <notifications@github.com> Datum: 16.05.2019  09:25  (GMT+01:00) An: Courseplay/courseplay <courseplay@noreply.github.com> Cc: game455 <game455@online.de>, Comment <comment@noreply.github.com> Betreff: Re: [Courseplay/courseplay] Mode 2: HUD verschwindet (#3776) Könnte es sein, dass du mit dem einen Fahrzeug in einer der Vorgängerversionen von CP mal einen Error hattest ?

Es gab da einen der kam immer wieder, wenn man ein Geräte angehangen hat.

Nachdem man das Fahrzeug und das Geräte zurückgesetzt hatte, ging alles wieder.



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Courseplay/courseplay/issues/3776?email_source=notifications\u0026email_token=ALHXCINPH36UK5JQ3X6E5YDPVUD7HA5CNFSM4HMPCR32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVQ5KOQ#issuecomment-492950842",

"url": "https://github.com/Courseplay/courseplay/issues/3776?email_source=notifications\u0026email_token=ALHXCINPH36UK5JQ3X6E5YDPVUD7HA5CNFSM4HMPCR32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVQ5KOQ#issuecomment-492950842",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by cucsijuan** [comment]
I think im having this issue, if I understood it right (translated german with google..). I tried to use the pickup (tried with a truck also) with a wagon attached in combi mode. managed to record the unload route to silo, selected manually the Harvester (tried with Mex 5 and new holland tx 32), when I start the route the HUD dissapears, I partially to completely loos the keyboard input, sometimes I manage to enter the map screen and the map get stuck constantly zomming out, Sometimes i have some more control and if I randomly click on the place where the courseplay HUD was, I can get to get the HUD working again, then i cancel the route and then I obtain control of the game again. pleasse tell me if you need more information. Im using courseplay 6.01.0227 in a vanilla FS19

**Comment by Tensuko** [comment]
@cucsijuan 
sry for late rply
do you have any Errors in your Logfile when that happens ?
I don't rly use Mode2 much couse of not rly working, but wonder how I could reporduce and what Error we got.

**Comment by stueja** [comment]
Hasn't been an issue ever since.
