### ISSUE TITLE
Error: Running LUA method 'draw' - AIDriver.lua:597: attempt to index field 'course' (a nil value)

### ISSUE THREAD

**Issue by chucklessduck** [Courseplay/courseplay#3921]
Every time I go to set up a grain cart to unload a combine the game freezes and crashes. The course play menu is stuck on my screen and I can only do random things until I get stuck in the map. I have to quit the game to get it to work again.

**Comment by Tensuko** [comment]
Logfile ? https://github.com/Courseplay/courseplay/wiki

**Comment by mehdinasef** [comment]
Hello,
I have a similar problem which is just one of many issues I have with mode 2. I didn't report them because mode 2 is being refactored ( #3311 ).
When I set up a grain card  course and click on 'drive course' the hole HUD disappears and I can't stop the driver. the HUD only disappears for the tructor that is in mode 2, other modes don't have that kind of problem.
when that happens, a 'nil value' error showes on the log:

[log.txt](https://github.com/Courseplay/courseplay/files/3317760/log.txt)

Hope that helps.

**Comment by Tensuko** [comment]
@mehdinasef 
2019-06-22 20:32 Error: Running LUA method 'draw'.
2019-06-22 20:32 C:/Users/samsung/Documents/My Games/FarmingSimulator2019/mods/FS19_courseplay/AIDriver.lua:597: attempt to index field 'course' (a nil value)
+ Callstack
#3909

**Comment by chucklessduck** [comment]
Here is my log. I duplicated the issue, it resulted in me having to force quit the game. [log.txt](https://github.com/Courseplay/courseplay/files/3318064/log.txt)

**Comment by Tensuko** [comment]
How and why you get Mode3 Errors, we had that somewhere already... #3868

**Comment by chucklessduck** [comment]
So is there a solution to this?

**Comment by Tensuko** [comment]
Actually no, as this is #3311 but I am not sure how some ppl get the mode3.lua Error.
That must be some settings when start CP Mode2 Driver...

**Comment by SteelRodent** [comment]
> I have a similar problem which is just one of many issues I have with mode 2. I didn't report them because mode 2 is being refactored ( #3311 ).
> When I set up a grain card course and click on 'drive course' the hole HUD disappears and I can't stop the driver. the HUD only disappears for the tructor that is in mode 2, other modes don't have that kind of problem.

I only get that when trying to use Mode 2 with potatoes. The entire HUD bar the clock vanishes, but CP still responds to the hotkeys thankfully. I've taken to just run the trailers myself until we get the new mode 2, because it currently has too many issues to work properly on the tight maps I play.

**Comment by wlfheart** [comment]
> 
> 
> Every time I go to set up a grain cart to unload a combine the game freezes and crashes. The course play menu is stuck on my screen and I can only do random things until I get stuck in the map. I have to quit the game to get it to work again.

Do you have the AI helper mod installed? I have found there is a conflict if you have both mods installed.

**Comment by Tensuko** [comment]
Closed couse #3311 
We will take a closer look on such Errors when Mode2 rework is done.
