### ISSUE TITLE
Cornering Too Fast, Not Slowing before a Corner

### ISSUE THREAD

**Issue by Krahazik** [Courseplay/courseplay#3962]
This is somthing I have noticed mostly with the transport mode. There are times where the vehicle doesn't slow down before it reaches the corner. This results in it missing the marker (starting the turn late) and swinging wide and nolonger being on the course. In some places this isn't an issue, in other it casues the vehicle to end up off the road and running into obstructions such as lamp posts, barriers, buildings, etc.

**Comment by Tensuko** [comment]
Did you record the course with that speed ?

**Comment by Krahazik** [comment]
No, I was having the vehicle drive at max speed for the vehicle, except at turns where I left that setting set a 6 mph.

**Comment by SpacemanJay** [comment]
I've seen it do this in fieldwork mode with a harvester. When it lifts the header to travel to the first turnaround after finishing the headlands, sometimes just before it gets to the turn, it will speed up, whip around the turn, then slow back down after it's already into the crop when the header turns on. Causes it to turn wide, and miss a chunk of crop at the start of that row. Doesn't happen all the time, only on occasion. Sounds like it may be related.

**Comment by Tensuko** [comment]
So you record a fast course with a fast vehicle and expect CP to slow down before corner ?
I doubt that this ever worked. From my own experience when I recorded the corners to fast, it will end up in a crash.

Or are we talking about different stuff ?

**Comment by Krahazik** [comment]
I recorded the rout slow, in order to be sure I stayed in the lane without drifting too much and to make sure I hit the corners. Was counting on the 'corner speed' setting to keep the vehicle on the course durring corners. Which on slight bends in the road it worked well, but not on 90 degree corners. It did slow down when it started the turn, but by then it was usually a whole tractor length past the turn point.

**Comment by sistem442** [comment]
My solution for this problem is manual edit of xml files. There you can set the speed as you wish.

**Comment by lounsberry** [comment]
As far as I am aware, corner speed only applies to turns on field. Not to turns on your recorded route.

**Comment by Krahazik** [comment]
**An idea;** Add a function to allow the editing of individual route nods with a max speed option? The max speed option would cause the vehicle to slowdown to the specified max speed when the node is reached. Max speed value would only be applied to vehicles driving under max speed option (not route recorded speed). Perhaps also include a pair of drag arrows that allow the positon of the node to be adjusted.

**Comment by oldmansutton** [comment]
I'm actually having almost this same problem, but while plowing or subsoiling (in fieldwork mode).  I've set the cornering speed to 3, but it doesn't seem to matter, it won't slow down very much on shallow curves.  The greater the curve, the more off course I get.  I notice if I set the turning circle really low, it's not as pronounced, but the initial value after generating a course always gives me a really high number.

**Comment by SteelRodent** [comment]
I only get these issues with articulated vehicles (which CP still can't drive properly - hopefully some day it will) and sometimes with four wheel steer. What I've found otherwise is that you can't give a recorded route to a vehicle that is too different from the one your recorded the route with or CP won't be able to figure it out - even using a different trailer can be a problem. It also won't do sharp turns correctly, never has been able to, and with the Challenger style tracked tractors it will happily jackknife no matter what turning radius you set. I've learned not to touch the speed settings and when CP screws up on a transport route, usually it's my fault because I gave it a route that doesn't work with what it's driving. The "from recording" setting actually works very well.

I do record my routes in pieces - for long routes sometimes that means I have legs between certain intersections that are pasted together as needed. CP will slow down where the routes connect, but if you do the start-stop points on each piece correctly they'll be in spots where CP needs to slow down anyway to either not crash or roll over (like going over a bank into a field or taking a sharp turn onto a ramp).

Not saying there isn't room for improvement, but CP will drive properly as long as you drive properly and record the route according to its limitations. By that I mean: Take it slow when you record, take turns very slow (IRL tractors go slower than walking speed when taking turns or they risk rolling over), and assume CP will need more space than you do.

**Comment by oldmansutton** [comment]
That would explain a bit, as I was using an articulated tractor.

**Comment by pvaiko** [comment]
This has been resolved in the above commit.
