### ISSUE TITLE
Suggestion: crossroad improvment

### ISSUE THREAD

**Issue by sistem442** [Courseplay/courseplay#3973]
Hello,
I have started to use courseplay recently. I have noticed that when you record a path between two points on the map each node has recorded speed visible in .xml file. Currently I am manualy seting the speeds because I am recording at lower speeds. One thing I would like to have is ability to set bypass speed for crossroads. It is for situation when you have perfectly strait road and somewhere in the middle you have a crossroad. Normally you can set high speed for strait road, let say 100km/h, but you need low speed (25 km/h) for turning in crossroad. So it would be very usefull  to  have ability to have extra attribute in xml file that would be called bypass speed, and driver would know that if he isn't turning in the crossroad he would use the bypass speed.

**Comment by Nila24** [comment]
I have actually done what you need for my FS17 PV3 map. do not have FS19 yet, sorry.
Still, my solution actually modifies all speed points for the vehicles when course is loaded to it, not dynamically when it is actually driving (modified only "course_management.lua", not "drive.lua").
All recorded speeds are ignored and replaced by max (road) speed as set on the vehicle at the moment courses are loaded/joined. 
Then all the course gets filtered in order to fins sharp turns (change in direction) - both instantaneus (say 90 degree angle) and gradual (90 degree angle over 30m or so). All preceding course points speeds are then modified in order to slow vehicle gradually before it arrives at the turn. Reduction of speed is dependant on actual magnitude of the turn angle and can be tuned quite a bit for different vehicles by setting road and turn speeds parameters - remainder of division from 5 is the parameters used as I did not want to change UI myself. For example if you set your turn speed at 10 km/h the "danger" angle would be 70. If 11 then 60; 12-50; 13-40; 14-30 degrees. Then it just wraps around with 15 again being 70.
Road speed parameter remainder signifies how long ahead the course is filtered (need to brake early for heavy vehicles, but need to brake late for light ones) range is 50 to 220 m ahead or so. Remainder for tun speed changes the "danger" angle from 70 degrees all the way to 30 degrees (as above for your log trucks...). Angles that are "dangerous" are done at "turn" speed. Below "danger" angle the speed is proportionately reduced, so 45 degree angles may be done at average between turn and road speeds or something to that tune.   
There is still a problem when one vehicle slows for turn and another crashes into it because it is on the course that does not to make this turn ocasionally or (much worse) - it decides to do an evasive action which. I have about 40+ CP vehicles doing transport on the map at ALL times so this does happen more often that I would like. Still it works good enough for me to hold on opening dynamic behaviour (drive.lua) can of worms.
I do have some other small custom tweaks as well - such as recording course every 20 m instead of 10 in the straight lines - not only it (dramatically) saves on number of points, but it reduces oscilations leading to crashes when vehicles run at 100+ km/h on straights. 
A lot of my vehicles are always "in traffic" at load/unload points, so I had to modify CP to show them in less red colour and "last" (up) in the list, which can only display 20 vehicle notifications by default... You get the idea :-)

**Comment by Nila24** [comment]
Hmmm, I see function courseplay:loadCourse() in "course_management.lua" (where all things you require are) has not really changed in CP6 vs CP5, so my stuff should also work in FS19.  
Still "course_management.lua" is not where such calculations should belong IMHO, so I am hesistant to post it as a branch or something (i am still not big in this Github thing either despite my course intersection changes being incorporated in) .

**Comment by Tensuko** [comment]
Speed gets recorded for all waypoints, Record with a fast Vehicle will end up in Waypoints with high speed for all Vehicles and ofc in Corners you will lower the Speed anyway.
Since this won't happen so fast and is (in my eyes) not rly necessary, I will close this one.
