### ISSUE TITLE
Still having issues with 2 vehicles and headland courses

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#4072]
Still having issues on the headland course..  using turn on field or not with the latest version..

This time it was the outside lane (left going clockwise) it reaches a point where it is doing the simple bypass island, and the vehicle turns around, and drives off in a straight line forever until it hits an obstacle.

![fsScreen_2019_08_12_14_40_50](https://user-images.githubusercontent.com/6591048/62889380-4584c900-bd0f-11e9-96b5-d457851b009d.png)

https://gist.github.com/sootysax/a8ff3719e8b37dc3a75362db9b64077e
![fsScreen_2019_08_12_14_43_37](https://user-images.githubusercontent.com/6591048/62889552-a57b6f80-bd0f-11e9-911d-ea3ff12b6640.png)
![fsScreen_2019_08_12_14_43_41](https://user-images.githubusercontent.com/6591048/62889568-ac09e700-bd0f-11e9-82b9-0bd2cd5725eb.png)

**Comment by pvaiko** [comment]
How is it with the 'circle' bypass?

**Comment by SteelRodent** [comment]
I've had something like this where the one vehicle goes to refill and then comes back and drives off the in wrong direction instead of returning to where it left off. Didn't report it because I've found it's not reliably reproducable in any way. With 265 I noticed an occasional glitch on certain fields where the one vehicle on the headland track (when doing headland first) will suddenly go off the path, as if it gets stuck doing a ridiculously big turn radius. But I got sidetracked trying to work out how to use AD and haven't checked how it works with the current version.

**Comment by pvaiko** [comment]
If anyone has a savegame to reproduce it, post it here.

**Comment by Tensuko** [comment]
Test with newest Version and report back pls.

**Comment by Tensuko** [comment]
This should be working fine now, if have more Issues with new Mutitool feature, make a new Issue.
