### ISSUE TITLE
help with combine and tractor

### ISSUE THREAD

**Issue by Kenji-dk** [Courseplay/courseplay#4105]
I need help
i use coursplay and want to hear if others have this problem ..
When I use combine harvesters in coursplay and make a route then drive it around as well as it should but when the combine has to be emptied then the combine returns back into the grain and is ready to be emptied so I have a tractor that is set to empty so drive it up to the combine and get filled up as it should but instead of reversing or waiting for the combine to run again. Then the tractor chooses to drive in front of the combine so that the two machines collide and do not move on.

**Comment by MacedonskyAlex** [comment]
The course should be used so that the tractor went back. I have already use AD for unloading combine

**Comment by RUGhost** [comment]
@MacedonskyAlex > The course should be used so that the tractor went back.
I couldn't understand, can you please explain a little bit?

**Comment by wlfheart** [comment]
Yes i have this problem. It really defeats the purpose of staying out of
the fruit. I would rather it go back to the okd way until its figured out.

**Comment by SteelRodent** [comment]
If I'm not mistaken (apologies if I'm wrong), he's talking about the "new" part of the combine harvester work method in mode 6 where it pulls into the next right lane when it's full (and there isn't space on the left), waits to be emptied. and continues as soon as it's empty without waiting for the tractor to move out of the way (ideally it should wait for the tractor to move even if it's not CP driving it). When used with mode 2 (in its current state) the mode 2 driver doesn't understand this and will usually drive into the combine or in front of it while trying to get into the wait spot as the combine is crossing back to its own path.

Mode 2 drivers currently don't work properly with the new combine behaviour and it essentially means you cannot use mode 2 drivers for chasing unless they're always able to reach the combine before it pulls in - and even then they have a bad habit of going in front of the combine, ramming it, or otherwise hitting it because mode 2 doesn't have working collision prevention atm (they appear to only see other mode 2 drivers). But believe this is all in the mode 2 thread.

**Comment by Kenji-dk** [comment]
SteelRodent  yes I use Cousplay six and what you say SteelRodent is pretty right and it is pretty annoying combine harvesters and tractors  do it like that because it ruins the fun of using Cousplay
i hope there come a fix for that...

**Comment by Tensuko** [comment]
#3311 
Closed.
We are working on that and it will come soon or later....
