### ISSUE TITLE
New issue with CP +AD (288)

### ISSUE THREAD

**Issue by alpha117** [Courseplay/courseplay#4135]
Morning all
First time I've seen this in the log was not in the .4 release. AD has not been updated either

[log.txt](https://github.com/Courseplay/courseplay/files/3528755/log.txt)

_2019-08-22 08:06 AD: Set to not recalculating routes_

**Comment by Tensuko** [comment]
So.... what doesn't work ?
A new entry in a logfile doesn't have to be an Issue...

**Comment by alpha117** [comment]
Update...since updating to 288 this morning the save game will not load. Was OkK with CP .4 last night.  Thanks
2019-08-22 08:21 G:/FS19 Maps/FentonForest4X/FS19_AutoDrive/scripts/AutoDriveXML.lua:264: attempt to index a nil value
[log.txt](https://github.com/Courseplay/courseplay/files/3528802/log.txt)

**Comment by Tensuko** [comment]
I think that is something for @Stephan-S or CP tries something @pvaiko ?

**Comment by alpha117** [comment]
FYI..just gone back to CP .4 and all is fine

**Comment by Stephan-S** [comment]
2019-08-22 08:06 AD: Set to not recalculating routes
Is Just a debug information, that Ad detected no Changes in the Network since the last recalculation. So the saved xml File should be up to Date.

2019-08-22 08:21 G:/FS19 Maps/FentonForest4X/FS19_AutoDrive/scripts/AutoDriveXML.lua:264: attempt to index a nil value

Is called during the AutoDrive initialization after map start. No CP issue. Might have something to do with some broken or offline changed xml Files. 
If you have a savegame of that Situation, please Open an issue on AD Github. This one can be closed Here, @Tensuko :-) Thank you

**Comment by Tensuko** [comment]
Thank you @Stephan-S 
Closed.

**Comment by alpha117** [comment]
Thanks Guys
