### ISSUE TITLE
savegame

### ISSUE THREAD

**Issue by Duveleir** [Courseplay/courseplay#4137]
so i just got the latest version but now my save game wond load in

**Comment by Tensuko** [comment]
1) no logfile
2) your AutoDrive is outdated, couse you only loaded the ModHub Version, the newest and needed Version is 1.0.4.9 wich you get from github https://github.com/Stephan-S/FS19_AutoDrive/releases
3) even I am 90% sure it is outdated AutoDrive, still need always a logfile, so we can see whats going on... https://github.com/Courseplay/courseplay/wiki

**Comment by Duveleir** [comment]
I just downloaded them again from github zo i got the latest update

**Comment by Duveleir** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3537176/log.txt)

**Comment by Tensuko** [comment]
You don't have the newest Version, this is what I told you:

-> your AutoDrive is outdated, couse you only loaded the ModHub Version, **the newest and needed Version is 1.0.4.9 wich you get from github** https://github.com/Stephan-S/FS19_AutoDrive/releases

After that, DO NOT update the AutoDrive in ModHub, since it is OLD...

Load mod: FS19_AutoDrive (Version: 1.0.1.9) (Hash: 6b9cce8e25592c84cecb0b5c475b348f)

And this is the msg that tells me that:
2019-08-24 12:19 C:/Users/Jerry/Documents/My Games/FarmingSimulator2019/mods/Courseplay_6_01_00291/course_management.lua:1714: attempt to call method 'GetAvailableDestinations' (a nil value)

You log only prooved what I guessed already...

**Comment by alpha117** [comment]
@Duveleir this post might help
https://forum.giants-software.com/viewtopic.php?f=963&t=151572

**Comment by Tensuko** [comment]
He just got to download the 2 Updates from GitHub and then NOT blindly update everything on ModHub...

**Comment by Duveleir** [comment]
Yea it was that i updated it in the mod folder on the game

**Comment by Tensuko** [comment]
So does it work now, so I can close this ?
