### ISSUE TITLE
Ability to use AD for unload with mode 2 / #4110 Still an issue

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#4158]
Any chance of adding the ability for AD to take over when its time to unload via mode 2  considering that the speed issues in #4110 are not really fixed (I can't make a single unload run with a full load without snaking back and forth between waypoints and eventally crashing into something).

**Comment by Tensuko** [comment]
I don't rly understand what you want...
AD replace our Mode2? When CP can't handle the AD Course, why not use AD for full operation instead ?
For CP, AD is an addittion to not create all the routes with CP, for refill course and stuff like that.
So why would you want CP to drive the course and AD to do the work?

**Comment by SledgeHammer75** [comment]
I think combination of AD / Courseplay for Mode 2 would be ideal (like AD usage for refill purpose). 

On the field Courseplay is far better at unloading a combine (e. g. start driving to the combine at certain fill level, unload while driving, taking field rows into account); on the road the AD network is superior to a Courseplay route. 

Imagine having a fully developed AD network with 5-10 vehicles constantly driving around on the road. The AD drivers look out for each other at intersections or when encountering a slower vehicle trying to prevent collisions. Throw a Courseplay driver into the mix things can get ugly fast, because they are not aware of each other.
