### ISSUE TITLE
Refill current silo type

### ISSUE THREAD

**Issue by ddiis** [Courseplay/courseplay#4181]
When attach fert tools, CP set fill type LIME as default, and if I use job+refill course and forgot to switch this option to fill fertilizer - it fill lime :( I think this option must be current fill type, instead default lime

![fslf](https://user-images.githubusercontent.com/4257956/64061759-a48b7e80-cbe7-11e9-8663-fd81efb6c907.png)

**Comment by Tensuko** [comment]
How to know current filltype, if is empty ?

**Comment by ddiis** [comment]
Already filled with fertilizer before attach, but in option every time lime

**Comment by ddiis** [comment]
Sorry its hard to explain with my eng, 
I have tool with 50% fertilize, attach it to tractor and in this option must be fertilize. 
If tool empty, then yes - any by default . i think

**Comment by MtBakerScum** [comment]
I agree with this, if the option could default to current fill type on course load that'd be great.  I'll often start a field with a cart partially filled with fert, attach a refill course onto the end, and start it forgetting to check the refill type option. Only to check in on the course later, to it spreading lime on the field. 

Maybe if the default setting were fertilizer all the time, since lime is only used once every 3 harvests anyways

**Comment by Tensuko** [comment]
Not sure how to handle this with a seeder, as you got 2 filltypes...
We will have to think about this and discuss this.
