### ISSUE TITLE
missing the corners

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#4197]
![fsScreen_2019_09_03_14_04_12](https://user-images.githubusercontent.com/27097241/64264475-43d2ad80-cf29-11e9-8b17-bce961643f75.png)
![fsScreen_2019_09_04_15_30_33](https://user-images.githubusercontent.com/27097241/64264481-47fecb00-cf29-11e9-9466-95fce95b8f7d.png)
![fsScreen_2019_09_04_15_30_49](https://user-images.githubusercontent.com/27097241/64264496-4d5c1580-cf29-11e9-8e09-fab3012818d9.png)
right ill repost as not happy with previous answer as you can see the cultivator is not take the whole part of a corner It turns as intended on a sharp corner but it missing the corner. it goes up to the edge slight bend missing. If I do the offset that's gonna mess the up and down roads up as it wont be central haven't got the log as I don't know the number needed. also its the culti ive got in pic the blue one

**Comment by bojanh66** [comment]
Thats pretty normal, i had same problem in FS 17 courseplay official version.
https://github.com/Courseplay/courseplay/issues/4106
I also opened similar thread, because i am perfectionist like you, i want to have 100% covered field, but its not possible, unless you decrease working width by at least 1 meter, but then you will have 1m overlap on up/down central which is waste of time/resource/money.
I gave suggestion to CP team to add headland working width option to Advanced Course Generator Settings, this would solve problem, but i am not developer, i dont know if its an easy task or hard.
Even if they add that option in the future, i am aware that we will have overlap on headlands, but those tight corners will be done perfectly...and yea, i am aware that headlands already have 7% overlap included :).

**Comment by SirStranger1989** [comment]
You have the "round corner" option selected. Sharp corners should take all
of the field, but takes longer to complete.

Op wo 4 sep. 2019 16:43 schreef bojanh66 <notifications@github.com>:

**Comment by matty2123** [comment]
Tried everything sirstranger only way I can do it is put offset on for headland and normal for up/down

**Comment by Tensuko** [comment]
Check your Field definitions too, Scan it manualy in hud and see the blue line.
This is some 'corners' (I don't call this a corner actually) can't be taken that sharp.
Closed.
