### ISSUE TITLE
Error: Running LUA method 'update' - AITurn.lua:69: attempt to index global 'self' (a nil value)

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#4247]
Hello,

today my game freezed out of nowhere. I was tabbing throug my vehicles as it happend.

Log said this (is also attached):
`2019-09-16 13:12 D:/LS19 Mods/FS19_CoursePlay6/PurePursuitController.lua:309: attempt to index field 'course' (a nil value)
2019-09-16 13:12 Error: Running LUA method 'update'.`

I used the newest version of CP and AD. 

[log.txt](https://github.com/Courseplay/courseplay/files/3615960/log.txt)

Hope you can solve this :)

Bye,
Knowen

**Comment by Tensuko** [comment]
Error: Failed to open xml file 'D:/LS19 Mods/AutoDrive/modDesc.xml'.
Load mod: AutoDrive
Error: Missing descVersion attribute in mod AutoDrive

10 Seconds into your logfile and found this.
Get a correct packed release of AutoDrive from here:
https://github.com/Stephan-S/FS19_AutoDrive/releases

**Comment by Tensuko** [comment]
Other Error starts at Line 1663

**Comment by fragster27** [comment]
Hi, I'm new here and I'm sorry to write under this section. Today I wanted to use a courseplay to silage the pit, but unfortunately without success. I recorded the route and when I switched on the tractor at the first point, it continues to the beginning of the silage pit and instead of piling up the tractor it turns around. I checked the log and there is a CP error 2019-09-20 23:21 C: / Users / Roman / Documents / My Games / FarmingSimulator2019 / mods / Courseplay_6_01_00300 / input.lua: 441: attempt to index and nil value. Please Where can I send the full log of the game ??? Thank you. I have a video on YouTube. Here is the link: https://www.youtube.com/watch?v=jLleFpUctjU&feature=youtu.be . I still want to apologize if the pronunciation does not fit, but I am from the Czech Republic and I do not know much English, so I used a Google translator. Thank you for your help.
