### ISSUE TITLE
Mode10: Problem with Bunker Mode

### ISSUE THREAD

**Issue by Heartbeatss1** [Courseplay/courseplay#4254]
Hey Guys, 
i have a Problem with the Mode 10 the Pushing of Mod Bunkers.

I bought 4 Silos and placed them on an old Field. The First course loads correct and the Driver works. If i go to the next bunker the driver trys to go to the first bunker not the second.

I made a Video of this but i dont know where the Problem is.
https://youtu.be/ZXUfZm4ryGs
The Bunker mod is this:
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=122963&title=fs2019
I also attached the log file

Best Matthias
[log_fuerfehler.txt](https://github.com/Courseplay/courseplay/files/3617633/log_fuerfehler.txt)

**Comment by DizzyBHigh** [comment]
I seem to be having the same issues as Heartbeats

Drive into Bunker backwards - Hit record
Drive forwards to parking place - Hit Park
Drive forward a tad, then hit reverse (otherwise it does some weird turn before reversing)
Click Reveres to turn it off Click Stop

Works for one bunker but if I try to set up course play to do the bunker next to it always tries to go to the first bunker.
[log.txt](https://github.com/Courseplay/courseplay/files/4362855/log.txt)
