### ISSUE TITLE
Buttons for Startoptions

### ISSUE THREAD

**Issue by prjndigo** [Courseplay/courseplay#4303]
placed to the right of the "drive course" button, or maybe three 'handy' buttons of "nearest" "next" and "start" then use the regular click location for stop/start

**Comment by Tensuko** [comment]
There is already a point to change where to start, I don't see a point in what you suggest here.

**Comment by cwattyeso** [comment]
I can sort of see what prjndigo is suggesting. Right now you have a "Start Drive" button to get Courseplay to actually start driving the course. This uses the setting selected on the line below and whether it's set to Nearest Waypoint, Next Waypoint, Current Waypoint or First Waypoint. The user has to select this first before then hitting the "Start Drive" option.

When you clear a course or generate a new course, this setting generally changes and resets. So for example if your sat next to a field with say a plough and generate a course to go straight up and down. You just want to hit "Start Drive" and let the Plough begin from the Starting Point/First Waypoint, however Courseplay seems to default to Next Waypoint or Nearest Waypoint, which means the Tractor would drive off and begin working somewhere else. So the player has to always manually change the starting from setting before hitting Drive Course.

Another example is when say seeding or fertilising with a tool and it runs out of material, you may not be running a refill course so have to manually stop the courseplay driver and manually go and refill the machine. When you return to the field, the player must remember to change the setting for "Start From" and make sure they select Current Waypoint and then click "Drive Course" to have Courseplay return where it left off. Otherwise it'll just go drive the course from whatever the previous setting the player had.

**Comment by Tensuko** [comment]
So it is just handling stuff. Well we will discuss about this.

**Comment by Tensuko** [comment]
No space on this HUD.
