### ISSUE TITLE
Rename and Update Current loaded Course (instead of save new ID)

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4367]
It would be very nice if we could rename the courses.
It would help to organize the list.

**Comment by Merrlin** [comment]
Short Workaround: Load the Course with a vehicle and save it under the new name.

**Comment by bojanh66** [comment]
Nice suggestion, i really hate when i have to load course, save it as a new one, then delete old one...ye ye i know it only takes couple of seconds, but renaming would be amazing.

I would like to suggest another suggestion to CP team.

Would it be possible to save vehicle Settings as a profile/preset?

For example, i have tractor who can equip narrow tires and wide tires, if i change tires in vehicle customization, CP settings would reset to default.
If we were able to save/load vehicle settings preset, it would save as a lot of headache.

**Comment by Tensuko** [comment]
I will merge the Suggestion with this one: #4352

**Comment by MicaelJarniac** [comment]
Being able to rename folders would be helpful too! Because the current workaround I think is to create a new folder with the desired name, then go to the old folder and move all of its contents one by one to the new folder, then delete the old one, thus it can be even more time-consuming and frustrating than the workaround for renaming a single course.

**Comment by Tensuko** [comment]
Add to collection: #6270
