### ISSUE TITLE
Is there a way to manually fix minor errors on the route?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4380]
During a long route, there are sometimes minor errors in the route.
If there is a small error (a wrong turn, an invasion of another street lane), to avoid having to redo the entire route again, I would like to know if there is any way to correct these small errors (visually), ie drag a point a little more to one side or the other ...
![image](https://user-images.githubusercontent.com/11199752/66882007-2c162c80-ef9f-11e9-9e90-7d35c6cba6f3.png)

**Comment by Tensuko** [comment]
There is no editing ingame.
you could use xml table and coordinates, but thats even more difficult.

What we suggest for long routes:
Create smal Routes-Parts and bind them togehter, then save the complete course:

You make a course to your silos and back to entrance, wich start and end at the entrance of your court.

Then all you got to do is create a courses from field to entrance and from entrance to field. Now Load them one by one and its fine. If you then notice you made a mistake for Silo part, just delete the combined course, create the silo course new and load the Field-Court + Silo Unload + Court-Field again, save it again and done.

Now you could even make a refill course on your court and use the already existing 'Field to Court' (and back one) as part of it, just combine the right courses that you need.

Since you got AutoDrive, you can load course from there and use them too, try it out a bit.

Closed.

**Comment by wlfheart** [comment]
Not sure if this is relevant to this but, you can delete way points and
reconnect them in game. Click the warning sign in th AD gui and the
relevant buttons appear.

**Comment by Tensuko** [comment]
That is for AD and not CP...

**Comment by wlfheart** [comment]
oh sorry  didn't look at the subject
