### ISSUE TITLE
Up to date tutorial to learn how to use multiple combines in the same field at the same time?

### ISSUE THREAD

**Issue by rogeriodec** [Courseplay/courseplay#4422]
I see some youtube tutorials which explain how to use multiple combines in the same field at the same time, but they are at least 2 years old.
As this mod is being constantly improved, I'd like to know if there is an up to date tutorial for this?

**Comment by andejx** [comment]
I find it works the same as before basically, but some of the UI has changed.

1. Get a combine on the field and generate a course however you want, but with 2+ tools (however many you want) selected. 

2. Save that course so that the other combines can load it.

The UI shows only one path through the course still, but it will calculate and split that up into lanes depending on how many tools you have selected during the course generation, each lane you can assign to a different combine.

3. Set the first combine to run that course in the outermost lane depending on which direction the combines set to take (eg. if the course goes clockwise headland then i make my first combine in the left lane, so its the outermost one.)  

4. Set the second, third, etc combine to load the same course as first, but in settings change to a different "lane" for each. 

5. Turn on convoy mode on in settings and set a distance (100m etc) so they don't run into each other while unloading/maneuvering. 

6. Start the first combine you want to lead and let them run, so long as you have convoy mode on you should be able to start the subsequent combines up and they should wait a sufficient distance between combines before they move and they should navigate into their own lanes so long as you have them set up to be in different ones.

7. Profit?

I'm simplifying it a bit I'm sure but I've not had much trouble with that way.
I apologize if I've missed something but I'm fairly sure that's all there is to it.

**Comment by rogeriodec** [comment]
Thanks. Although from 2014, I found [this youtube tutorial](https://youtu.be/lpr5UnnN6Uo) that's pretty informative from the main concepts, and it's very clear, so I could learn the ideal quickly.
