### ISSUE TITLE
No Refill at trigger point

### ISSUE THREAD

**Issue by Kloever** [Courseplay/courseplay#4433]
Hi, 

I recently started with Courseplay. With the new Platium DLC i started a new carreer on Marwell Manor. 

So, my issue is this. I made a course from my Silo(Marwell Standard) to the Selling Point, in this case Greendale Store.  I started recording the A-B course with the trailer under the Silo and drive to the Sell point and back. This part goes as planned. But, when i start the course it won't fill up my trailer with the grain type i choose in Courseplay. CP recognizes the trigger point but won't stop to fill up. If i manually fill the trailer it will sell the grain type. 

Same when seedinga field. The seeder is going to the fill point(placeabe fill station mod, one that sells everything) open the hatch and drives back to the field. But it won't fill the seeder with seeds or fertilizer.

Version of Courseplay i use is 6.01.00311. I can upload a log in the evening(at work atm). But maybe someone has the golden sollution. What i will try tonight is enter a wait point when starting the A-B course and when entering the Refill point.

**Comment by Tensuko** [comment]
Waitpoint is simple for waiting and just a workarround.
Mode one is simple this:
Trailer under Pipe, Start record, drive all the way to selltrigger and back and Stop BEFORE the Filltrigger, so just a few meters before the Pipe of the Silo. Choose the Fruit you want to reload and start. And that works very well, but keep in mind that, when you got a GC Trigger, you need to modify a file inside GC (see #4049 ).

For the Seedrefill.
Load your Fieldwork Course, then Add the refill course with the folder with the + in it.
The Refill course got to go through the trigger of the buy-stuff-silo. It could be that a silo that sells more then just one stuff is not working with seeding machines, since you can refill 2 typs (seed and fertilizer) wich can't be selected like in other machines.

**Comment by Kloever** [comment]
The selling errors is resolved. The GC modify was the trick.
The Seed Refill is resolved. Buying different seeding silo was the trick.
The Grain transport when doing harvesting isn't solved. The trailer goes to the harvester when at 50%. Drives off when full, but it won't empty at the silo. Will test this out today with a different course.

**Comment by Tensuko** [comment]
Old Mode2 isn't supported, see #3311 and #4286 
So rest seems solved.
Closed.
