### ISSUE TITLE
Mode 2 Alpha: CombineUnloadManager.lua:100 Error

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#4497]
Hello everybody,

during a test with a combine and an unloader, i got this error message in the log.

`2019-11-01 19:50 D:/LS19 Mods/FS19_CoursePlay6_1/CombineUnloadManager.lua:100: bad argument #3 to 'format' (number expected, got nil)
2019-11-01 19:50 Error: Running LUA method 'update'`

This error appears during the unloading process. The aproach of the unloader and following the combine..everything was great. So..the combine starts to unload and near the end of it, the combine continues driving without harvesting or unloading. The unloader just starts driving circles. 

For the record: I downloaded the latest version earier today.
Log: [log.txt](https://github.com/Courseplay/courseplay/files/3799869/log.txt)

Greetings,
Knowen

**Comment by tanordheim** [comment]
Same here; when this happens it seems the entire UI freeze in some odd way. Mouse interaction stops working, or at least mostly stops working. Keyboard interaction works for a little bit (I can tap ESC and get into the menu) but also stops responding eventually and I'm forced to Alt+F4 out of the game.

My log is attached as well if it's of any help, I guess the equipment I used can be found in there as well - otherwise I was using the following:

- New Holland CR10.90 combine with the New Holland 3162 Draper 13.7m header
- Fendt 1050 tractor towing the Strautmann Aperion 3401 trailer

[log.txt](https://github.com/Courseplay/courseplay/files/3964931/log.txt)

**Comment by tanordheim** [comment]
For what it's worth, commenting out the `print` statement on line 100 in `CombineUnloadManager.lua` (`print(string.format("%s: 80percent: %.1f  time: %.1f",nameNum(combine),g_combineUnloadManager:getSecondsTill80Percent(combine),timeToTarget))`) lets it gets past the issue. I have no idea if the fact that `timeToTarget` is nil is going to cause something else bad to happen here but it seems to continue just fine for me at least. Happy to provide any other information that I can.

**Comment by Tensuko** [comment]
#5272
