### ISSUE TITLE
unload harvester

### ISSUE THREAD

**Issue by Overgiver** [Courseplay/courseplay#4548]
When my tractor and trailer go to unload the combine, if it comes towards the front of the combine it runs strait into the front of it, I am using all in game equipment, and have the platinum edition installed

**Comment by Tensuko** [comment]
#3311 
#4286 
Closed.

**Comment by Gibbanator** [comment]
Think this problem is most prevalent when it comes to completing a field without having to keep going back to it making corrections or resetting while using CP. You close these reports each time. Being it mode2 there is no fix? maybe just using helper and manually unload is a work around since the field needs constant attention.

**Comment by Tensuko** [comment]
When you would read whats behind those numbers, then you would know why I close them.
Manualy unload is always a workarround, no matter if use CP or Helper on Combine....

**Comment by Gibbanator** [comment]
I do read those.. don't get me wrong here I mean no ill content you guys are great. I see this problem posted a lot and CP is something you would hope work to where those crashes are not a issue. They seem simple fixes but know they are not by your remarks.. Each update that comes out (and they are usually daily) I jump right on and look for that CP ease of play.
