### ISSUE TITLE
Cp won't spray herbicide with JD R4045 sprayer? 

### ISSUE THREAD

**Issue by lightbulb751** [Courseplay/courseplay#4562]
I set up the course with the correct headlands, sprayer width, starting position, farm silo load selected to herbicide, etc. However, when the sprayer starts at the first waypoint it refuses to actually spray the herbicide and will only drive along the course.

**Comment by Tensuko** [comment]
mod yes/no ? logfile ? and so on....
https://github.com/Courseplay/courseplay/wiki

**Comment by lightbulb751** [comment]
GIF showing what it does. Does the exact same thing when spreading fertilizer or spraying. When it gets to the first waypoint courseplay won't kick the spreader/sprayer active and won't fertilize nor spray. 
GIF:
https://gyazo.com/b7890ffd0b290cf7fc0c646f139a6dc2
LOG:
[log.txt](https://github.com/Courseplay/courseplay/files/3855885/log.txt)

**Comment by Tensuko** [comment]
You can try out a new CP Version, but this is clearly a Mod Issue

**Comment by Sanchez-1** [comment]
How does one fix this problem

**Comment by Tensuko** [comment]
Ask the Modder to fix the Mod and stick to GIANTS standarts.

**Comment by cwattyeso** [comment]
Check whether or not the John Deere Sprayer works with a regular in game worker. If it does not, then I suspect you have an old version of the mod. There is a fixed version of it out there where it does work with Courseplay, think the original version is missing the AI work info and working width info in the i3d file and xml which is why it doesn't work with Courseplay.

**Comment by Tensuko** [comment]
Interesting Information, thank you!

**Comment by Tensuko** [comment]
Closed since this is Mod Issue and no more reaction to it.
