### ISSUE TITLE
Mode2Alpha Tractor turn-around following Chopper

### ISSUE THREAD

**Issue by jhomer** [Courseplay/courseplay#4581]
I've ran mode 2 for about 5 hours in this large odd shaped field. BigX with 3 tractor/trailers.
I've had a few on field tractor collisions to correct. 
Had a few times earlier on when doing end rows where the tractors would get stuck in a reversing move and they would not come out of it. (I have no screenshots of this but they would keep trying to back up with the trailer jackknifed).

Field
![fsScreen_2019_11_17_09_01_31](https://user-images.githubusercontent.com/7943994/69009235-205cb380-0919-11ea-90d1-a3215d8db777.png)

Here is an issue I had more times than not.
When turning around at end the tractor waits for chopper.
After chopper is ready the tractor starts turning in that direction (going slow) but then straightens out and starts slowly creeping ahead getting further away from chopper.
![fsScreen_2019_11_16_19_25_39](https://user-images.githubusercontent.com/7943994/69009106-fa82df00-0917-11ea-88fd-b94652f87b6d.png)

Here is the point where the tractor stops and sits in this position and will not correct. 
![fsScreen_2019_11_16_19_26_55](https://user-images.githubusercontent.com/7943994/69009107-fce53900-0917-11ea-95e6-c4c66c2087f6.png)

After it gets to the above position I stop driver and start driver again without moving tractor myself and it will turn and head to chopper with no problems.
But when it gets to chopper it fly's by too far and chopper will stop and tractor stops.
Then I stop and start driver again, then it will turn a circle again and get next to chopper properly and they go just fine.   
![fsScreen_2019_11_16_19_29_23](https://user-images.githubusercontent.com/7943994/69009113-ffe02980-0917-11ea-8da7-0da5168505bb.png)

I did not seem to have much luck with them correcting problems on their own, even the "call for obstacle" did not seem to adjust course.
Like the below image. I let them sit in this position for quite some time but they did not correct.
![fsScreen_2019_11_13_22_14_26](https://user-images.githubusercontent.com/7943994/69009570-0cff1780-091c-11ea-9edc-f2a0ab3e0816.png)

**Comment by skjatala** [comment]
I am also having this problem. Map name = FS19_DondiegoMap v: 2.1 ( same as all  game's original Maps ) Tractor driver not drive mostly on empty side of field.
I think this problem is started from courseplay : 6.01.00322 . 
sorry my bad english
if i am doing some thing wrong please guide me. thanks 
https://www.youtube.com/watch?v=GIzqoJ2uFf8
video is private

**Comment by Severan500** [comment]
I have the same problem and I still can't solve it. the cutter at the end of the field begins to rotate and the transporter rotates in the same direction. They should rotate so that the derivative turns "out" from it, waits for the cutter to turn, and rolls back to its side where there is no crop. Unfortunately, this is not the case. The importer remains on the same side. Were you able to solve it "skjatala"? Thank you for any help.

**Comment by Tensuko** [comment]
#5272
