### ISSUE TITLE
Terra Variant 435 no longer loading Digestate

### ISSUE THREAD

**Issue by Hobbyalkoholiker** [Courseplay/courseplay#4607]
Hello,
I just updated to the latest version and noticed the Terra Variant 435 no longer loading Digestate at the Biogas Plant. The driver hust passing thru the Trigger(i can see the Start Refill option). Other tools like the Samson Slurry tank still seem to work.

[log.txt](https://github.com/Courseplay/courseplay/files/3887193/log.txt)

**Comment by Tensuko** [comment]
Logfile with channel 1 and 2 active then let run the course.
12 and 14 is for turns and not for Triggers.

**Comment by Hobbyalkoholiker** [comment]
my bad sir. there you go

[log.txt](https://github.com/Courseplay/courseplay/files/3887536/log.txt)

**Comment by Tensuko** [comment]
Do you have any other Tool at the Terra V435, or just use it for delivery ?
What Mode did you use it ?
I want to try this out to see whats happening there.

**Comment by Hobbyalkoholiker** [comment]
Im using the proper Slurry Tank and the Fix 15 for it to Fertelize my Fields. It worked fine before i updated. Even tested different Courses that worked before as well.

**Comment by Tensuko** [comment]
Well I got a guess whats wrong here.
Since Trailer Types works very fine or those refill things, the Terra one is a kind of selfdriver with the Tank.
I am not sure if @GeorgeEarslight have a solution for this. I think that is couse of the check for Trailer I guess. Actually haven't check the other Selfdriver on Refill yet :D

**Comment by Tensuko** [comment]
Terra Varian just loading fine in V 02.00040
