### ISSUE TITLE
Fertilizer refill problem

### ISSUE THREAD

**Issue by RedMonster-HUN** [Courseplay/courseplay#4617]
When I send a tractor to refill the seeder (which contains seeds and fertilizer as well), it gets refilled with seeds, but NOT with fertilizer. Even if I send it to two separate refill points.
Video and logfile later.

**Comment by RedMonster-HUN** [comment]
https://youtu.be/p_QesYH0tvM
I tried to illustrate the problem, I hope I succeeded. Please check video description on youtube as well.
[log.txt](https://github.com/Courseplay/courseplay/files/3907960/log.txt)

**Comment by Tensuko** [comment]
logfile with channel 1 and 2 active pls.

**Comment by RedMonster-HUN** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/3908009/log.txt)

**Comment by Tensuko** [comment]
Got to try this on my own, will take a while...

**Comment by betrox007** [comment]
The implement that you use is Horsch evo right?, i was try that's implement and that work for me at buying station, may be you must have separate silo for seed and fertilizer and make that silo fill 1 only for seed and another 1 only for fertilizer, also did you have check at CP HUD the fertilizer function set to active?,because i was try a few minute ago its work for me, you can check it here on my video, https://youtu.be/FwxV5eXKUtQ CMIIW

**Comment by RedMonster-HUN** [comment]
@betrox007 I have enabled fertilizing option in cp hud. If you watch my video you will see that fertilizer tank is completely empty, and worker departs to refill it. But for some reason, worker uses first silo only to refill seeds, however it should do the same with fertilizer as well.

**Comment by betrox007** [comment]
@RedMonster-HUN yea, i don't know for sure whats the problem is maybe the CP team have some answer for you, but you give me some idea, i want to try, create separate silo storage for seeds, fertilizer, herbicide, liquid fertilizer and lime without other fill type, since i didn't use GC Mod on the map i use to play and then see what the current version CP can do, so can give some suggestion for CP team for further development, cause last try i try refill at buying station not at silo storage,thanks mate

**Comment by Tensuko** [comment]
What I found out is, that it actually works, but it seems like not for all silos.
Those 2 are Mod Storages for Seed and Fertilizer, you can just use them for refill and it works fine.
The Big MultiSilo I placed near had the same Issue as you discribed. I guess that is due to the Fruit Selection and only one trigger. The smal one got that too but only for seed and fertilizer.
Can't explain waht CP technically does there, but thats what I can tell you and what I suggest you to use for now. Maybe we can advance it together with #4615 (add the option to select a 2nd fruit to fill up trailers, if that is possible, we will see)
![fsScreen_2019_12_01_17_44_45](https://user-images.githubusercontent.com/27344744/69917169-6f4f3080-1463-11ea-995e-5ac6928d13b8.png)

I put this to postponed, as it works for the most refill stations, just not big multisilos (so far).

**Comment by Tensuko** [comment]
Should basically work, not sure if still doesn't on some Silos.

**Comment by RedMonster-HUN** [comment]
@Tensuko Nope, still not working for me. For some reason CP still doesn't refill fertilizer in double chamber seeders. Map and silo are the same as last time.
