### ISSUE TITLE
M2Alpha: isAutoAimNodeFixed' (a nil value)

### ISSUE THREAD

**Issue by frm274** [Courseplay/courseplay#4662]
Hi,
i´ve just downloaded the newest Mode2Alpha version and got following Error after hitting the start button:
CombineUnloadAIDriver.lua:1277: attempt to call method 'isAutoAimNodeFixed' (a nil value)

**Comment by pvaiko** [comment]
Full log as always

**Comment by Farmer-87** [comment]
Hallo ich bin recht neu hier und habe auch ein Problem mit dem Courseplay Mod er Funktioniert nicht richtig. Im Spiel wird mir immer egal bei welchen Fahrzeug die Meldung TX32:false; rigthOK:false numUnloaders:0 timeTill80: 999 an. Ich hoffe das mir jemand helfen kann dabei. 

Falls das hier nicht rein gehört Entschuldige ich mich für den post hier.

[log.txt](https://github.com/Courseplay/courseplay/files/3988981/log.txt)

**Comment by frm274** [comment]
Issue #4662 seems to be fixed in the latest version. 

But now, i cant assign Combines manually anymore.
Getting following Error when clicking on Combines name:
1 Error: Running LUA method 'mouseEvent'.
2020-01-01 20:41 C:/Users/FD/Documents/My Games/FarmingSimulator2019/mods/ZZ_Courseplay/settings.lua:1833: attempt to perform arithmetic on local 'line' (a nil value)

[log.txt](https://github.com/Courseplay/courseplay/files/4014478/log.txt)

**Comment by szimre** [comment]
Having the same issue (although the error mentions line 1164 instead of 1277 but I guess that's just a version difference.

Tried both _CombineUnloadAIDriver_ and _Mode2_ branches.

Seems like a mod conflict but I'm having a hard time figuring out what's causing it. If I try to load these Courseplay versions on my normal savegame it dies with the same error as above (CombineUnloadAIDriver.lua:1164: attempt to call method 'isAutoAimNodeFixed' (a nil value)). If I disable every other mod the issue goes away. However I tried creating a fresh savegame with every mod enabled (even the ones I don't use in my main save) and I don't get the error. I even tried purchasing most of the equipment that I normally have (as it seems they are not really loaded by just having them enabled) and failed to reproduce the issue.

I don't do LUA or GE development so I'm not sure how to do this or if it's even possible but if you could give me a snipped to plug into the _CombineUnloadAIDriver:updateFillUnitAutoAimTarget()_ function to see what causes the issue I could report back my findings.

Until then I defined the _CombuneUnloadAIDriver.autoAimNodeFixed_ variable as _false_ on initialization and that made it possible to load into the game without a LUA error. I did not have time to test this solution but I would imagine that this does not brake anything as these values will be properly set later on when the game is running. (again, I don't do LUA and I don't know enough about how CP or GE works to say that it's a proper fix but at least one can load the game this way)

Log file attached of main savegame where the error occurs before I added my makeshift fix:
[log.txt](https://github.com/Courseplay/courseplay/files/4554935/log.txt)

**Comment by pvaiko** [comment]
CombineUnloadAIDriver branch is not maintained anymore. The latest mode 2 changes are on the Mode2 branch.

**Comment by Tensuko** [comment]
#5272
