### ISSUE TITLE
I can't delete the saved course, there is no delete button on the dedicated server.

### ISSUE THREAD

**Issue by purel81** [Courseplay/courseplay#4716]
Hello!
I can't delete the saved course, there is no delete button on the dedicated server.
dedicated server, multiplayer.
the version of courseplay is the latest version . 350
all with coming holidays!

**Comment by Tensuko** [comment]
@davboecki
I already feel bad to always mark you :)

**Comment by davboecki** [comment]
This was actually done intentionally. See: https://github.com/Courseplay/courseplay/commit/1fdd50c1b7108 (from 2011...) . As I cannot see any technical reasons for it I can only assume that it was done to protect the courses because anybody can see and delete any course otherwise. Implementing a complete permission system for those courses or merging that with the farm system of FS19 sounds like a really big task, which I personally don't have time to do. 

So the question really is what are the solutions to this problem. Just remove the restriction?

**Comment by Tensuko** [comment]
I would say to make it run in general (also to share the courses) should make it without any restriction.
Not everyone plays FS19 is Versus Mode :)

**Comment by Lillemats90** [comment]
tbh i think the restrictions need to be there, when in multiplayer without dedicated server, the host is able to delete, this would be the case for dedicated servers to. altho the owner would need to do it in the files on the server. Maybe adding so that admins can delete wont be to much of a hassle?

**Comment by Tensuko** [comment]
That could be an other solution.
But I prefer the easiest way to make it work 1st, then later can change it to a more usable and complex system, if got the time for it.

**Comment by Artifysical** [comment]
Hey guys,

Why not taking advantage of something already existing?
Courses can be arranged in folders. So my thought on MP courses would be an additional top-level-folder by farmid. A copy function to send courses to other farms could complete this.
And maybe, when the Dev's start getting bored, you could add an admin feature where admins can access other farmid courses.

**Comment by Tensuko** [comment]
> when the Dev's start getting bored

Nice Joke :)
Thats why I said, make it the easy way 1st, so it is working at least.
Couse as @davboecki said, he got not time for something like that and we are already happy that he takes his time to make CP MP ready and there is still some stuff to do.
So when anyone else can add such a permission system its fine, but, make it work in general 1st....

**Comment by cwattyeso** [comment]
One thing I will add to this now that Courseplay is being adapted to and being made MP Ready, is that with many of the Companies players use for hosting and running their Dedicated Servers, such as Nitrado, Gameservers, Fragnet etc all the places Giants themselves recommend and link to on their site, there is a problem with how Courseplay saves files for Server owners.

For single player or local play it's not a problem, in your main Farming Simulator 19 save directory where you find your mods folder, save game folders, log.txt, modsettings folder and game settings, Courseplay generates and creates a folder called "CoursePlay_Courses" where it stores the saved courses of every map you play on with courseplay installed and activated. So if a single player runs into problems with a bugged or broken course that is causing issues in game or with the game even running and starting or loading a game if they have too many courses being loaded, they can go to this folder, and delete the courses manually.

However for Dedicated Server Owners and Admins they have no access via the the webinterface or even via FTP to the root folder or file structure of the server. Therefore they have no way to access or remove the CoursePlay_Courses folder and anything that gets created and stored inside it, nor can they access and change anything that gets put inside the modsettings folder. Now I know courseplay tends to save it's setting locally within each individual save game folder which is great, as server players can access this by downloading a zip of the savegame from the server, they can edit this and then re-upload the zip if they need to change settings.

However a server owner will never be able to access or delete CoursePlay_Courses and the files settings within. Not sure what the fix is for this unless there is a way when using Courseplay in Multiplayer, that the Courses Folder is generated and saved within the savegame folder.

**Comment by Tensuko** [comment]
Collecting all in #5484
