### ISSUE TITLE
Ropa Keiler 2 startet nach Abtanken Erntemodus nicht mehr und fährt ohne zu arbeiten weiter den Kurs

### ISSUE THREAD

**Issue by spiessphilipp** [Courseplay/courseplay#4793]
Der Ropa Keiler 2 Anhängeernter für Kartoffeln fährt nach dem Abtanken einfach weiter ohne den Erntemodus (Taste B) anzuschalten. Es werden keine Fehler in der Log oder am Bildschirmrand angezeigt.

**Comment by spiessphilipp** [comment]
Er macht es auch wenn er von einer Vorgewendebahn auf die nächste wechselt

**Comment by Tensuko** [comment]
Nach dem abtanken heist was ? Selber abtanken oder wenn ein Abfahrer den Ropa abgetankt hat ?

**Comment by 820fahrer** [comment]
Hi,

I had the same issue a few months ago. (I played a bit for my own and accepted this issue)
I was able to reproduce it:

The Keiler 2 has to change the "mode" to unload. It's not possible to harvest and unload at the same time.
When you drive to the Keiler and it recognizes the trailer in the unload trigger, it wants to start the unloading and changes the "mode". If you have disabled stop for unloading it doesn't stop.
When you enable stop for unloading and drive to the full harvester it's no problem to unload it. But you mustn't move the trailer, otherwise it's possible that the trailer enters the unload trigger again.

My suggestion is, to implement a check for the Keiler so it doesn't move while unloading and it has to check if it's harvesting anything while moving otherwise it should change the "mode" or stop and raise an error.

In my case I only had these problems when I wanted to unload it while driving.

**Comment by Tensuko** [comment]
Sollte mit dem neuen Mode2 funktionieren.
