### ISSUE TITLE
Courseplay - WRONG TOOL FOR THIS MODE (FS19)

### ISSUE THREAD

**Issue by lechotek** [Courseplay/courseplay#4963]
Courseplay - WRONG TOOL FOR THIS MODE (FS19)

https://youtu.be/tvHKsYejbC4

**Comment by Tensuko** [comment]
Thats correct, you should check the Mode Page on the HUD, last Button on the Top.

Closed.

**Comment by KITT3000** [comment]
@Tensuko Please explain why this is a valid message (what to check in this tab from bunker silo mode). Here (FS17) the course is recorded the same and everything works, and in FS19 recording of this course results in a message about a wrong tool: https://www.youtube.com/watch?v=N9GPi1uX4pc More precisely, this does not work with the "Driving through" option, and with the "Reverse unloading" option, the tractor enters the silo walls. In addition, the automatic setting of the blade width does not work.

**Comment by Tensuko** [comment]
What does the 1st option do on that page ?
Maybe you should try to change that... On your Video you didnt even changed to that page and this is FS19 and not FS17.

**Comment by KITT3000** [comment]
@Tensuko The first option is mode, I have "leveling and compacting" selected because I want CP to do it. When "Silo is being filled by" is selected as "Driving through", CP claims that I have the wrong tool, after switching to "Reverse unloading" it starts working (but I fill the silo by driving through it), but it rolls into the walls as if not took into account the width of the tool. And what has changed in this mode since FS17 because apart from cosmetic changes in the HUD I see nothing more (no new option to choose).

**Comment by Tensuko** [comment]
For leveling and compacting you got to use the holaras Stego 485.
Thats the different of the tools and it is not us who choosed this.
The Shield is just for the other mode when unload reverse.
