### ISSUE TITLE
Pipe always out during harvesting (Adv. Settings)

### ISSUE THREAD

**Issue by L2KPerma** [Courseplay/courseplay#4985]
So one of the things I find weather quite annoying is when using a chaser bin to allow the combines to continuously do work, once the combine hits empty, it automatically brings the pipe back in while you’re still chasing it, this then leads to the combine continuously moving the pipe back and fourth.

My suggestion would be to add an option on the advanced options screen to allow you to change the way this works and have two options, standard and always out.

**Comment by Tensuko** [comment]
See #3311 and #4286 
Closed.

**Comment by L2KPerma** [comment]
Would that still be the case in the case of using courseplay for the harvester but running the chaser yourself? Which to me doesn’t sound like mode2 (though to be fair I’ve only played with CP on 19) As that is what I mainly do, hence my sort of annoyance lol. Just wanting clarification as rereading what I posted I feel like it may not have clearly indicated my usage.

**Comment by Tensuko** [comment]
So it is more a case of how the Harvester behave.

What do you mean with combine brings auger back in ?

**Comment by L2KPerma** [comment]
Yeah lol, I’ve just been dealing with auger wagons all day in game so for some reason I just kept thinking auger and not pipe. Which certainly would have probably lessened the confusion.

**Comment by polosubtil** [comment]
If I may, I would like to add a few comments on that.
FYI, we use to combine like that in my farm when the machines were smaller. With our machine today, and the size and weight of the "pipe", it is way better to keep it close when you don't need it, otherwise it might break quicker than expected.

It would be a great advantage in some cases to be able to keep it open as an option in the advanced settings for example. But it could be a problem on the first headland when trees or obstacles are really close from the field. So in a perfect world, it's open all the time when harvesting except on the first headland or at X meters from the field limits (priority really really low ;)
It would also be great with root harvesters except for the one which can't open it without stopping (trailed potato harvesters I think)

**Comment by Tensuko** [comment]
Good point @polosubtil 
I also think like it is now is the best way.
Our Mode2 Planes are not given up.
Also you won't have to permanently make sure the Harvester keeps going when you let him unload by itself (yes it takes time too) or you have a look from time to time and time it when pipe is outside of the fruit.

Anyway I keep this Issue on 1st as suggestion, but we will think about it...

**Comment by Tensuko** [comment]
Closed as this won't going to happen.
What you can do is that the Combine always unfold pipe when it have to get emptied so you can aim better, or just use Mode2 :)
