### ISSUE TITLE
Global market triggers not recognised by courseplay

### ISSUE THREAD

**Issue by PromGames** [Courseplay/courseplay#4986]
@Tensuko, I have tried to unload with Cp in global market triggers and they are not recognised.

Normal global company triggers works fine but not this global market.

Prom

**Comment by Tensuko** [comment]
I know already.
I will have to talk to kevin about this, if the GC Market Triggers get registered the same as normal GC Triggers.

What I also noticed is, when the .exe is not running, you can't unload into that GC Market at all.

**Comment by kevink98** [comment]
See pull request -> https://github.com/Courseplay/courseplay/pull/4991

**Comment by PromGames** [comment]
Triggers working perfectly in Global Market with Courseplay

Thanks

**Comment by Tensuko** [comment]
It is not done yet and also not a finished release out...

**Comment by SAM24986** [comment]
Error: Running LUA method 'update'.
2020-03-01 00:21 C:/Users/sam/Documents/My Games/FarmingSimulator2019/mods/courseplay_FS19/helpers.lua:367: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by Tensuko** [comment]
Becouse it is not fully done yet.
I will let you know when its done...

**Comment by SAM24986** [comment]
Thanks, have a nice weekend

**Comment by Tensuko** [comment]
Preview and explanation:
You should create the course from the same side like I do or be more exactly where you position the start and stop points (I think stop is more important).
The Problem is, when I did it from the other side, it took the liquid Trigger as the 1st to unload from and ofc will tell you it doesn't have the selected Fruit/FillType.
Do it like I did (start between the trigger, stop a few meters before trigger) and it work with the next release Version :)
![fsScreen_2020_03_02_19_12_36](https://user-images.githubusercontent.com/27344744/75704992-b1824b00-5cba-11ea-9f17-18fb413c1dc0.png)

**Comment by Tensuko** [comment]
Since it is fixed I close this one.
