### ISSUE TITLE
Mini-HUD disabled by default

### ISSUE THREAD

**Issue by Aidelis** [Courseplay/courseplay#5002]
It would be really nice if there was an option to have Mini-HUD be disabled by default, because it's annoying to set it to disabled every time it resets to enabled. If it's too difficult to add a setting like that, maybe you could change it to be disabled by default?

**Comment by Tensuko** [comment]
@pvaiko 
maybe move that option to adv. settings since those options seems to be saved.

**Comment by 51stHD** [comment]
This is something I have for some time been meaning to ask for. I was also wanting to ask if we could have other options added to the advanced settings so that every time you buy or customize a vehicle you don't have the same settings click fest.

These are the ones I would really like to see added if at all possible.

1. Mini-HUD (as per OP)
2. Open HUD with (I use my right mouse button for something else so there is a clash with CP)
3. Stop during unloading (On all but the largest of fields I prefer the combine to stop and I rarely play large fields)
4. Fuel save options (I find this unrealistic as invariably the combine is off when you come to unload it. In reality engines are on all the time for air-con and or heating depending on the weather. It's rare that they get turned off)
5. Turn on field (Not essential but I would prefer this off as default)

Thanks for at least considering these other options as it would make using CP so much more comfortable, at least for me.

**Comment by cwattyeso** [comment]
Another small change I would like to see implemented alongside the disabling of the mini-hud by default on all vehicles, is when you go into the Advance Options Menu the options for Lower Tools and Raise Tools are actually the reverse of what they default to currently. I'm sure 99% of people change these two options on every vehicle so that Tools get lowered Early and they get Raised Late. However courseplay always defaults to the opposite way round.

**Comment by pvaiko** [comment]
@cwattyeso why are you change the lower/raise settings? Except for the plows and maybe the sprayers and tools with multiple work areas or multiple tools the default early raise/late lower should work fine.

**Comment by cwattyeso** [comment]
I just personally prefer all my tools to lower early and raise late, to ensure the Courseplay Drivers don't miss any parts of the fields they are working, doing whatever task I'm assigning them, be that ploughing, cultivating, seeding, fertilising, weeding, harvesting etc.

**Comment by Tensuko** [comment]
Is done, just noticed this Issue.
