### ISSUE TITLE
Crash Mode 2 + Mode 6

### ISSUE THREAD

**Issue by Vanquish081** [Courseplay/courseplay#5075]
Use normally the mode 2 more mode 6 with cobine and the game crash when change in the last moment to the tractor in mode 2.
[log.txt](https://github.com/Courseplay/courseplay/files/4350579/log.txt)

**Comment by PromGames** [comment]
Hello Vanquish081, did you have the straw harvest active and any machine bought, I suppose yes, and that’s the problem, if you take out the straw harvest add on and then their machinery, it will work fine. 

Pity is that we can not disclose the code of straw harvest to the cp devs because our NDA. This problem will be solved when the add on is published and the cp devs can adjust it accordingly.

Prom

**Comment by Tensuko** [comment]
You should not show arround your log with a NDA 'mod/addon' arround while still under NDA, that one just aside...
Anway, Mode2 is WIP, anything that got to do with it will be this one:

See #3311 and #4286 
Closed.
