### ISSUE TITLE
CP not loading generated Courses from AD

### ISSUE THREAD

**Issue by iljarogoff** [Courseplay/courseplay#5315]
![fsScreen_2020_05_06_16_29_00](https://user-images.githubusercontent.com/21023840/81189396-caf38c00-8fb6-11ea-9d2e-919d7c055341.png)

When trying to load or append the courses that are generated from AD destinations, they are not loaded. Courses made with CP itself load as they should.
Did I miss anything?

**Comment by Tensuko** [comment]
Logfile ?

**Comment by iljarogoff** [comment]
sry... here it is
[log.txt](https://github.com/Courseplay/courseplay/files/4587427/log.txt)

**Comment by Tensuko** [comment]
You should only have one map in Mods Folder.
That is very important.

Loginfo:
2020-05-06 16:38 :21 [info lp4272] N134: AutoDrive could not give us a course from the current position to Am Hofsilo beladen
2020-05-06 16:38 :21 [info lp4272] N134: id 10000 -> course not found, return

I remember I had this too once when I used AD 1.1.0.4
You could try reload the Course. I am sure that happens when the AD Network got an Error or something. Maybe you should try ask in AD GitHub Too if there is some Debug for AD you can turn on that will tell you more :)

**Comment by iljarogoff** [comment]
OK, removed the other maps from my mod folder, but that didn't help. Asked now in [AD git](https://github.com/Stephan-S/FS19_AutoDrive/issues/1410), will report back if they can tell me more

**Comment by Tensuko** [comment]
Still a Problem with CP .00064 and AD RC6 ?

**Comment by iljarogoff** [comment]
no don't think so
