### ISSUE TITLE
Combine don't work.

### ISSUE THREAD

**Issue by dexus92** [Courseplay/courseplay#5352]
[log — kopia.txt](https://github.com/Courseplay/courseplay/files/4605506/log.kopia.txt)
In newest version CP combine don't start harvest. Worker is active but he stop (key H). Don't start. I can't drive. I must use key H to off.

You can see it:
https://youtu.be/T8TNcHU19Iw

**Comment by Tensuko** [comment]
MP Server ?

**Comment by dexus92** [comment]
No. Only single with seasons (don't look on humidity). If is ok problem not solving.

**Comment by Tensuko** [comment]
Get newest Beta from Creative Mesh Discord:
Load mod: FS19_addon_strawHarvest (Version: 1.0.0.0) (Hash: 1d15f60600f67db89fc72447145539f4)

Update to the newest AutoDrive from AD GitHub:
Load mod: FS19_AutoDrive (Version: 1.0.6.9) (Hash: 1cd7d699a9d3fb524383922e17f324c4)

And I think the Mod that cause the Problem was FollowMe. I read that on LSMC iirc:
Load mod: FS19_FollowMe (Version: 1.6.0.29) (Hash: e399c9089ef81c9179a21a215170f672)

Ehm, you should not do this:
Load mod: FS19_GlobalCompany (Version: 1.5.0.0) (Hash: 6b47269558829bc3ca7095b78312d889)
Load mod: FS19_GlobalCompany2 (Version: 1.3.0.0) (Hash: 6142e17c16f72b33f738706fe8b16cdd)
Delete GC2 (1.3.0.0)

This is not where the Usericons should go, check LSMC Website for Details:
Error: Failed to open xml file 'C:/Users/jakub/Documents/My Games/FarmingSimulator2019/mods/fs19_globalcompany_usericon/modDesc.xml'.
Load mod: fs19_globalcompany_usericon (Hash: acf38b3d23b331ad085423e694bffb7d)
Error: Missing descVersion attribute in mod fs19_globalcompany_usericon

What does this do?
Load mod: fs19_coveraddon (Version: 1.0.0.0) (Hash: 581de397374e3a4d6bc514c47f495c5d)

**Comment by dexus92** [comment]
Yes. GC2 is in mod folder but is off for this save. Cover addon and autodrive too is off.

Old version CP worked fine with followme.

**Comment by Tensuko** [comment]
And I can confirm that the Combine all works fine with actual CP Version.

**Comment by dexus92** [comment]
I delete from mod folder GC2, coveraddon and autodrive, I deactivate follow me. And still not working,

**Comment by Tensuko** [comment]
Straw Harvest ?

**Comment by dexus92** [comment]
Updated from discord.

**Comment by Tensuko** [comment]
Thie should be redownloaded too, forgot to tell, they hopefully increased the Version finaly:
Load mod: FS19_addon_strawHarvestBonus (Version: 1.0.0.0) (Hash: d22b91ab8b399d815468276bf8d6e04e)

**Comment by dexus92** [comment]
I find this mod! It's heating plant for straw harvest.
http://www.farmingsimulator19mods.com/addon-straw-harvest-bonus-pellet-heat-plant-v1-0-fs19/

Only after is building. If is no build work fine, but if I build this building It is this problem.

**Comment by Tensuko** [comment]
This is becouse you have the day one version of this mod.
Sadly the update was also version 1.0 so it is hard to find out if you have the day one version. So if you download it again it should be the working one and iirc they updated the version to 1.0.1.0

**Comment by dexus92** [comment]
No. I have 1.0.0.2-beta straw harvest but heat plant I can see only v1.0.

**Comment by Tensuko** [comment]
Well, did you redownload it today from original link then ? If so that version should work.

**Comment by dexus92** [comment]
Yes. After your post I download newest version Straw harvest from discord (1.0.0.2).
And after I buy "heat plant" from link in previous comment you can see this problem. 
I sell this building (heat plant = FS19_addon_strawHarvestBonus) CP work fine.

Problem is with this heat plant. (FS19_addon_strawHarvestBonus)

**Comment by Tensuko** [comment]
Ok once again:
Redownload the plant star harvest bonus. Day one version cause problem.
The actual version should not cause problem.
I asked redownload the plant.

**Comment by dexus92** [comment]
Where is this new version? I see only this version (v1.0). 
I download other version (another source) and problem not solving.

**Comment by Tensuko** [comment]
....
Dowload ONLY from original source to get the working version. Search for it. It might be still version 1.0.0.0 but it is newer then day one and maybe they changed it to 1.0.1.0

**Comment by Goof245** [comment]
Actual source is (probably) here: https://creative-mesh.com/easteregg. 
Confusing AF when they have a modhub release, but then they've had a beta version out for a month linked from discord (which also can break saves if the pallets back up so GLHF). And also this "extra" mod thing..... Official stuff spread across at least three different sites.

**Comment by dexus92** [comment]
CP work fine with 1.0.1.0 version heat plant. Sorry. ;)
