### ISSUE TITLE
Homemade Fields cant find combine

### ISSUE THREAD

**Issue by knarffenfarmer** [Courseplay/courseplay#5372]
Hey

So here is the deal
I play on a map with no made fields from the beginning.
So I made a field and plowed it, I made the borders manually by driving around the edges of the field.
All works fine with tools and implements.
I set a combine to harvist the field.
When I set a tractor to unload combine mode and try to find the harvester its at something called (Field0).
It seems like the  tractor finds the combine, but it says "blocked" and wont come unload even I try and use the requestfeature when riding the combine.

Is this cause its not a preset field in the game?  Because it seem to be working fine on other maps.

//regards

**Comment by Tensuko** [comment]
Try this:
Drive on the Field with any vehicle.
Click calculate Field borders in the HUD.
A blue border Line should appear.
Now you can give this Field a Number.
Maybe this works. That Number can also be used to create Fieldwork Course.

**Comment by Misamangame** [comment]
Hello guys,

I actually playing also on map where fields are not numbered. Make a field and save it under number like Tensuko saying is ok for any tools including combine but probably not for unloader. Actually when I made a course for unloader he worked fine for the first time but when he came back from the silo empty he stopped on the end of the course flashing "no combine in reach" (Combine HUD shows him as requested driver). Exactly like knarffenfarmer said when you ticking combine it shows Field0 even when I have Field saved as #1. I also tried to save course with both ends in the field but it did not worked at all. I thought it was because I have a big field until I found this thread. I can provide log with debug channels if it helps, for me it is not a big issue atm...

**Comment by Tensuko** [comment]
Actuall the Field Number shouldn't have any impact on unloading the Combine (@pvaiko is it ?). As it just shows you where the Combine is running on, to filter this.
You always have to tick the right Combine, so the Fieldnumber is just to make it easier to sort it out.

**Comment by Tensuko** [comment]
Closed due to inactivity.
Fieldnumbers should have no impact.
