### ISSUE TITLE
Unloading Problems at Custom Silo

### ISSUE THREAD

**Issue by JoaoSilva1994** [Courseplay/courseplay#5395]
Ok, so i finally read all that is stated in #5272, and i can't find what you were trying to point me at @Tensuko.

Still couldn't fix the actual problem, i used a CP course for the harverster, and it goes well, the truck follows the chopper, until full, when it comes to unload, it doesn't unload anything, spent 5 minutes waiting to see if it unloaded 1l of chaff, but it didn't.

So, i don't know if you are telling me to look at #5272 to see that it is still no implemented, or to look for the fix for the problem. But i have seen some youtube videos, of people making it work, with custom Silos (Like mine) as well as with normal vanilla silos, but i can't find a way to fix it. Trying my best, and read the entire #5272 and all the issues that #5272 was mentioned, and still, no solution found for my problem. 

I'm leaving a screenshot of the problem below.
![fsScreen_2020_05_14_09_32_14](https://user-images.githubusercontent.com/9709349/81912050-f7fefa80-95c5-11ea-8006-28d2e6536877.png)
![fsScreen_2020_05_14_09_32_20](https://user-images.githubusercontent.com/9709349/81912054-faf9eb00-95c5-11ea-8ef7-c722c641c953.png)
![fsScreen_2020_05_14_09_34_31](https://user-images.githubusercontent.com/9709349/81912227-34caf180-95c6-11ea-8be9-87db0cb26c3e.png)

Works perfect until this point in the course, where it simply doesn't unload. After seeing several tutorials, where it works with these kind of fermeting silos, still can't find a way to get to unload in the silo.

Edited: To have a screenshot, of 1 or 2 minutes of waiting in the same spot, also added the log file just in case you need it, it has debug channels 1, 2, 4, 9, 11, 19 and 20 turned on, since they are the ones i think are related to the unloading problem, plus i'm using the Michigan Farms Map, and the BSM Trailer for the chaff haulage in the this particular case, but have the same problem, even with vanilla trailers. And the version i'm using, is the latest version, since i used the auto updater from #5135 to update to the latest version, because i tought it was a version problem or something.
[log.txt](https://github.com/Courseplay/courseplay/files/4627085/log.txt)

**Comment by evybart** [comment]
you have a unloading trigger and a loading trigger on the same place cp dont like that make sur the the two trigger are not an the same place then works it great

**Comment by JoaoSilva1994** [comment]
@evybart Never noticed that honestly. Well, gonna try with other silo i have, that has 2 separate triggers, to see if it works.

@Tensuko Don't close this yet, please, going to try with another silo, just to see if the problem persists, or if it actually having 2 triggers in the same place.

**Comment by Tensuko** [comment]
The point was no log no screenshots and no debug informations.
I didn't even know what unloading problem since this could be anything.
At least you finaly posted some needed information.....

Now to your Problem:
Never ever place a waiting or unloading point at a silo or trigger!
All you got to do is drive over it.
Waitingpoint = Wait there (or some mode for some other actions)
Unload Point = unload here, but that doesn't count for any trigger.

Remove the extra CP Version from Mods folder: Courseplay_6_01_00396 (Version: 6.01.00396)
You got the correct Version: FS19_Courseplay (Version: 6.02.00012)

Also you need the newest Version from Creative Mesh Discord:
FS19_addon_strawHarvest (Version: 1.0.0.0)

Not sure if this Mode can cause Issues:
FS19_AIVehicleExtension (Version: 0.0.6.5)

Have only one in your Mods folder (both same Version, remove the _dev):
Load mod: FS19_guidanceSteering (Version: 1.0.0.0) (Hash: 3645a5c70e203ab001c499805eb2c473)
Load mod: FS19_guidanceSteering_dev (Version: 1.0.0.0) (Hash: b854730c38d2fa3b1f5885125e6ba2dc)

Very Important:
Get newest Version of this from GitHub, else you will have loading problems on trigger (not unloading) Load mod: FS19_manureSystem (Version: 1.0.0.0)

And one more very important rule that always persists:
Only one Map in mods Folder!

As you see all this important Information I could never tell you without a logfile and screenshots.
And as I have made pinned Issues and references, some ppl still don't listen and give this information and I am getting a bit tired of it when I got to ask for everything and I could never think of asking you all the Versions and double Mods... Hope you understand this a bit.

@evybart 

> you have a unloading trigger and a loading trigger on the same place cp dont like that make sur the the two trigger are not an the same place then works it great

This is not a problem.
CP looks for a loading Trigger between stop and start.
But it only unloads in a trigger in the middle of a course (without any wait or unload points!!)

**Comment by JoaoSilva1994** [comment]
@Tensuko Ok, i finally got it to work, since i changed the silo from the one in the pictures, to another i have, that has 2 separate triggers, it works perfectly, on the screens, i actually had to put the trigger by myself, cause without it, the truck was just going right trough without even giving the "Trigger Found" message on the bottom. And that's why i have the trigger placed there, to make it unload where he needs to unload. Didn't try it out with the new silo, but i will, as soon as the field is ready for harvest again.
In terms of the issue itself, maybe there is somekind of conflict with the T800 Fermeting Silo, cause it works with this new silo i have, but not the T800.
![fsScreen_2020_05_14_11_12_01](https://user-images.githubusercontent.com/9709349/81922370-ee7c8f00-95d3-11ea-989b-d7c75e97502d.png)
![fsScreen_2020_05_14_11_12_15](https://user-images.githubusercontent.com/9709349/81922391-f3414300-95d3-11ea-86d6-e79a81f8bd01.png)
![fsScreen_2020_05_14_11_12_31](https://user-images.githubusercontent.com/9709349/81922397-f63c3380-95d3-11ea-9eee-3771e17831b2.png)
![fsScreen_2020_05_14_11_12_35](https://user-images.githubusercontent.com/9709349/81922399-f6d4ca00-95d3-11ea-9102-29e8fc5d1f66.png)


It's been working for the past 10 minutes, and they are following the combine, with no issues at all, and then, both trucks are going to the silo, they unload and back to the combine, they are working like swiss watches.

That Double mod problem, i downloaded a couple of packs from 2 different servers, and never went and checked if there was any repeated mods in the folder.
Going to take care of it now!

I have been using AIVehicleExtension before i found the proper way to install CP6, and since then, i never erased it at all. Michigan Farms Map has some nasty ducts around some of the fields, and since i got CP, never had trouble, and before that i had some troubles with the AI workers, even the vanilla one, cause they would think the ducts were just normal, leveled terrain.

Going to take care of the double mods, and the versions of some of them.

About the maps, any reason for having just one map on the mod folder?
Cause since FS15 i have like 7 or 8 maps in the mod folder, and never had problems with CP because of that.

But i'll change places anyway.


Honestly, once i actually started reading some of the issues from other people, i noticed that it was my fault, since i didn't post any information about the issue itself, and i was frustated and didn't even tought about it.

So, i'm the one who needs to apoligize about that, i'm really sorry, the frustation made me not think at all, after almost 6h of trying to figure it out, of why the truck didn't want to unload at all! So, again, i'm so sorry for wasting your time, with the 2 other issues that i posted.

**Comment by Tensuko** [comment]
I will try that silo since I got to too, maybe I find whats wrong, thx for the information.
Anyway, the rule with do not place unload or wait trigger at the silo is important and I had to teach several ppl about this :) 

> About the maps, any reason for having just one map on the mod folder?
> Cause since FS15 i have like 7 or 8 maps in the mod folder, and never had problems with CP because of that.

Some maps got scripts in it and when you have some maps loaded with scripts, they can conflict. That is not only a problem for CP, but also for other Mods. It can work, but it also can cause trouble.



> But i'll change places anyway.
> 
> Honestly, once i actually started reading some of the issues from other people, i noticed that it was my fault, since i didn't post any information about the issue itself, and i was frustated and didn't even tought about it.
> 
> So, i'm the one who needs to apoligize about that, i'm really sorry, the frustation made me not think at all, after almost 6h of trying to figure it out, of why the truck didn't want to unload at all! So, again, i'm so sorry for wasting your time, with the 2 other issues that i posted.

Well I can understand your frustration, but mostly when you provid needed information we can mostly help you :) I make several tests with CP and I know whats definitly working and how it should work. Most things are Mods or User Errors and that we can find out for sure without frustration ;)

Anyway, hope you can enjoy it a bit now.
Closing this as beeing solved.

**Comment by JoaoSilva1994** [comment]
Is it normal after the three fine loads and unloads, the chopper stops? And then the truck returns to the field, and just stops, without going to the combine?

**Comment by Tensuko** [comment]
debug channels and screenshots with logfile :) so we can see what he tries to do.

**Comment by JoaoSilva1994** [comment]
It actually stopped doing that, when i restarted both courses, chopper and truck, and took one of the trucks out. Don't really know what happened, maybe it conflicted with the second truck?

If it repeats the same thing, i'll get the debug channels and log uploaded.

**Comment by JoaoSilva1994** [comment]
@Tensuko By the way, just in case you are in need of that. I'm portuguese, and if you need help translating CoursePlay to portuguese, hit me up on discord or on Facebook trough a PM, and i'll be proud in helping out this great mod !

[https://www.facebook.com/joao.p.c.silva/](url)
Discord - JoaoSilva#9117

**Comment by bullfrog-au** [comment]
Also have this issue with CP and T800 silo.
Course with no tip trigger will drive directly through the silo without unloading.
Adding a tip trigger at the unloading point will cause the unloading animation to begin, but actual transfer never starts. Tractor just sits in the unloading zone forever.
CP version 6.02.00048 
T800 Silo version 1.1.0.0
I have only tried this on the "No mans land" mod map.
Tractor and trailer are from the CLAAS mod pack.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/releases/tag/6.02.00049
