### ISSUE TITLE
Mode "Work with combines"

### ISSUE THREAD

**Issue by Yaroslavskii3** [Courseplay/courseplay#5507]
Hi, I have a problem. In new versions of Courseplay, the "Work with combines" mode does not work, in older versions everything works. How to fix?

[Screen: old version](https://imgur.com/a/xKqcXoQ)
[Screen: new version](https://imgur.com/a/sCZlqbx)

**Comment by Tensuko** [comment]
#5272 logfile........

**Comment by Yaroslavskii3** [comment]
did not quite understand what to do

**Comment by Tensuko** [comment]
Attach log.txt from My Games\FarmingSimulator2019\
Just drag and drop that log into comment box.

**Comment by Yaroslavskii3** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4701065/log.txt)

**Comment by Tensuko** [comment]
You have to delete those:
Load mod: Courseplay_6_01_00385 (Version: 6.01.00385) (Hash: a59d8e9f20ac0dd4304c80f2037b2326)
Load mod: Courseplay_6_01_00387 (Version: 6.01.00387) (Hash: 38b5a192866cd2cb5864ec5d7f373c19)
Load mod: Courseplay_6_01_00388 (Version: 6.01.00388) (Hash: b1b18f7986c93dabc0ba9d68923c5c98)
Load mod: Courseplay_6_01_00389 (Version: 6.01.00389) (Hash: bb82bbf7d1ccb84ce6980993f1b07f24)
Load mod: ZZZ_Courseplay_6_01_00145 (Version: 6.01.00145) (Hash: d0028bc4a81e0cd9058f766c2b0f9086)

And rename this: Load mod: FS19_Courseplay_2 (Version: 6.02.00020) (Hash: 11337cd60e949f9e3637c70433388122)
To just 'FS19_Coursepaly.zip'

**Comment by Yaroslavskii3** [comment]
didn't help
[Screenshot](https://imgur.com/a/rvViP8L)

**Comment by Tensuko** [comment]
Can you show me your new logfile ?

**Comment by Yaroslavskii3** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/4701518/log.txt)

**Comment by Yaroslavskii3** [comment]
If you do not know how to solve the problem, then I will return to the old version

**Comment by Tensuko** [comment]
If I can say there is no other problem I would say it is your Mod Truck.
And since it still doesn't work and beside 2 Mods with Errors it looks good, I would say your Truck got a Problem. What I can tell you for sure is that the new Version does work.

![fsScreen_2020_05_29_13_35_49](https://user-images.githubusercontent.com/27344744/83255783-62608f00-a1b1-11ea-9310-9848fd2e7fa5.png)

But ofc your are free to use the Version you like.

2 Mods with Errors:
Error: Failed to open xml file 'D:/Documents/My Games/FarmingSimulator2019/mods/garaz/modDesc.xml'.
Load mod: garaz (Hash: b8b8479d5eebe70b80db66604d81da20)
Error: Missing descVersion attribute in mod garaz

Error: Failed to open xml file 'D:/Documents/My Games/FarmingSimulator2019/mods/UMZ_6KLM_converted/modDesc.xml'.
Load mod: UMZ_6KLM_converted (Hash: 1173afe0fb1a157abacb8bf0273ed28a)
Error: Missing descVersion attribute in mod UMZ_6KLM_converted

**Comment by Tensuko** [comment]
Very strange is that your Truck can use Mode8, I am 100% sure there is something wrong with it.

**Comment by Yaroslavskii3** [comment]
There are also trucks in which work with combines is not available. I will probably use standard trucks and trailers

**Comment by paul-dotcom** [comment]
Hi, i think, i got the same problem. i tried to chop grass, but i can't choose a Harvester in the menu.. i tried it without mods, only CP6 activated, too.
[log.txt](https://github.com/Courseplay/courseplay/files/4707350/log.txt)
![fsScreen_2020_05_30_19_40_47](https://user-images.githubusercontent.com/66199602/83348181-6c59cd80-a32a-11ea-9241-3f57b94b3da8.png)

**Comment by Tensuko** [comment]
But there is the 9000 Series, isn't it the JD Chopper ?

**Comment by Tensuko** [comment]
Closed due to inactivity
