### ISSUE TITLE
Trucks/Light Vehicles Driving with no headlights at night time

### ISSUE THREAD

**Issue by looksALittleDodgey** [Courseplay/courseplay#5542]
First of all, I wish to congratulate you all on the best mod available for Farm Sim, if it wasn't for your mod I would have easily given up out of sheer bordem a long time ago.
So thank you for your continued development, it's amazing how talented you guys are and to what CP can do for us players.

Just a minor issue from me is the trucks I use of a night time to cart the grain from Silos to the Selling Points, the trucks drive with Parking Lights on, but no headlights.
This may be because of the multiple light types being used in mods whereas the standard vanilla trucks only use 1 light type which is 0, but is there any chance we can either;
1. Have the ability to turn on/off the vehicle's lights whilst under control by CP? or 
2. Add addition checks in the software and if >0 use 1 which will be then parking lights and low beam headlights?

I haven't included a log as it is really only a thank you and a question.

Thanks

**Comment by ddewar** [comment]
Hey @looksALittleDodgey, can you link to a truck mod where you see this? I'll take a look at it when I get some time.

**Comment by looksALittleDodgey** [comment]
Hello @ddewar  , thanks for the offer to help,

Here is the link to the T908 I use

http://www.farmingsimulator19mods.com/kenworth-t908-v1-0-0-0-fs19/

and to download it from here

[https://l.facebook.com/l.php?u=http%3A%2F%2Fwww.mediafire.com%2Ffile%2F8ytxtg55ze1biez%2FFS19_KenworthT908.zip%2Ffile%3Ffbclid%3DIwAR1VoSYjhU8H0da6pxA5CG4CgA0-MUkmCJhtrX7qpl4SseI_bWcvcJcesuY&h=AT3SITNwQYuRkxLlsZ3CBDvNKYiPtadyk08rrk-jOlKYdYQvZaTV3rzwg-Dpug9UtcsAeJjyTudihlrGOb03W_0tcw1ymWiRcyAPbdf1zMEFhEKW6r1hz7IgMV-71bf_QTSsg0M6cK2IXZ_i7NTJxU5JbUeVMUyIsNUrkIUs27ibvvZH8CJesWCTOac9ecRzclQEfHGK5rgsOGK5zMgor9CMDLBrFuSjD1SHZJqAjz7C7Ws4s8Fo26axPP0cFKEff4_LGIaYRNxmDqjSsYmjU9lLWmCYHm0hz2er9PqXDtWe9p3S20doVldG9ESxxFwKyYud-MuS-_ALe8h3HoIM25E8wPgouupqLDXZANQdWs1MNSYRCAcV8KJmqp51qpQ1wAPfztDEdqGJUZzjPnwJnqXkgprbPAG6OyxW3R1slzUs7CwndciR2Kx9Zt3_uyWnNHcsi-Rd696-Meupdx1gO34rWSlnKbQpBvEfRAv7avAlyccrFAU4_mrn79Y2-YbQsdhcHurBF-gLX9WDeOI3pQeLI-nChmV3pVZ1rldiUOvMofuhcdB0DzeWvG-j63KqE4LjyGWZZA9aF4O5buUXPIW1cWDjo2wezyMRhSMutbQymMUIurSDJ4G4f58sGd_GzO07wgKMcBHW6ns](url)

Thanks,

**Comment by ddewar** [comment]
Hey again @looksALittleDodgey, 

I took a closer look into this. It looks like trucks like this are slightly misusing the lightTypes in the xml of the vehicle. By changing lights that were set to `lightTypes="1"` (Back work lights) to `lightTypes="0"` (front lights), I was able to get more of a Farming Sim standard light mode. (There's also a headlight lightType the mod could be using but isn't.) I know it's not much of a solution, but unfortunately, without really complicating things, we need to try to stick close to the Giants standard light workflow. 

As far as an option to turn on/off lights while in control by CP, I will leave it up to @Tensuko and crew to decide if it's worth another setting. In most cases, this hasn't been an issue, because the lightTypes are more predictable.

**Comment by looksALittleDodgey** [comment]
Hi @ddewar 

Thanks for the follow-up, I assumed that may have been the case. I was hoping CP could so an additional check to see if light states are greater than 0

eg
	<states>
			<state lightTypes="0" /> (park lights)
			<state lightTypes="0 1" /> (Low Beam)
			<state lightTypes="0 1 2" /> (High Beam)
        </states>

But I understand it may not be possible and I will just make do we what we have.

Thanks again for your time.

**Comment by Tensuko** [comment]
Mod Issue.
