### ISSUE TITLE
Narrow Up-Down at the beginning of the course

### ISSUE THREAD

**Issue by Clouseau219** [Courseplay/courseplay#5660]
Hi,
is there a way to avoid this situationat the beginning of the course? 
![DELL-6GV1H32-WX-2020-06-22 12_57_44-unknown png (959×734) und 17 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/16350763/85281674-b72eb700-b48a-11ea-87e5-b0cb2f29fa1e.png)

It is no problem with one helper but if you use >=2 then the helper will collides.
Happend yesterday with 2 30m Bourgaults

thx,
Gobo

**Comment by Tensuko** [comment]
Only by reduceing the work width to have a more even rows.

**Comment by Clouseau219** [comment]
Would be a nice feature if cp could calculate the perfect work width, since cp has the field data. :) Or is there a way to get length and width of a field?

**Comment by masneoquil** [comment]
You could also change the Headland Overlap when creating a course.
In your case if you decrease the overlap, that row will get thinner until disappears. If not, you could increase it, until it get as wider as the other ones.

**Comment by enderwiggin07** [comment]
I don't think it's very realistic to eliminate a narrow row by intentionally overlapping every row.  Something I do see though, is in the case that not all rows are equal length, the narrow row should be put on the shortest row.  So in OP's example the narrow row should have been at the end of the course to make the narrow row the shortest.   

Another nice thing might be to give the user the option to just not do the narrow row from the course generation screen, because sometimes it is very tiny to the point that from the game's perspective, there isn't even any fruit or unworked ground left on the narrow strip, or so little that the user might not elect to do it under certain circumstances, like when spraying.

**Comment by masneoquil** [comment]
The Overlap option it is not for the up and down rows but for the headlands. In a 2 headlands course, only one headland gets the overlap percentage that you choose up to 20% max.

**Comment by Tensuko** [comment]
All headland rounds are getting the overlap.

**Comment by masneoquil** [comment]
I stand corrected :)

**Comment by excubated** [comment]
> All headland rounds are getting the overlap.

Wait, how do you overlap ? Is 10% overlap on a 10m header sticking 0,1m outside the field on first headland?

**Comment by enderwiggin07** [comment]
In your situation your up down rows would pretend there was a 9m headland

**Comment by pvaiko** [comment]
> Would be a nice feature if cp could calculate the perfect work width, since cp has the field data. :) Or is there a way to get length and width of a field?

Not sure how that would help, you'd have every up/down row overlapping meaning collisions everywhere when using multiple tools. Also remember not all fields are rectangular. 

Not going to change this.
