### ISSUE TITLE
triggers.lua:462: attempt to index field 'storages' (a nil value)

### ISSUE THREAD

**Issue by Knowen** [Courseplay/courseplay#5823]
Hi everyone,

Since a few versions, I can't use CP anymore. Every time I load an old course, or I generate a new one and press start; I get this error inside the log:

`2020-08-02 12:17 Error: Running LUA method 'mouseEvent'.
2020-08-02 12:17 D:/LS19 Mods Wild West/FS19_Courseplay/triggers.lua:462: attempt to index field 'storages' (a nil value)`

The tractor or combine doesn't move. I have to release the course from the tractor, to be able to move it again.
I'll post some screenshots later. 

Here is the log:
[log.txt](https://github.com/Courseplay/courseplay/files/5011969/log.txt)

And yes, I know there are some errors/warnings related to the Xerion. I'm working on that.

Thanks for help,
Knowen

**Comment by Tensuko** [comment]
Download this again only from the official easter egg website to get the updated Version:
Available mod: (Hash: b9644349211bcbf097298e0bbcdf88ac) (Version: 1.0.0.0) FS19_addon_strawHarvestBonus

This one COULD couse a conflict, never tried it:
Available mod: (Hash: 14d3d0119d9aff4b920a9c3b051f4402) (Version: 0.0.7.1) FS19_AIVehicleExtension

And you got a callstack from anything.
But I am very sure the Error is caused by the old Version of StrawHarvestBonus.

**Comment by Knowen** [comment]
You were right. I updated the StrawHavestBonus Mod and the error disappeared.
