### ISSUE TITLE
New version bugs, some comments

### ISSUE THREAD

**Issue by wertigoxxx** [Courseplay/courseplay#5860]
Problem 1.
the planned route in many cases collides with the other vehicle

Problem 2.
very long route search, few fps (20-25) or you can't even find the combine or the forage harvester!

Problem 3.
Turning on the plant avoidance, yet there are vehicles moving!

Problem 4.
When the trailer fills up, it starts to back away from the tractor, which is behind an obstacle not detected! It says the tractor spins! Course stops, restarts, and continues. It doesn't work well!
![fsScreen_2020_08_05_23_32_32](https://user-images.githubusercontent.com/65092037/89467012-1e6fa480-d775-11ea-90b4-1b0c11b21d52.png)

Problem 5.
When AIdriver is turned on, vehicles roam.

![fsScreen_2020_08_02_19_29_32](https://user-images.githubusercontent.com/65092037/89466962-0ef05b80-d775-11ea-9252-7933bde7532c.png)

![fsScreen_2020_08_05_23_26_30](https://user-images.githubusercontent.com/65092037/89466974-14e63c80-d775-11ea-8bfa-84840e074c9f.png)
![fsScreen_2020_08_05_23_28_24](https://user-images.githubusercontent.com/65092037/89466993-19aaf080-d775-11ea-9547-9192c5c2ece0.png)
![fsScreen_2020_08_05_23_32_34](https://user-images.githubusercontent.com/65092037/89467031-23ccef00-d775-11ea-906c-bdb0b49f5405.png)
![fsScreen_2020_08_05_23_38_06](https://user-images.githubusercontent.com/65092037/89467037-2891a300-d775-11ea-9d8b-d3855689430f.png)
![fsScreen_2020_08_05_23_38_34](https://user-images.githubusercontent.com/65092037/89467046-2d565700-d775-11ea-8db9-6f7996a01a4d.png)
![fsScreen_2020_08_05_23_38_44](https://user-images.githubusercontent.com/65092037/89467053-321b0b00-d775-11ea-990c-4afcde9cc79f.png)

In summary:

The CP thinks for a long time, it takes a very long time to plan a route.
Until the forage harvester cuts the crop around the ground, it will be very difficult or impossible to find the tractor route.
Unfortunately, the new "undload harvester on first headland" function does not work.
If the silo tube is short, it will constantly run into an obstacle and stop!

On the ground at the rounds the combine or silo leaves the plants, always leaving a small one at the rounds.

Overall, you did a good job, thank you!
I hope these bugs are fixed and we are happy to play with CP!

Regards

----------------------------------------------

Zusammenfassend:

Der CP denkt lange, es dauert sehr lange, eine Route zu planen.
Bis das Silo die Ernte um den Boden schneidet, wird es sehr schwierig oder unmöglich sein, die Traktorroute zu finden.
Leider funktioniert die neue Funktion "Harvester auf der ersten Landzunge entladen" nicht.
Wenn das Silorohr kurz ist, stößt es ständig auf ein Hindernis und stoppt!

Bei den Runden auf dem Boden verlässt der Mähdrescher oder das Silo die Pflanzen und hinterlässt bei den Runden immer eine kleine.

Insgesamt hast du gute Arbeit geleistet, danke!
Ich hoffe, diese Fehler sind behoben und wir spielen gerne mit CP!

Grüße

LOG:
[log.txt](https://github.com/Courseplay/courseplay/files/5031400/log.txt)

**Comment by Tensuko** [comment]
> Problem 1.
> the planned route in many cases collides with the other vehicle

The Problem is more complex then just this. Tractors and Combines do easy avoide each other, Trailers are not calculated into the Pathfinding. Also you use more then one Unloader, that is not supported yet.


> Problem 2.
> very long route search, few fps (20-25) or you can't even find the combine or the forage harvester!

We know that, can't do much about it right now. What does help is to turn off Avoid Fruit ONLY on the Unloader, more details in Wiki: https://github.com/Courseplay/courseplay/wiki/Mode-2-and-Mode-3-FAQ


> Problem 3.
> Turning on the plant avoidance, yet there are vehicles moving!

Don't get this.... keep Avoid Fruit on for Harvester, turn off for Unloder if your Routes are to complax and it takes to long to calculate them. Anything more, read Wiki.


> Problem 4.
> When the trailer fills up, it starts to back away from the tractor, which is behind an obstacle not detected! It says the tractor spins! Course stops, restarts, and continues. It doesn't work well!

We will have a look at this. Should not reverse all them time, but I remember there was a commit that added this, maybe have to add some checks or something. Basically if you start it then with first waypoint, it should directly drive to the unload course, if not there is a bug.


> Problem 5.
> When AIdriver is turned on, vehicles roam.

No Idea...

About Pics:
- again, more then one unloader is not supported yet.
- Unload Moving Combine on first Headland should be an option for the Harvester, as he controls the Unloader when they have to come
- Path thrue the Fruit is when Avoid Fruit is off or when he haven't found a way in some trys

**Comment by pvaiko** [comment]
Thanks for the screenshots, these issues were already reported by other users. Keep in mind that I don't have the mental capacity to track 12 different problems reported in a single issue. 

Sooner or later we'll fix these...
