### ISSUE TITLE
Mode 9 shovel doesn't recognize trailer

### ISSUE THREAD

**Issue by alepinci** [Courseplay/courseplay#5998]
hi I have a problem with mode 9. I created 2 courses, one for the wheel loader and one for the tractor that will unload the silage at the silo. The problem is that the loader only "recognize" the trailer if it's filled with a bit of silage, otherwise the wheel loader stops a few meters away. Any advice? 
(when the tractor returns from the silo I have to fill it manually for the first time, then it goes without problems)
![fsScreen_2020_08_28_23_47_23](https://user-images.githubusercontent.com/38883600/91617723-e8df6500-e988-11ea-8605-401b6ec7b817.png)

**Comment by ontot** [comment]
try to do the path of the shovel again ... try to stop closer or further away from the trailer ... you will see that it works perfectly

**Comment by schwiti6190** [comment]
@alepinci is this one still relevant or an active problem ?

**Comment by alepinci** [comment]
> @alepinci is this one still relevant or an active problem ?

Yep. I did the patch of the shovel again but when the tractor returns from the unload silo, the loader doesn't recognize it until i load a bit of silage.

**Comment by Crinouche** [comment]
I also have the same problem and this since version 6.02 0046. I have already reported it.
I was told to redo my courses. What I have done. But nothing helps. it still does not work.
And to this day, I don't have an answer or a solution. So I went back to version 6.02.0045

**Comment by Tensuko** [comment]
Version 55 no Problem at all...
![fsScreen_2020_09_11_14_36_28](https://user-images.githubusercontent.com/27344744/92926582-884a3080-f43c-11ea-8c67-60495306d244.png)

**Comment by polosubtil** [comment]
Hi @Tensuko,

I can't say it does it all the time but it happens to me quite often. At least for the first time you want to load the trailer
Here you can see the telehandler waiting. If I stop courseplay, load it manually and restart Courseplay, every works like a charm.

![fsScreen_2020_09_11_18_14_28](https://user-images.githubusercontent.com/60451845/92949080-c2c2c600-f45a-11ea-8ba9-a19f498b41c7.png)
![fsScreen_2020_09_11_18_14_38](https://user-images.githubusercontent.com/60451845/92949098-c9e9d400-f45a-11ea-8fad-9faadd0483a6.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5210298/log.txt)

**Comment by Tensuko** [comment]
even when log say 'Trailer found' he doesn't move to unload ?

**Comment by polosubtil** [comment]
Yes that’s correct

**Comment by polosubtil** [comment]
I have done some tests trying to understand what is happening here. I realize something I can't explain => I am loading 2 trailers to sell silage to the BGA. If I leave it as usual, when the 1st trailer is full, the shovel is only half empty. The telehandler then reverse and reload to get a full shovel. The next trailer goes to the loading area and the telehandler stops (same situation as the posts above)

So after that, I tried to reduce the filling % of my trailers so they could be filled with a full shovel before leaving. In that case, you only have to fill one shovel in the very first trailer and after that it works. It's like the issue is coming from the fact the shovel is half empty and then reloaded for the next trailer.

Not sure that clear ;), just let me know if you want me to do some more tests

**Comment by Evolution120** [comment]
Hello everyone,

i ve got the same problem.
Currently i am using 6.02.00064, but i also mentioned the same issue with previous versions (***42).
Problem:
Wheelloader stops before it reaches the 3rd waiting point.

Extended Information:
The problem is not related to the type of wheelloader / tractor.
The problem occures wheter there is a trailer or not.
The problem occures with all loading levels. 
The Problem also occures when changing direction, distance and position of Trailer / WP-3

This is my first post here. If you need any additional Information or any other support to understand and solve the problem, let me know.

![fsScreen_2020_09_23_10_28_59](https://user-images.githubusercontent.com/71757583/93990216-27e7b700-fd8b-11ea-95fc-20028c2d7aea.png)

**Comment by Tensuko** [comment]
@Evolution120 
I can tell you why he doesn't fidn the Trailer.
Your path towars the trailer is not straight enough.
![Mode9](https://user-images.githubusercontent.com/27344744/93991023-1c48c000-fd8c-11ea-9272-1ac8508c0cf2.png)
You would have enough space to create a propr course.
The System in general does work, I was even able to fill up a SeedHawk with a Wheelloader.
To see the Target Area, activate debugchannel 10 (?)

**Comment by Tensuko** [comment]
@polosubtil 
I will do some tests later this week to see whats happening here.

**Comment by Evolution120** [comment]
> To see the Target Area, activate debugchannel 10 (?)

Thanks for this tip. I did not know how to use the debug channels.
Now eveything works as it should. 
BR, Evo.

**Comment by Tensuko** [comment]
@schwiti6190 
for the original Problem of this Issue:
I had a Mode9 Wheelloader running a long time from a Bunkersilo bringing stuff to BGA and works without any Problem.
Then I needed some of the stuff and sneaked a Trailer inbetween the path to the BGA Bunker and it was filled without any Problem.
Then when he empty the shovel half way, couse Trailer was full, I moved the Trailer out of the way and was hope he continue its normal work. But no matter how many times I restart the Mode9 Driver, just for BGA or the now empty again Trailer, it won't unload, ending up in this Screenshot. Something gets stucked, could you take a look at this ? Wonder if Debugchannel 2 would help too ?
![fsScreen_2020_09_26_16_56_48](https://user-images.githubusercontent.com/27344744/94343582-57135800-0019-11eb-8996-81b09d668bc4.png)

**Comment by Crinouche** [comment]
224/5000
Hello
it still does not work. I have redone my routes many times and the shovel cannot find the trailer. As soon as I put some silage in the trailer, it works.
Please take a look at this problem
![image](https://user-images.githubusercontent.com/36656729/97090838-fb4be700-1637-11eb-99c9-cb650e9c9328.png)
![image](https://user-images.githubusercontent.com/36656729/97090894-00a93180-1638-11eb-9f4b-983aa67e280e.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5433545/log.txt)

**Comment by Tensuko** [comment]
This got enhanced a lot and should work now.
