### ISSUE TITLE
Vehicle unloading problem on uneven terrain, Ropa Panther 2

### ISSUE THREAD

**Issue by SirAdams** [Courseplay/courseplay#6053]
This equipment has something like slope leveling. It sounds nice, but there is a problem with CP in such terrain because in manual mode I can use the J / N / K / M keys to set the height and slope of the transmission belt, or whatever it is called.
Would it be possible to add an option to the CP so that when tilted to the left, this transmission belt was set higher so that the tractor with a high trailer could easily drive up?
Of course, when tilting to the other side, there is no such problem.
![20200910195342_1](https://user-images.githubusercontent.com/2748305/92781166-2c33cd80-f3a4-11ea-97dc-9ffeca0caf66.jpg)

**Comment by pvaiko** [comment]
Sorry, what is AC?

**Comment by SirAdams** [comment]
sory, CP ;) courseplay

**Comment by Hammerhi99** [comment]
Have the same issue. I was really wondering why this problem is mentioned so rarely across the net, especially on youtube you allways EVER see only Ropas getting unloaded in maps like NF-Marsch or Multimap 2019 with 99% flat terrain. But it doesn´t take much to run into this problem. 
Main part of the problem imo is, that each time the Ropa is full and calls for unloader, it resets the work angle of that transmission belt (or whatever its called^^) to default.

**Comment by GeorgeEarslight** [comment]
@pvaiko 
Perhaps if the trailer class has collision information (does it have a height marker?) 
and the pipe spec is controllable (apart from open/close) we could add a simple closed loop.
I'll try to take a look.
