### ISSUE TITLE
CombineUnloadManager.lua:57 Randomly stops responding during fieldwork / new course

### ISSUE THREAD

**Issue by AlexanderSS19** [Courseplay/courseplay#6058]
No idea what's going on with it. Never had such issues. It just goes bananas and keyboard inputs won't respond either. Can't save and exit the game, the only way is to alt+f4

2020-09-11 23:51 C:/Users/47941/OneDrive/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadManager.lua:57: attempt to call method 'is_a' (a nil value)
2020-09-11 23:51 Error: Running LUA method 'update'.

**Comment by SirAdams** [comment]
I have the same problem. v.054 and v.056
Field 5, Contract work. 
![20200912050551_1](https://user-images.githubusercontent.com/2748305/92985748-b9b31280-f4b5-11ea-8453-8069991029ce.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/5212101/log.txt)

**Comment by Tensuko** [comment]
@AlexanderSS19 logfile ?!

@SirAdams 
.00056 should have fixed it

**Comment by SirAdams** [comment]
020-09-13 04:01 Error: Running LUA method 'update'.
2020-09-13 04:01 E:/Documents and Settings/Marek/Moje dokumenty/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadManager.lua:57: attempt to call method 'is_a' (a nil value)
Contract work field 13
Ropa Keiler 2
![20200913040654_1](https://user-images.githubusercontent.com/2748305/93008594-baf84400-f576-11ea-836d-56d0f199e5b0.jpg)
[log.txt](https://github.com/Courseplay/courseplay/files/5213509/log.txt)
Are you sure these are two other mistakes? because so far there are only other fields on the same trailer.

**Comment by AlexanderSS19** [comment]
Same story with a fresh savegame, but different error this time. 

[
[log.txt](https://github.com/Courseplay/courseplay/files/5221113/log.txt)
](url)

**Comment by pvaiko** [comment]
You are running version 56, there's a fix out there v58
