### ISSUE TITLE
[Request] Multiple Mode 3 Unload Points

### ISSUE THREAD

**Issue by MtBakerScum** [Courseplay/courseplay#6152]
Would it be possible to get add multiple unload points to Mode 3? For example, I have 2 trailer setup running grain from the field to the sale point.  I would like my tractors to fill the rear trailer first, and once its full, move onto the front trailer and unload there. Pic for reference on the setup.

Thanks, and I cannot express to you how much I love CP,  it is absolutely fantastic.
![20200930194328_1](https://user-images.githubusercontent.com/54657774/94759951-25222e80-0356-11eb-9c72-f0683810c1fc.jpg)

**Comment by Tensuko** [comment]
Already discussed here: #6046

**Comment by Tensuko** [comment]
2nd wait point seems to work for now, but we want to improove it, but we just need one Issue and not more, thats why closed this one :)

**Comment by rohne83** [comment]
@MtBakerScum 2nd (or even 3rd and more) wait point is working. But atm the auger wagon is ignoring the waiting time which is set by you in the menu, and will wait forever if there's either no trailer at the current wait point, or the trailer there is full. That's why my initial suggestion was to have the Mode 3 driver obey that waiting time, and drive on if it could not start overloading within that time.
But it looks like CP team wants to implement something more sophisticated with moving the mode1 driver instead of the auger wagon, as this would also help in other use cases (conveyor belts, mother bins, etc). As far as I understand this is currently in development.
