### ISSUE TITLE
Mode 3: Auger Wagon will run course, will not locate combine

### ISSUE THREAD

**Issue by notoriousweber** [Courseplay/courseplay#6183]
I'm running mode 3 on Lone Oak. I've created an offload course, and instruct the tractor/auger wagon to find a combine on the field I am harvesting. Both the combine and the auger wagon are on the same field. It gets to the waiting point and says "WAITING FOR COMBINE TO CALL", even though the combine is at 100% and the "driver requested" button is selected. In the log it SAYS the combine with the most fill level is my S790, but will not drive to the combine.  I've tried multiple fields, but used the same equipment each time. 

I've attached my log. Hopefully that helps.

[log.txt](https://github.com/Courseplay/courseplay/files/5331096/log.txt)

**Comment by Tensuko** [comment]
#5272 Wiki
Combine must be driven by CP.

**Comment by notoriousweber** [comment]
I tried it with the combine on courseplay as well... Still getting the same result...
[log.txt](https://github.com/Courseplay/courseplay/files/5344843/log.txt)

**Comment by Tensuko** [comment]
Did you select the combine for the Mode3 Driver in the CombineManager ?

**Comment by notoriousweber** [comment]
Yes I did. Under the combine/magnifying glass tab, I have it selected to find the s790 on the field the combine and tractor are both working/parked on There’s a little “x” in the box next to the combine name

I feel like I’m probably still doing something wrong, as it doesn’t seem like anyone else is reporting this issue. Could it possibly be a conflict with the combine? It’s the S790i, I believe by JHHG. I’d have to double check on the modder but I’m pretty sure it’s the one by JHHG.

**Comment by rohne83** [comment]
Do you have fruit avoidance activated? If yes, your unloaders will only drive to the combine if the pipe is not above the fruit. And even if there's no fruit under the pipe: if there's no easy path to the combine to be found (especially on large fields), it can really take some time - had to learn it myself the hard way :D So you might try with fruit avoidance turned off for the unloader.
Furthermore you can help yourself by placing the unloader manually near the combine so that its driver just has a few meters left to the combine's pipe, and start mode 3 driver at waypoint 'unloading'. If it is still not working, you can be pretty sure it is an issue with your mods.

**Comment by notoriousweber** [comment]
I always have fruit avoidance off. I’ve tried it on before, but it seemed like it caused more problems than it was worth.

**Comment by Tensuko** [comment]
I have avoid fruit always on and it works fine too.
Not sure what is the Problem here... Screenshots might help...

**Comment by Tensuko** [comment]
Unloaded several times now with Auger Wagon with Version .00072
Had no Problem.
