### ISSUE TITLE
Use Pathfinder when turn start and turn distance is to far

### ISSUE THREAD

**Issue by Michaelheus** [Courseplay/courseplay#6266]
As in the title written, is Courseplay generating travelling routes through field islands.

The map is MVP19
![Pic_2](https://user-images.githubusercontent.com/26620658/97491389-62340d80-1962-11eb-9073-701e1a865a07.PNG)
![Pic_1](https://user-images.githubusercontent.com/26620658/97491394-63fdd100-1962-11eb-9b28-1f88bd6c5b86.PNG)

**Comment by Tensuko** [comment]
That are just visual lines. I am sure that are connections between turn start and turn end.
Pathfinder should do a nice way to the next row. Try to run the course.

**Comment by Michaelheus** [comment]
Thanks for your answer. I will try it today in the evening.

**Comment by Anonymous-any** [comment]
I got a bit same complication on a field that make a L form in "Marwell manor map" as example (field 19) where CP don't pay attention to externals fields colliders or other tractors colliders, like between the field 19 and 1. In fact pretty all generated I try to make with tools spreaders go into colliders and always need manual stop. Event in fields 15, 18 bref...I even have the impression that often one vehicle attracts the other :/ I see too an issue with generating tool and with bypass AD where you can set CP to disable stop next trigger and finally it always set it on you can't manage this for me...
Br

**Comment by Michaelheus** [comment]
Today I tried it again. Courseplay generates travelling routes through field islands.
![Pic_3](https://user-images.githubusercontent.com/26620658/98153869-25bd6000-1ed4-11eb-9c78-8f3da2334669.png)

**Comment by Tensuko** [comment]
@Anonymous-any no Idea what you are talking about, screenshots ? And don't mix any other Issues into this one, else I will delete the comment. I don't want to have messed up Issues here.

@Michaelheus 
Seems like he didn't generated a wide turn path to let Pathfinder create the way to turn end.
Will have to see if we can enhance the Pathfinder to take over when have such long distances.

**Comment by Michaelheus** [comment]
Dear Tensuko,
I will test it this evening and let you know!

I am not quite sure but I think it was activated. Anyhow I will check and post an update.

**Comment by Anonymous-any** [comment]
Hello @Tensuko, of course you can do what you think you need (delete) finally that can make me holidays.
When I was writing my view point, the tittle was "Courseplay generates traveling routes through field islands" and u change it as what you want and you add Ex:  **And don't mix any other Issues into this one, else I will delete the comment. I don't want to have messed up Issues here.**
You can be detailed into the issue (I'm not english). I report what I was writes mean Courseplay go outside the field among others.
I was thinking I do a good thing will talk you about that so maybe next time I will shut-up myself.
Maybe I should have post a new one and you will move it to another duplicate idk but it's your job, again I thought I was doing well.
I have other examples for my view point look linked to this issues, where my tractors and/or his tool finish their job locked into the wood or the bushes or into other tractors who work in same time in same fields. Like theses examples are not alone then the jobs must be stopped.
Because my time is not to report bugs, maybe later I will show you screenshots like you talk, if I will think to it.
I passed the time to write the post above with my bad english (that I understand what you say to me ? like **no Idea what you are talking about**) and like this same one, so I think I have been clear about (AN) issue linked to this CP generator maybe not alone. I said the map, the fields, and all different modes I tried to generate, the tools like spreaders trailer 36 meter "navigator6000.xml" which hangs everywhere with a well offset attachment moving axis so bad when it go front/rear.
I can more add another for now because I just think to it, Some outside maneuvers can not have a screenshot because their track do not appear in the generation eye icon.
Good reception

**Comment by Tensuko** [comment]
@Anonymous-any 
Can you try to turn on 'use Pathfinder in turns' in the advanced options ?

Simple explanation:

Most ppl start a topic with a general headline, wich will end in chaos.
So once I figured out, what the problem realy is, I will change the title to be more specific to better find it when looking for it.
And you comment just wasn't helping...

This one with examples and screenshots at least tell me, what is your problem and yes this one is the same as topic.
Now for you the same thing you got to try out, as the lines do NOT show the way the tractor will go...

We don't follow lines, we follow waypoints and on that complete lines that you mark there are no waypoints...

**Comment by Anonymous-any** [comment]
It's the same with 'use Pathfinder in turns' no change but !!
Because CP has now an embedded editor, so I was forgot I can move points and tried it.
I moved the 2 end/start point line to avoid the issue so that give me this below:
![1](https://user-images.githubusercontent.com/25174503/98622552-1e4dea80-230a-11eb-94e3-72cd96a57cee.png)
And because of that too, I just thought think it's will be good enhancement Interactive if we can move points into the generatormap view in 2D if it's possible. (Here I had to teleport the vehicle in field and max zoom out to succeed in to move them).
Regard

**Comment by Tensuko** [comment]
In 2D view yea what would be cool but that is not possible as it is now.

**Comment by pvaiko** [comment]
So, with pathfinding in turns on:
![image](https://user-images.githubusercontent.com/2379521/98740846-52102b00-2371-11eb-8c51-fa98dc3dca9b.png)
... it nicely drives around the field edges on the headland instead of through the woods: 
![image](https://user-images.githubusercontent.com/2379521/98740975-7ec44280-2371-11eb-8e12-0c7ee1e0aa92.png)

**Comment by pvaiko** [comment]
@Michaelheus I wasn't able to generate a course for field 13 on MVP19, not sure how you did it, it is most likely a map problem (see https://github.com/Courseplay/courseplay/wiki/Course-Generator-FAQ).

But I tried 14 and (when the pathfinder for turn is activated) it does not drive through the island.
![image](https://user-images.githubusercontent.com/2379521/98743677-0e6bf000-2376-11eb-9464-b182e9e109ba.png)

**Comment by Michaelheus** [comment]
@pvaiko I also had to try different settings to generate a course on field 13. Unfortunatley I haven't had the time to test it again. I hope you get it done today. Then I will show you my settings and will also try the Pathfinding-Settings.

**Comment by Anonymous-any** [comment]
@pvaiko 
I been would like to know how you show lighted blue line because I would like to know too what this twisted want to do to force as this rear maneuver ? I been tried to set same debug like your screen but no way...
[1](https://user-images.githubusercontent.com/25174503/98856127-66c9ed00-245d-11eb-9ea1-40583e3c3426.png)

**Comment by Tensuko** [comment]
Channel 12 and 14 or adv option show debug lines or however we called it. Left side 2nd from bottom I think...
