### ISSUE TITLE
Fuelling 

### ISSUE THREAD

**Issue by matty2123** [Courseplay/courseplay#6317]
Hello upon recently if I’m running cp and machine run out of fuel you could drive tanker beside and it would start refuelling but won’t happen now what’s changed?

**Comment by schwiti6190** [comment]
@matty2123 Hi, could you test different modi, like Fieldwork, Transport, GrainTransport and so on ?

**Comment by schwiti6190** [comment]
And If it depends on the fuel amount left. For example if it is almost full or empty till the point it stops working.

**Comment by matty2123** [comment]
Yeah I tested it when it was plowing so it was Field work I can remember in the past you could drive beside it and it would refuel and carry on once it was full. It would say it was in traffic but least it was stopped and not pushing the tractor whilst trying to continue

**Comment by Misamangame** [comment]
@schwiti6190  at the moment it doesn't work on any mode.  Here is the video trying to refuel harvester on Fieldwork mode https://youtu.be/uoTmws8o9-8, here is a Fastrack on mode 3 https://youtu.be/aLJ8mazOO08, that refuelling truck should have same function like static refuelling point when vehicle pass him he should refuel either Always or under 20% depends on his settings. In this videos I used Ural mode truck, which I know worked before but for testing should be used stock Thundercreek https://www.farming-simulator.com/about.php?lang=en&country=cz&platform=pc because not all mods are properly done ofcourse... Basically if you set grain transport vehicle with course passing correct point on this mobile refuel point it and it refuels, it should work on any other work/transport mode and hopefully on some modded vehicles as well.

**Comment by schwiti6190** [comment]
@matty2123, @Misamangame 

Thanks for your help in testing and reporting back. It seems this functionality got lost due to a big rework from our side.
We will have look once we've got time for it, but this might take a bit. 

Sincerely 
David

**Comment by matty2123** [comment]
Cheers David.
