### ISSUE TITLE
Sugar Cane Planter does not stop when empty

### ISSUE THREAD

**Issue by Friendlyx** [Courseplay/courseplay#6339]
Sugar Cane Planter does not stop when empty for refilling and drives on even with use fertilizer switched to off.

https://abload.de/img/unbenanntbbkwt.png

**Comment by polosubtil** [comment]
I think your issue is you are using the wrong mode
This is mode 6 and you should use mode 4
![image](https://user-images.githubusercontent.com/60451845/99696938-87aec580-2a8f-11eb-9a1b-9c3ee5997d66.png)

You should try with Mode 4
![image](https://user-images.githubusercontent.com/60451845/99697219-d3616f00-2a8f-11eb-94a8-887f0afa5089.png)

**Comment by Friendlyx** [comment]
I tried again but mode 4 is not available in the planter

**Comment by polosubtil** [comment]
Is that a mod ? Or one of the original planters ?

**Comment by Tensuko** [comment]
@polosubtil thx I didn't saw that on my phone...

and the ingame one just works fine as it allows mode4:

![fsScreen_2020_11_20_16_09_08](https://user-images.githubusercontent.com/27344744/99815572-c5bcef80-2b4a-11eb-9abd-afe5a85b3c83.png)

Stick to ingame one and not any special modded one wich the modder fked up, sry can't say that nicer becosue I keep wonder why have to 'remod' the existing ingame one and make them worse...

**Comment by Tensuko** [comment]
Try to use a different Tractor!
It just came in my mind that we had a similar Problem with a JD Tractor.

**Comment by Friendlyx** [comment]
yes now ok with it seems to be a tractor thing
