### ISSUE TITLE
Harvester self unload - conflict with trailer

### ISSUE THREAD

**Issue by bojanh66** [Courseplay/courseplay#6392]
I am using latest CP version.
As you can see on picture, harvester runs into trailer sometimes, so i need to babysit.
Maybe it can be improved ?
![Untitled](https://user-images.githubusercontent.com/32069662/100521949-7fe5d400-31a7-11eb-84c3-03966a98292b.jpg)

**Comment by Tensuko** [comment]
This is traffic message.
Maybe we should approach the trailer in reverse so the cutter is not in the way @pvaiko you think that would be possible ?

**Comment by pvaiko** [comment]
I was thinking of adding a little straight section to the end of the course so it has room to align

**Comment by Tensuko** [comment]
That is a better Idea :)

**Comment by bojanh66** [comment]
One more suggestion.
If you notice on the picture in the upper right corner below the clock, once the harvester reach 100% fill level, it doesnt stop for 2-3 seconds to unload straw swath, but he immediatly starts turning and leaves straw in the circle.
Is there any chance to make a harvester wait few seconds once he reaches 100% fill level and then start going to trailer ?

![100521949-7fe5d400-31a7-11eb-84c3-03966a98292b](https://user-images.githubusercontent.com/32069662/100628356-6a4be800-3328-11eb-9779-78dc09dc73c3.jpg)

**Comment by KMullins01** [comment]
Hello. I also have this issue after upgrading 6.01.00008. I was still on 6.01.00394 and it was working okay. I thought I'd update since you all are now up to 6.03. This started happening after updating.

After this started I backtracked to different releases trying to find one that still worked with the combine auto unload. After finding none I just returned to my original 6.01 and this issue now happens sporadically with that release as well. I see there is recent activity in dealing with this issue. 

Here is my log file (which I know is a little messy with mods giving performance issues) and a screen shot of what the old 6.01.00394 and newer is doing now. Either combines not creating an unload path, or getting to the trailer/truck and stopping short. 

Not sure if it has anything to do with this issue or not, but the last photo you can see that now it's not finishing the rows also. This was a saved course.

Any more information that you might need just ask.

Thanks in advance. 
[log.txt](https://github.com/Courseplay/courseplay/files/5649655/log.txt)
![fsScreen_2020_12_06_17_10_43](https://user-images.githubusercontent.com/73150569/101294899-57358e00-37e8-11eb-9071-ab5cdb9f92ba.png)
![fsScreen_2020_12_05_22_12_23](https://user-images.githubusercontent.com/73150569/101294938-7c2a0100-37e8-11eb-89ce-f40e5a97193d.png)
![fsScreen_2020_12_05_22_12_23](https://user-images.githubusercontent.com/73150569/101294947-80561e80-37e8-11eb-866e-3f1f984a3009.png)
![fsScreen_2020_12_05_22_10_21](https://user-images.githubusercontent.com/73150569/101294952-877d2c80-37e8-11eb-9218-ce3d954e36ef.png)




.

**Comment by Tensuko** [comment]
@KMullins01 by far a way to old Version... Also the Answer about what we will do is already written here... Just wait for it.

**Comment by KMullins01** [comment]
Sorry for the typo. I upgraded to 6.03.00008 then these issues started. Thanks for the reply.

**Comment by pvaiko** [comment]
@bojanh66 @KMullins01 test with 6.03.00010 and report back.

**Comment by bojanh66** [comment]
Harvester unloads just fine now, but there is a new problem.
Harvester goes back to his last point, then continue driving across the field to the unload point and starts harvesting.
![FarmingSimulator2019Game 2020-12-07 14-19-56](https://user-images.githubusercontent.com/32069662/101356412-50665400-3898-11eb-9075-a67f13343a0c.jpg)
![FarmingSimulator2019Game 2020-12-07 14-22-44](https://user-images.githubusercontent.com/32069662/101356420-52c8ae00-3898-11eb-80a7-0f79ed1c5224.jpg)
![FarmingSimulator2019Game 2020-12-07 14-22-50](https://user-images.githubusercontent.com/32069662/101356421-53f9db00-3898-11eb-93e3-e97ab7bfc5ce.jpg)
![FarmingSimulator2019Game 2020-12-07 14-23-03](https://user-images.githubusercontent.com/32069662/101356427-55c39e80-3898-11eb-91fd-b36c9326c9f4.jpg)
![FarmingSimulator2019Game 2020-12-07 14-23-07](https://user-images.githubusercontent.com/32069662/101356431-578d6200-3898-11eb-9959-dfbe95ee0c89.jpg)
![FarmingSimulator2019Game 2020-12-07 14-23-37](https://user-images.githubusercontent.com/32069662/101356436-59572580-3898-11eb-9795-c8d14386a5e1.jpg)
![FarmingSimulator2019Game 2020-12-07 14-23-43](https://user-images.githubusercontent.com/32069662/101356441-5b20e900-3898-11eb-8115-6dc2bea7d818.jpg)

**Comment by pvaiko** [comment]
Ooops. Sorry. 6.03.00011 should fix this.

**Comment by bojanh66** [comment]
Works perfect now, ty.
One thing i have noticed is this:
- if Avoid fruit is Activated, self unload will work
- if Avoid fruit is Deactivated, self unload will not work
Is it supposed to be like that or its a small bug ?
Take a look at video:
https://youtu.be/VJ9rGxks8wo

**Comment by pvaiko** [comment]
Looks like it is just an oversight, starting self unload is in the same block where the pocket making code is, which is only active with fruit avoidance. I'll fix that in the next release, closing this now.
