### ISSUE TITLE
combines not requesting overloaders

### ISSUE THREAD

**Issue by Commissar0617** [Courseplay/courseplay#6475]
![20201211190301_1](https://user-images.githubusercontent.com/5993529/101968224-a8c48b00-3be3-11eb-9add-d0636b580caf.jpg)

**Comment by betrox007** [comment]
are working with mode 2 or mode 3?, since what i know terra variant on that picture is only for load for bulk not the arable fruit, and what combine is used?, if using forager harvester, what i know forager harvester is only respond for mode 2 unloader not mode 3 unloader and for terra variant it is can't select mode 2 only mode 3 (CMIIW)
thanks

**Comment by Tensuko** [comment]
#5272 and Wiki
