### ISSUE TITLE
The allocation of an auger wagon to a combine harvester.

### ISSUE THREAD

**Issue by huseyinsayar** [Courseplay/courseplay#6701]
The allocation of an auger wagon to a combine harvester.
When setting up the Auger Wagon, the Find Combine tab lists the harvesters found in the field / fields.
This listing
Ideal Harvester # 1
Ideal Harvester # 2
Ideal Harvester # 3
Is it possible to do it?
So we can allocate an auger wagon for a combine harvester. It may be possible to avoid conflicts.

**Comment by Tensuko** [comment]
Not sure what you try to do....
You can simply select as many combines as you want to unload.
Just mark them all.

**Comment by Tensuko** [comment]
Then just do it. But I can tell you that it will be a bit chaotic due to Issue with Convoy Distance.
But all you got to do is have one course per Auger (else they will stuck at stop waiting for the 1st to drive off).
Assign Auger 1 to Combine 1 and 2, Auger 2 to Combine 3 and 4, Auger 3 to Combine 5 a
![3auger6combine](https://user-images.githubusercontent.com/27344744/105378017-ad7d5580-5c0b-11eb-9191-34335163e54d.png)
nd 6.

**Comment by JDTiger** [comment]
Or, you can just set your three auger wagons and select all combines on all wagons, works pretty fine for me (using 3 Combines and 2 auger wagons).

The Combines call wich ever auger wagon happens to be the best one.

I am running both augers on a single course

**Comment by Tensuko** [comment]
It is possible to do but this one is not rly an Issue.
Maybe you should also think if this is realy needed like you want to do it or maybe there is anothr way like @JDTiger suggested it.
