### ISSUE TITLE
Mode 2/3 Pathfinding around crop for multiple unloaders to prevent collisions

### ISSUE THREAD

**Issue by dragon1220** [Courseplay/courseplay#6785]
Hi guys
Using latest version, is there any chance of maybe improving the pathfinding for the unloaders so they dont hug the edge of the crop line all the time when driving to and from the thresher? I had two unloaders servicing a NH cr10.90 with a 13.5m draper head, on the map Kernstad. I constantly have to keep moving the overloader so he doesnt driver into the draper head when he pulls away to the unload course or when the incoming one tries to meet up with the thresher.

![fsScreen_2021_02_07_04_35_42](https://user-images.githubusercontent.com/75646825/107144513-832dd680-6933-11eb-990f-dc002b60baa6.png)

![fsScreen_2021_02_07_04_36_15](https://user-images.githubusercontent.com/75646825/107144532-9fca0e80-6933-11eb-9027-a6ba09cbcdfb.png)

![fsScreen_2021_02_07_04_36_24](https://user-images.githubusercontent.com/75646825/107144542-b1131b00-6933-11eb-8507-b7123f423dbd.png)

![fsScreen_2021_02_07_04_36_31](https://user-images.githubusercontent.com/75646825/107144549-be300a00-6933-11eb-8fd4-cb02c08bbdb2.png)

I had run 4 headlands to allow some space for the vehicles to work but still they keep hugging the crop line. I have attached screenshots and my log. Originally I only had channels 4 and 14 on as they are useful, but i switched on 7 and 12 too. The course I am running is 4 x HL with Lands x 14 for centre all at 13.5m with 20% headland overlap, starting partway down the left edge

[log.txt](https://github.com/Courseplay/courseplay/files/5938774/log.txt)

Thanks guys, I love the mod and thank you for your hard work

Gareth

**Comment by pvaiko** [comment]
On your screenshots I see two unusual things:
1. since the header's left side isn't in the crop, I guess this is the first row after the headland, and all other rows should be as wide as the header. If this is the case, I don't understand the 'constantly' part of your description.
2. more importantly though, obviously the full unloader just started its unload course, how can it be that the combine is already full? So I looked at your logs, I see your combine has a capacity of 250000 (normally it is what, like 15000?) and gets full within 40 seconds. 

Don't misunderstand me, I know Courseplay is far from perfect, but this is a highly unrealistic situation, and we have enough bugs/improvements to take care of the realistic ones already.

If you have this problem with realistically behaving equipment, please open another issue.
