### ISSUE TITLE
Harvesters

### ISSUE THREAD

**Issue by Yboux** [Courseplay/courseplay#7012]
Just a question since this is not a big deal.

I would like to know why when you start to harvest a field pipes go out on the harvesters. After it does the same thing on every field. You have to exit the game to correct this.

Thank you

**Comment by Tensuko** [comment]
No Idea what you talk about.
Do you have the option Pipe always unfold active or something ?
Logfile ?
Screenshot ?

**Comment by Yboux** [comment]
I will get back to you

**Comment by Yboux** [comment]
Problem reproduced this morning.

[log.txt](https://github.com/Courseplay/courseplay/files/6177613/log.txt)
![fsScreen_2021_03_21_10_27_06](https://user-images.githubusercontent.com/25300651/111908841-2c86e280-8a31-11eb-80fb-8ea036b3281a.png)
![fsScreen_2021_03_21_10_26_15](https://user-images.githubusercontent.com/25300651/111908844-2d1f7900-8a31-11eb-9247-57f27e0c8868.png)
![fsScreen_2021_03_21_10_27_52](https://user-images.githubusercontent.com/25300651/111908845-2db80f80-8a31-11eb-872a-f97d1d30000e.png)

Thank you

**Comment by pvaiko** [comment]
Is this a mod? It does not happen with vanilla combines. 

When starting, CP briefly opens and closes the pipe to determine its length. This has so far working fine with all combines.

You may want to enable debug channel 6 and post a log.

**Comment by Yboux** [comment]
It happens with both vanilla and modded harvesters. I will enable channel 6. Thank you.

**Comment by Yboux** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6215849/log.txt)

Hope this is ok...

**Comment by Yboux** [comment]
![fsScreen_2021_03_27_10_44_25](https://user-images.githubusercontent.com/25300651/112724798-65b8ca00-8eeb-11eb-9119-c2a488ea5596.png)

**Comment by pvaiko** [comment]
So you had two combines in this in a convoy but looks like only the second one opened the pipe, so it isn't _always_ happening. 

I see CP opens the pipe before the combine starts working, but I don't see why it would be doing it. Since you have always open pipe deactivated, and you don't seem to have AutoDrive installed, there could be only two reasons CP opening the pipe: either there is a fillable trailer in range or CP thinks this is a chopper, which can only happen if something is messing with the capacity.

Sorry, with this information there's not much I can do about it, and since you seem to be the only one having this problem, you'll have to experiment and figure out when is it happening.

**Comment by Yboux** [comment]
Like I said before this is not a big deal. And it does not happen all the time and it happens with any combine. I'm wondering if another mod could be causing this problem. I will try other things as soon as I have the time. If I find something I'll let you know. Thank you for looking into this.

**Comment by Yboux** [comment]
This was not a CP problem. Hired a worker to harvest a field and it did it again....
