### ISSUE TITLE
suggestion for creating a route (Beacon lights)

### ISSUE THREAD

**Issue by 0Pietro20** [Courseplay/courseplay#7223]
I have no bugs to report but I wanted to ask a question: is it possible during the sowing of a field (with the CP) to use an auger wagon (always controlled by the CP) to refill the seeder (which would stop in place once the tank is emptied) and, once the auger wagon is empty, go and fill up with seeds? To my knowledge there is no such feature, but maybe I don't know it

**Comment by Tensuko** [comment]
There is, Mode8 Field supply.
Basically you use an auger wagon that gets seed from a tank and brings it to the filed (at the border or somewhere).
That couse works basically like Mode1, but with a Waitpoint where the auger wagon will wait untill it is empty (will automatically get new seed then).

To automatically refill your seeder, it works like a normal refill course.
You make a course that starts somewhere on the field (I would start it near the edge) drive unter the pipe (I am not 100% sure right now if a wait point was needed there too, but try it without 1st) then back the the field (basically a short course).

Load your Fieldcourse, add the refill course with the + folder, so when the seeder is empty, it will drive the refill course under the auger pipe and should refill there.

The tricky part about this is, some seeder needs to be unfolded to refill, this is not possible, due to limited space, but I think you can understand that we can't do much about this.

**Comment by 0Pietro20** [comment]
thank you so much for the support, i will try the various methods

**Comment by 0Pietro20** [comment]
sorry for the long wait. I tried the route using mode 8 and it works great. The only "flaw" is that if I am not mistaken the tractor that takes care of the recovery and transport of the seeds does not turn on the flashing light during the charging process (it may be that I am wrong, I am using the integrated GPU by necessity and this forces me to keep the settings to the minimum so it is difficult to understand when a flashing light is on or off)

**Comment by Tensuko** [comment]
What do you mean with 'during the charging progrecess' ?
When he refills itself or when he refills the seeder ?

**Comment by 0Pietro20** [comment]
When the tractor goes to reload its seeder it turns on the flashing lights as it should be. But the tractor that loaded the route in mode 8 (so 99% of it moves along the road until it stops at the waiting point) always keeps the flashing lights off. Maybe it would be nice if he turned them on and at the waiting point he turned them off while he stood still waiting to unload the seeds from the auger wagon to the seeder.

**Comment by Tensuko** [comment]
Hmm well that is something not rly important... I might have to start a new Issue about when beacon lights should be on and when off to collect those things. But that is rly not high on our todo list.

**Comment by 0Pietro20** [comment]
Yes, no problem, in the end it's just an aesthetic thing

**Comment by Tensuko** [comment]
Alright. I keep this one open untill I made a collection Issue, maybe the next few days.

**Comment by 0Pietro20** [comment]
ok, thanks for the effort. It is not about the topic but I saw that CP was published on the official Modhub, this makes me happy. But for updates, can they also be downloaded directly here from GitHub?

**Comment by Tensuko** [comment]
Sure can load the branch, but we suggest waiting for updates unless you can provice good reports that help us find the bugs :)
