### ISSUE TITLE
Mode 2 How to unload combine in combination with AD?

### ISSUE THREAD

**Issue by TobiHH78** [Courseplay/courseplay#7330]
Just a question. I read somewhere, that it`s possible to unload combine in mode 2, but use AD for driving to the silo. How does this work?

usually in mode 2 I make a short course from the field to a point a little outside of the field where the unloader is waiting. Then I made a 2nd course from there to the silo and back. After that I connect these two courses.
If I only make the first course, how does the unloader know to switch to AD for emptying at the silo?
Sorry if this has been answered, but I could not find a describtion in the Wiki.

**Comment by Tensuko** [comment]
Mode2 in CP:
Start at Field, drive to the Bunker, (reverse with unload here WP or drive through) and back to the Field.

In Order to have Mode2 working with AD, make a simple start/stop Course somewhere near the Field and start CP with 'Unloading'. You should have an option to use AD on your HUD Page.

It also could be the other way round, that you have to start AD and ask AD to start CP at the target (here also CP need an short start stop course + set to 'Unload').

Since I don't use AD I can't tell you exactly how it does work. But else we have an option to use AD, or you tell AD to use CP at target. (Or maybe even both).

**Comment by Tensuko** [comment]
> Start CP driver with options 'Unloading' and use AutoDrive 
'refill/unload'. AutoDrive settings basically the same as for the 
fieldwork drivers: use pickup&deliver, select a proper field
exit strategy and take care about appropriate drive on
percentage (has to be lower than the setting in CP).

From @rohne83 who implemented this.

**Comment by TobiHH78** [comment]
Thanks for quick reply. So If I understand it correctly, I only need one CP course. Will give it a try later today.
