### ISSUE TITLE
tractor wont stop at quantum 10-22 (belt) to fill with manure

### ISSUE THREAD

**Issue by shadow250** [Courseplay/courseplay#7355]
ok so i have a tractor and a ps-3401 manure wagon trying to do a field. it works till i need to refill. it goes to the refill course and drives right by. i have the fill type set to manure and the mode to seed and fert.  it did work for awhile on the dev version of cp then it stopped. i switched to the version on modhub and still nothing. im not sure what happened.

i also tried to activate debug channels by clicking the numbers but that doesnt work eithier
also cant get the wait timer to work.

**Comment by Tensuko** [comment]
https://github.com/Courseplay/courseplay/wiki

**Comment by shadow250** [comment]
[log.txt](https://github.com/Courseplay/courseplay/files/6824287/log.txt)

here is the game log i used cp version 6.04040 i think the current dev version dubug channels work on this so i used channels 1&2. multiple passes with me slowly moving the belt closer to the course were made until i got stopped in traffic then i adjusted turn speed setting slower at 3mph it acted as though is may have detected something but still did not fully stop.
i also noticed there is no timer on this cp version.

**Comment by Tensuko** [comment]
> so i used channels 1&2

and why ?

> i also noticed there is no timer on this cp version

what timer ?

About your screenshot..
What Waypoint did you use there ?
Unload Waypoint ? Why ?
Try without Waypoint and I am not sure if convayers are getting detected, it might need a waitpoint.

**Comment by shadow250** [comment]
i used channels 1&2
why?  because i thought they would help. do you want a log without any channels? different channels?
there is a wait timer in 6.40.00  on modhub under the tractor icon i think. i thought it might work with a timed waitpoint
the screenshot was intended to show what i was trying to do
if waypoint is the triangle with an x in it then it was placed by the record course option im not sure how to delete a waypoint
the trailer is supposed to stop at that conveyor and fill.
ill try a wait point when i get back to the game

**Comment by Tensuko** [comment]
Debugchannels print informations in the log for specific things, read this:
https://github.com/Courseplay/courseplay/wiki/Debug-Channels


> there is a wait timer in 6.40.00 on modhub under the tractor icon i think. i thought it might work with a timed waitpoint

In 6.4.0.0 the waittime was still bugged, it was fixed in 6.4.0.3, read the changelog on release side:
https://github.com/Courseplay/courseplay/releases


> the screenshot was intended to show what i was trying to do

That did help, but it also showed, what you did wrong.
And you don't have to place a Cross waypoint or anything there.
A refill course is a simple start at field, drive by the reload point and back to the field course. Nothing more.

> it was placed by the record course option

record course does not place random special waypoints...

> ill try a wait point when i get back to the game

As I said I am not 100% sure if you even need a waitpoint at the belt, just drive like I said, from field, drive by where you want to refill and back to the field. If that does not help, use the Ingame Editor to change the waypoint to a waitpoint (not unter it, but how the tractor with spreader should wait).

**Comment by shadow250** [comment]
ok so i did get it working. just driving under the belt doesnt work which i find strange because it did work at first.  the triangle/cross symbols were from a manure selling course. i didnt realize non loaded courses were represented, so sorry bout that. so the set a wait point at the conveyor is what worked and i did try that before and it ignored that too but it worked this time.
also another malfunction i found was the pellet maker from straw harvest has to empty the water/molasses to 90-92% before it will work in fieldwork mode. above that it stops and backs up like a combine to be unloaded and says the tool needs to be emptied. thanks for your help. also are the rea and readynamic dirt mods incompatable with cp?

**Comment by Tensuko** [comment]
Use search for the other things, it got all answrred already.
