### ISSUE TITLE
Question about mode 8, slurry transport. 

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#888]
Is it possible to add support for mod http://www.modhoster.com/mods/bgaextension--2 My problem is, when im using slurry tank refilled from farm slurry tank and driving to bga slurry tank, it shows "....reached overload point" but never starts to unload. If i manually press "r" it starts unload and continues his road to refill at farm again. 
BTW: Im using slurry tank from this pack http://www.kyoshos-modfactory.de/MAN_TGS_AGRAR  becose ingame slurry tanker wont give me unload option.

**Comment by JakobTischler** [comment]
The BGA extension mod is not the problem, as it doesn't modify any liquid manure triggers. The problem is that mode 8 is not really an "overloading" mode, but rather a "wait until empty" mode, in which regular liquid manure barrels refill at the transporter (instead of the transporter filling into a barrell/silo).

We used to have special support for the Eifok liquid manure system in FS13, in which the liquid manure *trigger* was able to pump into both directions, but that is not the case with default triggers.

We may look into it in the future, but like I said, I'd rather have the pump activity coming from the target trigger/tool than the transporter itself.

**Comment by Raints** [comment]
Ok. I only asked this becose mode 8 works fine with placeable manure storage http://www.modhoster.com/mods/placeable-liquite-manure-lager 
There is no problem for me to hit "r" manually, since everything else works fine for me with this mod. 
Keep up the good work and Happy New Year to you all!

**Comment by JakobTischler** [comment]
I have to correct myself, I was wrong about the BGAextension mod. We are most likely going to add support for the overloading mechanism.

**Comment by ThomasGaertner** [comment]
please test again with v0006 and report...

**Comment by Raints** [comment]
Working great now. Thanks for quick response!
