### ISSUE TITLE
Combine will not unload at the end of course.

### ISSUE THREAD

**Issue by Muaddib-1** [Courseplay/courseplay#896]
A combine in mode 6 that has reached the end point of a harvesting course refuses to unload.  A trailer  (whether driven by the player or CP) under the pipe is completely ignored until the combine is released to player control. 
edit: Not completely ignored. the combine will extend and retract the pipe when a trailer is brought near but not unload grain.

![2015-01-03_00006](https://cloud.githubusercontent.com/assets/5287689/5602025/adcb0a40-92f5-11e4-8256-4a319809fe29.jpg)

Here's a log in debug 17. Let me know if you'd like a different one. This one doesn't seem to have anything relative that I could see.
https://gist.github.com/Muaddib-1/6a00b0d7f6c47ef0683b

**Comment by Raints** [comment]
I would recomend you to remove latest autotractor mod and try again, had same problems. Somehow version 1.16 not working with courseplay.

**Comment by Muaddib-1** [comment]
Have had this problem for a long while.  Long before trying the new version of autotractor and without it at all.

**Comment by Satissis** [comment]
Sorry for the late answer.
Well we talked a bit about it and this is not that big a problem, since most of the cases, people stops the combine after it have finished work and unload it them self.
This might or might not be something we wanna do anything about, but no matter what, it's on our low priority list, so if we decide to check fix it, it will take some time before we actually do.

I'll put this in our todo/suggestion list and close this, to clean up the issue list.
