### ISSUE TITLE
Adding support for Attacher Modules

### ISSUE THREAD

**Issue by Raints** [Courseplay/courseplay#912]
Not sure if its right place for asking this but here it goes.
Why some mods not working with courseplay; downloaded some mods from modhoster
http://www.modhoster.com/mods/man-fliegl-absetzer
http://www.modhoster.com/mods/man-mulde
http://www.modhoster.com/mods/absetzr-brantner-16000

If i try to use them in mode 1 to sell grain, they just wont stop at load point. I know its the mod fault, but just cant find the reason. 

Sorry if its not right place to ask.

**Comment by Satissis** [comment]
Yes this is the right place to ask questions as well.

Well as you said it your self, it's the mods fault. Just to clarify this a bit better, then CP mostly only support the default giant game script as of fs15, since we needed to remove all the old stuff that was only fs13 related. With that said, you can guess that the mods you are having problems with either don't uses the default game script or are very bad modded.

So with that said, we don't add support for mods until they are requested by a user or we need it our self.

**Comment by Satissis** [comment]
@Raints I might add support for it, so no need to close this until we are sure we are going to add them or not :)
I'm guessing that you still would like us to add them right ?

**Comment by Raints** [comment]
Yea, sure i would like that. Since there is not good dumper truck in game.

**Comment by Satissis** [comment]
So I really hates when modders using the wrong attacher joints for something else, which is our case here, like they were using the semitrailer attacher joint for the attachermodules which they should have made a totally new attacher joint type instead like attacherModule, so I had to fiddle around a bit to find an solution and it should work now.
So please try out v0027 or newer and report back.

**Comment by Satissis** [comment]
closed due to inactivity

**Comment by Raints** [comment]
Sorry, somehow missed your comment week ago. Just tested grain transport and all working. Thank you!
