### ISSUE TITLE
dutch translation

### ISSUE THREAD

**Issue by Goten87** [Courseplay/courseplay#920]
The consept of max is here known as the same
and i think this is for the new rename
if you mean turning speed with it
```<text name="COURSEPLAY_SPEED_REVERSING" text="omkeer snelheid" />```

donno for sure but this is the translation for turning speed like a U turn
sorry i post it here but donno how to comit to the translate file it self

**Comment by JakobTischler** [comment]
1. Please use pull requests for translation updates.
2. `COURSEPLAY_SPEED_REVERSING` is the speed used when reversing the vehicle, i.e. driving backwards.

**Comment by Goten87** [comment]
oke then its ``<text name="COURSEPLAY_SPEED_REVERSING" text="achteruit snelheid" />``

**Comment by Goten87** [comment]
and i donno how to put it as a pull request sorry about that

**Comment by Goten87** [comment]
and ``<text name="COURSEPLAY_MAX_SPEED_MODE_AUTOMATIC" text="automatisch (van opname, max. %s)" />`` is the same as the term max is the same in dutch as in english

**Comment by Vanguard22** [comment]
Why was this changed? The value is used for reversing and unloading as far as I can tell. I use it ensure an even distribution across the silobunker while unloading into it, otherwise you end up with a big heap at the end. Seems like a lot of work to change a meaning that actually has two purposed ;)

**Comment by Satissis** [comment]
@Vanguard22 The speed while unloading in a BGA are still using that value, but it doesn't matter what you set it to, since the code I made for it, automatic calculates the unloading speed and set the reverse speed to that automatic and reverse it back to the value you set it to after it have finished unloading. So the value you are setting will only be used when you are reversing.
