### ISSUE TITLE
Suggestion: save course type

### ISSUE THREAD

**Issue by OldFisher** [Courseplay/courseplay#961]
Most courses are made for a specific task that requires specific course type. Would be nice to save the type with the course and select it when the course is loaded. If another type is needed, it can be selected after loading.

**Comment by PromGames** [comment]
This is a very interesting approach that can provide Courseplay a strong system for course settings management (Creation & Update) 

If I try to be more specific, I will go in the direction of saving default mode and default vehicle settings as a list of selectable `default_course(Mode&Vehicle)_settlement`

We could get some features with this approach:

- When creating a course, choose from a list of `default_course_settlement` at starting point and the vehicle and the course will be set accordingly.
- When selecting a course where `default_course_settlement = empty`, be able to set it to a previous saved default_course_settlement
- When having a vehicle with a new adjusted settings be able to update the `default_course_settlement`  based on actual settings defined in the current course_vehicle.

In fact, CP is saving some of this information already if we look at the information that appears in `vehicles.xml` by CP. 

As a conclusion, this could be a very good method to sort, use and be able to update settings of the current vehicle-course with just the selection of a `default_course_settlement`.

**Comment by hurr1k4ne** [comment]
You may use an index/abbreviation for your course names for this as an alternative.

FIELDNUMBER_CP-TASKNUMBER
15_02 is for unload combine and empty at silo.

I had some courses which are used for several task, like general field work.

Idea 2: In latest verision they added possibilities to add folders for courses. why not think of a system with these that fits your demand...

This will help you manage your courses although.

**Comment by OldFisher** [comment]
@hurr1k4ne  I'm already getting most of the *manual* course management. What I wanted was a little bit of automation to eliminate some manual actions, namely - switching course type.

**Comment by SystemParadox** [comment]
Yes please. This would be really useful.

**Comment by tjb8907** [comment]
I made my own add on mod for something similar to this. 

I can set a global field number (changing it changes on all vehicles), and then I can give each vehicle a type (Planter, Cultivator, Bale Loader, Sprayer, Grain Cart, Semi, etc)

Then I save all my courses and FieldNumber.CourseType i.e. 10.Planter or 15.Sprayer. 

So I hit CTRL KP +/- to change field number, and CTRL KP 0 to change vehicle type (vehicle type gets saved to the vehicle attributes). Then I have a hotkey to execute, which means it puts the field number together with the vehicle type and finds to corresponding course, and loads it into courseplay. Works pretty good. I made it a standalone mod, because I want to be able to update courseplay, it just executes courseplay functions.

**Comment by SystemParadox** [comment]
That sounds great. Any chance of releasing it? :)

**Comment by tjb8907** [comment]
Possibly. I have some more work to do on it before it's releaseable.

**Comment by ThomasGaertner** [comment]
moved to the tracker to keep the issues area clean
