### ISSUE TITLE
Suggestion: combine requests trailer at end of harvest

### ISSUE THREAD

**Issue by lansalot** [Courseplay/courseplay#976]
As a suggestion (I searched, couldn't see this already), how about when harvesting, a request is made to the CP trailer to come empty whatever is left in the bin when the field is complete?

**Comment by Otterbear** [comment]
I would like to add my vote for this as well. Not sure how well this can be incorporated due to the "Help" leaving the vehicle at the end of the harvest. Maybe if the combine was under CP control, it could work.

**Comment by AndyK70** [comment]
adding my vote to it.
I'm having my combines work with CP, too and agree it would be only possible in that case.

**Comment by ThomasGaertner** [comment]
please try v0049 and report.... please note that this is and will be forever valid for combines driven in field work mode only.

**Comment by lansalot** [comment]
Works a treat! Thanks for that.

(I meant with the combine being under CP control, but thanks to Otterbear for clarifying.)

**Comment by AndyK70** [comment]
I think we got a little issue here.

When the harvester has called the driver to unload and has finished to unload, it not only closes the harvester (key X pushed?), but also prepares the header to be dropped off (another X pushed?)
The next problem with this: You can't just unfold the harvester again with x because the pipe isn't in. So you first have to pipe in, then unfold again...

![afterwork.jpg](http://www11.pic-upload.de/03.02.15/8dbohtmm2yvc.jpg)

I would like not to have this automatic X (fold harvester, unfold header) at end of work. I let the harvester stay unfolded all day and only close it, when all work is finished.

Another thing I stumbled upon, but did not investigate further: It seems, that the "request for driver" at end of work remains active even after unloding and even after stopping CP on harvester?
I stopped this harvester (on screenshot) off the field and the truck began to drive. 
I switched to the truck and in the status it said something like: drive behind combine.
Not to sure about the status text, because stopped the truck immediatly as it was about to crash into a tree.
Have to redo it to get screenshots or video.

**Comment by ThomasGaertner** [comment]
in one point I agree: the call was set continuously . I fixed it in v0071. 
For your other issues I don't want to follow your arguments. when the field is empty and the work is done, the tools will be folded, if empty . If we change it now, then we will  have other guys who wants to have it as it was. If you send away the tractor, the pipe will fold too and you can do what you want with the combine....

**Comment by AndyK70** [comment]
Well... the automatic folding of the harvester is new, as it is the function to call the driver to unload.

But please bear in mind, that not only the harvester was folded, but the header was **un**folded, too. Even if I follow your arguments, that after a work is done the harvester should be folded it ain't right to unfold the header, don't you agree?

Will get the 0071 and test again.
