### ISSUE TITLE
CP 0051, reversing with a trailer

### ISSUE THREAD

**Issue by AndyK70** [Courseplay/courseplay#990]
I read #469 and also #495, but these belonged to the FS13 CP 3.xx, don't they?

Well, don't know if something has changed, or if again I made a mistake recording the course.

I read the manual for reversing several times and I'm pretty sure it recommends to record the course without trailer and supports both types of trailer (tandem and pivot) and also curved routes.

I was driving a NH T6 with the HKD Trailer which has pivot attachment.
For recording I detached the trailer, drove to the starting position, start recording some meters forward, came to full stop, clicked reverse, drove backwards some meters in a curve (to park that trailer) and stopped recording.

I drove back to my trailer, attached it, drove a turn to get in front of the startpoint and in mode 5 (transfer) i started to test if CP would do what I wanted.
Well it didn't.

Did 2 other attempts, the last even with waitingpoint where I clicked on reverse.

The Logfile: [FS15 logfile (2015-01-22 20:31)](https://gist.github.com/AndyK70/4ceac1d256fed4fb290d#file-fs15-logfile-2015-01-22-20-31)
The video: [FS15 CP driving backwards? - YouTube](https://www.youtube.com/watch?v=73li2dgJ56w)

**Comment by Satissis** [comment]
You are close.
There is 2 main issues and one minor.
First one is that reversing with trailers don't work in transport mode, it simple skips the reversing with trailer (It only works for developers in that mode to test things.) so use mode 1,2,3,4 and 6 instead. Would suggest mode 1 for testing.

The second one is that that when you recording the route, then take the tractor length + the trailer length and make a more or less strait line the on that length before changing it to reverse and again when reversing, reverse the same length strait backwards before starting to turn. The reason is that the first part, you straiten up the tractor and trailer and when starting reversing, it's actually the trailer that follows the waypoints, so if you didn't reverse a bit strait first, the turn the trailer needs to take would be more than the script can handle.

The minor one is that when you know that you need to reverse with an pivot trailer, don't make the turn too sharp or the tractor and pivot trailer can't coop with it. This is normally only with pivot trailer, so a good rule would be to only reverse turn ½ of the tractors max turn radius and everything should be fine.

Hope this helps you.

**Comment by AndyK70** [comment]
sorry for late answer, was lying down with a severe cold.

tested it again in mode 1 and CP was trying to turn the trailer. 
was recording a new test parcour with a longer straight beginning and was hauling out now before making a wider turn into the shelter.
Once it even succeded, but with a pivot trailer it's hard, even for CP, to turn in reverse.

I'll test it again with a tandem trailer.
My question was answered, so I think this one can be closed.

Though, would suggest to include your suggestions for recording a reverse course into the manual.
* long enough straight at the beginning to pull the trailer straight
* long enough straight at beginning of reverse to include the length of hauler and trailer
* with pivot trailer only go nearly straight when reversing, so turn before you reverse if possible.
* does not work in modes 5, 7 and 9
